.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel func_001014B8
    /* 1538 001014B8 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 153C 001014BC 2000B2FF */  sd         $s2, 0x20($sp)
    /* 1540 001014C0 1000B1FF */  sd         $s1, 0x10($sp)
    /* 1544 001014C4 2D908000 */  daddu      $s2, $a0, $zero
    /* 1548 001014C8 0000B0FF */  sd         $s0, 0x0($sp)
    /* 154C 001014CC 2D88A000 */  daddu      $s1, $a1, $zero
    /* 1550 001014D0 3000BFFF */  sd         $ra, 0x30($sp)
    /* 1554 001014D4 F82F040C */  jal        func_0010BFE0
    /* 1558 001014D8 2D80C000 */   daddu     $s0, $a2, $zero
    /* 155C 001014DC 000024DA */  lqc2       $vf4, 0x0($s1)
    /* 1560 001014E0 100025DA */  lqc2       $vf5, 0x10($s1)
    /* 1564 001014E4 200026DA */  lqc2       $vf6, 0x20($s1)
    /* 1568 001014E8 300027DA */  lqc2       $vf7, 0x30($s1)
    /* 156C 001014EC 04000724 */  addiu      $a3, $zero, 0x4
  .L001014F0:
    /* 1570 001014F0 000008DA */  lqc2       $vf8, 0x0($s0)
    /* 1574 001014F4 BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 1578 001014F8 BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 157C 001014FC BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 1580 00101500 4B3AE84B */  vmaddw.xyzw $vf9, $vf7, $vf8w
    /* 1584 00101504 000049FA */  sqc2       $vf9, 0x0($s2)
    /* 1588 00101508 FFFFE720 */  addi       $a3, $a3, -0x1 /* handwritten instruction */
    /* 158C 0010150C 10001022 */  addi       $s0, $s0, 0x10 /* handwritten instruction */
    /* 1590 00101510 F7FF0714 */  bne        $zero, $a3, .L001014F0
    /* 1594 00101514 10005222 */   addi      $s2, $s2, 0x10 /* handwritten instruction */
    /* 1598 00101518 06004010 */  beqz       $v0, .L00101534
    /* 159C 0010151C 3000BFDF */   ld        $ra, 0x30($sp)
    /* 15A0 00101520 2000B2DF */  ld         $s2, 0x20($sp)
    /* 15A4 00101524 1000B1DF */  ld         $s1, 0x10($sp)
    /* 15A8 00101528 0000B0DF */  ld         $s0, 0x0($sp)
    /* 15AC 0010152C 0E300408 */  j          func_0010C038
    /* 15B0 00101530 4000BD27 */   addiu     $sp, $sp, 0x40
  .L00101534:
    /* 15B4 00101534 2000B2DF */  ld         $s2, 0x20($sp)
    /* 15B8 00101538 1000B1DF */  ld         $s1, 0x10($sp)
    /* 15BC 0010153C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 15C0 00101540 0800E003 */  jr         $ra
    /* 15C4 00101544 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_001014B8, . - func_001014B8

glabel func_00101548
    /* 15C8 00101548 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 15CC 0010154C 2000B2FF */  sd         $s2, 0x20($sp)
    /* 15D0 00101550 1000B1FF */  sd         $s1, 0x10($sp)
    /* 15D4 00101554 2D908000 */  daddu      $s2, $a0, $zero
    /* 15D8 00101558 0000B0FF */  sd         $s0, 0x0($sp)
    /* 15DC 0010155C 2D88A000 */  daddu      $s1, $a1, $zero
    /* 15E0 00101560 3000BFFF */  sd         $ra, 0x30($sp)
    /* 15E4 00101564 F82F040C */  jal        func_0010BFE0
    /* 15E8 00101568 2D80C000 */   daddu     $s0, $a2, $zero
    /* 15EC 0010156C 000024DA */  lqc2       $vf4, 0x0($s1)
    /* 15F0 00101570 000005DA */  lqc2       $vf5, 0x0($s0)
    /* 15F4 00101574 FE22C54B */  vopmula.xyz $ACC, $vf4, $vf5
    /* 15F8 00101578 AE29C44B */  vopmsub.xyz $vf6, $vf5, $vf4
    /* 15FC 0010157C AC31264A */  vsub.w     $vf6, $vf6, $vf6
    /* 1600 00101580 000046FA */  sqc2       $vf6, 0x0($s2)
    /* 1604 00101584 06004010 */  beqz       $v0, .L001015A0
    /* 1608 00101588 3000BFDF */   ld        $ra, 0x30($sp)
    /* 160C 0010158C 2000B2DF */  ld         $s2, 0x20($sp)
    /* 1610 00101590 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1614 00101594 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1618 00101598 0E300408 */  j          func_0010C038
    /* 161C 0010159C 4000BD27 */   addiu     $sp, $sp, 0x40
  .L001015A0:
    /* 1620 001015A0 2000B2DF */  ld         $s2, 0x20($sp)
    /* 1624 001015A4 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1628 001015A8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 162C 001015AC 0800E003 */  jr         $ra
    /* 1630 001015B0 4000BD27 */   addiu     $sp, $sp, 0x40
    /* 1634 001015B4 00000000 */  nop
.size func_00101548, . - func_00101548
