.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_001016A8
    /* 1728 001016A8 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 172C 001016AC 1000B1FF */  sd         $s1, 0x10($sp)
    /* 1730 001016B0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 1734 001016B4 2D888000 */  daddu      $s1, $a0, $zero
    /* 1738 001016B8 2000BFFF */  sd         $ra, 0x20($sp)
    /* 173C 001016BC F82F040C */  jal        func_0010BFE0
    /* 1740 001016C0 2D80A000 */   daddu     $s0, $a1, $zero
    /* 1744 001016C4 0000087A */  lq         $t0, 0x0($s0)
    /* 1748 001016C8 1000097A */  lq         $t1, 0x10($s0)
    /* 174C 001016CC 20000A7A */  lq         $t2, 0x20($s0)
    /* 1750 001016D0 30000B7A */  lq         $t3, 0x30($s0)
    /* 1754 001016D4 88642871 */  pextlw     $t4, $t1, $t0
    /* 1758 001016D8 A86C2871 */  pextuw     $t5, $t1, $t0
    /* 175C 001016DC 88746A71 */  pextlw     $t6, $t3, $t2
    /* 1760 001016E0 A87C6A71 */  pextuw     $t7, $t3, $t2
    /* 1764 001016E4 8943CC71 */  pcpyld     $t0, $t6, $t4
    /* 1768 001016E8 A94B8E71 */  pcpyud     $t1, $t4, $t6
    /* 176C 001016EC 8953ED71 */  pcpyld     $t2, $t7, $t5
    /* 1770 001016F0 A95BAF71 */  pcpyud     $t3, $t5, $t7
    /* 1774 001016F4 0000287E */  sq         $t0, 0x0($s1)
    /* 1778 001016F8 1000297E */  sq         $t1, 0x10($s1)
    /* 177C 001016FC 20002A7E */  sq         $t2, 0x20($s1)
    /* 1780 00101700 30002B7E */  sq         $t3, 0x30($s1)
    /* 1784 00101704 05004010 */  beqz       $v0, .L0010171C
    /* 1788 00101708 2000BFDF */   ld        $ra, 0x20($sp)
    /* 178C 0010170C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1790 00101710 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1794 00101714 0E300408 */  j          func_0010C038
    /* 1798 00101718 3000BD27 */   addiu     $sp, $sp, 0x30
  .L0010171C:
    /* 179C 0010171C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 17A0 00101720 0000B0DF */  ld         $s0, 0x0($sp)
    /* 17A4 00101724 0800E003 */  jr         $ra
    /* 17A8 00101728 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 17AC 0010172C 00000000 */  nop
.size func_001016A8, . - func_001016A8

glabel func_00101730
    /* 17B0 00101730 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 17B4 00101734 1000B1FF */  sd         $s1, 0x10($sp)
    /* 17B8 00101738 0000B0FF */  sd         $s0, 0x0($sp)
    /* 17BC 0010173C 2D888000 */  daddu      $s1, $a0, $zero
    /* 17C0 00101740 2000BFFF */  sd         $ra, 0x20($sp)
    /* 17C4 00101744 F82F040C */  jal        func_0010BFE0
    /* 17C8 00101748 2D80A000 */   daddu     $s0, $a1, $zero
    /* 17CC 0010174C 0000087A */  lq         $t0, 0x0($s0)
    /* 17D0 00101750 1000097A */  lq         $t1, 0x10($s0)
    /* 17D4 00101754 20000A7A */  lq         $t2, 0x20($s0)
    /* 17D8 00101758 300004DA */  lqc2       $vf4, 0x30($s0)
    /* 17DC 0010175C 3C23E54B */  vmove.xyzw $vf5, $vf4
    /* 17E0 00101760 2C21C44B */  vsub.xyz   $vf4, $vf4, $vf4
    /* 17E4 00101764 3C23E94B */  vmove.xyzw $vf9, $vf4
    /* 17E8 00101768 00202B48 */  qmfc2      $t3, $vf4
    /* 17EC 0010176C 88642871 */  pextlw     $t4, $t1, $t0
    /* 17F0 00101770 A86C2871 */  pextuw     $t5, $t1, $t0
    /* 17F4 00101774 88746A71 */  pextlw     $t6, $t3, $t2
    /* 17F8 00101778 A87C6A71 */  pextuw     $t7, $t3, $t2
    /* 17FC 0010177C 8943CC71 */  pcpyld     $t0, $t6, $t4
    /* 1800 00101780 A94B8E71 */  pcpyud     $t1, $t4, $t6
    /* 1804 00101784 8953ED71 */  pcpyld     $t2, $t7, $t5
    /* 1808 00101788 0030A848 */  qmtc2      $t0, $vf6
    /* 180C 0010178C 0038A948 */  qmtc2      $t1, $vf7
    /* 1810 00101790 0040AA48 */  qmtc2      $t2, $vf8
    /* 1814 00101794 BC31C54B */  vmulax.xyz $ACC, $vf6, $vf5x
    /* 1818 00101798 BD38C54B */  vmadday.xyz $ACC, $vf7, $vf5y
    /* 181C 0010179C 0A41C54B */  vmaddz.xyz $vf4, $vf8, $vf5z
    /* 1820 001017A0 2C49C44B */  vsub.xyz   $vf4, $vf9, $vf4
    /* 1824 001017A4 0000287E */  sq         $t0, 0x0($s1)
    /* 1828 001017A8 1000297E */  sq         $t1, 0x10($s1)
    /* 182C 001017AC 20002A7E */  sq         $t2, 0x20($s1)
    /* 1830 001017B0 300024FA */  sqc2       $vf4, 0x30($s1)
    /* 1834 001017B4 05004010 */  beqz       $v0, .L001017CC
    /* 1838 001017B8 2000BFDF */   ld        $ra, 0x20($sp)
    /* 183C 001017BC 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1840 001017C0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1844 001017C4 0E300408 */  j          func_0010C038
    /* 1848 001017C8 3000BD27 */   addiu     $sp, $sp, 0x30
  .L001017CC:
    /* 184C 001017CC 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1850 001017D0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1854 001017D4 0800E003 */  jr         $ra
    /* 1858 001017D8 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 185C 001017DC 00000000 */  nop
.size func_00101730, . - func_00101730

glabel func_001017E0
    /* 1860 001017E0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 1864 001017E4 1000B1FF */  sd         $s1, 0x10($sp)
    /* 1868 001017E8 0000B0FF */  sd         $s0, 0x0($sp)
    /* 186C 001017EC 2D888000 */  daddu      $s1, $a0, $zero
    /* 1870 001017F0 3000B4E7 */  swc1       $f20, 0x30($sp)
    /* 1874 001017F4 2D80A000 */  daddu      $s0, $a1, $zero
    /* 1878 001017F8 2000BFFF */  sd         $ra, 0x20($sp)
    /* 187C 001017FC F82F040C */  jal        func_0010BFE0
    /* 1880 00101800 06650046 */   mov.s     $f20, $f12
    /* 1884 00101804 000004DA */  lqc2       $vf4, 0x0($s0)
    /* 1888 00101808 00A00844 */  mfc1       $t0, $f20
    /* 188C 0010180C 0028A848 */  qmtc2      $t0, $vf5
    /* 1890 00101810 BC03654A */  vdiv       $Q, $vf0w, $vf5x
    /* 1894 00101814 BF03004A */  vwaitq
    /* 1898 00101818 1C21E04B */  vmulq.xyzw $vf4, $vf4, $Q
    /* 189C 0010181C 000024FA */  sqc2       $vf4, 0x0($s1)
    /* 18A0 00101820 06004010 */  beqz       $v0, .L0010183C
    /* 18A4 00101824 2000BFDF */   ld        $ra, 0x20($sp)
    /* 18A8 00101828 1000B1DF */  ld         $s1, 0x10($sp)
    /* 18AC 0010182C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 18B0 00101830 3000B4C7 */  lwc1       $f20, 0x30($sp)
    /* 18B4 00101834 0E300408 */  j          func_0010C038
    /* 18B8 00101838 4000BD27 */   addiu     $sp, $sp, 0x40
  .L0010183C:
    /* 18BC 0010183C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 18C0 00101840 0000B0DF */  ld         $s0, 0x0($sp)
    /* 18C4 00101844 3000B4C7 */  lwc1       $f20, 0x30($sp)
    /* 18C8 00101848 0800E003 */  jr         $ra
    /* 18CC 0010184C 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_001017E0, . - func_001017E0

glabel func_00101850
    /* 18D0 00101850 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 18D4 00101854 1000B1FF */  sd         $s1, 0x10($sp)
    /* 18D8 00101858 0000B0FF */  sd         $s0, 0x0($sp)
    /* 18DC 0010185C 2D888000 */  daddu      $s1, $a0, $zero
    /* 18E0 00101860 3000B4E7 */  swc1       $f20, 0x30($sp)
    /* 18E4 00101864 2D80A000 */  daddu      $s0, $a1, $zero
    /* 18E8 00101868 2000BFFF */  sd         $ra, 0x20($sp)
    /* 18EC 0010186C F82F040C */  jal        func_0010BFE0
    /* 18F0 00101870 06650046 */   mov.s     $f20, $f12
    /* 18F4 00101874 000004DA */  lqc2       $vf4, 0x0($s0)
    /* 18F8 00101878 00A00844 */  mfc1       $t0, $f20
    /* 18FC 0010187C 0028A848 */  qmtc2      $t0, $vf5
    /* 1900 00101880 BC03654A */  vdiv       $Q, $vf0w, $vf5x
    /* 1904 00101884 BF03004A */  vwaitq
    /* 1908 00101888 1C21C04B */  vmulq.xyz  $vf4, $vf4, $Q
    /* 190C 0010188C 000024FA */  sqc2       $vf4, 0x0($s1)
    /* 1910 00101890 06004010 */  beqz       $v0, .L001018AC
    /* 1914 00101894 2000BFDF */   ld        $ra, 0x20($sp)
    /* 1918 00101898 1000B1DF */  ld         $s1, 0x10($sp)
    /* 191C 0010189C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1920 001018A0 3000B4C7 */  lwc1       $f20, 0x30($sp)
    /* 1924 001018A4 0E300408 */  j          func_0010C038
    /* 1928 001018A8 4000BD27 */   addiu     $sp, $sp, 0x40
  .L001018AC:
    /* 192C 001018AC 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1930 001018B0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1934 001018B4 3000B4C7 */  lwc1       $f20, 0x30($sp)
    /* 1938 001018B8 0800E003 */  jr         $ra
    /* 193C 001018BC 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_00101850, . - func_00101850

glabel func_001018C0
    /* 1940 001018C0 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 1944 001018C4 2000B2FF */  sd         $s2, 0x20($sp)
    /* 1948 001018C8 1000B1FF */  sd         $s1, 0x10($sp)
    /* 194C 001018CC 2D908000 */  daddu      $s2, $a0, $zero
    /* 1950 001018D0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 1954 001018D4 2D88A000 */  daddu      $s1, $a1, $zero
    /* 1958 001018D8 4000B4E7 */  swc1       $f20, 0x40($sp)
    /* 195C 001018DC 2D80C000 */  daddu      $s0, $a2, $zero
    /* 1960 001018E0 3000BFFF */  sd         $ra, 0x30($sp)
    /* 1964 001018E4 F82F040C */  jal        func_0010BFE0
    /* 1968 001018E8 06650046 */   mov.s     $f20, $f12
    /* 196C 001018EC 000024DA */  lqc2       $vf4, 0x0($s1)
    /* 1970 001018F0 000005DA */  lqc2       $vf5, 0x0($s0)
    /* 1974 001018F4 00A00844 */  mfc1       $t0, $f20
    /* 1978 001018F8 0030A848 */  qmtc2      $t0, $vf6
    /* 197C 001018FC C301004B */  vaddw.x    $vf7, $vf0, $vf0w
    /* 1980 00101900 2C3A064B */  vsub.x     $vf8, $vf7, $vf6
    /* 1984 00101904 BC21E64B */  vmulax.xyzw $ACC, $vf4, $vf6x
    /* 1988 00101908 482AE84B */  vmaddx.xyzw $vf9, $vf5, $vf8x
    /* 198C 0010190C 000049FA */  sqc2       $vf9, 0x0($s2)
    /* 1990 00101910 07004010 */  beqz       $v0, .L00101930
    /* 1994 00101914 3000BFDF */   ld        $ra, 0x30($sp)
    /* 1998 00101918 2000B2DF */  ld         $s2, 0x20($sp)
    /* 199C 0010191C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 19A0 00101920 0000B0DF */  ld         $s0, 0x0($sp)
    /* 19A4 00101924 4000B4C7 */  lwc1       $f20, 0x40($sp)
    /* 19A8 00101928 0E300408 */  j          func_0010C038
    /* 19AC 0010192C 5000BD27 */   addiu     $sp, $sp, 0x50
  .L00101930:
    /* 19B0 00101930 2000B2DF */  ld         $s2, 0x20($sp)
    /* 19B4 00101934 1000B1DF */  ld         $s1, 0x10($sp)
    /* 19B8 00101938 0000B0DF */  ld         $s0, 0x0($sp)
    /* 19BC 0010193C 4000B4C7 */  lwc1       $f20, 0x40($sp)
    /* 19C0 00101940 0800E003 */  jr         $ra
    /* 19C4 00101944 5000BD27 */   addiu     $sp, $sp, 0x50
.size func_001018C0, . - func_001018C0

glabel func_00101948
    /* 19C8 00101948 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 19CC 0010194C 2000B2FF */  sd         $s2, 0x20($sp)
    /* 19D0 00101950 1000B1FF */  sd         $s1, 0x10($sp)
    /* 19D4 00101954 2D908000 */  daddu      $s2, $a0, $zero
    /* 19D8 00101958 0000B0FF */  sd         $s0, 0x0($sp)
    /* 19DC 0010195C 2D88A000 */  daddu      $s1, $a1, $zero
    /* 19E0 00101960 3000BFFF */  sd         $ra, 0x30($sp)
    /* 19E4 00101964 F82F040C */  jal        func_0010BFE0
    /* 19E8 00101968 2D80C000 */   daddu     $s0, $a2, $zero
    /* 19EC 0010196C 000024DA */  lqc2       $vf4, 0x0($s1)
    /* 19F0 00101970 000005DA */  lqc2       $vf5, 0x0($s0)
    /* 19F4 00101974 A821E54B */  vadd.xyzw  $vf6, $vf4, $vf5
    /* 19F8 00101978 000046FA */  sqc2       $vf6, 0x0($s2)
    /* 19FC 0010197C 06004010 */  beqz       $v0, .L00101998
    /* 1A00 00101980 3000BFDF */   ld        $ra, 0x30($sp)
    /* 1A04 00101984 2000B2DF */  ld         $s2, 0x20($sp)
    /* 1A08 00101988 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1A0C 0010198C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1A10 00101990 0E300408 */  j          func_0010C038
    /* 1A14 00101994 4000BD27 */   addiu     $sp, $sp, 0x40
  .L00101998:
    /* 1A18 00101998 2000B2DF */  ld         $s2, 0x20($sp)
    /* 1A1C 0010199C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1A20 001019A0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1A24 001019A4 0800E003 */  jr         $ra
    /* 1A28 001019A8 4000BD27 */   addiu     $sp, $sp, 0x40
    /* 1A2C 001019AC 00000000 */  nop
.size func_00101948, . - func_00101948

glabel func_001019B0
    /* 1A30 001019B0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 1A34 001019B4 2000B2FF */  sd         $s2, 0x20($sp)
    /* 1A38 001019B8 1000B1FF */  sd         $s1, 0x10($sp)
    /* 1A3C 001019BC 2D908000 */  daddu      $s2, $a0, $zero
    /* 1A40 001019C0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 1A44 001019C4 2D88A000 */  daddu      $s1, $a1, $zero
    /* 1A48 001019C8 3000BFFF */  sd         $ra, 0x30($sp)
    /* 1A4C 001019CC F82F040C */  jal        func_0010BFE0
    /* 1A50 001019D0 2D80C000 */   daddu     $s0, $a2, $zero
    /* 1A54 001019D4 000024DA */  lqc2       $vf4, 0x0($s1)
    /* 1A58 001019D8 000005DA */  lqc2       $vf5, 0x0($s0)
    /* 1A5C 001019DC AC21E54B */  vsub.xyzw  $vf6, $vf4, $vf5
    /* 1A60 001019E0 000046FA */  sqc2       $vf6, 0x0($s2)
    /* 1A64 001019E4 06004010 */  beqz       $v0, .L00101A00
    /* 1A68 001019E8 3000BFDF */   ld        $ra, 0x30($sp)
    /* 1A6C 001019EC 2000B2DF */  ld         $s2, 0x20($sp)
    /* 1A70 001019F0 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1A74 001019F4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1A78 001019F8 0E300408 */  j          func_0010C038
    /* 1A7C 001019FC 4000BD27 */   addiu     $sp, $sp, 0x40
  .L00101A00:
    /* 1A80 00101A00 2000B2DF */  ld         $s2, 0x20($sp)
    /* 1A84 00101A04 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1A88 00101A08 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1A8C 00101A0C 0800E003 */  jr         $ra
    /* 1A90 00101A10 4000BD27 */   addiu     $sp, $sp, 0x40
    /* 1A94 00101A14 00000000 */  nop
.size func_001019B0, . - func_001019B0
