.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00101B68
    /* 1BE8 00101B68 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 1BEC 00101B6C 1000B1FF */  sd         $s1, 0x10($sp)
    /* 1BF0 00101B70 0000B0FF */  sd         $s0, 0x0($sp)
    /* 1BF4 00101B74 2D888000 */  daddu      $s1, $a0, $zero
    /* 1BF8 00101B78 2000BFFF */  sd         $ra, 0x20($sp)
    /* 1BFC 00101B7C F82F040C */  jal        func_0010BFE0
    /* 1C00 00101B80 2D80A000 */   daddu     $s0, $a1, $zero
    /* 1C04 00101B84 0000067A */  lq         $a2, 0x0($s0)
    /* 1C08 00101B88 0000267E */  sq         $a2, 0x0($s1)
    /* 1C0C 00101B8C 05004010 */  beqz       $v0, .L00101BA4
    /* 1C10 00101B90 2000BFDF */   ld        $ra, 0x20($sp)
    /* 1C14 00101B94 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1C18 00101B98 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1C1C 00101B9C 0E300408 */  j          func_0010C038
    /* 1C20 00101BA0 3000BD27 */   addiu     $sp, $sp, 0x30
  .L00101BA4:
    /* 1C24 00101BA4 1000B1DF */  ld         $s1, 0x10($sp)
    /* 1C28 00101BA8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 1C2C 00101BAC 0800E003 */  jr         $ra
    /* 1C30 00101BB0 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 1C34 00101BB4 00000000 */  nop
.size func_00101B68, . - func_00101B68
