.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00102878
    /* 28F8 00102878 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 28FC 0010287C 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2900 00102880 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2904 00102884 2D888000 */  daddu      $s1, $a0, $zero
    /* 2908 00102888 3000B4E7 */  swc1       $f20, 0x30($sp)
    /* 290C 0010288C 2D80A000 */  daddu      $s0, $a1, $zero
    /* 2910 00102890 2000BFFF */  sd         $ra, 0x20($sp)
    /* 2914 00102894 F82F040C */  jal        func_0010BFE0
    /* 2918 00102898 06650046 */   mov.s     $f20, $f12
    /* 291C 0010289C 000004DA */  lqc2       $vf4, 0x0($s0)
    /* 2920 001028A0 00A00844 */  mfc1       $t0, $f20
    /* 2924 001028A4 0028A848 */  qmtc2      $t0, $vf5
    /* 2928 001028A8 1821C54B */  vmulx.xyz  $vf4, $vf4, $vf5x
    /* 292C 001028AC 000024FA */  sqc2       $vf4, 0x0($s1)
    /* 2930 001028B0 06004010 */  beqz       $v0, .L001028CC
    /* 2934 001028B4 2000BFDF */   ld        $ra, 0x20($sp)
    /* 2938 001028B8 1000B1DF */  ld         $s1, 0x10($sp)
    /* 293C 001028BC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2940 001028C0 3000B4C7 */  lwc1       $f20, 0x30($sp)
    /* 2944 001028C4 0E300408 */  j          func_0010C038
    /* 2948 001028C8 4000BD27 */   addiu     $sp, $sp, 0x40
  .L001028CC:
    /* 294C 001028CC 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2950 001028D0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2954 001028D4 3000B4C7 */  lwc1       $f20, 0x30($sp)
    /* 2958 001028D8 0800E003 */  jr         $ra
    /* 295C 001028DC 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_00102878, . - func_00102878

glabel func_001028E0
    /* 2960 001028E0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2964 001028E4 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2968 001028E8 1000BFFF */  sd         $ra, 0x10($sp)
    /* 296C 001028EC F82F040C */  jal        func_0010BFE0
    /* 2970 001028F0 2D808000 */   daddu     $s0, $a0, $zero
    /* 2974 001028F4 2C01E04B */  vsub.xyzw  $vf4, $vf0, $vf0
    /* 2978 001028F8 8045033C */  lui        $v1, (0x45800000 >> 16)
    /* 297C 001028FC 381C0300 */  dsll       $v1, $v1, 16
    /* 2980 00102900 80456334 */  ori        $v1, $v1, 0x4580
    /* 2984 00102904 381C0300 */  dsll       $v1, $v1, 16
    /* 2988 00102908 000007DA */  lqc2       $vf7, 0x0($s0)
    /* 298C 0010290C 0030A348 */  qmtc2      $v1, $vf6
    /* 2990 00102910 0080C048 */  ctc2       $zero, $vi16
    /* 2994 00102914 6C39A44B */  vsub.xyw   $vf5, $vf7, $vf4
    /* 2998 00102918 6C31874B */  vsub.xy    $vf5, $vf6, $vf7
    /* 299C 0010291C FF02004A */  vnop
    /* 29A0 00102920 FF02004A */  vnop
    /* 29A4 00102924 FF02004A */  vnop
    /* 29A8 00102928 FF02004A */  vnop
    /* 29AC 0010292C FF02004A */  vnop
    /* 29B0 00102930 00804348 */  cfc2       $v1, $vi16
    /* 29B4 00102934 C0006330 */  andi       $v1, $v1, 0xC0
    /* 29B8 00102938 03004010 */  beqz       $v0, .L00102948
    /* 29BC 0010293C 2D806000 */   daddu     $s0, $v1, $zero
    /* 29C0 00102940 0E30040C */  jal        func_0010C038
    /* 29C4 00102944 00000000 */   nop
  .L00102948:
    /* 29C8 00102948 2D100002 */  daddu      $v0, $s0, $zero
    /* 29CC 0010294C 1000BFDF */  ld         $ra, 0x10($sp)
    /* 29D0 00102950 0000B0DF */  ld         $s0, 0x0($sp)
    /* 29D4 00102954 0800E003 */  jr         $ra
    /* 29D8 00102958 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 29DC 0010295C 00000000 */  nop
.size func_001028E0, . - func_001028E0

glabel func_00102960
    /* 29E0 00102960 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 29E4 00102964 2000B2FF */  sd         $s2, 0x20($sp)
    /* 29E8 00102968 1000B1FF */  sd         $s1, 0x10($sp)
    /* 29EC 0010296C 2D908000 */  daddu      $s2, $a0, $zero
    /* 29F0 00102970 0000B0FF */  sd         $s0, 0x0($sp)
    /* 29F4 00102974 2D88A000 */  daddu      $s1, $a1, $zero
    /* 29F8 00102978 3000BFFF */  sd         $ra, 0x30($sp)
    /* 29FC 0010297C F82F040C */  jal        func_0010BFE0
    /* 2A00 00102980 2D80C000 */   daddu     $s0, $a2, $zero
    /* 2A04 00102984 2C01E04B */  vsub.xyzw  $vf4, $vf0, $vf0
    /* 2A08 00102988 8045033C */  lui        $v1, (0x45800000 >> 16)
    /* 2A0C 0010298C 381C0300 */  dsll       $v1, $v1, 16
    /* 2A10 00102990 80456334 */  ori        $v1, $v1, 0x4580
    /* 2A14 00102994 381C0300 */  dsll       $v1, $v1, 16
    /* 2A18 00102998 000046DA */  lqc2       $vf6, 0x0($s2)
    /* 2A1C 0010299C 000028DA */  lqc2       $vf8, 0x0($s1)
    /* 2A20 001029A0 000009DA */  lqc2       $vf9, 0x0($s0)
    /* 2A24 001029A4 0038A348 */  qmtc2      $v1, $vf7
    /* 2A28 001029A8 0080C048 */  ctc2       $zero, $vi16
    /* 2A2C 001029AC 6C31A44B */  vsub.xyw   $vf5, $vf6, $vf4
    /* 2A30 001029B0 6C39864B */  vsub.xy    $vf5, $vf7, $vf6
    /* 2A34 001029B4 6C41A44B */  vsub.xyw   $vf5, $vf8, $vf4
    /* 2A38 001029B8 6C39884B */  vsub.xy    $vf5, $vf7, $vf8
    /* 2A3C 001029BC 6C49A44B */  vsub.xyw   $vf5, $vf9, $vf4
    /* 2A40 001029C0 6C39894B */  vsub.xy    $vf5, $vf7, $vf9
    /* 2A44 001029C4 FF02004A */  vnop
    /* 2A48 001029C8 FF02004A */  vnop
    /* 2A4C 001029CC FF02004A */  vnop
    /* 2A50 001029D0 FF02004A */  vnop
    /* 2A54 001029D4 FF02004A */  vnop
    /* 2A58 001029D8 00804348 */  cfc2       $v1, $vi16
    /* 2A5C 001029DC C0006330 */  andi       $v1, $v1, 0xC0
    /* 2A60 001029E0 03004010 */  beqz       $v0, .L001029F0
    /* 2A64 001029E4 2D806000 */   daddu     $s0, $v1, $zero
    /* 2A68 001029E8 0E30040C */  jal        func_0010C038
    /* 2A6C 001029EC 00000000 */   nop
  .L001029F0:
    /* 2A70 001029F0 2D100002 */  daddu      $v0, $s0, $zero
    /* 2A74 001029F4 3000BFDF */  ld         $ra, 0x30($sp)
    /* 2A78 001029F8 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2A7C 001029FC 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2A80 00102A00 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2A84 00102A04 0800E003 */  jr         $ra
    /* 2A88 00102A08 4000BD27 */   addiu     $sp, $sp, 0x40
    /* 2A8C 00102A0C 00000000 */  nop
.size func_00102960, . - func_00102960

/* Handwritten function */
glabel func_00102A10
    /* 2A90 00102A10 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 2A94 00102A14 4000B4FF */  sd         $s4, 0x40($sp)
    /* 2A98 00102A18 3000B3FF */  sd         $s3, 0x30($sp)
    /* 2A9C 00102A1C 2DA08000 */  daddu      $s4, $a0, $zero
    /* 2AA0 00102A20 2000B2FF */  sd         $s2, 0x20($sp)
    /* 2AA4 00102A24 2D98A000 */  daddu      $s3, $a1, $zero
    /* 2AA8 00102A28 1000B1FF */  sd         $s1, 0x10($sp)
    /* 2AAC 00102A2C 2D90C000 */  daddu      $s2, $a2, $zero
    /* 2AB0 00102A30 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2AB4 00102A34 2D88E000 */  daddu      $s1, $a3, $zero
    /* 2AB8 00102A38 5000BFFF */  sd         $ra, 0x50($sp)
    /* 2ABC 00102A3C F82F040C */  jal        func_0010BFE0
    /* 2AC0 00102A40 2D800001 */   daddu     $s0, $t0, $zero
    /* 2AC4 00102A44 000028DA */  lqc2       $vf8, 0x0($s1)
    /* 2AC8 00102A48 000044DA */  lqc2       $vf4, 0x0($s2)
    /* 2ACC 00102A4C 100045DA */  lqc2       $vf5, 0x10($s2)
    /* 2AD0 00102A50 200046DA */  lqc2       $vf6, 0x20($s2)
    /* 2AD4 00102A54 300047DA */  lqc2       $vf7, 0x30($s2)
    /* 2AD8 00102A58 000089DA */  lqc2       $vf9, 0x0($s4)
    /* 2ADC 00102A5C 00006ADA */  lqc2       $vf10, 0x0($s3)
    /* 2AE0 00102A60 00008BDA */  lqc2       $vf11, 0x0($s4)
    /* 2AE4 00102A64 00006CDA */  lqc2       $vf12, 0x0($s3)
  .L00102A68:
    /* 2AE8 00102A68 BC21E84B */  vmulax.xyzw $ACC, $vf4, $vf8x
    /* 2AEC 00102A6C BD28E84B */  vmadday.xyzw $ACC, $vf5, $vf8y
    /* 2AF0 00102A70 BE30E84B */  vmaddaz.xyzw $ACC, $vf6, $vf8z
    /* 2AF4 00102A74 0B3AE84B */  vmaddw.xyzw $vf8, $vf7, $vf8w
    /* 2AF8 00102A78 DB4AC84B */  vmulw.xyz  $vf11, $vf9, $vf8w
    /* 2AFC 00102A7C 1B53C84B */  vmulw.xyz  $vf12, $vf10, $vf8w
    /* 2B00 00102A80 FF02004A */  vnop
    /* 2B04 00102A84 FF02004A */  vnop
    /* 2B08 00102A88 0080C048 */  ctc2       $zero, $vi16
    /* 2B0C 00102A8C EC42AB4B */  vsub.xyw   $vf11, $vf8, $vf11
    /* 2B10 00102A90 2C63A84B */  vsub.xyw   $vf12, $vf12, $vf8
    /* 2B14 00102A94 3C4B2B4A */  vmove.w    $vf11, $vf9
    /* 2B18 00102A98 3C532C4A */  vmove.w    $vf12, $vf10
    /* 2B1C 00102A9C FF02004A */  vnop
    /* 2B20 00102AA0 10003122 */  addi       $s1, $s1, 0x10 /* handwritten instruction */
    /* 2B24 00102AA4 000028DA */  lqc2       $vf8, 0x0($s1)
    /* 2B28 00102AA8 FFFF1022 */  addi       $s0, $s0, -0x1 /* handwritten instruction */
    /* 2B2C 00102AAC 00804348 */  cfc2       $v1, $vi16
    /* 2B30 00102AB0 C0006330 */  andi       $v1, $v1, 0xC0
    /* 2B34 00102AB4 04006010 */  beqz       $v1, .L00102AC8
    /* 2B38 00102AB8 00000000 */   nop
    /* 2B3C 00102ABC EAFF1014 */  bne        $zero, $s0, .L00102A68
    /* 2B40 00102AC0 00000000 */   nop
    /* 2B44 00102AC4 01000320 */  addi       $v1, $zero, 0x1 /* handwritten instruction */
  .L00102AC8:
    /* 2B48 00102AC8 03004010 */  beqz       $v0, .L00102AD8
    /* 2B4C 00102ACC 2D806000 */   daddu     $s0, $v1, $zero
    /* 2B50 00102AD0 0E30040C */  jal        func_0010C038
    /* 2B54 00102AD4 00000000 */   nop
  .L00102AD8:
    /* 2B58 00102AD8 2D100002 */  daddu      $v0, $s0, $zero
    /* 2B5C 00102ADC 5000BFDF */  ld         $ra, 0x50($sp)
    /* 2B60 00102AE0 4000B4DF */  ld         $s4, 0x40($sp)
    /* 2B64 00102AE4 3000B3DF */  ld         $s3, 0x30($sp)
    /* 2B68 00102AE8 2000B2DF */  ld         $s2, 0x20($sp)
    /* 2B6C 00102AEC 1000B1DF */  ld         $s1, 0x10($sp)
    /* 2B70 00102AF0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2B74 00102AF4 0800E003 */  jr         $ra
    /* 2B78 00102AF8 6000BD27 */   addiu     $sp, $sp, 0x60
    /* 2B7C 00102AFC 00000000 */  nop
.size func_00102A10, . - func_00102A10

glabel func_00102B00
    /* 2B80 00102B00 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 2B84 00102B04 0000BFFF */  sd         $ra, 0x0($sp)
    /* 2B88 00102B08 F82F040C */  jal        func_0010BFE0
    /* 2B8C 00102B0C 00000000 */   nop
    /* 2B90 00102B10 0010033C */  lui        $v1, (0x10003830 >> 16)
    /* 2B94 00102B14 0010043C */  lui        $a0, (0x10003820 >> 16)
    /* 2B98 00102B18 30386334 */  ori        $v1, $v1, (0x10003830 & 0xFFFF)
    /* 2B9C 00102B1C 20388434 */  ori        $a0, $a0, (0x10003820 & 0xFFFF)
    /* 2BA0 00102B20 000060AC */  sw         $zero, 0x0($v1)
    /* 2BA4 00102B24 0010053C */  lui        $a1, (0x10003810 >> 16)
    /* 2BA8 00102B28 000080AC */  sw         $zero, 0x0($a0)
    /* 2BAC 00102B2C 1038A534 */  ori        $a1, $a1, (0x10003810 & 0xFFFF)
    /* 2BB0 00102B30 01000324 */  addiu      $v1, $zero, 0x1
    /* 2BB4 00102B34 0000A3AC */  sw         $v1, 0x0($a1)
    /* 2BB8 00102B38 00E04848 */  cfc2       $t0, $vi28
    /* 2BBC 00102B3C 02000835 */  ori        $t0, $t0, 0x2
    /* 2BC0 00102B40 00E0C848 */  ctc2       $t0, $vi28
    /* 2BC4 00102B44 0F040000 */  sync.p
    /* 2BC8 00102B48 3E00053C */  lui        $a1, %hi(D_003E75A0)
    /* 2BCC 00102B4C 0010063C */  lui        $a2, (0x10004000 >> 16)
    /* 2BD0 00102B50 A075A524 */  addiu      $a1, $a1, %lo(D_003E75A0)
    /* 2BD4 00102B54 0040C634 */  ori        $a2, $a2, (0x10004000 & 0xFFFF)
    /* 2BD8 00102B58 0000A378 */  lq         $v1, 0x0($a1)
    /* 2BDC 00102B5C 0000C37C */  sq         $v1, 0x0($a2)
    /* 2BE0 00102B60 1000A478 */  lq         $a0, 0x10($a1)
    /* 2BE4 00102B64 0000C47C */  sq         $a0, 0x0($a2)
    /* 2BE8 00102B68 03004010 */  beqz       $v0, .L00102B78
    /* 2BEC 00102B6C 0000BFDF */   ld        $ra, 0x0($sp)
    /* 2BF0 00102B70 0E300408 */  j          func_0010C038
    /* 2BF4 00102B74 1000BD27 */   addiu     $sp, $sp, 0x10
  .L00102B78:
    /* 2BF8 00102B78 0800E003 */  jr         $ra
    /* 2BFC 00102B7C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00102B00, . - func_00102B00

/* Handwritten function */
glabel func_00102B80
    /* 2C00 00102B80 00000324 */  addiu      $v1, $zero, 0x0
    /* 2C04 00102B84 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C08 00102B88 0800E003 */  jr         $ra
    /* 2C0C 00102B8C 00000000 */   nop
.size func_00102B80, . - func_00102B80

/* Handwritten function */
glabel func_00102B90
    /* 2C10 00102B90 01000324 */  addiu      $v1, $zero, 0x1
    /* 2C14 00102B94 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C18 00102B98 0800E003 */  jr         $ra
    /* 2C1C 00102B9C 00000000 */   nop
.size func_00102B90, . - func_00102B90

/* Handwritten function */
glabel func_00102BA0
    /* 2C20 00102BA0 02000324 */  addiu      $v1, $zero, 0x2
    /* 2C24 00102BA4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C28 00102BA8 0800E003 */  jr         $ra
    /* 2C2C 00102BAC 00000000 */   nop
.size func_00102BA0, . - func_00102BA0

/* Handwritten function */
glabel func_00102BB0
    /* 2C30 00102BB0 03000324 */  addiu      $v1, $zero, 0x3
    /* 2C34 00102BB4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C38 00102BB8 0800E003 */  jr         $ra
    /* 2C3C 00102BBC 00000000 */   nop
.size func_00102BB0, . - func_00102BB0

/* Handwritten function */
glabel func_00102BC0
    /* 2C40 00102BC0 04000324 */  addiu      $v1, $zero, 0x4
    /* 2C44 00102BC4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C48 00102BC8 0800E003 */  jr         $ra
    /* 2C4C 00102BCC 00000000 */   nop
.size func_00102BC0, . - func_00102BC0

/* Handwritten function */
glabel func_00102BD0
    /* 2C50 00102BD0 05000324 */  addiu      $v1, $zero, 0x5
    /* 2C54 00102BD4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C58 00102BD8 0800E003 */  jr         $ra
    /* 2C5C 00102BDC 00000000 */   nop
.size func_00102BD0, . - func_00102BD0

/* Handwritten function */
glabel func_00102BE0
    /* 2C60 00102BE0 06000324 */  addiu      $v1, $zero, 0x6
    /* 2C64 00102BE4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C68 00102BE8 0800E003 */  jr         $ra
    /* 2C6C 00102BEC 00000000 */   nop
.size func_00102BE0, . - func_00102BE0

/* Handwritten function */
glabel func_00102BF0
    /* 2C70 00102BF0 07000324 */  addiu      $v1, $zero, 0x7
    /* 2C74 00102BF4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C78 00102BF8 0800E003 */  jr         $ra
    /* 2C7C 00102BFC 00000000 */   nop
.size func_00102BF0, . - func_00102BF0

/* Handwritten function */
glabel func_00102C00
    /* 2C80 00102C00 08000324 */  addiu      $v1, $zero, 0x8
    /* 2C84 00102C04 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C88 00102C08 0800E003 */  jr         $ra
    /* 2C8C 00102C0C 00000000 */   nop
.size func_00102C00, . - func_00102C00

/* Handwritten function */
glabel func_00102C10
    /* 2C90 00102C10 09000324 */  addiu      $v1, $zero, 0x9
    /* 2C94 00102C14 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2C98 00102C18 0800E003 */  jr         $ra
    /* 2C9C 00102C1C 00000000 */   nop
.size func_00102C10, . - func_00102C10

/* Handwritten function */
glabel func_00102C20
    /* 2CA0 00102C20 0A000324 */  addiu      $v1, $zero, 0xA
    /* 2CA4 00102C24 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2CA8 00102C28 0800E003 */  jr         $ra
    /* 2CAC 00102C2C 00000000 */   nop
.size func_00102C20, . - func_00102C20

/* Handwritten function */
glabel func_00102C30
    /* 2CB0 00102C30 0B000324 */  addiu      $v1, $zero, 0xB
    /* 2CB4 00102C34 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2CB8 00102C38 0800E003 */  jr         $ra
    /* 2CBC 00102C3C 00000000 */   nop
.size func_00102C30, . - func_00102C30

/* Handwritten function */
glabel func_00102C40
    /* 2CC0 00102C40 0C000324 */  addiu      $v1, $zero, 0xC
    /* 2CC4 00102C44 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2CC8 00102C48 0800E003 */  jr         $ra
    /* 2CCC 00102C4C 00000000 */   nop
.size func_00102C40, . - func_00102C40

/* Handwritten function */
glabel func_00102C50
    /* 2CD0 00102C50 0D000324 */  addiu      $v1, $zero, 0xD
    /* 2CD4 00102C54 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2CD8 00102C58 0800E003 */  jr         $ra
    /* 2CDC 00102C5C 00000000 */   nop
.size func_00102C50, . - func_00102C50

/* Handwritten function */
glabel func_00102C60
    /* 2CE0 00102C60 0E000324 */  addiu      $v1, $zero, 0xE
    /* 2CE4 00102C64 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2CE8 00102C68 0800E003 */  jr         $ra
    /* 2CEC 00102C6C 00000000 */   nop
.size func_00102C60, . - func_00102C60

/* Handwritten function */
glabel func_00102C70
    /* 2CF0 00102C70 0F000324 */  addiu      $v1, $zero, 0xF
    /* 2CF4 00102C74 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2CF8 00102C78 0800E003 */  jr         $ra
    /* 2CFC 00102C7C 00000000 */   nop
.size func_00102C70, . - func_00102C70

/* Handwritten function */
glabel func_00102C80
    /* 2D00 00102C80 10000324 */  addiu      $v1, $zero, 0x10
    /* 2D04 00102C84 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D08 00102C88 0800E003 */  jr         $ra
    /* 2D0C 00102C8C 00000000 */   nop
.size func_00102C80, . - func_00102C80

/* Handwritten function */
glabel func_00102C90
    /* 2D10 00102C90 10000324 */  addiu      $v1, $zero, 0x10
    /* 2D14 00102C94 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D18 00102C98 0800E003 */  jr         $ra
    /* 2D1C 00102C9C 00000000 */   nop
.size func_00102C90, . - func_00102C90

/* Handwritten function */
glabel func_00102CA0
    /* 2D20 00102CA0 11000324 */  addiu      $v1, $zero, 0x11
    /* 2D24 00102CA4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D28 00102CA8 0800E003 */  jr         $ra
    /* 2D2C 00102CAC 00000000 */   nop
.size func_00102CA0, . - func_00102CA0

/* Handwritten function */
glabel func_00102CB0
    /* 2D30 00102CB0 12000324 */  addiu      $v1, $zero, 0x12
    /* 2D34 00102CB4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D38 00102CB8 0800E003 */  jr         $ra
    /* 2D3C 00102CBC 00000000 */   nop
.size func_00102CB0, . - func_00102CB0

/* Handwritten function */
glabel func_00102CC0
    /* 2D40 00102CC0 12000324 */  addiu      $v1, $zero, 0x12
    /* 2D44 00102CC4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D48 00102CC8 0800E003 */  jr         $ra
    /* 2D4C 00102CCC 00000000 */   nop
.size func_00102CC0, . - func_00102CC0

/* Handwritten function */
glabel func_00102CD0
    /* 2D50 00102CD0 13000324 */  addiu      $v1, $zero, 0x13
    /* 2D54 00102CD4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D58 00102CD8 0800E003 */  jr         $ra
    /* 2D5C 00102CDC 00000000 */   nop
.size func_00102CD0, . - func_00102CD0

/* Handwritten function */
glabel func_00102CE0
    /* 2D60 00102CE0 14000324 */  addiu      $v1, $zero, 0x14
    /* 2D64 00102CE4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D68 00102CE8 0800E003 */  jr         $ra
    /* 2D6C 00102CEC 00000000 */   nop
.size func_00102CE0, . - func_00102CE0

/* Handwritten function */
glabel func_00102CF0
    /* 2D70 00102CF0 15000324 */  addiu      $v1, $zero, 0x15
    /* 2D74 00102CF4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D78 00102CF8 0800E003 */  jr         $ra
    /* 2D7C 00102CFC 00000000 */   nop
.size func_00102CF0, . - func_00102CF0

/* Handwritten function */
glabel func_00102D00
    /* 2D80 00102D00 16000324 */  addiu      $v1, $zero, 0x16
    /* 2D84 00102D04 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D88 00102D08 0800E003 */  jr         $ra
    /* 2D8C 00102D0C 00000000 */   nop
.size func_00102D00, . - func_00102D00

/* Handwritten function */
glabel func_00102D10
    /* 2D90 00102D10 17000324 */  addiu      $v1, $zero, 0x17
    /* 2D94 00102D14 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2D98 00102D18 0800E003 */  jr         $ra
    /* 2D9C 00102D1C 00000000 */   nop
.size func_00102D10, . - func_00102D10

/* Handwritten function */
glabel func_00102D20
    /* 2DA0 00102D20 FC000324 */  addiu      $v1, $zero, 0xFC
    /* 2DA4 00102D24 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2DA8 00102D28 0800E003 */  jr         $ra
    /* 2DAC 00102D2C 00000000 */   nop
.size func_00102D20, . - func_00102D20

/* Handwritten function */
glabel func_00102D30
    /* 2DB0 00102D30 FD000324 */  addiu      $v1, $zero, 0xFD
    /* 2DB4 00102D34 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2DB8 00102D38 0800E003 */  jr         $ra
    /* 2DBC 00102D3C 00000000 */   nop
.size func_00102D30, . - func_00102D30

/* Handwritten function */
glabel func_00102D40
    /* 2DC0 00102D40 E6FF0324 */  addiu      $v1, $zero, -0x1A
    /* 2DC4 00102D44 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2DC8 00102D48 0800E003 */  jr         $ra
    /* 2DCC 00102D4C 00000000 */   nop
.size func_00102D40, . - func_00102D40

/* Handwritten function */
glabel func_00102D50
    /* 2DD0 00102D50 E5FF0324 */  addiu      $v1, $zero, -0x1B
    /* 2DD4 00102D54 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2DD8 00102D58 0800E003 */  jr         $ra
    /* 2DDC 00102D5C 00000000 */   nop
.size func_00102D50, . - func_00102D50

/* Handwritten function */
glabel func_00102D60
    /* 2DE0 00102D60 E4FF0324 */  addiu      $v1, $zero, -0x1C
    /* 2DE4 00102D64 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2DE8 00102D68 0800E003 */  jr         $ra
    /* 2DEC 00102D6C 00000000 */   nop
.size func_00102D60, . - func_00102D60

/* Handwritten function */
glabel func_00102D70
    /* 2DF0 00102D70 E3FF0324 */  addiu      $v1, $zero, -0x1D
    /* 2DF4 00102D74 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2DF8 00102D78 0800E003 */  jr         $ra
    /* 2DFC 00102D7C 00000000 */   nop
.size func_00102D70, . - func_00102D70

/* Handwritten function */
glabel func_00102D80
    /* 2E00 00102D80 02FF0324 */  addiu      $v1, $zero, -0xFE
    /* 2E04 00102D84 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E08 00102D88 0800E003 */  jr         $ra
    /* 2E0C 00102D8C 00000000 */   nop
.size func_00102D80, . - func_00102D80

/* Handwritten function */
glabel func_00102D90
    /* 2E10 00102D90 01FF0324 */  addiu      $v1, $zero, -0xFF
    /* 2E14 00102D94 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E18 00102D98 0800E003 */  jr         $ra
    /* 2E1C 00102D9C 00000000 */   nop
.size func_00102D90, . - func_00102D90

/* Handwritten function */
glabel func_00102DA0
    /* 2E20 00102DA0 20000324 */  addiu      $v1, $zero, 0x20
    /* 2E24 00102DA4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E28 00102DA8 0800E003 */  jr         $ra
    /* 2E2C 00102DAC 00000000 */   nop
.size func_00102DA0, . - func_00102DA0

/* Handwritten function */
glabel func_00102DB0
    /* 2E30 00102DB0 21000324 */  addiu      $v1, $zero, 0x21
    /* 2E34 00102DB4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E38 00102DB8 0800E003 */  jr         $ra
    /* 2E3C 00102DBC 00000000 */   nop
.size func_00102DB0, . - func_00102DB0

/* Handwritten function */
glabel func_00102DC0
    /* 2E40 00102DC0 22000324 */  addiu      $v1, $zero, 0x22
    /* 2E44 00102DC4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E48 00102DC8 0800E003 */  jr         $ra
    /* 2E4C 00102DCC 00000000 */   nop
.size func_00102DC0, . - func_00102DC0

/* Handwritten function */
glabel func_00102DD0
    /* 2E50 00102DD0 23000324 */  addiu      $v1, $zero, 0x23
    /* 2E54 00102DD4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E58 00102DD8 0800E003 */  jr         $ra
    /* 2E5C 00102DDC 00000000 */   nop
.size func_00102DD0, . - func_00102DD0

/* Handwritten function */
glabel func_00102DE0
    /* 2E60 00102DE0 24000324 */  addiu      $v1, $zero, 0x24
    /* 2E64 00102DE4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E68 00102DE8 0800E003 */  jr         $ra
    /* 2E6C 00102DEC 00000000 */   nop
.size func_00102DE0, . - func_00102DE0

/* Handwritten function */
glabel func_00102DF0
    /* 2E70 00102DF0 25000324 */  addiu      $v1, $zero, 0x25
    /* 2E74 00102DF4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E78 00102DF8 0800E003 */  jr         $ra
    /* 2E7C 00102DFC 00000000 */   nop
.size func_00102DF0, . - func_00102DF0

/* Handwritten function */
glabel func_00102E00
    /* 2E80 00102E00 DAFF0324 */  addiu      $v1, $zero, -0x26
    /* 2E84 00102E04 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E88 00102E08 0800E003 */  jr         $ra
    /* 2E8C 00102E0C 00000000 */   nop
.size func_00102E00, . - func_00102E00

/* Handwritten function */
glabel func_00102E10
    /* 2E90 00102E10 27000324 */  addiu      $v1, $zero, 0x27
    /* 2E94 00102E14 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2E98 00102E18 0800E003 */  jr         $ra
    /* 2E9C 00102E1C 00000000 */   nop
.size func_00102E10, . - func_00102E10

/* Handwritten function */
glabel func_00102E20
    /* 2EA0 00102E20 28000324 */  addiu      $v1, $zero, 0x28
    /* 2EA4 00102E24 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2EA8 00102E28 0800E003 */  jr         $ra
    /* 2EAC 00102E2C 00000000 */   nop
.size func_00102E20, . - func_00102E20

/* Handwritten function */
glabel func_00102E30
    /* 2EB0 00102E30 29000324 */  addiu      $v1, $zero, 0x29
    /* 2EB4 00102E34 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2EB8 00102E38 0800E003 */  jr         $ra
    /* 2EBC 00102E3C 00000000 */   nop
.size func_00102E30, . - func_00102E30

/* Handwritten function */
glabel func_00102E40
    /* 2EC0 00102E40 D6FF0324 */  addiu      $v1, $zero, -0x2A
    /* 2EC4 00102E44 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2EC8 00102E48 0800E003 */  jr         $ra
    /* 2ECC 00102E4C 00000000 */   nop
.size func_00102E40, . - func_00102E40

/* Handwritten function */
glabel func_00102E50
    /* 2ED0 00102E50 2B000324 */  addiu      $v1, $zero, 0x2B
    /* 2ED4 00102E54 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2ED8 00102E58 0800E003 */  jr         $ra
    /* 2EDC 00102E5C 00000000 */   nop
.size func_00102E50, . - func_00102E50

/* Handwritten function */
glabel func_00102E60
    /* 2EE0 00102E60 D4FF0324 */  addiu      $v1, $zero, -0x2C
    /* 2EE4 00102E64 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2EE8 00102E68 0800E003 */  jr         $ra
    /* 2EEC 00102E6C 00000000 */   nop
.size func_00102E60, . - func_00102E60

/* Handwritten function */
glabel func_00102E70
    /* 2EF0 00102E70 2D000324 */  addiu      $v1, $zero, 0x2D
    /* 2EF4 00102E74 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2EF8 00102E78 0800E003 */  jr         $ra
    /* 2EFC 00102E7C 00000000 */   nop
.size func_00102E70, . - func_00102E70

/* Handwritten function */
glabel func_00102E80
    /* 2F00 00102E80 D2FF0324 */  addiu      $v1, $zero, -0x2E
    /* 2F04 00102E84 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F08 00102E88 0800E003 */  jr         $ra
    /* 2F0C 00102E8C 00000000 */   nop
.size func_00102E80, . - func_00102E80

/* Handwritten function */
glabel func_00102E90
    /* 2F10 00102E90 2F000324 */  addiu      $v1, $zero, 0x2F
    /* 2F14 00102E94 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F18 00102E98 0800E003 */  jr         $ra
    /* 2F1C 00102E9C 00000000 */   nop
.size func_00102E90, . - func_00102E90

/* Handwritten function */
glabel func_00102EA0
    /* 2F20 00102EA0 30000324 */  addiu      $v1, $zero, 0x30
    /* 2F24 00102EA4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F28 00102EA8 0800E003 */  jr         $ra
    /* 2F2C 00102EAC 00000000 */   nop
.size func_00102EA0, . - func_00102EA0

/* Handwritten function */
glabel func_00102EB0
    /* 2F30 00102EB0 CFFF0324 */  addiu      $v1, $zero, -0x31
    /* 2F34 00102EB4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F38 00102EB8 0800E003 */  jr         $ra
    /* 2F3C 00102EBC 00000000 */   nop
.size func_00102EB0, . - func_00102EB0

/* Handwritten function */
glabel func_00102EC0
    /* 2F40 00102EC0 32000324 */  addiu      $v1, $zero, 0x32
    /* 2F44 00102EC4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F48 00102EC8 0800E003 */  jr         $ra
    /* 2F4C 00102ECC 00000000 */   nop
.size func_00102EC0, . - func_00102EC0

/* Handwritten function */
glabel func_00102ED0
    /* 2F50 00102ED0 33000324 */  addiu      $v1, $zero, 0x33
    /* 2F54 00102ED4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F58 00102ED8 0800E003 */  jr         $ra
    /* 2F5C 00102EDC 00000000 */   nop
.size func_00102ED0, . - func_00102ED0

/* Handwritten function */
glabel func_00102EE0
    /* 2F60 00102EE0 CCFF0324 */  addiu      $v1, $zero, -0x34
    /* 2F64 00102EE4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F68 00102EE8 0800E003 */  jr         $ra
    /* 2F6C 00102EEC 00000000 */   nop
.size func_00102EE0, . - func_00102EE0

/* Handwritten function */
glabel func_00102EF0
    /* 2F70 00102EF0 35000324 */  addiu      $v1, $zero, 0x35
    /* 2F74 00102EF4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F78 00102EF8 0800E003 */  jr         $ra
    /* 2F7C 00102EFC 00000000 */   nop
.size func_00102EF0, . - func_00102EF0

/* Handwritten function */
glabel func_00102F00
    /* 2F80 00102F00 CAFF0324 */  addiu      $v1, $zero, -0x36
    /* 2F84 00102F04 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F88 00102F08 0800E003 */  jr         $ra
    /* 2F8C 00102F0C 00000000 */   nop
.size func_00102F00, . - func_00102F00

/* Handwritten function */
glabel func_00102F10
    /* 2F90 00102F10 37000324 */  addiu      $v1, $zero, 0x37
    /* 2F94 00102F14 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2F98 00102F18 0800E003 */  jr         $ra
    /* 2F9C 00102F1C 00000000 */   nop
.size func_00102F10, . - func_00102F10

/* Handwritten function */
glabel func_00102F20
    /* 2FA0 00102F20 C8FF0324 */  addiu      $v1, $zero, -0x38
    /* 2FA4 00102F24 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2FA8 00102F28 0800E003 */  jr         $ra
    /* 2FAC 00102F2C 00000000 */   nop
.size func_00102F20, . - func_00102F20

/* Handwritten function */
glabel func_00102F30
    /* 2FB0 00102F30 39000324 */  addiu      $v1, $zero, 0x39
    /* 2FB4 00102F34 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2FB8 00102F38 0800E003 */  jr         $ra
    /* 2FBC 00102F3C 00000000 */   nop
.size func_00102F30, . - func_00102F30

/* Handwritten function */
glabel func_00102F40
    /* 2FC0 00102F40 C6FF0324 */  addiu      $v1, $zero, -0x3A
    /* 2FC4 00102F44 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2FC8 00102F48 0800E003 */  jr         $ra
    /* 2FCC 00102F4C 00000000 */   nop
.size func_00102F40, . - func_00102F40

/* Handwritten function */
glabel func_00102F50
    /* 2FD0 00102F50 3B000324 */  addiu      $v1, $zero, 0x3B
    /* 2FD4 00102F54 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2FD8 00102F58 0800E003 */  jr         $ra
    /* 2FDC 00102F5C 00000000 */   nop
.size func_00102F50, . - func_00102F50

/* Handwritten function */
glabel func_00102F60
    /* 2FE0 00102F60 3C000324 */  addiu      $v1, $zero, 0x3C
    /* 2FE4 00102F64 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2FE8 00102F68 0800E003 */  jr         $ra
    /* 2FEC 00102F6C 00000000 */   nop
.size func_00102F60, . - func_00102F60

/* Handwritten function */
glabel func_00102F70
    /* 2FF0 00102F70 3D000324 */  addiu      $v1, $zero, 0x3D
    /* 2FF4 00102F74 0C000000 */  syscall    0 /* handwritten instruction */
    /* 2FF8 00102F78 0800E003 */  jr         $ra
    /* 2FFC 00102F7C 00000000 */   nop
.size func_00102F70, . - func_00102F70

/* Handwritten function */
glabel func_00102F80
    /* 3000 00102F80 3E000324 */  addiu      $v1, $zero, 0x3E
    /* 3004 00102F84 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3008 00102F88 0800E003 */  jr         $ra
    /* 300C 00102F8C 00000000 */   nop
.size func_00102F80, . - func_00102F80

/* Handwritten function */
glabel func_00102F90
    /* 3010 00102F90 3F000324 */  addiu      $v1, $zero, 0x3F
    /* 3014 00102F94 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3018 00102F98 0800E003 */  jr         $ra
    /* 301C 00102F9C 00000000 */   nop
.size func_00102F90, . - func_00102F90

/* Handwritten function */
glabel func_00102FA0
    /* 3020 00102FA0 40000324 */  addiu      $v1, $zero, 0x40
    /* 3024 00102FA4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3028 00102FA8 0800E003 */  jr         $ra
    /* 302C 00102FAC 00000000 */   nop
.size func_00102FA0, . - func_00102FA0

/* Handwritten function */
glabel func_00102FB0
    /* 3030 00102FB0 41000324 */  addiu      $v1, $zero, 0x41
    /* 3034 00102FB4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3038 00102FB8 0800E003 */  jr         $ra
    /* 303C 00102FBC 00000000 */   nop
.size func_00102FB0, . - func_00102FB0

/* Handwritten function */
glabel func_00102FC0
    /* 3040 00102FC0 42000324 */  addiu      $v1, $zero, 0x42
    /* 3044 00102FC4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3048 00102FC8 0800E003 */  jr         $ra
    /* 304C 00102FCC 00000000 */   nop
.size func_00102FC0, . - func_00102FC0

/* Handwritten function */
glabel func_00102FD0
    /* 3050 00102FD0 BDFF0324 */  addiu      $v1, $zero, -0x43
    /* 3054 00102FD4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3058 00102FD8 0800E003 */  jr         $ra
    /* 305C 00102FDC 00000000 */   nop
.size func_00102FD0, . - func_00102FD0

/* Handwritten function */
glabel func_00102FE0
    /* 3060 00102FE0 44000324 */  addiu      $v1, $zero, 0x44
    /* 3064 00102FE4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3068 00102FE8 0800E003 */  jr         $ra
    /* 306C 00102FEC 00000000 */   nop
.size func_00102FE0, . - func_00102FE0

/* Handwritten function */
glabel func_00102FF0
    /* 3070 00102FF0 45000324 */  addiu      $v1, $zero, 0x45
    /* 3074 00102FF4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3078 00102FF8 0800E003 */  jr         $ra
    /* 307C 00102FFC 00000000 */   nop
.size func_00102FF0, . - func_00102FF0

/* Handwritten function */
glabel func_00103000
    /* 3080 00103000 BAFF0324 */  addiu      $v1, $zero, -0x46
    /* 3084 00103004 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3088 00103008 0800E003 */  jr         $ra
    /* 308C 0010300C 00000000 */   nop
.size func_00103000, . - func_00103000

/* Handwritten function */
glabel func_00103010
    /* 3090 00103010 47000324 */  addiu      $v1, $zero, 0x47
    /* 3094 00103014 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3098 00103018 0800E003 */  jr         $ra
    /* 309C 0010301C 00000000 */   nop
.size func_00103010, . - func_00103010

/* Handwritten function */
glabel func_00103020
    /* 30A0 00103020 B8FF0324 */  addiu      $v1, $zero, -0x48
    /* 30A4 00103024 0C000000 */  syscall    0 /* handwritten instruction */
    /* 30A8 00103028 0800E003 */  jr         $ra
    /* 30AC 0010302C 00000000 */   nop
.size func_00103020, . - func_00103020

/* Handwritten function */
glabel func_00103030
    /* 30B0 00103030 49000324 */  addiu      $v1, $zero, 0x49
    /* 30B4 00103034 0C000000 */  syscall    0 /* handwritten instruction */
    /* 30B8 00103038 0800E003 */  jr         $ra
    /* 30BC 0010303C 00000000 */   nop
.size func_00103030, . - func_00103030

/* Handwritten function */
glabel func_00103040
    /* 30C0 00103040 4A000324 */  addiu      $v1, $zero, 0x4A
    /* 30C4 00103044 0C000000 */  syscall    0 /* handwritten instruction */
    /* 30C8 00103048 0800E003 */  jr         $ra
    /* 30CC 0010304C 00000000 */   nop
.size func_00103040, . - func_00103040

/* Handwritten function */
glabel func_00103050
    /* 30D0 00103050 4B000324 */  addiu      $v1, $zero, 0x4B
    /* 30D4 00103054 0C000000 */  syscall    0 /* handwritten instruction */
    /* 30D8 00103058 0800E003 */  jr         $ra
    /* 30DC 0010305C 00000000 */   nop
.size func_00103050, . - func_00103050

/* Handwritten function */
glabel func_00103060
    /* 30E0 00103060 4C000324 */  addiu      $v1, $zero, 0x4C
    /* 30E4 00103064 0C000000 */  syscall    0 /* handwritten instruction */
    /* 30E8 00103068 0800E003 */  jr         $ra
    /* 30EC 0010306C 00000000 */   nop
.size func_00103060, . - func_00103060

/* Handwritten function */
glabel func_00103070
    /* 30F0 00103070 4D000324 */  addiu      $v1, $zero, 0x4D
    /* 30F4 00103074 0C000000 */  syscall    0 /* handwritten instruction */
    /* 30F8 00103078 0800E003 */  jr         $ra
    /* 30FC 0010307C 00000000 */   nop
.size func_00103070, . - func_00103070

/* Handwritten function */
glabel func_00103080
    /* 3100 00103080 4E000324 */  addiu      $v1, $zero, 0x4E
    /* 3104 00103084 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3108 00103088 0800E003 */  jr         $ra
    /* 310C 0010308C 00000000 */   nop
.size func_00103080, . - func_00103080

/* Handwritten function */
glabel func_00103090
    /* 3110 00103090 4F000324 */  addiu      $v1, $zero, 0x4F
    /* 3114 00103094 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3118 00103098 0800E003 */  jr         $ra
    /* 311C 0010309C 00000000 */   nop
.size func_00103090, . - func_00103090

/* Handwritten function */
glabel func_001030A0
    /* 3120 001030A0 50000324 */  addiu      $v1, $zero, 0x50
    /* 3124 001030A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3128 001030A8 0800E003 */  jr         $ra
    /* 312C 001030AC 00000000 */   nop
.size func_001030A0, . - func_001030A0

/* Handwritten function */
glabel func_001030B0
    /* 3130 001030B0 51000324 */  addiu      $v1, $zero, 0x51
    /* 3134 001030B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3138 001030B8 0800E003 */  jr         $ra
    /* 313C 001030BC 00000000 */   nop
.size func_001030B0, . - func_001030B0

/* Handwritten function */
glabel func_001030C0
    /* 3140 001030C0 52000324 */  addiu      $v1, $zero, 0x52
    /* 3144 001030C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3148 001030C8 0800E003 */  jr         $ra
    /* 314C 001030CC 00000000 */   nop
.size func_001030C0, . - func_001030C0

/* Handwritten function */
glabel func_001030D0
    /* 3150 001030D0 ADFF0324 */  addiu      $v1, $zero, -0x53
    /* 3154 001030D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3158 001030D8 0800E003 */  jr         $ra
    /* 315C 001030DC 00000000 */   nop
.size func_001030D0, . - func_001030D0

/* Handwritten function */
glabel func_001030E0
    /* 3160 001030E0 54000324 */  addiu      $v1, $zero, 0x54
    /* 3164 001030E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3168 001030E8 0800E003 */  jr         $ra
    /* 316C 001030EC 00000000 */   nop
.size func_001030E0, . - func_001030E0

/* Handwritten function */
glabel func_001030F0
    /* 3170 001030F0 ABFF0324 */  addiu      $v1, $zero, -0x55
    /* 3174 001030F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3178 001030F8 0800E003 */  jr         $ra
    /* 317C 001030FC 00000000 */   nop
.size func_001030F0, . - func_001030F0

/* Handwritten function */
glabel func_00103100
    /* 3180 00103100 56000324 */  addiu      $v1, $zero, 0x56
    /* 3184 00103104 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3188 00103108 0800E003 */  jr         $ra
    /* 318C 0010310C 00000000 */   nop
.size func_00103100, . - func_00103100

/* Handwritten function */
glabel func_00103110
    /* 3190 00103110 57000324 */  addiu      $v1, $zero, 0x57
    /* 3194 00103114 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3198 00103118 0800E003 */  jr         $ra
    /* 319C 0010311C 00000000 */   nop
.size func_00103110, . - func_00103110

/* Handwritten function */
glabel func_00103120
    /* 31A0 00103120 A8FF0324 */  addiu      $v1, $zero, -0x58
    /* 31A4 00103124 0C000000 */  syscall    0 /* handwritten instruction */
    /* 31A8 00103128 0800E003 */  jr         $ra
    /* 31AC 0010312C 00000000 */   nop
.size func_00103120, . - func_00103120

/* Handwritten function */
glabel func_00103130
    /* 31B0 00103130 59000324 */  addiu      $v1, $zero, 0x59
    /* 31B4 00103134 0C000000 */  syscall    0 /* handwritten instruction */
    /* 31B8 00103138 0800E003 */  jr         $ra
    /* 31BC 0010313C 00000000 */   nop
.size func_00103130, . - func_00103130

/* Handwritten function */
glabel func_00103140
    /* 31C0 00103140 A6FF0324 */  addiu      $v1, $zero, -0x5A
    /* 31C4 00103144 0C000000 */  syscall    0 /* handwritten instruction */
    /* 31C8 00103148 0800E003 */  jr         $ra
    /* 31CC 0010314C 00000000 */   nop
.size func_00103140, . - func_00103140

/* Handwritten function */
glabel func_00103150
    /* 31D0 00103150 5B000324 */  addiu      $v1, $zero, 0x5B
    /* 31D4 00103154 0C000000 */  syscall    0 /* handwritten instruction */
    /* 31D8 00103158 0800E003 */  jr         $ra
    /* 31DC 0010315C 00000000 */   nop
.size func_00103150, . - func_00103150

/* Handwritten function */
glabel func_00103160
    /* 31E0 00103160 5C000324 */  addiu      $v1, $zero, 0x5C
    /* 31E4 00103164 0C000000 */  syscall    0 /* handwritten instruction */
    /* 31E8 00103168 0800E003 */  jr         $ra
    /* 31EC 0010316C 00000000 */   nop
.size func_00103160, . - func_00103160

/* Handwritten function */
glabel func_00103170
    /* 31F0 00103170 A4FF0324 */  addiu      $v1, $zero, -0x5C
    /* 31F4 00103174 0C000000 */  syscall    0 /* handwritten instruction */
    /* 31F8 00103178 0800E003 */  jr         $ra
    /* 31FC 0010317C 00000000 */   nop
.size func_00103170, . - func_00103170

/* Handwritten function */
glabel func_00103180
    /* 3200 00103180 5D000324 */  addiu      $v1, $zero, 0x5D
    /* 3204 00103184 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3208 00103188 0800E003 */  jr         $ra
    /* 320C 0010318C 00000000 */   nop
.size func_00103180, . - func_00103180

/* Handwritten function */
glabel func_00103190
    /* 3210 00103190 A3FF0324 */  addiu      $v1, $zero, -0x5D
    /* 3214 00103194 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3218 00103198 0800E003 */  jr         $ra
    /* 321C 0010319C 00000000 */   nop
.size func_00103190, . - func_00103190

/* Handwritten function */
glabel func_001031A0
    /* 3220 001031A0 5E000324 */  addiu      $v1, $zero, 0x5E
    /* 3224 001031A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3228 001031A8 0800E003 */  jr         $ra
    /* 322C 001031AC 00000000 */   nop
.size func_001031A0, . - func_001031A0

/* Handwritten function */
glabel func_001031B0
    /* 3230 001031B0 A2FF0324 */  addiu      $v1, $zero, -0x5E
    /* 3234 001031B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3238 001031B8 0800E003 */  jr         $ra
    /* 323C 001031BC 00000000 */   nop
.size func_001031B0, . - func_001031B0

/* Handwritten function */
glabel func_001031C0
    /* 3240 001031C0 5F000324 */  addiu      $v1, $zero, 0x5F
    /* 3244 001031C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3248 001031C8 0800E003 */  jr         $ra
    /* 324C 001031CC 00000000 */   nop
.size func_001031C0, . - func_001031C0

/* Handwritten function */
glabel func_001031D0
    /* 3250 001031D0 A1FF0324 */  addiu      $v1, $zero, -0x5F
    /* 3254 001031D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3258 001031D8 0800E003 */  jr         $ra
    /* 325C 001031DC 00000000 */   nop
.size func_001031D0, . - func_001031D0

/* Handwritten function */
glabel func_001031E0
    /* 3260 001031E0 60000324 */  addiu      $v1, $zero, 0x60
    /* 3264 001031E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3268 001031E8 0800E003 */  jr         $ra
    /* 326C 001031EC 00000000 */   nop
.size func_001031E0, . - func_001031E0

/* Handwritten function */
glabel func_001031F0
    /* 3270 001031F0 61000324 */  addiu      $v1, $zero, 0x61
    /* 3274 001031F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3278 001031F8 0800E003 */  jr         $ra
    /* 327C 001031FC 00000000 */   nop
.size func_001031F0, . - func_001031F0

/* Handwritten function */
glabel func_00103200
    /* 3280 00103200 62000324 */  addiu      $v1, $zero, 0x62
    /* 3284 00103204 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3288 00103208 0800E003 */  jr         $ra
    /* 328C 0010320C 00000000 */   nop
.size func_00103200, . - func_00103200

/* Handwritten function */
glabel func_00103210
    /* 3290 00103210 63000324 */  addiu      $v1, $zero, 0x63
    /* 3294 00103214 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3298 00103218 0800E003 */  jr         $ra
    /* 329C 0010321C 00000000 */   nop
.size func_00103210, . - func_00103210

/* Handwritten function */
glabel func_00103220
    /* 32A0 00103220 64000324 */  addiu      $v1, $zero, 0x64
    /* 32A4 00103224 0C000000 */  syscall    0 /* handwritten instruction */
    /* 32A8 00103228 0800E003 */  jr         $ra
    /* 32AC 0010322C 00000000 */   nop
.size func_00103220, . - func_00103220

/* Handwritten function */
glabel func_00103230
    /* 32B0 00103230 66000324 */  addiu      $v1, $zero, 0x66
    /* 32B4 00103234 0C000000 */  syscall    0 /* handwritten instruction */
    /* 32B8 00103238 0800E003 */  jr         $ra
    /* 32BC 0010323C 00000000 */   nop
.size func_00103230, . - func_00103230

/* Handwritten function */
glabel func_00103240
    /* 32C0 00103240 99FF0324 */  addiu      $v1, $zero, -0x67
    /* 32C4 00103244 0C000000 */  syscall    0 /* handwritten instruction */
    /* 32C8 00103248 0800E003 */  jr         $ra
    /* 32CC 0010324C 00000000 */   nop
.size func_00103240, . - func_00103240

/* Handwritten function */
glabel func_00103250
    /* 32D0 00103250 98FF0324 */  addiu      $v1, $zero, -0x68
    /* 32D4 00103254 0C000000 */  syscall    0 /* handwritten instruction */
    /* 32D8 00103258 0800E003 */  jr         $ra
    /* 32DC 0010325C 00000000 */   nop
.size func_00103250, . - func_00103250

/* Handwritten function */
glabel func_00103260
    /* 32E0 00103260 96FF0324 */  addiu      $v1, $zero, -0x6A
    /* 32E4 00103264 0C000000 */  syscall    0 /* handwritten instruction */
    /* 32E8 00103268 0800E003 */  jr         $ra
    /* 32EC 0010326C 00000000 */   nop
.size func_00103260, . - func_00103260

/* Handwritten function */
glabel func_00103270
    /* 32F0 00103270 6B000324 */  addiu      $v1, $zero, 0x6B
    /* 32F4 00103274 0C000000 */  syscall    0 /* handwritten instruction */
    /* 32F8 00103278 0800E003 */  jr         $ra
    /* 32FC 0010327C 00000000 */   nop
.size func_00103270, . - func_00103270

/* Handwritten function */
glabel func_00103280
    /* 3300 00103280 6C000324 */  addiu      $v1, $zero, 0x6C
    /* 3304 00103284 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3308 00103288 0800E003 */  jr         $ra
    /* 330C 0010328C 00000000 */   nop
.size func_00103280, . - func_00103280

/* Handwritten function */
glabel func_00103290
    /* 3310 00103290 6D000324 */  addiu      $v1, $zero, 0x6D
    /* 3314 00103294 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3318 00103298 0800E003 */  jr         $ra
    /* 331C 0010329C 00000000 */   nop
.size func_00103290, . - func_00103290

/* Handwritten function */
glabel func_001032A0
    /* 3320 001032A0 6E000324 */  addiu      $v1, $zero, 0x6E
    /* 3324 001032A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3328 001032A8 0800E003 */  jr         $ra
    /* 332C 001032AC 00000000 */   nop
.size func_001032A0, . - func_001032A0

/* Handwritten function */
glabel func_001032B0
    /* 3330 001032B0 6F000324 */  addiu      $v1, $zero, 0x6F
    /* 3334 001032B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3338 001032B8 0800E003 */  jr         $ra
    /* 333C 001032BC 00000000 */   nop
.size func_001032B0, . - func_001032B0

/* Handwritten function */
glabel func_001032C0
    /* 3340 001032C0 70000324 */  addiu      $v1, $zero, 0x70
    /* 3344 001032C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3348 001032C8 0800E003 */  jr         $ra
    /* 334C 001032CC 00000000 */   nop
.size func_001032C0, . - func_001032C0

/* Handwritten function */
glabel func_001032D0
    /* 3350 001032D0 90FF0324 */  addiu      $v1, $zero, -0x70
    /* 3354 001032D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3358 001032D8 0800E003 */  jr         $ra
    /* 335C 001032DC 00000000 */   nop
.size func_001032D0, . - func_001032D0

/* Handwritten function */
glabel func_001032E0
    /* 3360 001032E0 71000324 */  addiu      $v1, $zero, 0x71
    /* 3364 001032E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3368 001032E8 0800E003 */  jr         $ra
    /* 336C 001032EC 00000000 */   nop
.size func_001032E0, . - func_001032E0

/* Handwritten function */
glabel func_001032F0
    /* 3370 001032F0 8FFF0324 */  addiu      $v1, $zero, -0x71
    /* 3374 001032F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3378 001032F8 0800E003 */  jr         $ra
    /* 337C 001032FC 00000000 */   nop
.size func_001032F0, . - func_001032F0

/* Handwritten function */
glabel func_00103300
    /* 3380 00103300 72000324 */  addiu      $v1, $zero, 0x72
    /* 3384 00103304 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3388 00103308 0800E003 */  jr         $ra
    /* 338C 0010330C 00000000 */   nop
.size func_00103300, . - func_00103300

/* Handwritten function */
glabel func_00103310
    /* 3390 00103310 73000324 */  addiu      $v1, $zero, 0x73
    /* 3394 00103314 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3398 00103318 0800E003 */  jr         $ra
    /* 339C 0010331C 00000000 */   nop
.size func_00103310, . - func_00103310

/* Handwritten function */
glabel func_00103320
    /* 33A0 00103320 74000324 */  addiu      $v1, $zero, 0x74
    /* 33A4 00103324 0C000000 */  syscall    0 /* handwritten instruction */
    /* 33A8 00103328 0800E003 */  jr         $ra
    /* 33AC 0010332C 00000000 */   nop
.size func_00103320, . - func_00103320

/* Handwritten function */
glabel func_00103330
    /* 33B0 00103330 75000324 */  addiu      $v1, $zero, 0x75
    /* 33B4 00103334 0C000000 */  syscall    0 /* handwritten instruction */
    /* 33B8 00103338 0800E003 */  jr         $ra
    /* 33BC 0010333C 00000000 */   nop
.size func_00103330, . - func_00103330

/* Handwritten function */
glabel func_00103340
    /* 33C0 00103340 76000324 */  addiu      $v1, $zero, 0x76
    /* 33C4 00103344 0C000000 */  syscall    0 /* handwritten instruction */
    /* 33C8 00103348 0800E003 */  jr         $ra
    /* 33CC 0010334C 00000000 */   nop
.size func_00103340, . - func_00103340

/* Handwritten function */
glabel func_00103350
    /* 33D0 00103350 8AFF0324 */  addiu      $v1, $zero, -0x76
    /* 33D4 00103354 0C000000 */  syscall    0 /* handwritten instruction */
    /* 33D8 00103358 0800E003 */  jr         $ra
    /* 33DC 0010335C 00000000 */   nop
.size func_00103350, . - func_00103350

/* Handwritten function */
glabel func_00103360
    /* 33E0 00103360 77000324 */  addiu      $v1, $zero, 0x77
    /* 33E4 00103364 0C000000 */  syscall    0 /* handwritten instruction */
    /* 33E8 00103368 0800E003 */  jr         $ra
    /* 33EC 0010336C 00000000 */   nop
.size func_00103360, . - func_00103360

/* Handwritten function */
glabel func_00103370
    /* 33F0 00103370 89FF0324 */  addiu      $v1, $zero, -0x77
    /* 33F4 00103374 0C000000 */  syscall    0 /* handwritten instruction */
    /* 33F8 00103378 0800E003 */  jr         $ra
    /* 33FC 0010337C 00000000 */   nop
.size func_00103370, . - func_00103370

/* Handwritten function */
glabel func_00103380
    /* 3400 00103380 78000324 */  addiu      $v1, $zero, 0x78
    /* 3404 00103384 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3408 00103388 0800E003 */  jr         $ra
    /* 340C 0010338C 00000000 */   nop
.size func_00103380, . - func_00103380

/* Handwritten function */
glabel func_00103390
    /* 3410 00103390 88FF0324 */  addiu      $v1, $zero, -0x78
    /* 3414 00103394 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3418 00103398 0800E003 */  jr         $ra
    /* 341C 0010339C 00000000 */   nop
.size func_00103390, . - func_00103390

/* Handwritten function */
glabel func_001033A0
    /* 3420 001033A0 79000324 */  addiu      $v1, $zero, 0x79
    /* 3424 001033A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3428 001033A8 0800E003 */  jr         $ra
    /* 342C 001033AC 00000000 */   nop
.size func_001033A0, . - func_001033A0

/* Handwritten function */
glabel func_001033B0
    /* 3430 001033B0 7A000324 */  addiu      $v1, $zero, 0x7A
    /* 3434 001033B4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3438 001033B8 0800E003 */  jr         $ra
    /* 343C 001033BC 00000000 */   nop
.size func_001033B0, . - func_001033B0

/* Handwritten function */
glabel func_001033C0
    /* 3440 001033C0 7B000324 */  addiu      $v1, $zero, 0x7B
    /* 3444 001033C4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3448 001033C8 0800E003 */  jr         $ra
    /* 344C 001033CC 00000000 */   nop
.size func_001033C0, . - func_001033C0

/* Handwritten function */
glabel func_001033D0
    /* 3450 001033D0 7C000324 */  addiu      $v1, $zero, 0x7C
    /* 3454 001033D4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3458 001033D8 0800E003 */  jr         $ra
    /* 345C 001033DC 00000000 */   nop
.size func_001033D0, . - func_001033D0

/* Handwritten function */
glabel func_001033E0
    /* 3460 001033E0 7D000324 */  addiu      $v1, $zero, 0x7D
    /* 3464 001033E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3468 001033E8 0800E003 */  jr         $ra
    /* 346C 001033EC 00000000 */   nop
.size func_001033E0, . - func_001033E0

/* Handwritten function */
glabel func_001033F0
    /* 3470 001033F0 7E000324 */  addiu      $v1, $zero, 0x7E
    /* 3474 001033F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3478 001033F8 0800E003 */  jr         $ra
    /* 347C 001033FC 00000000 */   nop
.size func_001033F0, . - func_001033F0

/* Handwritten function */
glabel func_00103400
    /* 3480 00103400 7F000324 */  addiu      $v1, $zero, 0x7F
    /* 3484 00103404 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3488 00103408 0800E003 */  jr         $ra
    /* 348C 0010340C 00000000 */   nop
.size func_00103400, . - func_00103400

/* Handwritten function */
glabel func_00103410
    /* 3490 00103410 82000324 */  addiu      $v1, $zero, 0x82
    /* 3494 00103414 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3498 00103418 0800E003 */  jr         $ra
    /* 349C 0010341C 00000000 */   nop
.size func_00103410, . - func_00103410

glabel func_00103420
    /* 34A0 00103420 3E00023C */  lui        $v0, %hi(D_003E75D0)
    /* 34A4 00103424 0800E003 */  jr         $ra
    /* 34A8 00103428 D07540AC */   sw        $zero, %lo(D_003E75D0)($v0)
    /* 34AC 0010342C 00000000 */  nop
.size func_00103420, . - func_00103420

glabel func_00103430
    /* 34B0 00103430 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 34B4 00103434 0000BFFF */  sd         $ra, 0x0($sp)
    /* 34B8 00103438 F82F040C */  jal        func_0010BFE0
    /* 34BC 0010343C 00000000 */   nop
    /* 34C0 00103440 0010033C */  lui        $v1, (0x1000F000 >> 16)
    /* 34C4 00103444 04000424 */  addiu      $a0, $zero, 0x4
    /* 34C8 00103448 00F06334 */  ori        $v1, $v1, (0x1000F000 & 0xFFFF)
    /* 34CC 0010344C 000064AC */  sw         $a0, 0x0($v1)
    /* 34D0 00103450 0F000000 */  sync
    /* 34D4 00103454 04004010 */  beqz       $v0, .L00103468
    /* 34D8 00103458 0010033C */   lui       $v1, (0x1000F000 >> 16)
    /* 34DC 0010345C 0E30040C */  jal        func_0010C038
    /* 34E0 00103460 00000000 */   nop
    /* 34E4 00103464 0010033C */  lui        $v1, (0x1000F000 >> 16)
  .L00103468:
    /* 34E8 00103468 00F06334 */  ori        $v1, $v1, (0x1000F000 & 0xFFFF)
    /* 34EC 0010346C 00000000 */  nop
  .L00103470:
    /* 34F0 00103470 0000628C */  lw         $v0, 0x0($v1)
    /* 34F4 00103474 04004230 */  andi       $v0, $v0, 0x4
    /* 34F8 00103478 00000000 */  nop
    /* 34FC 0010347C 00000000 */  nop
    /* 3500 00103480 00000000 */  nop
    /* 3504 00103484 FAFF4010 */  beqz       $v0, .L00103470
    /* 3508 00103488 00000000 */   nop
    /* 350C 0010348C F82F040C */  jal        func_0010BFE0
    /* 3510 00103490 00000000 */   nop
    /* 3514 00103494 0010033C */  lui        $v1, (0x1000F000 >> 16)
    /* 3518 00103498 04000424 */  addiu      $a0, $zero, 0x4
    /* 351C 0010349C 00F06334 */  ori        $v1, $v1, (0x1000F000 & 0xFFFF)
    /* 3520 001034A0 000064AC */  sw         $a0, 0x0($v1)
    /* 3524 001034A4 0F000000 */  sync
    /* 3528 001034A8 03004010 */  beqz       $v0, .L001034B8
    /* 352C 001034AC 0000BFDF */   ld        $ra, 0x0($sp)
    /* 3530 001034B0 0E300408 */  j          func_0010C038
    /* 3534 001034B4 1000BD27 */   addiu     $sp, $sp, 0x10
  .L001034B8:
    /* 3538 001034B8 0800E003 */  jr         $ra
    /* 353C 001034BC 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00103430, . - func_00103430

glabel func_001034C0
    /* 3540 001034C0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 3544 001034C4 1000BFFF */  sd         $ra, 0x10($sp)
    /* 3548 001034C8 2D20A003 */  daddu      $a0, $sp, $zero
    /* 354C 001034CC 0000A0AF */  sw         $zero, 0x0($sp)
    /* 3550 001034D0 C40C040C */  jal        func_00103310
    /* 3554 001034D4 0800A537 */   ori       $a1, $sp, 0x8
    /* 3558 001034D8 F82F040C */  jal        func_0010BFE0
    /* 355C 001034DC 00000000 */   nop
    /* 3560 001034E0 0010033C */  lui        $v1, (0x1000F000 >> 16)
    /* 3564 001034E4 04000424 */  addiu      $a0, $zero, 0x4
    /* 3568 001034E8 00F06334 */  ori        $v1, $v1, (0x1000F000 & 0xFFFF)
    /* 356C 001034EC 000064AC */  sw         $a0, 0x0($v1)
    /* 3570 001034F0 0F000000 */  sync
    /* 3574 001034F4 04004010 */  beqz       $v0, .L00103508
    /* 3578 001034F8 0010033C */   lui       $v1, (0x1000F000 >> 16)
    /* 357C 001034FC 0E30040C */  jal        func_0010C038
    /* 3580 00103500 00000000 */   nop
    /* 3584 00103504 0010033C */  lui        $v1, (0x1000F000 >> 16)
  .L00103508:
    /* 3588 00103508 00F06334 */  ori        $v1, $v1, (0x1000F000 & 0xFFFF)
    /* 358C 0010350C 00000000 */  nop
  .L00103510:
    /* 3590 00103510 0000628C */  lw         $v0, 0x0($v1)
    /* 3594 00103514 04004230 */  andi       $v0, $v0, 0x4
    /* 3598 00103518 04004014 */  bnez       $v0, .L0010352C
    /* 359C 0010351C 00000000 */   nop
    /* 35A0 00103520 0000A28F */  lw         $v0, 0x0($sp)
    /* 35A4 00103524 FAFF4010 */  beqz       $v0, .L00103510
    /* 35A8 00103528 00000000 */   nop
  .L0010352C:
    /* 35AC 0010352C F82F040C */  jal        func_0010BFE0
    /* 35B0 00103530 00000000 */   nop
    /* 35B4 00103534 04000324 */  addiu      $v1, $zero, 0x4
    /* 35B8 00103538 0110013C */  lui        $at, (0x10010000 >> 16)
    /* 35BC 0010353C 00F023AC */  sw         $v1, -0x1000($at)
    /* 35C0 00103540 0F000000 */  sync
    /* 35C4 00103544 03004010 */  beqz       $v0, .L00103554
    /* 35C8 00103548 00000000 */   nop
    /* 35CC 0010354C 0E30040C */  jal        func_0010C038
    /* 35D0 00103550 00000000 */   nop
  .L00103554:
    /* 35D4 00103554 0800A2DF */  ld         $v0, 0x8($sp)
    /* 35D8 00103558 1000BFDF */  ld         $ra, 0x10($sp)
    /* 35DC 0010355C 0800E003 */  jr         $ra
    /* 35E0 00103560 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 35E4 00103564 00000000 */  nop
.size func_001034C0, . - func_001034C0
