.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00103568
    /* 35E8 00103568 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 35EC 0010356C FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 35F0 00103570 2000B2FF */  sd         $s2, 0x20($sp)
    /* 35F4 00103574 0200842C */  sltiu      $a0, $a0, 0x2
    /* 35F8 00103578 1000B1FF */  sd         $s1, 0x10($sp)
    /* 35FC 0010357C 2D90C000 */  daddu      $s2, $a2, $zero
    /* 3600 00103580 3000BFFF */  sd         $ra, 0x30($sp)
    /* 3604 00103584 2D88A000 */  daddu      $s1, $a1, $zero
    /* 3608 00103588 0F008010 */  beqz       $a0, .L001035C8
    /* 360C 0010358C 0000B0FF */   sd        $s0, 0x0($sp)
    /* 3610 00103590 3E00103C */  lui        $s0, (0x3E75D0 >> 16)
    /* 3614 00103594 D075028E */  lw         $v0, (0x3E75D0 & 0xFFFF)($s0)
    /* 3618 00103598 07004014 */  bnez       $v0, .L001035B8
    /* 361C 0010359C 2D202002 */   daddu     $a0, $s1, $zero
    /* 3620 001035A0 EC11040C */  jal        func_001047B0
    /* 3624 001035A4 00000000 */   nop
    /* 3628 001035A8 07004010 */  beqz       $v0, .L001035C8
    /* 362C 001035AC 01000224 */   addiu     $v0, $zero, 0x1
    /* 3630 001035B0 D07502AE */  sw         $v0, (0x3E75D0 & 0xFFFF)($s0)
    /* 3634 001035B4 2D202002 */  daddu      $a0, $s1, $zero
  .L001035B8:
    /* 3638 001035B8 5A11040C */  jal        func_00104568
    /* 363C 001035BC 2D284002 */   daddu     $a1, $s2, $zero
    /* 3640 001035C0 03000010 */  b          .L001035D0
    /* 3644 001035C4 3000BFDF */   ld        $ra, 0x30($sp)
  .L001035C8:
    /* 3648 001035C8 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 364C 001035CC 3000BFDF */  ld         $ra, 0x30($sp)
  .L001035D0:
    /* 3650 001035D0 2000B2DF */  ld         $s2, 0x20($sp)
    /* 3654 001035D4 1000B1DF */  ld         $s1, 0x10($sp)
    /* 3658 001035D8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 365C 001035DC 0800E003 */  jr         $ra
    /* 3660 001035E0 4000BD27 */   addiu     $sp, $sp, 0x40
    /* 3664 001035E4 00000000 */  nop
.size func_00103568, . - func_00103568
