.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_001035E8
    /* 3668 001035E8 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 366C 001035EC 2000B2FF */  sd         $s2, 0x20($sp)
    /* 3670 001035F0 1000B1FF */  sd         $s1, 0x10($sp)
    /* 3674 001035F4 2D90C000 */  daddu      $s2, $a2, $zero
    /* 3678 001035F8 3000BFFF */  sd         $ra, 0x30($sp)
    /* 367C 001035FC 2D88A000 */  daddu      $s1, $a1, $zero
    /* 3680 00103600 0F008014 */  bnez       $a0, .L00103640
    /* 3684 00103604 0000B0FF */   sd        $s0, 0x0($sp)
    /* 3688 00103608 3E00103C */  lui        $s0, (0x3E75D0 >> 16)
    /* 368C 0010360C D075028E */  lw         $v0, (0x3E75D0 & 0xFFFF)($s0)
    /* 3690 00103610 07004014 */  bnez       $v0, .L00103630
    /* 3694 00103614 2D202002 */   daddu     $a0, $s1, $zero
    /* 3698 00103618 EC11040C */  jal        func_001047B0
    /* 369C 0010361C 00000000 */   nop
    /* 36A0 00103620 07004010 */  beqz       $v0, .L00103640
    /* 36A4 00103624 01000224 */   addiu     $v0, $zero, 0x1
    /* 36A8 00103628 D07502AE */  sw         $v0, (0x3E75D0 & 0xFFFF)($s0)
    /* 36AC 0010362C 2D202002 */  daddu      $a0, $s1, $zero
  .L00103630:
    /* 36B0 00103630 B811040C */  jal        func_001046E0
    /* 36B4 00103634 2D284002 */   daddu     $a1, $s2, $zero
    /* 36B8 00103638 03000010 */  b          .L00103648
    /* 36BC 0010363C 3000BFDF */   ld        $ra, 0x30($sp)
  .L00103640:
    /* 36C0 00103640 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 36C4 00103644 3000BFDF */  ld         $ra, 0x30($sp)
  .L00103648:
    /* 36C8 00103648 2000B2DF */  ld         $s2, 0x20($sp)
    /* 36CC 0010364C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 36D0 00103650 0000B0DF */  ld         $s0, 0x0($sp)
    /* 36D4 00103654 0800E003 */  jr         $ra
    /* 36D8 00103658 4000BD27 */   addiu     $sp, $sp, 0x40
    /* 36DC 0010365C 00000000 */  nop
.size func_001035E8, . - func_001035E8

glabel func_00103660
    /* 36E0 00103660 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 36E4 00103664 0000BFFF */  sd         $ra, 0x0($sp)
    /* 36E8 00103668 0CCD0D0C */  jal        func_00373430
    /* 36EC 0010366C 00000000 */   nop
    /* 36F0 00103670 05000324 */  addiu      $v1, $zero, 0x5
    /* 36F4 00103674 0000BFDF */  ld         $ra, 0x0($sp)
    /* 36F8 00103678 000043AC */  sw         $v1, 0x0($v0)
    /* 36FC 0010367C FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 3700 00103680 0800E003 */  jr         $ra
    /* 3704 00103684 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00103660, . - func_00103660

glabel func_00103688
    /* 3708 00103688 0800E003 */  jr         $ra
    /* 370C 0010368C FFFF0224 */   addiu     $v0, $zero, -0x1
.size func_00103688, . - func_00103688

glabel func_00103690
    /* 3710 00103690 0800E003 */  jr         $ra
    /* 3714 00103694 FFFF0224 */   addiu     $v0, $zero, -0x1
.size func_00103690, . - func_00103690

glabel func_00103698
    /* 3718 00103698 0800E003 */  jr         $ra
    /* 371C 0010369C FFFF0224 */   addiu     $v0, $zero, -0x1
.size func_00103698, . - func_00103698

/* Handwritten function */
glabel func_001036A0
    /* 3720 001036A0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 3724 001036A4 3000BFFF */  sd         $ra, 0x30($sp)
    /* 3728 001036A8 2000B2FF */  sd         $s2, 0x20($sp)
    /* 372C 001036AC 1000B1FF */  sd         $s1, 0x10($sp)
    /* 3730 001036B0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 3734 001036B4 00601140 */  mfc0       $s1, $12 /* handwritten instruction */
    /* 3738 001036B8 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 373C 001036BC 24882202 */  and        $s1, $s1, $v0
    /* 3740 001036C0 0A002012 */  beqz       $s1, .L001036EC
    /* 3744 001036C4 3E00123C */   lui       $s2, (0x3E75D4 >> 16)
  .L001036C8:
    /* 3748 001036C8 39000042 */  di /* handwritten instruction */
    /* 374C 001036CC 0F040000 */  sync.p
    /* 3750 001036D0 00600240 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 3754 001036D4 0100033C */  lui        $v1, (0x10000 >> 16)
    /* 3758 001036D8 24104300 */  and        $v0, $v0, $v1
    /* 375C 001036DC FAFF4014 */  bnez       $v0, .L001036C8
    /* 3760 001036E0 00000000 */   nop
    /* 3764 001036E4 02000010 */  b          .L001036F0
    /* 3768 001036E8 D475428E */   lw        $v0, (0x3E75D4 & 0xFFFF)($s2)
  .L001036EC:
    /* 376C 001036EC D475428E */  lw         $v0, (0x3E75D4 & 0xFFFF)($s2)
  .L001036F0:
    /* 3770 001036F0 E00B040C */  jal        func_00102F80
    /* 3774 001036F4 21804400 */   addu      $s0, $v0, $a0
    /* 3778 001036F8 2B105000 */  sltu       $v0, $v0, $s0
    /* 377C 001036FC 0A004010 */  beqz       $v0, .L00103728
    /* 3780 00103700 D475428E */   lw        $v0, (0x3E75D4 & 0xFFFF)($s2)
    /* 3784 00103704 0CCD0D0C */  jal        func_00373430
    /* 3788 00103708 00000000 */   nop
    /* 378C 0010370C 0C000324 */  addiu      $v1, $zero, 0xC
    /* 3790 00103710 02002012 */  beqz       $s1, .L0010371C
    /* 3794 00103714 000043AC */   sw        $v1, 0x0($v0)
    /* 3798 00103718 38000042 */  ei /* handwritten instruction */
  .L0010371C:
    /* 379C 0010371C FFFF023C */  lui        $v0, (0xFFFFFFFF >> 16)
    /* 37A0 00103720 04000010 */  b          .L00103734
    /* 37A4 00103724 FFFF4234 */   ori       $v0, $v0, (0xFFFFFFFF & 0xFFFF)
  .L00103728:
    /* 37A8 00103728 02002012 */  beqz       $s1, .L00103734
    /* 37AC 0010372C D47550AE */   sw        $s0, (0x3E75D4 & 0xFFFF)($s2)
    /* 37B0 00103730 38000042 */  ei /* handwritten instruction */
  .L00103734:
    /* 37B4 00103734 3000BFDF */  ld         $ra, 0x30($sp)
    /* 37B8 00103738 2000B2DF */  ld         $s2, 0x20($sp)
    /* 37BC 0010373C 1000B1DF */  ld         $s1, 0x10($sp)
    /* 37C0 00103740 0000B0DF */  ld         $s0, 0x0($sp)
    /* 37C4 00103744 0800E003 */  jr         $ra
    /* 37C8 00103748 4000BD27 */   addiu     $sp, $sp, 0x40
    /* 37CC 0010374C 00000000 */  nop
.size func_001036A0, . - func_001036A0

glabel func_00103750
    /* 37D0 00103750 0800E003 */  jr         $ra
    /* 37D4 00103754 01000224 */   addiu     $v0, $zero, 0x1
.size func_00103750, . - func_00103750

glabel func_00103758
    /* 37D8 00103758 00200224 */  addiu      $v0, $zero, 0x2000
    /* 37DC 0010375C 4800A0FC */  sd         $zero, 0x48($a1)
    /* 37E0 00103760 0400A2AC */  sw         $v0, 0x4($a1)
    /* 37E4 00103764 0800E003 */  jr         $ra
    /* 37E8 00103768 2D100000 */   daddu     $v0, $zero, $zero
    /* 37EC 0010376C 00000000 */  nop
.size func_00103758, . - func_00103758

glabel func_00103770
    /* 37F0 00103770 0800E003 */  jr         $ra
    /* 37F4 00103774 01000224 */   addiu     $v0, $zero, 0x1
.size func_00103770, . - func_00103770

glabel func_00103778
    /* 37F8 00103778 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 37FC 0010377C 01000224 */  addiu      $v0, $zero, 0x1
    /* 3800 00103780 03008214 */  bne        $a0, $v0, .L00103790
    /* 3804 00103784 0000BFFF */   sd        $ra, 0x0($sp)
    /* 3808 00103788 A231040C */  jal        func_0010C688
    /* 380C 0010378C 2D20A000 */   daddu     $a0, $a1, $zero
  .L00103790:
    /* 3810 00103790 0000BFDF */  ld         $ra, 0x0($sp)
    /* 3814 00103794 2D100000 */  daddu      $v0, $zero, $zero
    /* 3818 00103798 0800E003 */  jr         $ra
    /* 381C 0010379C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00103778, . - func_00103778

glabel func_001037A0
    /* 3820 001037A0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 3824 001037A4 0000BFFF */  sd         $ra, 0x0($sp)
    /* 3828 001037A8 0CCD0D0C */  jal        func_00373430
    /* 382C 001037AC 00000000 */   nop
    /* 3830 001037B0 05000324 */  addiu      $v1, $zero, 0x5
    /* 3834 001037B4 0000BFDF */  ld         $ra, 0x0($sp)
    /* 3838 001037B8 000043AC */  sw         $v1, 0x0($v0)
    /* 383C 001037BC FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 3840 001037C0 0800E003 */  jr         $ra
    /* 3844 001037C4 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_001037A0, . - func_001037A0

glabel func_001037C8
    /* 3848 001037C8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 384C 001037CC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 3850 001037D0 0CCD0D0C */  jal        func_00373430
    /* 3854 001037D4 00000000 */   nop
    /* 3858 001037D8 05000324 */  addiu      $v1, $zero, 0x5
    /* 385C 001037DC 0000BFDF */  ld         $ra, 0x0($sp)
    /* 3860 001037E0 000043AC */  sw         $v1, 0x0($v0)
    /* 3864 001037E4 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 3868 001037E8 0800E003 */  jr         $ra
    /* 386C 001037EC 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_001037C8, . - func_001037C8

/* Handwritten function */
glabel func_001037F0
    /* 3870 001037F0 FFFF073C */  lui        $a3, (0xFFFFF000 >> 16)
    /* 3874 001037F4 2D300000 */  daddu      $a2, $zero, $zero
    /* 3878 001037F8 00F0E734 */  ori        $a3, $a3, (0xFFFFF000 & 0xFFFF)
    /* 387C 001037FC 00000000 */  nop
  .L00103800:
    /* 3880 00103800 0F000000 */  sync
    /* 3884 00103804 0000D0BC */  cache      0x10, 0x0($a2) /* handwritten instruction */
    /* 3888 00103808 0F000000 */  sync
    /* 388C 0010380C 00E00240 */  mfc0       $v0, $28 /* handwritten instruction */
    /* 3890 00103810 24104700 */  and        $v0, $v0, $a3
    /* 3894 00103814 21104600 */  addu       $v0, $v0, $a2
    /* 3898 00103818 2B18A200 */  sltu       $v1, $a1, $v0
    /* 389C 0010381C 2B104400 */  sltu       $v0, $v0, $a0
    /* 38A0 00103820 06004014 */  bnez       $v0, .L0010383C
    /* 38A4 00103824 00000000 */   nop
    /* 38A8 00103828 04006014 */  bnez       $v1, .L0010383C
    /* 38AC 0010382C 00000000 */   nop
    /* 38B0 00103830 0F000000 */  sync
    /* 38B4 00103834 0000D4BC */  cache      0x14, 0x0($a2) /* handwritten instruction */
    /* 38B8 00103838 0F000000 */  sync
  .L0010383C:
    /* 38BC 0010383C 0F000000 */  sync
    /* 38C0 00103840 0100D0BC */  cache      0x10, 0x1($a2) /* handwritten instruction */
    /* 38C4 00103844 0F000000 */  sync
    /* 38C8 00103848 00E00240 */  mfc0       $v0, $28 /* handwritten instruction */
    /* 38CC 0010384C 24104700 */  and        $v0, $v0, $a3
    /* 38D0 00103850 21104600 */  addu       $v0, $v0, $a2
    /* 38D4 00103854 2B18A200 */  sltu       $v1, $a1, $v0
    /* 38D8 00103858 2B104400 */  sltu       $v0, $v0, $a0
    /* 38DC 0010385C 06004014 */  bnez       $v0, .L00103878
    /* 38E0 00103860 00000000 */   nop
    /* 38E4 00103864 04006014 */  bnez       $v1, .L00103878
    /* 38E8 00103868 00000000 */   nop
    /* 38EC 0010386C 0F000000 */  sync
    /* 38F0 00103870 0100D4BC */  cache      0x14, 0x1($a2) /* handwritten instruction */
    /* 38F4 00103874 0F000000 */  sync
  .L00103878:
    /* 38F8 00103878 0F000000 */  sync
    /* 38FC 0010387C 4000C624 */  addiu      $a2, $a2, 0x40
    /* 3900 00103880 0010C228 */  slti       $v0, $a2, 0x1000
    /* 3904 00103884 DEFF4014 */  bnez       $v0, .L00103800
    /* 3908 00103888 00000000 */   nop
    /* 390C 0010388C 0800E003 */  jr         $ra
    /* 3910 00103890 00000000 */   nop
    /* 3914 00103894 00000000 */  nop
.size func_001037F0, . - func_001037F0
