.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00103918
    /* 3998 00103918 FFFF023C */  lui        $v0, (0xFFFFFFC0 >> 16)
    /* 399C 0010391C C0FF4234 */  ori        $v0, $v0, (0xFFFFFFC0 & 0xFFFF)
    /* 39A0 00103920 2428A200 */  and        $a1, $a1, $v0
    /* 39A4 00103924 FC0D0408 */  j          func_001037F0
    /* 39A8 00103928 24208200 */   and       $a0, $a0, $v0
    /* 39AC 0010392C 00000000 */  nop
.size func_00103918, . - func_00103918

/* Handwritten function */
glabel func_00103930
    /* 39B0 00103930 FFFF073C */  lui        $a3, (0xFFFFF000 >> 16)
    /* 39B4 00103934 2D300000 */  daddu      $a2, $zero, $zero
    /* 39B8 00103938 00F0E734 */  ori        $a3, $a3, (0xFFFFF000 & 0xFFFF)
    /* 39BC 0010393C 00000000 */  nop
  .L00103940:
    /* 39C0 00103940 0F000000 */  sync
    /* 39C4 00103944 0000D0BC */  cache      0x10, 0x0($a2) /* handwritten instruction */
    /* 39C8 00103948 0F000000 */  sync
    /* 39CC 0010394C 00E00240 */  mfc0       $v0, $28 /* handwritten instruction */
    /* 39D0 00103950 24104700 */  and        $v0, $v0, $a3
    /* 39D4 00103954 21104600 */  addu       $v0, $v0, $a2
    /* 39D8 00103958 2B18A200 */  sltu       $v1, $a1, $v0
    /* 39DC 0010395C 2B104400 */  sltu       $v0, $v0, $a0
    /* 39E0 00103960 06004014 */  bnez       $v0, .L0010397C
    /* 39E4 00103964 00000000 */   nop
    /* 39E8 00103968 04006014 */  bnez       $v1, .L0010397C
    /* 39EC 0010396C 00000000 */   nop
    /* 39F0 00103970 0F000000 */  sync
    /* 39F4 00103974 0000D6BC */  cache      0x16, 0x0($a2) /* handwritten instruction */
    /* 39F8 00103978 0F000000 */  sync
  .L0010397C:
    /* 39FC 0010397C 0F000000 */  sync
    /* 3A00 00103980 0100D0BC */  cache      0x10, 0x1($a2) /* handwritten instruction */
    /* 3A04 00103984 0F000000 */  sync
    /* 3A08 00103988 00E00240 */  mfc0       $v0, $28 /* handwritten instruction */
    /* 3A0C 0010398C 24104700 */  and        $v0, $v0, $a3
    /* 3A10 00103990 21104600 */  addu       $v0, $v0, $a2
    /* 3A14 00103994 2B18A200 */  sltu       $v1, $a1, $v0
    /* 3A18 00103998 2B104400 */  sltu       $v0, $v0, $a0
    /* 3A1C 0010399C 06004014 */  bnez       $v0, .L001039B8
    /* 3A20 001039A0 00000000 */   nop
    /* 3A24 001039A4 04006014 */  bnez       $v1, .L001039B8
    /* 3A28 001039A8 00000000 */   nop
    /* 3A2C 001039AC 0F000000 */  sync
    /* 3A30 001039B0 0100D6BC */  cache      0x16, 0x1($a2) /* handwritten instruction */
    /* 3A34 001039B4 0F000000 */  sync
  .L001039B8:
    /* 3A38 001039B8 0F000000 */  sync
    /* 3A3C 001039BC 4000C624 */  addiu      $a2, $a2, 0x40
    /* 3A40 001039C0 0010C228 */  slti       $v0, $a2, 0x1000
    /* 3A44 001039C4 DEFF4014 */  bnez       $v0, .L00103940
    /* 3A48 001039C8 00000000 */   nop
    /* 3A4C 001039CC 0800E003 */  jr         $ra
    /* 3A50 001039D0 00000000 */   nop
    /* 3A54 001039D4 00000000 */  nop
.size func_00103930, . - func_00103930
