.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel func_001039D8
    /* 3A58 001039D8 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 3A5C 001039DC 2000B2FF */  sd         $s2, 0x20($sp)
    /* 3A60 001039E0 1000B1FF */  sd         $s1, 0x10($sp)
    /* 3A64 001039E4 2D908000 */  daddu      $s2, $a0, $zero
    /* 3A68 001039E8 3000BFFF */  sd         $ra, 0x30($sp)
    /* 3A6C 001039EC 2D88A000 */  daddu      $s1, $a1, $zero
    /* 3A70 001039F0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 3A74 001039F4 00601040 */  mfc0       $s0, $12 /* handwritten instruction */
    /* 3A78 001039F8 0100023C */  lui        $v0, (0x10000 >> 16)
    /* 3A7C 001039FC 24800202 */  and        $s0, $s0, $v0
    /* 3A80 00103A00 03000012 */  beqz       $s0, .L00103A10
    /* 3A84 00103A04 00000000 */   nop
    /* 3A88 00103A08 F82F040C */  jal        func_0010BFE0
    /* 3A8C 00103A0C 00000000 */   nop
  .L00103A10:
    /* 3A90 00103A10 FFFF043C */  lui        $a0, (0xFFFFFFC0 >> 16)
    /* 3A94 00103A14 C0FF8434 */  ori        $a0, $a0, (0xFFFFFFC0 & 0xFFFF)
    /* 3A98 00103A18 24282402 */  and        $a1, $s1, $a0
    /* 3A9C 00103A1C 4C0E040C */  jal        func_00103930
    /* 3AA0 00103A20 24204402 */   and       $a0, $s2, $a0
    /* 3AA4 00103A24 06000012 */  beqz       $s0, .L00103A40
    /* 3AA8 00103A28 3000BFDF */   ld        $ra, 0x30($sp)
    /* 3AAC 00103A2C 2000B2DF */  ld         $s2, 0x20($sp)
    /* 3AB0 00103A30 1000B1DF */  ld         $s1, 0x10($sp)
    /* 3AB4 00103A34 0000B0DF */  ld         $s0, 0x0($sp)
    /* 3AB8 00103A38 0E300408 */  j          func_0010C038
    /* 3ABC 00103A3C 4000BD27 */   addiu     $sp, $sp, 0x40
  .L00103A40:
    /* 3AC0 00103A40 2000B2DF */  ld         $s2, 0x20($sp)
    /* 3AC4 00103A44 1000B1DF */  ld         $s1, 0x10($sp)
    /* 3AC8 00103A48 0000B0DF */  ld         $s0, 0x0($sp)
    /* 3ACC 00103A4C 0800E003 */  jr         $ra
    /* 3AD0 00103A50 4000BD27 */   addiu     $sp, $sp, 0x40
    /* 3AD4 00103A54 00000000 */  nop
.size func_001039D8, . - func_001039D8
