.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel func_00103F68
    /* 3FE8 00103F68 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 3FEC 00103F6C 1000BFFF */  sd         $ra, 0x10($sp)
    /* 3FF0 00103F70 0000B0FF */  sd         $s0, 0x0($sp)
    /* 3FF4 00103F74 D1FF0324 */  addiu      $v1, $zero, -0x2F
    /* 3FF8 00103F78 0C000000 */  syscall    0 /* handwritten instruction */
    /* 3FFC 00103F7C 2D804000 */  daddu      $s0, $v0, $zero
    /* 4000 00103F80 05000412 */  beq        $s0, $a0, .L00103F98
    /* 4004 00103F84 0001022E */   sltiu     $v0, $s0, 0x100
    /* 4008 00103F88 C80B040C */  jal        func_00102F20
    /* 400C 00103F8C 00000000 */   nop
    /* 4010 00103F90 18000010 */  b          .L00103FF4
    /* 4014 00103F94 1000BFDF */   ld        $ra, 0x10($sp)
  .L00103F98:
    /* 4018 00103F98 04004010 */  beqz       $v0, .L00103FAC
    /* 401C 00103F9C 3E00023C */   lui       $v0, %hi(D_003E75D8)
    /* 4020 00103FA0 D875438C */  lw         $v1, %lo(D_003E75D8)($v0)
    /* 4024 00103FA4 03006014 */  bnez       $v1, .L00103FB4
    /* 4028 00103FA8 5000033C */   lui       $v1, %hi(D_4FB328)
  .L00103FAC:
    /* 402C 00103FAC 10000010 */  b          .L00103FF0
    /* 4030 00103FB0 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L00103FB4:
    /* 4034 00103FB4 5000053C */  lui        $a1, (0x500000 >> 16)
    /* 4038 00103FB8 28B36324 */  addiu      $v1, $v1, %lo(D_4FB328)
    /* 403C 00103FBC 20B3A48C */  lw         $a0, -0x4CE0($a1)
    /* 4040 00103FC0 0400628C */  lw         $v0, 0x4($v1)
    /* 4044 00103FC4 02000724 */  addiu      $a3, $zero, 0x2
    /* 4048 00103FC8 FF014230 */  andi       $v0, $v0, 0x1FF
    /* 404C 00103FCC 40300200 */  sll        $a2, $v0, 1
    /* 4050 00103FD0 01004224 */  addiu      $v0, $v0, 0x1
    /* 4054 00103FD4 21286600 */  addu       $a1, $v1, $a2
    /* 4058 00103FD8 040062AC */  sw         $v0, 0x4($v1)
    /* 405C 00103FDC 0800A7A0 */  sb         $a3, 0x8($a1)
    /* 4060 00103FE0 2D18A000 */  daddu      $v1, $a1, $zero
    /* 4064 00103FE4 F40B040C */  jal        func_00102FD0
    /* 4068 00103FE8 090070A0 */   sb        $s0, 0x9($v1)
    /* 406C 00103FEC 2D100002 */  daddu      $v0, $s0, $zero
  .L00103FF0:
    /* 4070 00103FF0 1000BFDF */  ld         $ra, 0x10($sp)
  .L00103FF4:
    /* 4074 00103FF4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 4078 00103FF8 0800E003 */  jr         $ra
    /* 407C 00103FFC 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_00103F68, . - func_00103F68

/* Handwritten function */
glabel func_00104000
    /* 4080 00104000 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 4084 00104004 3000B1FF */  sd         $s1, 0x30($sp)
    /* 4088 00104008 4000BFFF */  sd         $ra, 0x40($sp)
    /* 408C 0010400C 2D888000 */  daddu      $s1, $a0, $zero
    /* 4090 00104010 2000B0FF */  sd         $s0, 0x20($sp)
    /* 4094 00104014 00600240 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 4098 00104018 0100033C */  lui        $v1, (0x10000 >> 16)
    /* 409C 0010401C 24104300 */  and        $v0, $v0, $v1
    /* 40A0 00104020 04004054 */  bnel       $v0, $zero, .L00104034
    /* 40A4 00104024 4600023C */   lui       $v0, %hi(D_00459980)
    /* 40A8 00104028 0080023C */  lui        $v0, (0x80008008 >> 16)
    /* 40AC 0010402C 21000010 */  b          .L001040B4
    /* 40B0 00104030 08804234 */   ori       $v0, $v0, (0x80008008 & 0xFFFF)
  .L00104034:
    /* 40B4 00104034 01000324 */  addiu      $v1, $zero, 0x1
    /* 40B8 00104038 80994224 */  addiu      $v0, $v0, %lo(D_00459980)
    /* 40BC 0010403C 0400A3AF */  sw         $v1, 0x4($sp)
    /* 40C0 00104040 1400A2AF */  sw         $v0, 0x14($sp)
    /* 40C4 00104044 2D20A003 */  daddu      $a0, $sp, $zero
    /* 40C8 00104048 E80B040C */  jal        func_00102FA0
    /* 40CC 0010404C 0800A0AF */   sw        $zero, 0x8($sp)
    /* 40D0 00104050 2D804000 */  daddu      $s0, $v0, $zero
    /* 40D4 00104054 04000106 */  bgez       $s0, .L00104068
    /* 40D8 00104058 2D282002 */   daddu     $a1, $s1, $zero
    /* 40DC 0010405C 0080023C */  lui        $v0, (0x80008003 >> 16)
    /* 40E0 00104060 14000010 */  b          .L001040B4
    /* 40E4 00104064 03804234 */   ori       $v0, $v0, (0x80008003 & 0xFFFF)
  .L00104068:
    /* 40E8 00104068 AA36040C */  jal        func_0010DAA8
    /* 40EC 0010406C 2D200000 */   daddu     $a0, $zero, $zero
    /* 40F0 00104070 1000053C */  lui        $a1, %hi(func_001040C8)
    /* 40F4 00104074 2D204000 */  daddu      $a0, $v0, $zero
    /* 40F8 00104078 C840A524 */  addiu      $a1, $a1, %lo(func_001040C8)
    /* 40FC 0010407C 1637040C */  jal        func_0010DC58
    /* 4100 00104080 2D300002 */   daddu     $a2, $s0, $zero
    /* 4104 00104084 2D884000 */  daddu      $s1, $v0, $zero
    /* 4108 00104088 05002106 */  bgez       $s1, .L001040A0
    /* 410C 0010408C 00000000 */   nop
    /* 4110 00104090 EC0B040C */  jal        func_00102FB0
    /* 4114 00104094 2D200002 */   daddu     $a0, $s0, $zero
    /* 4118 00104098 06000010 */  b          .L001040B4
    /* 411C 0010409C 2D102002 */   daddu     $v0, $s1, $zero
  .L001040A0:
    /* 4120 001040A0 F80B040C */  jal        func_00102FE0
    /* 4124 001040A4 2D200002 */   daddu     $a0, $s0, $zero
    /* 4128 001040A8 EC0B040C */  jal        func_00102FB0
    /* 412C 001040AC 2D200002 */   daddu     $a0, $s0, $zero
    /* 4130 001040B0 2D100000 */  daddu      $v0, $zero, $zero
  .L001040B4:
    /* 4134 001040B4 4000BFDF */  ld         $ra, 0x40($sp)
    /* 4138 001040B8 3000B1DF */  ld         $s1, 0x30($sp)
    /* 413C 001040BC 2000B0DF */  ld         $s0, 0x20($sp)
    /* 4140 001040C0 0800E003 */  jr         $ra
    /* 4144 001040C4 5000BD27 */   addiu     $sp, $sp, 0x50
.size func_00104000, . - func_00104000

/* Handwritten function */
glabel func_001040C8
    /* 4148 001040C8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 414C 001040CC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 4150 001040D0 F40B040C */  jal        func_00102FD0
    /* 4154 001040D4 2D20E000 */   daddu     $a0, $a3, $zero
    /* 4158 001040D8 0F000000 */  sync
    /* 415C 001040DC 38000042 */  ei /* handwritten instruction */
    /* 4160 001040E0 0000BFDF */  ld         $ra, 0x0($sp)
    /* 4164 001040E4 2D100000 */  daddu      $v0, $zero, $zero
    /* 4168 001040E8 0800E003 */  jr         $ra
    /* 416C 001040EC 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_001040C8, . - func_001040C8

glabel func_001040F0
    /* 4170 001040F0 5000023C */  lui        $v0, %hi(D_4FB730)
    /* 4174 001040F4 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 4178 001040F8 0020033C */  lui        $v1, (0x20000000 >> 16)
    /* 417C 001040FC 30B74224 */  addiu      $v0, $v0, %lo(D_4FB730)
    /* 4180 00104100 FFFF8430 */  andi       $a0, $a0, 0xFFFF
    /* 4184 00104104 25104300 */  or         $v0, $v0, $v1
    /* 4188 00104108 0400A5AF */  sw         $a1, 0x4($sp)
    /* 418C 0010410C 0000A4AF */  sw         $a0, 0x0($sp)
    /* 4190 00104110 2D28A003 */  daddu      $a1, $sp, $zero
    /* 4194 00104114 1000BFFF */  sd         $ra, 0x10($sp)
    /* 4198 00104118 01000424 */  addiu      $a0, $zero, 0x1
    /* 419C 0010411C 0800A6AF */  sw         $a2, 0x8($sp)
    /* 41A0 00104120 F40C040C */  jal        func_001033D0
    /* 41A4 00104124 0C00A2AF */   sw        $v0, 0xC($sp)
    /* 41A8 00104128 1000BFDF */  ld         $ra, 0x10($sp)
    /* 41AC 0010412C 0800E003 */  jr         $ra
    /* 41B0 00104130 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 41B4 00104134 00000000 */  nop
.size func_001040F0, . - func_001040F0
