.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00103EE8
    /* 3F68 00103EE8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 3F6C 00103EEC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 3F70 00103EF0 2D808000 */  daddu      $s0, $a0, $zero
    /* 3F74 00103EF4 8000022E */  sltiu      $v0, $s0, 0x80
    /* 3F78 00103EF8 05004010 */  beqz       $v0, .L00103F10
    /* 3F7C 00103EFC 1000BFFF */   sd        $ra, 0x10($sp)
    /* 3F80 00103F00 3E00023C */  lui        $v0, %hi(D_003E75D8)
    /* 3F84 00103F04 D875438C */  lw         $v1, %lo(D_003E75D8)($v0)
    /* 3F88 00103F08 03006014 */  bnez       $v1, .L00103F18
    /* 3F8C 00103F0C 5000033C */   lui       $v1, %hi(D_4FB328)
  .L00103F10:
    /* 3F90 00103F10 10000010 */  b          .L00103F54
    /* 3F94 00103F14 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L00103F18:
    /* 3F98 00103F18 5000053C */  lui        $a1, (0x500000 >> 16)
    /* 3F9C 00103F1C 28B36324 */  addiu      $v1, $v1, %lo(D_4FB328)
    /* 3FA0 00103F20 20B3A48C */  lw         $a0, -0x4CE0($a1)
    /* 3FA4 00103F24 0400628C */  lw         $v0, 0x4($v1)
    /* 3FA8 00103F28 01000724 */  addiu      $a3, $zero, 0x1
    /* 3FAC 00103F2C FF014230 */  andi       $v0, $v0, 0x1FF
    /* 3FB0 00103F30 40300200 */  sll        $a2, $v0, 1
    /* 3FB4 00103F34 01004224 */  addiu      $v0, $v0, 0x1
    /* 3FB8 00103F38 21286600 */  addu       $a1, $v1, $a2
    /* 3FBC 00103F3C 040062AC */  sw         $v0, 0x4($v1)
    /* 3FC0 00103F40 0800A7A0 */  sb         $a3, 0x8($a1)
    /* 3FC4 00103F44 2D18A000 */  daddu      $v1, $a1, $zero
    /* 3FC8 00103F48 F40B040C */  jal        func_00102FD0
    /* 3FCC 00103F4C 090070A0 */   sb        $s0, 0x9($v1)
    /* 3FD0 00103F50 2D100002 */  daddu      $v0, $s0, $zero
  .L00103F54:
    /* 3FD4 00103F54 1000BFDF */  ld         $ra, 0x10($sp)
    /* 3FD8 00103F58 0000B0DF */  ld         $s0, 0x0($sp)
    /* 3FDC 00103F5C 0800E003 */  jr         $ra
    /* 3FE0 00103F60 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 3FE4 00103F64 00000000 */  nop
.size func_00103EE8, . - func_00103EE8
