.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

/* Handwritten function */
glabel func_0010C278
    /* C2F8 0010C278 74000324 */  addiu      $v1, $zero, 0x74
    /* C2FC 0010C27C 0C000000 */  syscall    0 /* handwritten instruction */
    /* C300 0010C280 0800E003 */  jr         $ra
    /* C304 0010C284 00000000 */   nop
.size func_0010C278, . - func_0010C278

glabel func_0010C288
    /* C308 0010C288 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* C30C 0010C28C 0000BFFF */  sd         $ra, 0x0($sp)
    /* C310 0010C290 1430040C */  jal        func_0010C050
    /* C314 0010C294 00000000 */   nop
    /* C318 0010C298 5E30040C */  jal        func_0010C178
    /* C31C 0010C29C 00000000 */   nop
    /* C320 0010C2A0 DA31040C */  jal        func_0010C768
    /* C324 0010C2A4 00000000 */   nop
    /* C328 0010C2A8 3832040C */  jal        func_0010C8E0
    /* C32C 0010C2AC 02000424 */   addiu     $a0, $zero, 0x2
    /* C330 0010C2B0 C832040C */  jal        func_0010CB20
    /* C334 0010C2B4 00000000 */   nop
    /* C338 0010C2B8 5E0F040C */  jal        func_00103D78
    /* C33C 0010C2BC 00000000 */   nop
    /* C340 0010C2C0 EC30040C */  jal        func_0010C3B0
    /* C344 0010C2C4 00000000 */   nop
    /* C348 0010C2C8 222E040C */  jal        func_0010B888
    /* C34C 0010C2CC 00000000 */   nop
    /* C350 0010C2D0 0000BFDF */  ld         $ra, 0x0($sp)
    /* C354 0010C2D4 E6370408 */  j          func_0010DF98
    /* C358 0010C2D8 1000BD27 */   addiu     $sp, $sp, 0x10
    /* C35C 0010C2DC 00000000 */  nop
.size func_0010C288, . - func_0010C288

/* Handwritten function */
glabel func_0010C2E0
    /* C360 0010C2E0 74000324 */  addiu      $v1, $zero, 0x74
    /* C364 0010C2E4 0C000000 */  syscall    0 /* handwritten instruction */
    /* C368 0010C2E8 0800E003 */  jr         $ra
    /* C36C 0010C2EC 00000000 */   nop
.size func_0010C2E0, . - func_0010C2E0

/* Handwritten function */
glabel func_0010C2F0
    /* C370 0010C2F0 5A000324 */  addiu      $v1, $zero, 0x5A
    /* C374 0010C2F4 0C000000 */  syscall    0 /* handwritten instruction */
    /* C378 0010C2F8 0800E003 */  jr         $ra
    /* C37C 0010C2FC 00000000 */   nop
.size func_0010C2F0, . - func_0010C2F0

glabel func_0010C300
    /* C380 0010C300 82300600 */  srl        $a2, $a2, 2
    /* C384 0010C304 0A00C010 */  beqz       $a2, .L0010C330
    /* C388 0010C308 2D380000 */   daddu     $a3, $zero, $zero
    /* C38C 0010C30C 00000000 */  nop
  .L0010C310:
    /* C390 0010C310 0000A38C */  lw         $v1, 0x0($a1)
    /* C394 0010C314 0100E724 */  addiu      $a3, $a3, 0x1
    /* C398 0010C318 0400A524 */  addiu      $a1, $a1, 0x4
    /* C39C 0010C31C 2B10E600 */  sltu       $v0, $a3, $a2
    /* C3A0 0010C320 000083AC */  sw         $v1, 0x0($a0)
    /* C3A4 0010C324 04008424 */  addiu      $a0, $a0, 0x4
    /* C3A8 0010C328 F9FF4014 */  bnez       $v0, .L0010C310
    /* C3AC 0010C32C 00000000 */   nop
  .L0010C330:
    /* C3B0 0010C330 0800E003 */  jr         $ra
    /* C3B4 0010C334 2D100000 */   daddu     $v0, $zero, $zero
.size func_0010C300, . - func_0010C300

/* Handwritten function */
glabel func_0010C338
    /* C3B8 0010C338 5B000324 */  addiu      $v1, $zero, 0x5B
    /* C3BC 0010C33C 0C000000 */  syscall    0 /* handwritten instruction */
    /* C3C0 0010C340 0800E003 */  jr         $ra
    /* C3C4 0010C344 00000000 */   nop
.size func_0010C338, . - func_0010C338

glabel func_0010C348
    /* C3C8 0010C348 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* C3CC 0010C34C 1000B0FF */  sd         $s0, 0x10($sp)
    /* C3D0 0010C350 2000BFFF */  sd         $ra, 0x20($sp)
    /* C3D4 0010C354 140C040C */  jal        func_00103050
    /* C3D8 0010C358 2D20A003 */   daddu     $a0, $sp, $zero
    /* C3DC 0010C35C 0000A38F */  lw         $v1, 0x0($sp)
    /* C3E0 0010C360 FFFF023C */  lui        $v0, (0xFFFF1FFF >> 16)
    /* C3E4 0010C364 FF1F4234 */  ori        $v0, $v0, (0xFFFF1FFF & 0xFFFF)
    /* C3E8 0010C368 0400B027 */  addiu      $s0, $sp, 0x4
    /* C3EC 0010C36C 24186200 */  and        $v1, $v1, $v0
    /* C3F0 0010C370 2D200002 */  daddu      $a0, $s0, $zero
    /* C3F4 0010C374 00206334 */  ori        $v1, $v1, 0x2000
    /* C3F8 0010C378 100C040C */  jal        func_00103040
    /* C3FC 0010C37C 0400A3AF */   sw        $v1, 0x4($sp)
    /* C400 0010C380 140C040C */  jal        func_00103050
    /* C404 0010C384 2D200002 */   daddu     $a0, $s0, $zero
    /* C408 0010C388 100C040C */  jal        func_00103040
    /* C40C 0010C38C 2D20A003 */   daddu     $a0, $sp, $zero
    /* C410 0010C390 0400A28F */  lw         $v0, 0x4($sp)
    /* C414 0010C394 2000BFDF */  ld         $ra, 0x20($sp)
    /* C418 0010C398 42130200 */  srl        $v0, $v0, 13
    /* C41C 0010C39C 1000B0DF */  ld         $s0, 0x10($sp)
    /* C420 0010C3A0 07004230 */  andi       $v0, $v0, 0x7
    /* C424 0010C3A4 0100422C */  sltiu      $v0, $v0, 0x1
    /* C428 0010C3A8 0800E003 */  jr         $ra
    /* C42C 0010C3AC 3000BD27 */   addiu     $sp, $sp, 0x30
.size func_0010C348, . - func_0010C348

glabel func_0010C3B0
    /* C430 0010C3B0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* C434 0010C3B4 3000BFFF */  sd         $ra, 0x30($sp)
    /* C438 0010C3B8 2000B2FF */  sd         $s2, 0x20($sp)
    /* C43C 0010C3BC 1000B1FF */  sd         $s1, 0x10($sp)
    /* C440 0010C3C0 D230040C */  jal        func_0010C348
    /* C444 0010C3C4 0000B0FF */   sd        $s0, 0x0($sp)
    /* C448 0010C3C8 1E004010 */  beqz       $v0, .L0010C444
    /* C44C 0010C3CC 3F00023C */   lui       $v0, %hi(D_3E84C0)
    /* C450 0010C3D0 02001224 */  addiu      $s2, $zero, 0x2
    /* C454 0010C3D4 C0845024 */  addiu      $s0, $v0, %lo(D_3E84C0)
    /* C458 0010C3D8 C084448C */  lw         $a0, -0x7B40($v0)
    /* C45C 0010C3DC 0400058E */  lw         $a1, 0x4($s0)
    /* C460 0010C3E0 B830040C */  jal        func_0010C2E0
    /* C464 0010C3E4 10001126 */   addiu     $s1, $s0, 0x10
    /* C468 0010C3E8 3E00053C */  lui        $a1, %hi(D_3E7D18)
    /* C46C 0010C3EC 0780043C */  lui        $a0, (0x80074000 >> 16)
    /* C470 0010C3F0 A8070624 */  addiu      $a2, $zero, 0x7A8
    /* C474 0010C3F4 187DA524 */  addiu      $a1, $a1, %lo(D_3E7D18)
    /* C478 0010C3F8 BC30040C */  jal        func_0010C2F0
    /* C47C 0010C3FC 00408434 */   ori       $a0, $a0, (0x80074000 & 0xFFFF)
    /* C480 0010C400 880C040C */  jal        func_00103220
    /* C484 0010C404 2D200000 */   daddu     $a0, $zero, $zero
    /* C488 0010C408 880C040C */  jal        func_00103220
    /* C48C 0010C40C 02000424 */   addiu     $a0, $zero, 0x2
    /* C490 0010C410 0800048E */  lw         $a0, 0x8($s0)
    /* C494 0010C414 B830040C */  jal        func_0010C2E0
    /* C498 0010C418 0C00058E */   lw        $a1, 0xC($s0)
    /* C49C 0010C41C 0000248E */  lw         $a0, 0x0($s1)
  .L0010C420:
    /* C4A0 0010C420 CE30040C */  jal        func_0010C338
    /* C4A4 0010C424 01005226 */   addiu     $s2, $s2, 0x1
    /* C4A8 0010C428 0000248E */  lw         $a0, 0x0($s1)
    /* C4AC 0010C42C 2D284000 */  daddu      $a1, $v0, $zero
    /* C4B0 0010C430 B830040C */  jal        func_0010C2E0
    /* C4B4 0010C434 08003126 */   addiu     $s1, $s1, 0x8
    /* C4B8 0010C438 0300422E */  sltiu      $v0, $s2, 0x3
    /* C4BC 0010C43C F8FF4054 */  bnel       $v0, $zero, .L0010C420
    /* C4C0 0010C440 0000248E */   lw        $a0, 0x0($s1)
  .L0010C444:
    /* C4C4 0010C444 3000BFDF */  ld         $ra, 0x30($sp)
    /* C4C8 0010C448 2000B2DF */  ld         $s2, 0x20($sp)
    /* C4CC 0010C44C 1000B1DF */  ld         $s1, 0x10($sp)
    /* C4D0 0010C450 0000B0DF */  ld         $s0, 0x0($sp)
    /* C4D4 0010C454 0800E003 */  jr         $ra
    /* C4D8 0010C458 4000BD27 */   addiu     $sp, $sp, 0x40
    /* C4DC 0010C45C 00000000 */  nop
.size func_0010C3B0, . - func_0010C3B0

/* Handwritten function */
glabel func_0010C460
    /* C4E0 0010C460 5A000324 */  addiu      $v1, $zero, 0x5A
    /* C4E4 0010C464 0C000000 */  syscall    0 /* handwritten instruction */
    /* C4E8 0010C468 0800E003 */  jr         $ra
    /* C4EC 0010C46C 00000000 */   nop
.size func_0010C460, . - func_0010C460

glabel func_0010C470
    /* C4F0 0010C470 0900C010 */  beqz       $a2, .L0010C498
    /* C4F4 0010C474 2D380000 */   daddu     $a3, $zero, $zero
  .L0010C478:
    /* C4F8 0010C478 0000A390 */  lbu        $v1, 0x0($a1)
    /* C4FC 0010C47C 0100E724 */  addiu      $a3, $a3, 0x1
    /* C500 0010C480 0100A524 */  addiu      $a1, $a1, 0x1
    /* C504 0010C484 2B10E600 */  sltu       $v0, $a3, $a2
    /* C508 0010C488 000083A0 */  sb         $v1, 0x0($a0)
    /* C50C 0010C48C 01008424 */  addiu      $a0, $a0, 0x1
    /* C510 0010C490 F9FF4014 */  bnez       $v0, .L0010C478
    /* C514 0010C494 00000000 */   nop
  .L0010C498:
    /* C518 0010C498 0800E003 */  jr         $ra
    /* C51C 0010C49C 2D100000 */   daddu     $v0, $zero, $zero
.size func_0010C470, . - func_0010C470

/* Handwritten function */
glabel func_0010C4A0
    /* C520 0010C4A0 74000324 */  addiu      $v1, $zero, 0x74
    /* C524 0010C4A4 0C000000 */  syscall    0 /* handwritten instruction */
    /* C528 0010C4A8 0800E003 */  jr         $ra
    /* C52C 0010C4AC 00000000 */   nop
.size func_0010C4A0, . - func_0010C4A0

glabel func_0010C4B0
    /* C530 0010C4B0 80FFBD27 */  addiu      $sp, $sp, -0x80
    /* C534 0010C4B4 3E00023C */  lui        $v0, (0x3E7A20 >> 16)
    /* C538 0010C4B8 4000B3FF */  sd         $s3, 0x40($sp)
    /* C53C 0010C4BC 3F00033C */  lui        $v1, %hi(D_3E84D8)
    /* C540 0010C4C0 207A538C */  lw         $s3, (0x3E7A20 & 0xFFFF)($v0)
    /* C544 0010C4C4 D8846724 */  addiu      $a3, $v1, %lo(D_3E84D8)
    /* C548 0010C4C8 6000B5FF */  sd         $s5, 0x60($sp)
    /* C54C 0010C4CC 5000B4FF */  sd         $s4, 0x50($sp)
    /* C550 0010C4D0 40006226 */  addiu      $v0, $s3, 0x40
    /* C554 0010C4D4 3000B2FF */  sd         $s2, 0x30($sp)
    /* C558 0010C4D8 2DA84000 */  daddu      $s5, $v0, $zero
    /* C55C 0010C4DC 2000B1FF */  sd         $s1, 0x20($sp)
    /* C560 0010C4E0 2D90A000 */  daddu      $s2, $a1, $zero
    /* C564 0010C4E4 1000B0FF */  sd         $s0, 0x10($sp)
    /* C568 0010C4E8 2DA0C000 */  daddu      $s4, $a2, $zero
    /* C56C 0010C4EC 7000BFFF */  sd         $ra, 0x70($sp)
    /* C570 0010C4F0 2D808000 */  daddu      $s0, $a0, $zero
    /* C574 0010C4F4 D884648C */  lw         $a0, -0x7B28($v1)
    /* C578 0010C4F8 0400E58C */  lw         $a1, 0x4($a3)
    /* C57C 0010C4FC 2831040C */  jal        func_0010C4A0
    /* C580 0010C500 0000A2AF */   sw        $v0, 0x0($sp)
    /* C584 0010C504 1000432A */  slti       $v1, $s2, 0x10
    /* C588 0010C508 0F000224 */  addiu      $v0, $zero, 0xF
    /* C58C 0010C50C 2D206002 */  daddu      $a0, $s3, $zero
    /* C590 0010C510 0A904300 */  movz       $s2, $v0, $v1
    /* C594 0010C514 2D28A003 */  daddu      $a1, $sp, $zero
    /* C598 0010C518 1831040C */  jal        func_0010C460
    /* C59C 0010C51C 04000624 */   addiu     $a2, $zero, 0x4
    /* C5A0 0010C520 04007326 */  addiu      $s3, $s3, 0x4
    /* C5A4 0010C524 70DB0D0C */  jal        func_00376DC0
    /* C5A8 0010C528 2D200002 */   daddu     $a0, $s0, $zero
    /* C5AC 0010C52C 01005124 */  addiu      $s1, $v0, 0x1
    /* C5B0 0010C530 0000A48F */  lw         $a0, 0x0($sp)
    /* C5B4 0010C534 2D280002 */  daddu      $a1, $s0, $zero
    /* C5B8 0010C538 1831040C */  jal        func_0010C460
    /* C5BC 0010C53C 2D302002 */   daddu     $a2, $s1, $zero
    /* C5C0 0010C540 0000A38F */  lw         $v1, 0x0($sp)
    /* C5C4 0010C544 21187100 */  addu       $v1, $v1, $s1
    /* C5C8 0010C548 1500401A */  blez       $s2, .L0010C5A0
    /* C5CC 0010C54C 0000A3AF */   sw        $v1, 0x0($sp)
    /* C5D0 0010C550 2D808002 */  daddu      $s0, $s4, $zero
    /* C5D4 0010C554 00000000 */  nop
  .L0010C558:
    /* C5D8 0010C558 2D206002 */  daddu      $a0, $s3, $zero
    /* C5DC 0010C55C 2D28A003 */  daddu      $a1, $sp, $zero
    /* C5E0 0010C560 04000624 */  addiu      $a2, $zero, 0x4
    /* C5E4 0010C564 1831040C */  jal        func_0010C460
    /* C5E8 0010C568 04007326 */   addiu     $s3, $s3, 0x4
    /* C5EC 0010C56C FFFF5226 */  addiu      $s2, $s2, -0x1
    /* C5F0 0010C570 70DB0D0C */  jal        func_00376DC0
    /* C5F4 0010C574 0000048E */   lw        $a0, 0x0($s0)
    /* C5F8 0010C578 01005124 */  addiu      $s1, $v0, 0x1
    /* C5FC 0010C57C 0000058E */  lw         $a1, 0x0($s0)
    /* C600 0010C580 0000A48F */  lw         $a0, 0x0($sp)
    /* C604 0010C584 2D302002 */  daddu      $a2, $s1, $zero
    /* C608 0010C588 1831040C */  jal        func_0010C460
    /* C60C 0010C58C 04001026 */   addiu     $s0, $s0, 0x4
    /* C610 0010C590 0000A38F */  lw         $v1, 0x0($sp)
    /* C614 0010C594 21187100 */  addu       $v1, $v1, $s1
    /* C618 0010C598 EFFF4016 */  bnez       $s2, .L0010C558
    /* C61C 0010C59C 0000A3AF */   sw        $v1, 0x0($sp)
  .L0010C5A0:
    /* C620 0010C5A0 2D10A002 */  daddu      $v0, $s5, $zero
    /* C624 0010C5A4 7000BFDF */  ld         $ra, 0x70($sp)
    /* C628 0010C5A8 6000B5DF */  ld         $s5, 0x60($sp)
    /* C62C 0010C5AC 5000B4DF */  ld         $s4, 0x50($sp)
    /* C630 0010C5B0 4000B3DF */  ld         $s3, 0x40($sp)
    /* C634 0010C5B4 3000B2DF */  ld         $s2, 0x30($sp)
    /* C638 0010C5B8 2000B1DF */  ld         $s1, 0x20($sp)
    /* C63C 0010C5BC 1000B0DF */  ld         $s0, 0x10($sp)
    /* C640 0010C5C0 0800E003 */  jr         $ra
    /* C644 0010C5C4 8000BD27 */   addiu     $sp, $sp, 0x80
.size func_0010C4B0, . - func_0010C4B0

glabel func_0010C5C8
    /* C648 0010C5C8 842E0408 */  j          func_0010BA10
    /* C64C 0010C5CC 00000000 */   nop
.size func_0010C5C8, . - func_0010C5C8

glabel func_0010C5D0
    /* C650 0010C5D0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* C654 0010C5D4 1000B1FF */  sd         $s1, 0x10($sp)
    /* C658 0010C5D8 2D888000 */  daddu      $s1, $a0, $zero
    /* C65C 0010C5DC 2000B2FF */  sd         $s2, 0x20($sp)
    /* C660 0010C5E0 0000B0FF */  sd         $s0, 0x0($sp)
    /* C664 0010C5E4 2D90A000 */  daddu      $s2, $a1, $zero
    /* C668 0010C5E8 2D80C000 */  daddu      $s0, $a2, $zero
    /* C66C 0010C5EC 4600043C */  lui        $a0, %hi(D_459C90)
    /* C670 0010C5F0 2D280002 */  daddu      $a1, $s0, $zero
    /* C674 0010C5F4 3000BFFF */  sd         $ra, 0x30($sp)
    /* C678 0010C5F8 909C8424 */  addiu      $a0, $a0, %lo(D_459C90)
    /* C67C 0010C5FC 2C31040C */  jal        func_0010C4B0
    /* C680 0010C600 2D30E000 */   daddu     $a2, $a3, $zero
    /* C684 0010C604 7231040C */  jal        func_0010C5C8
    /* C688 0010C608 00000000 */   nop
    /* C68C 0010C60C 3E00023C */  lui        $v0, (0x3E7A20 >> 16)
    /* C690 0010C610 2D202002 */  daddu      $a0, $s1, $zero
    /* C694 0010C614 207A478C */  lw         $a3, (0x3E7A20 & 0xFFFF)($v0)
    /* C698 0010C618 2D284002 */  daddu      $a1, $s2, $zero
    /* C69C 0010C61C 2D300002 */  daddu      $a2, $s0, $zero
    /* C6A0 0010C620 FC0A040C */  jal        func_00102BF0
    /* C6A4 0010C624 0400E724 */   addiu     $a3, $a3, 0x4
    /* C6A8 0010C628 3000BFDF */  ld         $ra, 0x30($sp)
    /* C6AC 0010C62C 2000B2DF */  ld         $s2, 0x20($sp)
    /* C6B0 0010C630 1000B1DF */  ld         $s1, 0x10($sp)
    /* C6B4 0010C634 0000B0DF */  ld         $s0, 0x0($sp)
    /* C6B8 0010C638 0800E003 */  jr         $ra
    /* C6BC 0010C63C 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_0010C5D0, . - func_0010C5D0

glabel func_0010C640
    /* C6C0 0010C640 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* C6C4 0010C644 1000B1FF */  sd         $s1, 0x10($sp)
    /* C6C8 0010C648 0000B0FF */  sd         $s0, 0x0($sp)
    /* C6CC 0010C64C 2000BFFF */  sd         $ra, 0x20($sp)
    /* C6D0 0010C650 2C31040C */  jal        func_0010C4B0
    /* C6D4 0010C654 2D88A000 */   daddu     $s1, $a1, $zero
    /* C6D8 0010C658 7231040C */  jal        func_0010C5C8
    /* C6DC 0010C65C 2D804000 */   daddu     $s0, $v0, $zero
    /* C6E0 0010C660 3E00023C */  lui        $v0, (0x3E7A20 >> 16)
    /* C6E4 0010C664 2D200002 */  daddu      $a0, $s0, $zero
    /* C6E8 0010C668 207A468C */  lw         $a2, (0x3E7A20 & 0xFFFF)($v0)
    /* C6EC 0010C66C 2D282002 */  daddu      $a1, $s1, $zero
    /* C6F0 0010C670 2000BFDF */  ld         $ra, 0x20($sp)
    /* C6F4 0010C674 1000B1DF */  ld         $s1, 0x10($sp)
    /* C6F8 0010C678 0400C624 */  addiu      $a2, $a2, 0x4
    /* C6FC 0010C67C 0000B0DF */  ld         $s0, 0x0($sp)
    /* C700 0010C680 F80A0408 */  j          func_00102BE0
    /* C704 0010C684 3000BD27 */   addiu     $sp, $sp, 0x30
.size func_0010C640, . - func_0010C640

glabel func_0010C688
    /* C708 0010C688 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* C70C 0010C68C 0000B0FF */  sd         $s0, 0x0($sp)
    /* C710 0010C690 1000BFFF */  sd         $ra, 0x10($sp)
    /* C714 0010C694 7231040C */  jal        func_0010C5C8
    /* C718 0010C698 2D808000 */   daddu     $s0, $a0, $zero
    /* C71C 0010C69C 2D200002 */  daddu      $a0, $s0, $zero
    /* C720 0010C6A0 1000BFDF */  ld         $ra, 0x10($sp)
    /* C724 0010C6A4 0000B0DF */  ld         $s0, 0x0($sp)
    /* C728 0010C6A8 F00A0408 */  j          func_00102BC0
    /* C72C 0010C6AC 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_0010C688, . - func_0010C688

glabel func_0010C6B0
    /* C730 0010C6B0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* C734 0010C6B4 2D30A000 */  daddu      $a2, $a1, $zero
    /* C738 0010C6B8 0000B0FF */  sd         $s0, 0x0($sp)
    /* C73C 0010C6BC 2D808000 */  daddu      $s0, $a0, $zero
    /* C740 0010C6C0 1000BFFF */  sd         $ra, 0x10($sp)
    /* C744 0010C6C4 4600043C */  lui        $a0, %hi(D_459C90)
    /* C748 0010C6C8 2D280002 */  daddu      $a1, $s0, $zero
    /* C74C 0010C6CC 2C31040C */  jal        func_0010C4B0
    /* C750 0010C6D0 909C8424 */   addiu     $a0, $a0, %lo(D_459C90)
    /* C754 0010C6D4 7231040C */  jal        func_0010C5C8
    /* C758 0010C6D8 00000000 */   nop
    /* C75C 0010C6DC 3E00023C */  lui        $v0, (0x3E7A20 >> 16)
    /* C760 0010C6E0 2D200002 */  daddu      $a0, $s0, $zero
    /* C764 0010C6E4 207A458C */  lw         $a1, (0x3E7A20 & 0xFFFF)($v0)
    /* C768 0010C6E8 1000BFDF */  ld         $ra, 0x10($sp)
    /* C76C 0010C6EC 0000B0DF */  ld         $s0, 0x0($sp)
    /* C770 0010C6F0 0400A524 */  addiu      $a1, $a1, 0x4
    /* C774 0010C6F4 F00C0408 */  j          func_001033C0
    /* C778 0010C6F8 2000BD27 */   addiu     $sp, $sp, 0x20
    /* C77C 0010C6FC 00000000 */  nop
.size func_0010C6B0, . - func_0010C6B0

/* Handwritten function */
glabel func_0010C700
    /* C780 0010C700 74000324 */  addiu      $v1, $zero, 0x74
    /* C784 0010C704 0C000000 */  syscall    0 /* handwritten instruction */
    /* C788 0010C708 0800E003 */  jr         $ra
    /* C78C 0010C70C 00000000 */   nop
.size func_0010C700, . - func_0010C700

/* Handwritten function */
glabel func_0010C710
    /* C790 0010C710 5A000324 */  addiu      $v1, $zero, 0x5A
    /* C794 0010C714 0C000000 */  syscall    0 /* handwritten instruction */
    /* C798 0010C718 0800E003 */  jr         $ra
    /* C79C 0010C71C 00000000 */   nop
.size func_0010C710, . - func_0010C710

glabel func_0010C720
    /* C7A0 0010C720 82300600 */  srl        $a2, $a2, 2
    /* C7A4 0010C724 0A00C010 */  beqz       $a2, .L0010C750
    /* C7A8 0010C728 2D380000 */   daddu     $a3, $zero, $zero
    /* C7AC 0010C72C 00000000 */  nop
  .L0010C730:
    /* C7B0 0010C730 0000A38C */  lw         $v1, 0x0($a1)
    /* C7B4 0010C734 0100E724 */  addiu      $a3, $a3, 0x1
    /* C7B8 0010C738 0400A524 */  addiu      $a1, $a1, 0x4
    /* C7BC 0010C73C 2B10E600 */  sltu       $v0, $a3, $a2
    /* C7C0 0010C740 000083AC */  sw         $v1, 0x0($a0)
    /* C7C4 0010C744 04008424 */  addiu      $a0, $a0, 0x4
    /* C7C8 0010C748 F9FF4014 */  bnez       $v0, .L0010C730
    /* C7CC 0010C74C 00000000 */   nop
  .L0010C750:
    /* C7D0 0010C750 0800E003 */  jr         $ra
    /* C7D4 0010C754 2D100000 */   daddu     $v0, $zero, $zero
.size func_0010C720, . - func_0010C720

/* Handwritten function */
glabel func_0010C758
    /* C7D8 0010C758 5B000324 */  addiu      $v1, $zero, 0x5B
    /* C7DC 0010C75C 0C000000 */  syscall    0 /* handwritten instruction */
    /* C7E0 0010C760 0800E003 */  jr         $ra
    /* C7E4 0010C764 00000000 */   nop
.size func_0010C758, . - func_0010C758

glabel func_0010C768
    /* C7E8 0010C768 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* C7EC 0010C76C 0010023C */  lui        $v0, (0x10001810 >> 16)
    /* C7F0 0010C770 3000BFFF */  sd         $ra, 0x30($sp)
    /* C7F4 0010C774 10184234 */  ori        $v0, $v0, (0x10001810 & 0xFFFF)
    /* C7F8 0010C778 2000B2FF */  sd         $s2, 0x20($sp)
    /* C7FC 0010C77C 1000B1FF */  sd         $s1, 0x10($sp)
    /* C800 0010C780 0000B0FF */  sd         $s0, 0x0($sp)
    /* C804 0010C784 0000438C */  lw         $v1, 0x0($v0)
    /* C808 0010C788 00016330 */  andi       $v1, $v1, 0x100
    /* C80C 0010C78C 26006014 */  bnez       $v1, .L0010C828
    /* C810 0010C790 3000BFDF */   ld        $ra, 0x30($sp)
    /* C814 0010C794 3F00023C */  lui        $v0, %hi(D_3E8C48)
    /* C818 0010C798 02001224 */  addiu      $s2, $zero, 0x2
    /* C81C 0010C79C 488C5024 */  addiu      $s0, $v0, %lo(D_3E8C48)
    /* C820 0010C7A0 488C448C */  lw         $a0, -0x73B8($v0)
    /* C824 0010C7A4 0400058E */  lw         $a1, 0x4($s0)
    /* C828 0010C7A8 C031040C */  jal        func_0010C700
    /* C82C 0010C7AC 10001126 */   addiu     $s1, $s0, 0x10
    /* C830 0010C7B0 3F00053C */  lui        $a1, %hi(D_3E84E0)
    /* C834 0010C7B4 0780043C */  lui        $a0, (0x80076000 >> 16)
    /* C838 0010C7B8 E084A524 */  addiu      $a1, $a1, %lo(D_3E84E0)
    /* C83C 0010C7BC 00608434 */  ori        $a0, $a0, (0x80076000 & 0xFFFF)
    /* C840 0010C7C0 C431040C */  jal        func_0010C710
    /* C844 0010C7C4 40070624 */   addiu     $a2, $zero, 0x740
    /* C848 0010C7C8 3F00053C */  lui        $a1, %hi(D_3E8C20)
    /* C84C 0010C7CC 0800043C */  lui        $a0, (0x82000 >> 16)
    /* C850 0010C7D0 208CA524 */  addiu      $a1, $a1, %lo(D_3E8C20)
    /* C854 0010C7D4 00208434 */  ori        $a0, $a0, (0x82000 & 0xFFFF)
    /* C858 0010C7D8 C431040C */  jal        func_0010C710
    /* C85C 0010C7DC 28000624 */   addiu     $a2, $zero, 0x28
    /* C860 0010C7E0 880C040C */  jal        func_00103220
    /* C864 0010C7E4 2D200000 */   daddu     $a0, $zero, $zero
    /* C868 0010C7E8 880C040C */  jal        func_00103220
    /* C86C 0010C7EC 02000424 */   addiu     $a0, $zero, 0x2
    /* C870 0010C7F0 0800048E */  lw         $a0, 0x8($s0)
    /* C874 0010C7F4 C031040C */  jal        func_0010C700
    /* C878 0010C7F8 0C00058E */   lw        $a1, 0xC($s0)
    /* C87C 0010C7FC 0000248E */  lw         $a0, 0x0($s1)
  .L0010C800:
    /* C880 0010C800 D631040C */  jal        func_0010C758
    /* C884 0010C804 01005226 */   addiu     $s2, $s2, 0x1
    /* C888 0010C808 0000248E */  lw         $a0, 0x0($s1)
    /* C88C 0010C80C 2D284000 */  daddu      $a1, $v0, $zero
    /* C890 0010C810 C031040C */  jal        func_0010C700
    /* C894 0010C814 08003126 */   addiu     $s1, $s1, 0x8
    /* C898 0010C818 0800422E */  sltiu      $v0, $s2, 0x8
    /* C89C 0010C81C F8FF4054 */  bnel       $v0, $zero, .L0010C800
    /* C8A0 0010C820 0000248E */   lw        $a0, 0x0($s1)
    /* C8A4 0010C824 3000BFDF */  ld         $ra, 0x30($sp)
  .L0010C828:
    /* C8A8 0010C828 2000B2DF */  ld         $s2, 0x20($sp)
    /* C8AC 0010C82C 1000B1DF */  ld         $s1, 0x10($sp)
    /* C8B0 0010C830 0000B0DF */  ld         $s0, 0x0($sp)
    /* C8B4 0010C834 0800E003 */  jr         $ra
    /* C8B8 0010C838 4000BD27 */   addiu     $sp, $sp, 0x40
    /* C8BC 0010C83C 00000000 */  nop
.size func_0010C768, . - func_0010C768

/* Handwritten function */
glabel func_0010C840
    /* C8C0 0010C840 00600340 */  mfc0       $v1, $12 /* handwritten instruction */
    /* C8C4 0010C844 0100023C */  lui        $v0, (0x10000 >> 16)
    /* C8C8 0010C848 24186200 */  and        $v1, $v1, $v0
    /* C8CC 0010C84C 0B006010 */  beqz       $v1, .L0010C87C
    /* C8D0 0010C850 0100063C */   lui       $a2, (0x10000 >> 16)
    /* C8D4 0010C854 00000000 */  nop
  .L0010C858:
    /* C8D8 0010C858 39000042 */  di /* handwritten instruction */
    /* C8DC 0010C85C 0F040000 */  sync.p
    /* C8E0 0010C860 00600240 */  mfc0       $v0, $12 /* handwritten instruction */
    /* C8E4 0010C864 24104600 */  and        $v0, $v0, $a2
    /* C8E8 0010C868 00000000 */  nop
    /* C8EC 0010C86C 00000000 */  nop
    /* C8F0 0010C870 00000000 */  nop
    /* C8F4 0010C874 F8FF4014 */  bnez       $v0, .L0010C858
    /* C8F8 0010C878 00000000 */   nop
  .L0010C87C:
    /* C8FC 0010C87C 00600240 */  mfc0       $v0, $12 /* handwritten instruction */
    /* C900 0010C880 0F040000 */  sync.p
    /* C904 0010C884 06004234 */  ori        $v0, $v0, 0x6
    /* C908 0010C888 02004238 */  xori       $v0, $v0, 0x2
    /* C90C 0010C88C 25104300 */  or         $v0, $v0, $v1
    /* C910 0010C890 00608240 */  mtc0       $v0, $12 /* handwritten instruction */
    /* C914 0010C894 0F040000 */  sync.p
    /* C918 0010C898 000085AC */  sw         $a1, 0x0($a0)
    /* C91C 0010C89C 00F09F40 */  mtc0       $ra, $30 /* handwritten instruction */
    /* C920 0010C8A0 0F040000 */  sync.p
    /* C924 0010C8A4 18000042 */  eret /* handwritten instruction */
    /* C928 0010C8A8 0800E003 */  jr         $ra
    /* C92C 0010C8AC 00000000 */   nop
.size func_0010C840, . - func_0010C840

glabel func_0010C8B0
    /* C930 0010C8B0 2D288000 */  daddu      $a1, $a0, $zero
    /* C934 0010C8B4 00B0043C */  lui        $a0, (0xB0001000 >> 16)
    /* C938 0010C8B8 10320408 */  j          func_0010C840
    /* C93C 0010C8BC 00108434 */   ori       $a0, $a0, (0xB0001000 & 0xFFFF)
.size func_0010C8B0, . - func_0010C8B0

glabel func_0010C8C0
    /* C940 0010C8C0 2D288000 */  daddu      $a1, $a0, $zero
    /* C944 0010C8C4 00B0043C */  lui        $a0, (0xB0001010 >> 16)
    /* C948 0010C8C8 10320408 */  j          func_0010C840
    /* C94C 0010C8CC 10108434 */   ori       $a0, $a0, (0xB0001010 & 0xFFFF)
.size func_0010C8C0, . - func_0010C8C0

glabel func_0010C8D0
    /* C950 0010C8D0 2D288000 */  daddu      $a1, $a0, $zero
    /* C954 0010C8D4 00B0043C */  lui        $a0, (0xB0001020 >> 16)
    /* C958 0010C8D8 10320408 */  j          func_0010C840
    /* C95C 0010C8DC 20108434 */   ori       $a0, $a0, (0xB0001020 & 0xFFFF)
.size func_0010C8D0, . - func_0010C8D0

glabel func_0010C8E0
    /* C960 0010C8E0 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* C964 0010C8E4 2000B2FF */  sd         $s2, 0x20($sp)
    /* C968 0010C8E8 4000B4FF */  sd         $s4, 0x40($sp)
    /* C96C 0010C8EC 3F00123C */  lui        $s2, %hi(D_3E8C88)
    /* C970 0010C8F0 1000B1FF */  sd         $s1, 0x10($sp)
    /* C974 0010C8F4 5000BFFF */  sd         $ra, 0x50($sp)
    /* C978 0010C8F8 888C5126 */  addiu      $s1, $s2, %lo(D_3E8C88)
    /* C97C 0010C8FC 3000B3FF */  sd         $s3, 0x30($sp)
    /* C980 0010C900 0000B0FF */  sd         $s0, 0x0($sp)
    /* C984 0010C904 0800228E */  lw         $v0, 0x8($s1)
    /* C988 0010C908 04004004 */  bltz       $v0, .L0010C91C
    /* C98C 0010C90C 2DA08000 */   daddu     $s4, $a0, $zero
    /* C990 0010C910 0080023C */  lui        $v0, (0x80008001 >> 16)
    /* C994 0010C914 3F000010 */  b          .L0010CA14
    /* C998 0010C918 01804234 */   ori       $v0, $v0, (0x80008001 & 0xFFFF)
  .L0010C91C:
    /* C99C 0010C91C 5000133C */  lui        $s3, %hi(D_500600)
    /* C9A0 0010C920 888C40FE */  sd         $zero, -0x7378($s2)
    /* C9A4 0010C924 00067026 */  addiu      $s0, $s3, %lo(D_500600)
    /* C9A8 0010C928 100020AE */  sw         $zero, 0x10($s1)
    /* C9AC 0010C92C 2D200002 */  daddu      $a0, $s0, $zero
    /* C9B0 0010C930 2D280000 */  daddu      $a1, $zero, $zero
    /* C9B4 0010C934 84D40D0C */  jal        func_00375210
    /* C9B8 0010C938 00200624 */   addiu     $a2, $zero, 0x2000
    /* C9BC 0010C93C 140030AE */  sw         $s0, 0x14($s1)
    /* C9C0 0010C940 00200326 */  addiu      $v1, $s0, 0x2000
    /* C9C4 0010C944 7F000224 */  addiu      $v0, $zero, 0x7F
    /* C9C8 0010C948 C01F1026 */  addiu      $s0, $s0, 0x1FC0
    /* C9CC 0010C94C 00000000 */  nop
  .L0010C950:
    /* C9D0 0010C950 000003AE */  sw         $v1, 0x0($s0)
    /* C9D4 0010C954 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* C9D8 0010C958 C0FF1026 */  addiu      $s0, $s0, -0x40
    /* C9DC 0010C95C C0FF6324 */  addiu      $v1, $v1, -0x40
    /* C9E0 0010C960 00000000 */  nop
    /* C9E4 0010C964 FAFF4104 */  bgez       $v0, .L0010C950
    /* C9E8 0010C968 00000000 */   nop
    /* C9EC 0010C96C 00066226 */  addiu      $v0, $s3, %lo(D_500600)
    /* C9F0 0010C970 EA36040C */  jal        func_0010DBA8
    /* C9F4 0010C974 C01F40AC */   sw        $zero, 0x1FC0($v0)
    /* C9F8 0010C978 1100053C */  lui        $a1, %hi(func_0010CE80)
    /* C9FC 0010C97C 0B000424 */  addiu      $a0, $zero, 0xB
    /* CA00 0010C980 80CEA524 */  addiu      $a1, $a1, %lo(func_0010CE80)
    /* CA04 0010C984 2D300000 */  daddu      $a2, $zero, $zero
    /* CA08 0010C988 240B040C */  jal        func_00102C90
    /* CA0C 0010C98C 2D380000 */   daddu     $a3, $zero, $zero
    /* CA10 0010C990 2D184000 */  daddu      $v1, $v0, $zero
    /* CA14 0010C994 04006304 */  bgezl      $v1, .L0010C9A8
    /* CA18 0010C998 888C4226 */   addiu     $v0, $s2, %lo(D_3E8C88)
    /* CA1C 0010C99C 0080023C */  lui        $v0, (0x80009021 >> 16)
    /* CA20 0010C9A0 1C000010 */  b          .L0010CA14
    /* CA24 0010C9A4 21904234 */   ori       $v0, $v0, (0x80009021 & 0xFFFF)
  .L0010C9A8:
    /* CA28 0010C9A8 F82F040C */  jal        func_0010BFE0
    /* CA2C 0010C9AC 080043AC */   sw        $v1, 0x8($v0)
    /* CA30 0010C9B0 0010033C */  lui        $v1, (0x10001010 >> 16)
    /* CA34 0010C9B4 2D884000 */  daddu      $s1, $v0, $zero
    /* CA38 0010C9B8 10106334 */  ori        $v1, $v1, (0x10001010 & 0xFFFF)
    /* CA3C 0010C9BC FFFF023C */  lui        $v0, (0xFFFFFFFC >> 16)
    /* CA40 0010C9C0 0000708C */  lw         $s0, 0x0($v1)
    /* CA44 0010C9C4 FCFF4234 */  ori        $v0, $v0, (0xFFFFFFFC & 0xFFFF)
    /* CA48 0010C9C8 24100202 */  and        $v0, $s0, $v0
    /* CA4C 0010C9CC 25805400 */  or         $s0, $v0, $s4
    /* CA50 0010C9D0 00031036 */  ori        $s0, $s0, 0x300
    /* CA54 0010C9D4 80000232 */  andi       $v0, $s0, 0x80
    /* CA58 0010C9D8 05004014 */  bnez       $v0, .L0010C9F0
    /* CA5C 0010C9DC 2D200000 */   daddu     $a0, $zero, $zero
    /* CA60 0010C9E0 2C32040C */  jal        func_0010C8B0
    /* CA64 0010C9E4 800C1036 */   ori       $s0, $s0, 0xC80
    /* CA68 0010C9E8 3432040C */  jal        func_0010C8D0
    /* CA6C 0010C9EC FFFF0434 */   ori       $a0, $zero, 0xFFFF
  .L0010C9F0:
    /* CA70 0010C9F0 3032040C */  jal        func_0010C8C0
    /* CA74 0010C9F4 2D200002 */   daddu     $a0, $s0, $zero
    /* CA78 0010C9F8 BA0E040C */  jal        func_00103AE8
    /* CA7C 0010C9FC 0B000424 */   addiu     $a0, $zero, 0xB
    /* CA80 0010CA00 04002012 */  beqz       $s1, .L0010CA14
    /* CA84 0010CA04 2D100000 */   daddu     $v0, $zero, $zero
    /* CA88 0010CA08 0E30040C */  jal        func_0010C038
    /* CA8C 0010CA0C 00000000 */   nop
    /* CA90 0010CA10 2D100000 */  daddu      $v0, $zero, $zero
  .L0010CA14:
    /* CA94 0010CA14 5000BFDF */  ld         $ra, 0x50($sp)
    /* CA98 0010CA18 4000B4DF */  ld         $s4, 0x40($sp)
    /* CA9C 0010CA1C 3000B3DF */  ld         $s3, 0x30($sp)
    /* CAA0 0010CA20 2000B2DF */  ld         $s2, 0x20($sp)
    /* CAA4 0010CA24 1000B1DF */  ld         $s1, 0x10($sp)
    /* CAA8 0010CA28 0000B0DF */  ld         $s0, 0x0($sp)
    /* CAAC 0010CA2C 0800E003 */  jr         $ra
    /* CAB0 0010CA30 6000BD27 */   addiu     $sp, $sp, 0x60
    /* CAB4 0010CA34 00000000 */  nop
.size func_0010C8E0, . - func_0010C8E0
