.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0010D448
    /* D4C8 0010D448 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* D4CC 0010D44C 82120400 */  srl        $v0, $a0, 10
    /* D4D0 0010D450 0000B0FF */  sd         $s0, 0x0($sp)
    /* D4D4 0010D454 2000BFFF */  sd         $ra, 0x20($sp)
    /* D4D8 0010D458 80810200 */  sll        $s0, $v0, 6
    /* D4DC 0010D45C 05008004 */  bltz       $a0, .L0010D474
    /* D4E0 0010D460 1000B1FF */   sd        $s1, 0x10($sp)
    /* D4E4 0010D464 0800038E */  lw         $v1, 0x8($s0)
    /* D4E8 0010D468 FF038230 */  andi       $v0, $a0, 0x3FF
    /* D4EC 0010D46C 04004350 */  beql       $v0, $v1, .L0010D480
    /* D4F0 0010D470 3F00023C */   lui       $v0, %hi(D_3E8C88)
  .L0010D474:
    /* D4F4 0010D474 0080023C */  lui        $v0, (0x80008002 >> 16)
    /* D4F8 0010D478 19000010 */  b          .L0010D4E0
    /* D4FC 0010D47C 02804234 */   ori       $v0, $v0, (0x80008002 & 0xFFFF)
  .L0010D480:
    /* D500 0010D480 888C4224 */  addiu      $v0, $v0, %lo(D_3E8C88)
    /* D504 0010D484 1C00438C */  lw         $v1, 0x1C($v0)
    /* D508 0010D488 04006454 */  bnel       $v1, $a0, .L0010D49C
    /* D50C 0010D48C 0C00028E */   lw        $v0, 0xC($s0)
    /* D510 0010D490 0080023C */  lui        $v0, (0x80000010 >> 16)
    /* D514 0010D494 12000010 */  b          .L0010D4E0
    /* D518 0010D498 10004234 */   ori       $v0, $v0, (0x80000010 & 0xFFFF)
  .L0010D49C:
    /* D51C 0010D49C 01004230 */  andi       $v0, $v0, 0x1
    /* D520 0010D4A0 0F004014 */  bnez       $v0, .L0010D4E0
    /* D524 0010D4A4 01000224 */   addiu     $v0, $zero, 0x1
    /* D528 0010D4A8 4834040C */  jal        func_0010D120
    /* D52C 0010D4AC 00000000 */   nop
    /* D530 0010D4B0 2D884000 */  daddu      $s1, $v0, $zero
    /* D534 0010D4B4 0C00028E */  lw         $v0, 0xC($s0)
    /* D538 0010D4B8 100011FE */  sd         $s1, 0x10($s0)
    /* D53C 0010D4BC 01004234 */  ori        $v0, $v0, 0x1
    /* D540 0010D4C0 02004330 */  andi       $v1, $v0, 0x2
    /* D544 0010D4C4 05006010 */  beqz       $v1, .L0010D4DC
    /* D548 0010D4C8 0C0002AE */   sw        $v0, 0xC($s0)
    /* D54C 0010D4CC 7033040C */  jal        func_0010CDC0
    /* D550 0010D4D0 2D200002 */   daddu     $a0, $s0, $zero
    /* D554 0010D4D4 0C33040C */  jal        func_0010CC30
    /* D558 0010D4D8 2D202002 */   daddu     $a0, $s1, $zero
  .L0010D4DC:
    /* D55C 0010D4DC 2D100000 */  daddu      $v0, $zero, $zero
  .L0010D4E0:
    /* D560 0010D4E0 2000BFDF */  ld         $ra, 0x20($sp)
    /* D564 0010D4E4 1000B1DF */  ld         $s1, 0x10($sp)
    /* D568 0010D4E8 0000B0DF */  ld         $s0, 0x0($sp)
    /* D56C 0010D4EC 0800E003 */  jr         $ra
    /* D570 0010D4F0 3000BD27 */   addiu     $sp, $sp, 0x30
    /* D574 0010D4F4 00000000 */  nop
.size func_0010D448, . - func_0010D448
