.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0010D888
    /* D908 0010D888 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* D90C 0010D88C 82120400 */  srl        $v0, $a0, 10
    /* D910 0010D890 3000B3FF */  sd         $s3, 0x30($sp)
    /* D914 0010D894 2000B2FF */  sd         $s2, 0x20($sp)
    /* D918 0010D898 2D98E000 */  daddu      $s3, $a3, $zero
    /* D91C 0010D89C 1000B1FF */  sd         $s1, 0x10($sp)
    /* D920 0010D8A0 2D90A000 */  daddu      $s2, $a1, $zero
    /* D924 0010D8A4 0000B0FF */  sd         $s0, 0x0($sp)
    /* D928 0010D8A8 2D88C000 */  daddu      $s1, $a2, $zero
    /* D92C 0010D8AC 4000BFFF */  sd         $ra, 0x40($sp)
    /* D930 0010D8B0 05008004 */  bltz       $a0, .L0010D8C8
    /* D934 0010D8B4 80810200 */   sll       $s0, $v0, 6
    /* D938 0010D8B8 0800038E */  lw         $v1, 0x8($s0)
    /* D93C 0010D8BC FF038230 */  andi       $v0, $a0, 0x3FF
    /* D940 0010D8C0 04004350 */  beql       $v0, $v1, .L0010D8D4
    /* D944 0010D8C4 3F00023C */   lui       $v0, %hi(D_003E8C88)
  .L0010D8C8:
    /* D948 0010D8C8 0080023C */  lui        $v0, (0x80008002 >> 16)
    /* D94C 0010D8CC 24000010 */  b          .L0010D960
    /* D950 0010D8D0 02804234 */   ori       $v0, $v0, (0x80008002 & 0xFFFF)
  .L0010D8D4:
    /* D954 0010D8D4 888C4224 */  addiu      $v0, $v0, %lo(D_003E8C88)
    /* D958 0010D8D8 1C00438C */  lw         $v1, 0x1C($v0)
    /* D95C 0010D8DC 04006454 */  bnel       $v1, $a0, .L0010D8F0
    /* D960 0010D8E0 0C00038E */   lw        $v1, 0xC($s0)
    /* D964 0010D8E4 0080023C */  lui        $v0, (0x80000010 >> 16)
    /* D968 0010D8E8 1D000010 */  b          .L0010D960
    /* D96C 0010D8EC 10004234 */   ori       $v0, $v0, (0x80000010 & 0xFFFF)
  .L0010D8F0:
    /* D970 0010D8F0 02006230 */  andi       $v0, $v1, 0x2
    /* D974 0010D8F4 04004010 */  beqz       $v0, .L0010D908
    /* D978 0010D8F8 00000000 */   nop
    /* D97C 0010D8FC 9233040C */  jal        func_0010CE48
    /* D980 0010D900 2D200002 */   daddu     $a0, $s0, $zero
    /* D984 0010D904 0C00038E */  lw         $v1, 0xC($s0)
  .L0010D908:
    /* D988 0010D908 06002016 */  bnez       $s1, .L0010D924
    /* D98C 0010D90C 280011AE */   sw        $s1, 0x28($s0)
    /* D990 0010D910 FFFF023C */  lui        $v0, (0xFFFFFFFD >> 16)
    /* D994 0010D914 FDFF4234 */  ori        $v0, $v0, (0xFFFFFFFD & 0xFFFF)
    /* D998 0010D918 24106200 */  and        $v0, $v1, $v0
    /* D99C 0010D91C 0B000010 */  b          .L0010D94C
    /* D9A0 0010D920 0C0002AE */   sw        $v0, 0xC($s0)
  .L0010D924:
    /* D9A4 0010D924 02006234 */  ori        $v0, $v1, 0x2
    /* D9A8 0010D928 200012FE */  sd         $s2, 0x20($s0)
    /* D9AC 0010D92C 0C0002AE */  sw         $v0, 0xC($s0)
    /* D9B0 0010D930 2C001CAE */  sw         $gp, 0x2C($s0)
    /* D9B4 0010D934 0C00028E */  lw         $v0, 0xC($s0)
    /* D9B8 0010D938 01004230 */  andi       $v0, $v0, 0x1
    /* D9BC 0010D93C 03004010 */  beqz       $v0, .L0010D94C
    /* D9C0 0010D940 300013AE */   sw        $s3, 0x30($s0)
    /* D9C4 0010D944 7033040C */  jal        func_0010CDC0
    /* D9C8 0010D948 2D200002 */   daddu     $a0, $s0, $zero
  .L0010D94C:
    /* D9CC 0010D94C 4834040C */  jal        func_0010D120
    /* D9D0 0010D950 00000000 */   nop
    /* D9D4 0010D954 0C33040C */  jal        func_0010CC30
    /* D9D8 0010D958 2D204000 */   daddu     $a0, $v0, $zero
    /* D9DC 0010D95C 2D100000 */  daddu      $v0, $zero, $zero
  .L0010D960:
    /* D9E0 0010D960 4000BFDF */  ld         $ra, 0x40($sp)
    /* D9E4 0010D964 3000B3DF */  ld         $s3, 0x30($sp)
    /* D9E8 0010D968 2000B2DF */  ld         $s2, 0x20($sp)
    /* D9EC 0010D96C 1000B1DF */  ld         $s1, 0x10($sp)
    /* D9F0 0010D970 0000B0DF */  ld         $s0, 0x0($sp)
    /* D9F4 0010D974 0800E003 */  jr         $ra
    /* D9F8 0010D978 5000BD27 */   addiu     $sp, $sp, 0x50
    /* D9FC 0010D97C 00000000 */  nop
.size func_0010D888, . - func_0010D888

glabel func_0010D980
    /* DA00 0010D980 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* DA04 0010D984 3000B3FF */  sd         $s3, 0x30($sp)
    /* DA08 0010D988 2000B2FF */  sd         $s2, 0x20($sp)
    /* DA0C 0010D98C 2D98E000 */  daddu      $s3, $a3, $zero
    /* DA10 0010D990 1000B1FF */  sd         $s1, 0x10($sp)
    /* DA14 0010D994 2D90C000 */  daddu      $s2, $a2, $zero
    /* DA18 0010D998 0000B0FF */  sd         $s0, 0x0($sp)
    /* DA1C 0010D99C 2D88A000 */  daddu      $s1, $a1, $zero
    /* DA20 0010D9A0 4000B4FF */  sd         $s4, 0x40($sp)
    /* DA24 0010D9A4 5000BFFF */  sd         $ra, 0x50($sp)
    /* DA28 0010D9A8 F82F040C */  jal        func_0010BFE0
    /* DA2C 0010D9AC 2D808000 */   daddu     $s0, $a0, $zero
    /* DA30 0010D9B0 2D200002 */  daddu      $a0, $s0, $zero
    /* DA34 0010D9B4 2DA04000 */  daddu      $s4, $v0, $zero
    /* DA38 0010D9B8 2D282002 */  daddu      $a1, $s1, $zero
    /* DA3C 0010D9BC 2D304002 */  daddu      $a2, $s2, $zero
    /* DA40 0010D9C0 2236040C */  jal        func_0010D888
    /* DA44 0010D9C4 2D386002 */   daddu     $a3, $s3, $zero
    /* DA48 0010D9C8 03008012 */  beqz       $s4, .L0010D9D8
    /* DA4C 0010D9CC 2D804000 */   daddu     $s0, $v0, $zero
    /* DA50 0010D9D0 0E30040C */  jal        func_0010C038
    /* DA54 0010D9D4 00000000 */   nop
  .L0010D9D8:
    /* DA58 0010D9D8 2D100002 */  daddu      $v0, $s0, $zero
    /* DA5C 0010D9DC 5000BFDF */  ld         $ra, 0x50($sp)
    /* DA60 0010D9E0 4000B4DF */  ld         $s4, 0x40($sp)
    /* DA64 0010D9E4 3000B3DF */  ld         $s3, 0x30($sp)
    /* DA68 0010D9E8 2000B2DF */  ld         $s2, 0x20($sp)
    /* DA6C 0010D9EC 1000B1DF */  ld         $s1, 0x10($sp)
    /* DA70 0010D9F0 0000B0DF */  ld         $s0, 0x0($sp)
    /* DA74 0010D9F4 0800E003 */  jr         $ra
    /* DA78 0010D9F8 6000BD27 */   addiu     $sp, $sp, 0x60
    /* DA7C 0010D9FC 00000000 */  nop
.size func_0010D980, . - func_0010D980

glabel func_0010DA00
    /* DA80 0010DA00 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* DA84 0010DA04 1000B1FF */  sd         $s1, 0x10($sp)
    /* DA88 0010DA08 0000B0FF */  sd         $s0, 0x0($sp)
    /* DA8C 0010DA0C 2D888000 */  daddu      $s1, $a0, $zero
    /* DA90 0010DA10 2000B2FF */  sd         $s2, 0x20($sp)
    /* DA94 0010DA14 2D80A000 */  daddu      $s0, $a1, $zero
    /* DA98 0010DA18 3000BFFF */  sd         $ra, 0x30($sp)
    /* DA9C 0010DA1C 2D90C000 */  daddu      $s2, $a2, $zero
    /* DAA0 0010DA20 EE50040C */  jal        func_001143B8
    /* DAA4 0010DA24 CA08053C */   lui       $a1, (0x8CA0000 >> 16)
    /* DAA8 0010DA28 3C100200 */  dsll32     $v0, $v0, 0
    /* DAAC 0010DA2C 3F100200 */  dsra32     $v0, $v0, 0
    /* DAB0 0010DA30 01000056 */  bnel       $s0, $zero, .L0010DA38
    /* DAB4 0010DA34 000002AE */   sw        $v0, 0x0($s0)
  .L0010DA38:
    /* DAB8 0010DA38 15004012 */  beqz       $s2, .L0010DA90
    /* DABC 0010DA3C CA08033C */   lui       $v1, (0x8CA0000 >> 16)
    /* DAC0 0010DA40 CA08053C */  lui        $a1, (0x8CA0000 >> 16)
    /* DAC4 0010DA44 19004300 */  multu      $v0, $v1
    /* DAC8 0010DA48 12300000 */  mflo       $a2
    /* DACC 0010DA4C 10180000 */  mfhi       $v1
    /* DAD0 0010DA50 3C300600 */  dsll32     $a2, $a2, 0
    /* DAD4 0010DA54 3C180300 */  dsll32     $v1, $v1, 0
    /* DAD8 0010DA58 3E300600 */  dsrl32     $a2, $a2, 0
    /* DADC 0010DA5C 25186600 */  or         $v1, $v1, $a2
    /* DAE0 0010DA60 2F182302 */  dsubu      $v1, $s1, $v1
    /* DAE4 0010DA64 78110300 */  dsll       $v0, $v1, 5
    /* DAE8 0010DA68 2F104300 */  dsubu      $v0, $v0, $v1
    /* DAEC 0010DA6C B8210200 */  dsll       $a0, $v0, 6
    /* DAF0 0010DA70 2F208200 */  dsubu      $a0, $a0, $v0
    /* DAF4 0010DA74 F8200400 */  dsll       $a0, $a0, 3
    /* DAF8 0010DA78 2D208300 */  daddu      $a0, $a0, $v1
    /* DAFC 0010DA7C EE50040C */  jal        func_001143B8
    /* DB00 0010DA80 B8210400 */   dsll      $a0, $a0, 6
    /* DB04 0010DA84 3C100200 */  dsll32     $v0, $v0, 0
    /* DB08 0010DA88 3F100200 */  dsra32     $v0, $v0, 0
    /* DB0C 0010DA8C 000042AE */  sw         $v0, 0x0($s2)
  .L0010DA90:
    /* DB10 0010DA90 3000BFDF */  ld         $ra, 0x30($sp)
    /* DB14 0010DA94 2000B2DF */  ld         $s2, 0x20($sp)
    /* DB18 0010DA98 1000B1DF */  ld         $s1, 0x10($sp)
    /* DB1C 0010DA9C 0000B0DF */  ld         $s0, 0x0($sp)
    /* DB20 0010DAA0 0800E003 */  jr         $ra
    /* DB24 0010DAA4 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_0010DA00, . - func_0010DA00

glabel func_0010DAA8
    /* DB28 0010DAA8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* DB2C 0010DAAC CA08023C */  lui        $v0, (0x8CA0000 >> 16)
    /* DB30 0010DAB0 0000B0FF */  sd         $s0, 0x0($sp)
    /* DB34 0010DAB4 2D808000 */  daddu      $s0, $a0, $zero
    /* DB38 0010DAB8 1000BFFF */  sd         $ra, 0x10($sp)
    /* DB3C 0010DABC 2D20A000 */  daddu      $a0, $a1, $zero
    /* DB40 0010DAC0 19000272 */  multu1     $zero, $s0, $v0
    /* DB44 0010DAC4 19008200 */  multu      $a0, $v0
    /* DB48 0010DAC8 0F00053C */  lui        $a1, (0xF4240 >> 16)
    /* DB4C 0010DACC 4042A534 */  ori        $a1, $a1, (0xF4240 & 0xFFFF)
    /* DB50 0010DAD0 10800070 */  mfhi1      $s0
    /* DB54 0010DAD4 12300000 */  mflo       $a2
    /* DB58 0010DAD8 3C801000 */  dsll32     $s0, $s0, 0
    /* DB5C 0010DADC 3C300600 */  dsll32     $a2, $a2, 0
    /* DB60 0010DAE0 10200000 */  mfhi       $a0
    /* DB64 0010DAE4 3E300600 */  dsrl32     $a2, $a2, 0
    /* DB68 0010DAE8 3C200400 */  dsll32     $a0, $a0, 0
    /* DB6C 0010DAEC 25208600 */  or         $a0, $a0, $a2
    /* DB70 0010DAF0 12300070 */  mflo1      $a2
    /* DB74 0010DAF4 3C300600 */  dsll32     $a2, $a2, 0
    /* DB78 0010DAF8 3E300600 */  dsrl32     $a2, $a2, 0
    /* DB7C 0010DAFC EE50040C */  jal        func_001143B8
    /* DB80 0010DB00 25800602 */   or        $s0, $s0, $a2
    /* DB84 0010DB04 2D100202 */  daddu      $v0, $s0, $v0
    /* DB88 0010DB08 1000BFDF */  ld         $ra, 0x10($sp)
    /* DB8C 0010DB0C 0000B0DF */  ld         $s0, 0x0($sp)
    /* DB90 0010DB10 0800E003 */  jr         $ra
    /* DB94 0010DB14 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_0010DAA8, . - func_0010DAA8

glabel func_0010DB18
    /* DB98 0010DB18 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* DB9C 0010DB1C 05008004 */  bltz       $a0, .L0010DB34
    /* DBA0 0010DB20 0000BFFF */   sd        $ra, 0x0($sp)
    /* DBA4 0010DB24 4E4C040C */  jal        func_00113138
    /* DBA8 0010DB28 00000000 */   nop
    /* DBAC 0010DB2C 06000010 */  b          .L0010DB48
    /* DBB0 0010DB30 46000046 */   mov.s     $f1, $f0
  .L0010DB34:
    /* DBB4 0010DB34 7A100400 */  dsrl       $v0, $a0, 1
    /* DBB8 0010DB38 01008430 */  andi       $a0, $a0, 0x1
    /* DBBC 0010DB3C 4E4C040C */  jal        func_00113138
    /* DBC0 0010DB40 25208200 */   or        $a0, $a0, $v0
    /* DBC4 0010DB44 40000046 */  add.s      $f1, $f0, $f0
  .L0010DB48:
    /* DBC8 0010DB48 0C4D013C */  lui        $at, (0x4D0CA000 >> 16)
    /* DBCC 0010DB4C 00A02134 */  ori        $at, $at, (0x4D0CA000 & 0xFFFF)
    /* DBD0 0010DB50 00008144 */  mtc1       $at, $f0
    /* DBD4 0010DB54 0000BFDF */  ld         $ra, 0x0($sp)
    /* DBD8 0010DB58 00000000 */  nop
    /* DBDC 0010DB5C 00000000 */  nop
    /* DBE0 0010DB60 03000146 */  div.s      $f0, $f0, $f1
    /* DBE4 0010DB64 0800E003 */  jr         $ra
    /* DBE8 0010DB68 1000BD27 */   addiu     $sp, $sp, 0x10
    /* DBEC 0010DB6C 00000000 */  nop
.size func_0010DB18, . - func_0010DB18

glabel func_0010DB70
    /* DBF0 0010DB70 0C4D013C */  lui        $at, (0x4D0CA000 >> 16)
    /* DBF4 0010DB74 00A02134 */  ori        $at, $at, (0x4D0CA000 & 0xFFFF)
    /* DBF8 0010DB78 00008144 */  mtc1       $at, $f0
    /* DBFC 0010DB7C F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* DC00 0010DB80 0000BFFF */  sd         $ra, 0x0($sp)
    /* DC04 0010DB84 00000000 */  nop
    /* DC08 0010DB88 00000000 */  nop
    /* DC0C 0010DB8C 03030C46 */  div.s      $f12, $f0, $f12
    /* DC10 0010DB90 C04C040C */  jal        func_00113300
    /* DC14 0010DB94 00000000 */   nop
    /* DC18 0010DB98 0000BFDF */  ld         $ra, 0x0($sp)
    /* DC1C 0010DB9C 0800E003 */  jr         $ra
    /* DC20 0010DBA0 1000BD27 */   addiu     $sp, $sp, 0x10
    /* DC24 0010DBA4 00000000 */  nop
.size func_0010DB70, . - func_0010DB70
