.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0010DC58
    /* DCD8 0010DC58 80FFBD27 */  addiu      $sp, $sp, -0x80
    /* DCDC 0010DC5C 6000B6FF */  sd         $s6, 0x60($sp)
    /* DCE0 0010DC60 5000B5FF */  sd         $s5, 0x50($sp)
    /* DCE4 0010DC64 2DB08000 */  daddu      $s6, $a0, $zero
    /* DCE8 0010DC68 4000B4FF */  sd         $s4, 0x40($sp)
    /* DCEC 0010DC6C 2DA8C000 */  daddu      $s5, $a2, $zero
    /* DCF0 0010DC70 7000BFFF */  sd         $ra, 0x70($sp)
    /* DCF4 0010DC74 2DA0A000 */  daddu      $s4, $a1, $zero
    /* DCF8 0010DC78 3000B3FF */  sd         $s3, 0x30($sp)
    /* DCFC 0010DC7C 2000B2FF */  sd         $s2, 0x20($sp)
    /* DD00 0010DC80 1000B1FF */  sd         $s1, 0x10($sp)
    /* DD04 0010DC84 04008016 */  bnez       $s4, .L0010DC98
    /* DD08 0010DC88 0000B0FF */   sd        $s0, 0x0($sp)
    /* DD0C 0010DC8C 0080023C */  lui        $v0, (0x80000016 >> 16)
    /* DD10 0010DC90 32000010 */  b          .L0010DD5C
    /* DD14 0010DC94 16004234 */   ori       $v0, $v0, (0x80000016 & 0xFFFF)
  .L0010DC98:
    /* DD18 0010DC98 F82F040C */  jal        func_0010BFE0
    /* DD1C 0010DC9C 5000123C */   lui       $s2, (0x502A00 >> 16)
    /* DD20 0010DCA0 002A508E */  lw         $s0, (0x502A00 & 0xFFFF)($s2)
    /* DD24 0010DCA4 03000012 */  beqz       $s0, .L0010DCB4
    /* DD28 0010DCA8 2D984000 */   daddu     $s3, $v0, $zero
    /* DD2C 0010DCAC 0000028E */  lw         $v0, 0x0($s0)
    /* DD30 0010DCB0 002A42AE */  sw         $v0, (0x502A00 & 0xFFFF)($s2)
  .L0010DCB4:
    /* DD34 0010DCB4 08000016 */  bnez       $s0, .L0010DCD8
    /* DD38 0010DCB8 00000000 */   nop
    /* DD3C 0010DCBC 03006012 */  beqz       $s3, .L0010DCCC
    /* DD40 0010DCC0 00000000 */   nop
    /* DD44 0010DCC4 0E30040C */  jal        func_0010C038
    /* DD48 0010DCC8 00000000 */   nop
  .L0010DCCC:
    /* DD4C 0010DCCC 0080023C */  lui        $v0, (0x80008005 >> 16)
    /* DD50 0010DCD0 22000010 */  b          .L0010DD5C
    /* DD54 0010DCD4 05804234 */   ori       $v0, $v0, (0x80008005 & 0xFFFF)
  .L0010DCD8:
    /* DD58 0010DCD8 9834040C */  jal        func_0010D260
    /* DD5C 0010DCDC 00000000 */   nop
    /* DD60 0010DCE0 2D884000 */  daddu      $s1, $v0, $zero
    /* DD64 0010DCE4 0B002306 */  bgezl      $s1, .L0010DD14
    /* DD68 0010DCE8 080014AE */   sw        $s4, 0x8($s0)
    /* DD6C 0010DCEC 002A428E */  lw         $v0, (0x502A00 & 0xFFFF)($s2)
    /* DD70 0010DCF0 002A50AE */  sw         $s0, (0x502A00 & 0xFFFF)($s2)
    /* DD74 0010DCF4 000002AE */  sw         $v0, 0x0($s0)
    /* DD78 0010DCF8 040000AE */  sw         $zero, 0x4($s0)
    /* DD7C 0010DCFC 17006012 */  beqz       $s3, .L0010DD5C
    /* DD80 0010DD00 2D102002 */   daddu     $v0, $s1, $zero
    /* DD84 0010DD04 0E30040C */  jal        func_0010C038
    /* DD88 0010DD08 00000000 */   nop
    /* DD8C 0010DD0C 13000010 */  b          .L0010DD5C
    /* DD90 0010DD10 2D102002 */   daddu     $v0, $s1, $zero
  .L0010DD14:
    /* DD94 0010DD14 1100063C */  lui        $a2, %hi(func_0010DBF8)
    /* DD98 0010DD18 0C0015AE */  sw         $s5, 0xC($s0)
    /* DD9C 0010DD1C F8DBC624 */  addiu      $a2, $a2, %lo(func_0010DBF8)
    /* DDA0 0010DD20 040011AE */  sw         $s1, 0x4($s0)
    /* DDA4 0010DD24 2D28C002 */  daddu      $a1, $s6, $zero
    /* DDA8 0010DD28 2D202002 */  daddu      $a0, $s1, $zero
    /* DDAC 0010DD2C 6036040C */  jal        func_0010D980
    /* DDB0 0010DD30 2D380002 */   daddu     $a3, $s0, $zero
    /* DDB4 0010DD34 3E35040C */  jal        func_0010D4F8
    /* DDB8 0010DD38 2D202002 */   daddu     $a0, $s1, $zero
    /* DDBC 0010DD3C 04006012 */  beqz       $s3, .L0010DD50
    /* DDC0 0010DD40 00111000 */   sll       $v0, $s0, 4
    /* DDC4 0010DD44 0E30040C */  jal        func_0010C038
    /* DDC8 0010DD48 00000000 */   nop
    /* DDCC 0010DD4C 00111000 */  sll        $v0, $s0, 4
  .L0010DD50:
    /* DDD0 0010DD50 FE002332 */  andi       $v1, $s1, 0xFE
    /* DDD4 0010DD54 25104300 */  or         $v0, $v0, $v1
    /* DDD8 0010DD58 01004234 */  ori        $v0, $v0, 0x1
  .L0010DD5C:
    /* DDDC 0010DD5C 7000BFDF */  ld         $ra, 0x70($sp)
    /* DDE0 0010DD60 6000B6DF */  ld         $s6, 0x60($sp)
    /* DDE4 0010DD64 5000B5DF */  ld         $s5, 0x50($sp)
    /* DDE8 0010DD68 4000B4DF */  ld         $s4, 0x40($sp)
    /* DDEC 0010DD6C 3000B3DF */  ld         $s3, 0x30($sp)
    /* DDF0 0010DD70 2000B2DF */  ld         $s2, 0x20($sp)
    /* DDF4 0010DD74 1000B1DF */  ld         $s1, 0x10($sp)
    /* DDF8 0010DD78 0000B0DF */  ld         $s0, 0x0($sp)
    /* DDFC 0010DD7C 0800E003 */  jr         $ra
    /* DE00 0010DD80 8000BD27 */   addiu     $sp, $sp, 0x80
    /* DE04 0010DD84 00000000 */  nop
.size func_0010DC58, . - func_0010DC58
