.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00110968
    /* 109E8 00110968 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 109EC 0011096C 5000043C */  lui        $a0, %hi(D_502F00)
    /* 109F0 00110970 1000B0FF */  sd         $s0, 0x10($sp)
    /* 109F4 00110974 5000073C */  lui        $a3, %hi(D_502F80)
    /* 109F8 00110978 5000103C */  lui        $s0, (0x5044C0 >> 16)
    /* 109FC 0011097C 11000B3C */  lui        $t3, %hi(func_0010FF08)
    /* 10A00 00110980 2000BFFF */  sd         $ra, 0x20($sp)
    /* 10A04 00110984 002F8424 */  addiu      $a0, $a0, %lo(D_502F00)
    /* 10A08 00110988 802FE724 */  addiu      $a3, $a3, %lo(D_502F80)
    /* 10A0C 0011098C 08FF6B25 */  addiu      $t3, $t3, %lo(func_0010FF08)
    /* 10A10 00110990 0000A0AF */  sw         $zero, 0x0($sp)
    /* 10A14 00110994 35000524 */  addiu      $a1, $zero, 0x35
    /* 10A18 00110998 2D300000 */  daddu      $a2, $zero, $zero
    /* 10A1C 0011099C 30000824 */  addiu      $t0, $zero, 0x30
    /* 10A20 001109A0 C0440926 */  addiu      $t1, $s0, %lo(D_5044C0)
    /* 10A24 001109A4 DA18040C */  jal        func_00106368
    /* 10A28 001109A8 04000A24 */   addiu     $t2, $zero, 0x4
    /* 10A2C 001109AC 05004010 */  beqz       $v0, .L001109C4
    /* 10A30 001109B0 4600043C */   lui       $a0, %hi(D_00459EF8)
    /* 10A34 001109B4 7214040C */  jal        func_001051C8
    /* 10A38 001109B8 F89E8424 */   addiu     $a0, $a0, %lo(D_00459EF8)
    /* 10A3C 001109BC 02000010 */  b          .L001109C8
    /* 10A40 001109C0 FFFF0224 */   addiu     $v0, $zero, -0x1
  .L001109C4:
    /* 10A44 001109C4 C044028E */  lw         $v0, (0x5044C0 & 0xFFFF)($s0)
  .L001109C8:
    /* 10A48 001109C8 2000BFDF */  ld         $ra, 0x20($sp)
    /* 10A4C 001109CC 1000B0DF */  ld         $s0, 0x10($sp)
    /* 10A50 001109D0 0800E003 */  jr         $ra
    /* 10A54 001109D4 3000BD27 */   addiu     $sp, $sp, 0x30
.size func_00110968, . - func_00110968

glabel func_001109D8
    /* 10A58 001109D8 60FFBD27 */  addiu      $sp, $sp, -0xA0
    /* 10A5C 001109DC 5000023C */  lui        $v0, %hi(D_502F00)
    /* 10A60 001109E0 8000B7FF */  sd         $s7, 0x80($sp)
    /* 10A64 001109E4 6000B5FF */  sd         $s5, 0x60($sp)
    /* 10A68 001109E8 002F5724 */  addiu      $s7, $v0, %lo(D_502F00)
    /* 10A6C 001109EC 5000B4FF */  sd         $s4, 0x50($sp)
    /* 10A70 001109F0 2DA88000 */  daddu      $s5, $a0, $zero
    /* 10A74 001109F4 4000B3FF */  sd         $s3, 0x40($sp)
    /* 10A78 001109F8 2DA0A000 */  daddu      $s4, $a1, $zero
    /* 10A7C 001109FC 3000B2FF */  sd         $s2, 0x30($sp)
    /* 10A80 00110A00 2D98E000 */  daddu      $s3, $a3, $zero
    /* 10A84 00110A04 2000B1FF */  sd         $s1, 0x20($sp)
    /* 10A88 00110A08 2D902001 */  daddu      $s2, $t1, $zero
    /* 10A8C 00110A0C 1000B0FF */  sd         $s0, 0x10($sp)
    /* 10A90 00110A10 2D880001 */  daddu      $s1, $t0, $zero
    /* 10A94 00110A14 9000BFFF */  sd         $ra, 0x90($sp)
    /* 10A98 00110A18 7000B6FF */  sd         $s6, 0x70($sp)
    /* 10A9C 00110A1C 2400E28E */  lw         $v0, 0x24($s7)
    /* 10AA0 00110A20 03004014 */  bnez       $v0, .L00110A30
    /* 10AA4 00110A24 2D80C000 */   daddu     $s0, $a2, $zero
    /* 10AA8 00110A28 33000010 */  b          .L00110AF8
    /* 10AAC 00110A2C 9CFF0224 */   addiu     $v0, $zero, -0x64
  .L00110A30:
    /* 10AB0 00110A30 3F00163C */  lui        $s6, %hi(D_003EA88C)
    /* 10AB4 00110A34 FC0B040C */  jal        func_00102FF0
    /* 10AB8 00110A38 8CA8C48E */   lw        $a0, %lo(D_003EA88C)($s6)
    /* 10ABC 00110A3C 2E004004 */  bltz       $v0, .L00110AF8
    /* 10AC0 00110A40 38FF0224 */   addiu     $v0, $zero, -0xC8
    /* 10AC4 00110A44 04000012 */  beqz       $s0, .L00110A58
    /* 10AC8 00110A48 00000000 */   nop
    /* 10ACC 00110A4C 00000282 */  lb         $v0, 0x0($s0)
    /* 10AD0 00110A50 05004014 */  bnez       $v0, .L00110A68
    /* 10AD4 00110A54 5000023C */   lui       $v0, (0x502FB0 >> 16)
  .L00110A58:
    /* 10AD8 00110A58 F00B040C */  jal        func_00102FC0
    /* 10ADC 00110A5C 8CA8C48E */   lw        $a0, %lo(D_003EA88C)($s6)
    /* 10AE0 00110A60 25000010 */  b          .L00110AF8
    /* 10AE4 00110A64 2EFF0224 */   addiu     $v0, $zero, -0xD2
  .L00110A68:
    /* 10AE8 00110A68 2D280002 */  daddu      $a1, $s0, $zero
    /* 10AEC 00110A6C B02F5024 */  addiu      $s0, $v0, %lo(D_502FB0)
    /* 10AF0 00110A70 B02F55AC */  sw         $s5, (0x502FB0 & 0xFFFF)($v0)
    /* 10AF4 00110A74 040014AE */  sw         $s4, 0x4($s0)
    /* 10AF8 00110A78 14000426 */  addiu      $a0, $s0, 0x14
    /* 10AFC 00110A7C 080013AE */  sw         $s3, 0x8($s0)
    /* 10B00 00110A80 FF030624 */  addiu      $a2, $zero, 0x3FF
    /* 10B04 00110A84 0C0011AE */  sw         $s1, 0xC($s0)
    /* 10B08 00110A88 98DC0D0C */  jal        func_00377260
    /* 10B0C 00110A8C 100012AE */   sw        $s2, 0x10($s0)
    /* 10B10 00110A90 04002006 */  bltz       $s1, .L00110AA4
    /* 10B14 00110A94 130400A2 */   sb        $zero, 0x413($s0)
    /* 10B18 00110A98 2D204002 */  daddu      $a0, $s2, $zero
    /* 10B1C 00110A9C 5416040C */  jal        func_00105950
    /* 10B20 00110AA0 80291100 */   sll       $a1, $s1, 6
  .L00110AA4:
    /* 10B24 00110AA4 5000093C */  lui        $t1, %hi(D_5044C0)
    /* 10B28 00110AA8 11000B3C */  lui        $t3, %hi(func_0010FF08)
    /* 10B2C 00110AAC 2D380002 */  daddu      $a3, $s0, $zero
    /* 10B30 00110AB0 2D20E002 */  daddu      $a0, $s7, $zero
    /* 10B34 00110AB4 C0442925 */  addiu      $t1, $t1, %lo(D_5044C0)
    /* 10B38 00110AB8 08FF6B25 */  addiu      $t3, $t3, %lo(func_0010FF08)
    /* 10B3C 00110ABC 0000A0AF */  sw         $zero, 0x0($sp)
    /* 10B40 00110AC0 0D000524 */  addiu      $a1, $zero, 0xD
    /* 10B44 00110AC4 01000624 */  addiu      $a2, $zero, 0x1
    /* 10B48 00110AC8 14040824 */  addiu      $t0, $zero, 0x414
    /* 10B4C 00110ACC DA18040C */  jal        func_00106368
    /* 10B50 00110AD0 04000A24 */   addiu     $t2, $zero, 0x4
    /* 10B54 00110AD4 2D804000 */  daddu      $s0, $v0, $zero
    /* 10B58 00110AD8 04000016 */  bnez       $s0, .L00110AEC
    /* 10B5C 00110ADC 3F00033C */   lui       $v1, %hi(D_003EA888)
    /* 10B60 00110AE0 0D000224 */  addiu      $v0, $zero, 0xD
    /* 10B64 00110AE4 03000010 */  b          .L00110AF4
    /* 10B68 00110AE8 88A862AC */   sw        $v0, %lo(D_003EA888)($v1)
  .L00110AEC:
    /* 10B6C 00110AEC F00B040C */  jal        func_00102FC0
    /* 10B70 00110AF0 8CA8C48E */   lw        $a0, %lo(D_003EA88C)($s6)
  .L00110AF4:
    /* 10B74 00110AF4 2D100002 */  daddu      $v0, $s0, $zero
  .L00110AF8:
    /* 10B78 00110AF8 9000BFDF */  ld         $ra, 0x90($sp)
    /* 10B7C 00110AFC 8000B7DF */  ld         $s7, 0x80($sp)
    /* 10B80 00110B00 7000B6DF */  ld         $s6, 0x70($sp)
    /* 10B84 00110B04 6000B5DF */  ld         $s5, 0x60($sp)
    /* 10B88 00110B08 5000B4DF */  ld         $s4, 0x50($sp)
    /* 10B8C 00110B0C 4000B3DF */  ld         $s3, 0x40($sp)
    /* 10B90 00110B10 3000B2DF */  ld         $s2, 0x30($sp)
    /* 10B94 00110B14 2000B1DF */  ld         $s1, 0x20($sp)
    /* 10B98 00110B18 1000B0DF */  ld         $s0, 0x10($sp)
    /* 10B9C 00110B1C 0800E003 */  jr         $ra
    /* 10BA0 00110B20 A000BD27 */   addiu     $sp, $sp, 0xA0
    /* 10BA4 00110B24 00000000 */  nop
.size func_001109D8, . - func_001109D8
