.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00112FA8
    /* 13028 00112FA8 FF7F0F3C */  lui        $t7, (0x7FFFFFFF >> 16)
    /* 1302C 00112FAC 00600B44 */  mfc1       $t3, $f12
    /* 13030 00112FB0 FFFFEF35 */  ori        $t7, $t7, (0x7FFFFFFF & 0xFFFF)
    /* 13034 00112FB4 00600C44 */  mfc1       $t4, $f12
    /* 13038 00112FB8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 1303C 00112FBC 24786F01 */  and        $t7, $t3, $t7
    /* 13040 00112FC0 7F000E3C */  lui        $t6, (0x7FFFFF >> 16)
    /* 13044 00112FC4 0000BFFF */  sd         $ra, 0x0($sp)
    /* 13048 00112FC8 FFFFCE35 */  ori        $t6, $t6, (0x7FFFFF & 0xFFFF)
    /* 1304C 00112FCC 0800B4E7 */  swc1       $f20, 0x8($sp)
    /* 13050 00112FD0 C26D0F00 */  srl        $t5, $t7, 23
    /* 13054 00112FD4 2B70CF01 */  sltu       $t6, $t6, $t7
    /* 13058 00112FD8 0A00C011 */  beqz       $t6, .L00113004
    /* 1305C 00112FDC 2168A401 */   addu      $t5, $t5, $a0
    /* 13060 00112FE0 0001AF29 */  slti       $t7, $t5, 0x100
    /* 13064 00112FE4 1100E011 */  beqz       $t7, .L0011302C
    /* 13068 00112FE8 46000F3C */   lui       $t7, %hi(D_0045A598)
    /* 1306C 00112FEC 0A00A019 */  blez       $t5, .L00113018
    /* 13070 00112FF0 7F800F3C */   lui       $t7, (0x807FFFFF >> 16)
    /* 13074 00112FF4 C0750D00 */  sll        $t6, $t5, 23
    /* 13078 00112FF8 FFFFEF35 */  ori        $t7, $t7, (0x807FFFFF & 0xFFFF)
    /* 1307C 00112FFC 24786F01 */  and        $t7, $t3, $t7
    /* 13080 00113000 2560EE01 */  or         $t4, $t7, $t6
  .L00113004:
    /* 13084 00113004 00008C44 */  mtc1       $t4, $f0
    /* 13088 00113008 0000BFDF */  ld         $ra, 0x0($sp)
    /* 1308C 0011300C 0800B4C7 */  lwc1       $f20, 0x8($sp)
    /* 13090 00113010 0800E003 */  jr         $ra
    /* 13094 00113014 1000BD27 */   addiu     $sp, $sp, 0x10
  .L00113018:
    /* 13098 00113018 50C30F34 */  ori        $t7, $zero, 0xC350
    /* 1309C 0011301C 2A78E401 */  slt        $t7, $t7, $a0
    /* 130A0 00113020 0A00E011 */  beqz       $t7, .L0011304C
    /* 130A4 00113024 46000F3C */   lui       $t7, %hi(D_0045A59C)
    /* 130A8 00113028 46000F3C */  lui        $t7, %hi(D_0045A598)
  .L0011302C:
    /* 130AC 0011302C 98A5EF25 */  addiu      $t7, $t7, %lo(D_0045A598)
  .L00113030:
    /* 130B0 00113030 46630046 */  mov.s      $f13, $f12
    /* 130B4 00113034 0000F4C5 */  lwc1       $f20, 0x0($t7)
    /* 130B8 00113038 784B040C */  jal        func_00112DE0
    /* 130BC 0011303C 06A30046 */   mov.s     $f12, $f20
    /* 130C0 00113040 02001446 */  mul.s      $f0, $f0, $f20
    /* 130C4 00113044 EFFF0010 */  b          .L00113004
    /* 130C8 00113048 00000C44 */   mfc1      $t4, $f0
  .L0011304C:
    /* 130CC 0011304C F8FF0010 */  b          .L00113030
    /* 130D0 00113050 9CA5EF25 */   addiu     $t7, $t7, %lo(D_0045A59C)
    /* 130D4 00113054 00000000 */  nop
  glabel func_00113058
    /* 130D8 00113058 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 130DC 0011305C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 130E0 00113060 0000BFDF */  ld         $ra, 0x0($sp)
    /* 130E4 00113064 2E450408 */  j          func_001114B8
    /* 130E8 00113068 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 130EC 0011306C 00000000 */  nop
.size func_00112FA8, . - func_00112FA8

glabel func_00113070
    /* 130F0 00113070 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 130F4 00113074 0000BFFF */  sd         $ra, 0x0($sp)
    /* 130F8 00113078 0000BFDF */  ld         $ra, 0x0($sp)
    /* 130FC 0011307C DC450408 */  j          func_00111770
    /* 13100 00113080 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 13104 00113084 00000000 */  nop
.size func_00113070, . - func_00113070
