.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00355558
    /* 2555D8 00355558 840086AC */  sw         $a2, 0x84($a0)
    /* 2555DC 0035555C 0800E003 */  jr         $ra
    /* 2555E0 00355560 800085AC */   sw        $a1, 0x80($a0)
    /* 2555E4 00355564 00000000 */  nop
.size func_00355558, . - func_00355558
