.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00355A68
    /* 255AE8 00355A68 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 255AEC 00355A6C 48008324 */  addiu      $v1, $a0, 0x48
    /* 255AF0 00355A70 0800BFFF */  sd         $ra, 0x8($sp)
    /* 255AF4 00355A74 40280500 */  sll        $a1, $a1, 1
    /* 255AF8 00355A78 0000B0FF */  sd         $s0, 0x0($sp)
    /* 255AFC 00355A7C 2D30A000 */  daddu      $a2, $a1, $zero
    /* 255B00 00355A80 2000628C */  lw         $v0, 0x20($v1)
    /* 255B04 00355A84 1400678C */  lw         $a3, 0x14($v1)
    /* 255B08 00355A88 1C00688C */  lw         $t0, 0x1C($v1)
    /* 255B0C 00355A8C 40100200 */  sll        $v0, $v0, 1
    /* 255B10 00355A90 0800908C */  lw         $s0, 0x8($a0)
    /* 255B14 00355A94 2138E200 */  addu       $a3, $a3, $v0
    /* 255B18 00355A98 0000658C */  lw         $a1, 0x0($v1)
    /* 255B1C 00355A9C 40400800 */  sll        $t0, $t0, 1
    /* 255B20 00355AA0 2D200002 */  daddu      $a0, $s0, $zero
    /* 255B24 00355AA4 528C0D0C */  jal        func_00363148
    /* 255B28 00355AA8 2140E800 */   addu      $t0, $a3, $t0
    /* 255B2C 00355AAC 2D200002 */  daddu      $a0, $s0, $zero
    /* 255B30 00355AB0 0800BFDF */  ld         $ra, 0x8($sp)
    /* 255B34 00355AB4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 255B38 00355AB8 6A8C0D08 */  j          func_003631A8
    /* 255B3C 00355ABC 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00355A68, . - func_00355A68

glabel func_00355AC0
    /* 255B40 00355AC0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 255B44 00355AC4 48008324 */  addiu      $v1, $a0, 0x48
    /* 255B48 00355AC8 0800BFFF */  sd         $ra, 0x8($sp)
    /* 255B4C 00355ACC 2D30A000 */  daddu      $a2, $a1, $zero
    /* 255B50 00355AD0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 255B54 00355AD4 2000628C */  lw         $v0, 0x20($v1)
    /* 255B58 00355AD8 1400678C */  lw         $a3, 0x14($v1)
    /* 255B5C 00355ADC 1C00688C */  lw         $t0, 0x1C($v1)
    /* 255B60 00355AE0 40100200 */  sll        $v0, $v0, 1
    /* 255B64 00355AE4 0800908C */  lw         $s0, 0x8($a0)
    /* 255B68 00355AE8 2138E200 */  addu       $a3, $a3, $v0
    /* 255B6C 00355AEC 0000658C */  lw         $a1, 0x0($v1)
    /* 255B70 00355AF0 40400800 */  sll        $t0, $t0, 1
    /* 255B74 00355AF4 2D200002 */  daddu      $a0, $s0, $zero
    /* 255B78 00355AF8 5E8C0D0C */  jal        func_00363178
    /* 255B7C 00355AFC 2140E800 */   addu      $t0, $a3, $t0
    /* 255B80 00355B00 2D200002 */  daddu      $a0, $s0, $zero
    /* 255B84 00355B04 0800BFDF */  ld         $ra, 0x8($sp)
    /* 255B88 00355B08 0000B0DF */  ld         $s0, 0x0($sp)
    /* 255B8C 00355B0C 6A8C0D08 */  j          func_003631A8
    /* 255B90 00355B10 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 255B94 00355B14 00000000 */  nop
.size func_00355AC0, . - func_00355AC0
