.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00358E18
    /* 258E98 00358E18 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 258E9C 00358E1C 0001842C */  sltiu      $a0, $a0, 0x100
    /* 258EA0 00358E20 05008014 */  bnez       $a0, .L00358E38
    /* 258EA4 00358E24 0000BFFF */   sd        $ra, 0x0($sp)
    /* 258EA8 00358E28 4E00043C */  lui        $a0, %hi(D_4D9690)
    /* 258EAC 00358E2C 06000010 */  b          .L00358E48
    /* 258EB0 00358E30 90968424 */   addiu     $a0, $a0, %lo(D_4D9690)
    /* 258EB4 00358E34 00000000 */  nop
  .L00358E38:
    /* 258EB8 00358E38 0600A014 */  bnez       $a1, .L00358E54
    /* 258EBC 00358E3C 2D100000 */   daddu     $v0, $zero, $zero
    /* 258EC0 00358E40 4E00043C */  lui        $a0, %hi(D_4D96C8)
    /* 258EC4 00358E44 C8968424 */  addiu      $a0, $a0, %lo(D_4D96C8)
  .L00358E48:
    /* 258EC8 00358E48 44620D0C */  jal        func_00358910
    /* 258ECC 00358E4C 00000000 */   nop
    /* 258ED0 00358E50 FDFF0224 */  addiu      $v0, $zero, -0x3
  .L00358E54:
    /* 258ED4 00358E54 0000BFDF */  ld         $ra, 0x0($sp)
    /* 258ED8 00358E58 0800E003 */  jr         $ra
    /* 258EDC 00358E5C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00358E18, . - func_00358E18

glabel func_00358E60
    /* 258EE0 00358E60 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 258EE4 00358E64 2D38C000 */  daddu      $a3, $a2, $zero
    /* 258EE8 00358E68 0000BFFF */  sd         $ra, 0x0($sp)
    /* 258EEC 00358E6C 2D300000 */  daddu      $a2, $zero, $zero
    /* 258EF0 00358E70 0000BFDF */  ld         $ra, 0x0($sp)
    /* 258EF4 00358E74 A0630D08 */  j          func_00358E80
    /* 258EF8 00358E78 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 258EFC 00358E7C 00000000 */  nop
.size func_00358E60, . - func_00358E60

glabel func_00358E80
    /* 258F00 00358E80 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 258F04 00358E84 0000B0FF */  sd         $s0, 0x0($sp)
    /* 258F08 00358E88 2D808000 */  daddu      $s0, $a0, $zero
    /* 258F0C 00358E8C 0800B1FF */  sd         $s1, 0x8($sp)
    /* 258F10 00358E90 04001124 */  addiu      $s1, $zero, 0x4
    /* 258F14 00358E94 1000B2FF */  sd         $s2, 0x10($sp)
    /* 258F18 00358E98 1800BFFF */  sd         $ra, 0x18($sp)
    /* 258F1C 00358E9C C0630D0C */  jal        func_00358F00
    /* 258F20 00358EA0 03001224 */   addiu     $s2, $zero, 0x3
    /* 258F24 00358EA4 08004104 */  bgez       $v0, .L00358EC8
    /* 258F28 00358EA8 00000000 */   nop
    /* 258F2C 00358EAC 0E000010 */  b          .L00358EE8
    /* 258F30 00358EB0 0000B0DF */   ld        $s0, 0x0($sp)
    /* 258F34 00358EB4 00000000 */  nop
  .L00358EB8:
    /* 258F38 00358EB8 52710D0C */  jal        func_0035C548
    /* 258F3C 00358EBC 00000000 */   nop
    /* 258F40 00358EC0 7A630D0C */  jal        func_00358DE8
    /* 258F44 00358EC4 00000000 */   nop
  .L00358EC8:
    /* 258F48 00358EC8 D6640D0C */  jal        func_00359358
    /* 258F4C 00358ECC 2D200002 */   daddu     $a0, $s0, $zero
    /* 258F50 00358ED0 03005210 */  beq        $v0, $s2, .L00358EE0
    /* 258F54 00358ED4 2D180000 */   daddu     $v1, $zero, $zero
    /* 258F58 00358ED8 F7FF5114 */  bne        $v0, $s1, .L00358EB8
    /* 258F5C 00358EDC FFFF0324 */   addiu     $v1, $zero, -0x1
  .L00358EE0:
    /* 258F60 00358EE0 2D106000 */  daddu      $v0, $v1, $zero
    /* 258F64 00358EE4 0000B0DF */  ld         $s0, 0x0($sp)
  .L00358EE8:
    /* 258F68 00358EE8 0800B1DF */  ld         $s1, 0x8($sp)
    /* 258F6C 00358EEC 1000B2DF */  ld         $s2, 0x10($sp)
    /* 258F70 00358EF0 1800BFDF */  ld         $ra, 0x18($sp)
    /* 258F74 00358EF4 0800E003 */  jr         $ra
    /* 258F78 00358EF8 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 258F7C 00358EFC 00000000 */  nop
.size func_00358E80, . - func_00358E80

glabel func_00358F00
    /* 258F80 00358F00 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 258F84 00358F04 4300083C */  lui        $t0, %hi(D_4295E8)
    /* 258F88 00358F08 0000BFFF */  sd         $ra, 0x0($sp)
    /* 258F8C 00358F0C C0FF0224 */  addiu      $v0, $zero, -0x40
    /* 258F90 00358F10 E8950825 */  addiu      $t0, $t0, %lo(D_4295E8)
    /* 258F94 00358F14 00080924 */  addiu      $t1, $zero, 0x800
    /* 258F98 00358F18 0000BFDF */  ld         $ra, 0x0($sp)
    /* 258F9C 00358F1C 24400201 */  and        $t0, $t0, $v0
    /* 258FA0 00358F20 E8630D08 */  j          func_00358FA0
    /* 258FA4 00358F24 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00358F00, . - func_00358F00

glabel func_00358F28
    /* 258FA8 00358F28 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 258FAC 00358F2C 4300083C */  lui        $t0, %hi(D_4295E8)
    /* 258FB0 00358F30 0000BFFF */  sd         $ra, 0x0($sp)
    /* 258FB4 00358F34 C0FF0224 */  addiu      $v0, $zero, -0x40
    /* 258FB8 00358F38 E8950825 */  addiu      $t0, $t0, %lo(D_4295E8)
    /* 258FBC 00358F3C 00080924 */  addiu      $t1, $zero, 0x800
    /* 258FC0 00358F40 0000BFDF */  ld         $ra, 0x0($sp)
    /* 258FC4 00358F44 24400201 */  and        $t0, $t0, $v0
    /* 258FC8 00358F48 FA630D08 */  j          func_00358FE8
    /* 258FCC 00358F4C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00358F28, . - func_00358F28

glabel func_00358F50
    /* 258FD0 00358F50 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 258FD4 00358F54 4300083C */  lui        $t0, %hi(D_4295E8)
    /* 258FD8 00358F58 0000BFFF */  sd         $ra, 0x0($sp)
    /* 258FDC 00358F5C C0FF0224 */  addiu      $v0, $zero, -0x40
    /* 258FE0 00358F60 E8950825 */  addiu      $t0, $t0, %lo(D_4295E8)
    /* 258FE4 00358F64 00080924 */  addiu      $t1, $zero, 0x800
    /* 258FE8 00358F68 0000BFDF */  ld         $ra, 0x0($sp)
    /* 258FEC 00358F6C 24400201 */  and        $t0, $t0, $v0
    /* 258FF0 00358F70 08640D08 */  j          func_00359020
    /* 258FF4 00358F74 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00358F50, . - func_00358F50

glabel func_00358F78
    /* 258FF8 00358F78 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 258FFC 00358F7C 4300083C */  lui        $t0, %hi(D_4295E8)
    /* 259000 00358F80 0000BFFF */  sd         $ra, 0x0($sp)
    /* 259004 00358F84 C0FF0224 */  addiu      $v0, $zero, -0x40
    /* 259008 00358F88 E8950825 */  addiu      $t0, $t0, %lo(D_4295E8)
    /* 25900C 00358F8C 00080924 */  addiu      $t1, $zero, 0x800
    /* 259010 00358F90 0000BFDF */  ld         $ra, 0x0($sp)
    /* 259014 00358F94 24400201 */  and        $t0, $t0, $v0
    /* 259018 00358F98 1A640D08 */  j          func_00359068
    /* 25901C 00358F9C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00358F78, . - func_00358F78

glabel func_00358FA0
    /* 259020 00358FA0 2D18C000 */  daddu      $v1, $a2, $zero
    /* 259024 00358FA4 2D300000 */  daddu      $a2, $zero, $zero
    /* 259028 00358FA8 2D60E000 */  daddu      $t4, $a3, $zero
    /* 25902C 00358FAC 2D10A000 */  daddu      $v0, $a1, $zero
    /* 259030 00358FB0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 259034 00358FB4 2D500001 */  daddu      $t2, $t0, $zero
    /* 259038 00358FB8 2D582001 */  daddu      $t3, $t1, $zero
    /* 25903C 00358FBC 2D488001 */  daddu      $t1, $t4, $zero
    /* 259040 00358FC0 2D280000 */  daddu      $a1, $zero, $zero
    /* 259044 00358FC4 2D384000 */  daddu      $a3, $v0, $zero
    /* 259048 00358FC8 2D406000 */  daddu      $t0, $v1, $zero
    /* 25904C 00358FCC 1000BFFF */  sd         $ra, 0x10($sp)
    /* 259050 00358FD0 28640D0C */  jal        func_003590A0
    /* 259054 00358FD4 0000A0AF */   sw        $zero, 0x0($sp)
    /* 259058 00358FD8 1000BFDF */  ld         $ra, 0x10($sp)
    /* 25905C 00358FDC 0800E003 */  jr         $ra
    /* 259060 00358FE0 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 259064 00358FE4 00000000 */  nop
.size func_00358FA0, . - func_00358FA0
