.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035A018
    /* 25A098 0035A018 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 25A09C 0035A01C 2D280000 */  daddu      $a1, $zero, $zero
    /* 25A0A0 0035A020 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25A0A4 0035A024 2D808000 */  daddu      $s0, $a0, $zero
    /* 25A0A8 0035A028 2D300002 */  daddu      $a2, $s0, $zero
    /* 25A0AC 0035A02C FFFF0724 */  addiu      $a3, $zero, -0x1
    /* 25A0B0 0035A030 05000424 */  addiu      $a0, $zero, 0x5
    /* 25A0B4 0035A034 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25A0B8 0035A038 1000BFFF */  sd         $ra, 0x10($sp)
    /* 25A0BC 0035A03C 4E630D0C */  jal        func_00358D38
    /* 25A0C0 0035A040 FFFF0824 */   addiu     $t0, $zero, -0x1
    /* 25A0C4 0035A044 4E00043C */  lui        $a0, %hi(D_4D9A80)
    /* 25A0C8 0035A048 05000016 */  bnez       $s0, .L0035A060
    /* 25A0CC 0035A04C 809A8424 */   addiu     $a0, $a0, %lo(D_4D9A80)
    /* 25A0D0 0035A050 44620D0C */  jal        func_00358910
    /* 25A0D4 0035A054 00000000 */   nop
    /* 25A0D8 0035A058 25000010 */  b          .L0035A0F0
    /* 25A0DC 0035A05C FDFF0224 */   addiu     $v0, $zero, -0x3
  .L0035A060:
    /* 25A0E0 0035A060 01000382 */  lb         $v1, 0x1($s0)
    /* 25A0E4 0035A064 01001124 */  addiu      $s1, $zero, 0x1
    /* 25A0E8 0035A068 20007110 */  beq        $v1, $s1, .L0035A0EC
    /* 25A0EC 0035A06C 03000224 */   addiu     $v0, $zero, 0x3
    /* 25A0F0 0035A070 03006254 */  bnel       $v1, $v0, .L0035A080
    /* 25A0F4 0035A074 0400048E */   lw        $a0, 0x4($s0)
    /* 25A0F8 0035A078 1C000010 */  b          .L0035A0EC
    /* 25A0FC 0035A07C 010011A2 */   sb        $s1, 0x1($s0)
  .L0035A080:
    /* 25A100 0035A080 07008014 */  bnez       $a0, .L0035A0A0
    /* 25A104 0035A084 00000000 */   nop
    /* 25A108 0035A088 4E00043C */  lui        $a0, %hi(D_4D9AA8)
    /* 25A10C 0035A08C 44620D0C */  jal        func_00358910
    /* 25A110 0035A090 A89A8424 */   addiu     $a0, $a0, %lo(D_4D9AA8)
    /* 25A114 0035A094 16000010 */  b          .L0035A0F0
    /* 25A118 0035A098 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 25A11C 0035A09C 00000000 */  nop
  .L0035A0A0:
    /* 25A120 0035A0A0 FC790D0C */  jal        func_0035E7F0
    /* 25A124 0035A0A4 00000000 */   nop
    /* 25A128 0035A0A8 485B0D0C */  jal        func_00356D20
    /* 25A12C 0035A0AC 00000000 */   nop
    /* 25A130 0035A0B0 AC790D0C */  jal        func_0035E6B0
    /* 25A134 0035A0B4 0400048E */   lw        $a0, 0x4($s0)
    /* 25A138 0035A0B8 1400038E */  lw         $v1, 0x14($s0)
    /* 25A13C 0035A0BC 2D200002 */  daddu      $a0, $s0, $zero
    /* 25A140 0035A0C0 23104300 */  subu       $v0, $v0, $v1
    /* 25A144 0035A0C4 C6660D0C */  jal        func_00359B18
    /* 25A148 0035A0C8 200002AE */   sw        $v0, 0x20($s0)
    /* 25A14C 0035A0CC 4E5B0D0C */  jal        func_00356D38
    /* 25A150 0035A0D0 010011A2 */   sb        $s1, 0x1($s0)
    /* 25A154 0035A0D4 05000424 */  addiu      $a0, $zero, 0x5
    /* 25A158 0035A0D8 01000524 */  addiu      $a1, $zero, 0x1
    /* 25A15C 0035A0DC 2D300002 */  daddu      $a2, $s0, $zero
    /* 25A160 0035A0E0 FFFF0724 */  addiu      $a3, $zero, -0x1
    /* 25A164 0035A0E4 4E630D0C */  jal        func_00358D38
    /* 25A168 0035A0E8 FFFF0824 */   addiu     $t0, $zero, -0x1
  .L0035A0EC:
    /* 25A16C 0035A0EC 1400028E */  lw         $v0, 0x14($s0)
  .L0035A0F0:
    /* 25A170 0035A0F0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25A174 0035A0F4 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25A178 0035A0F8 1000BFDF */  ld         $ra, 0x10($sp)
    /* 25A17C 0035A0FC 0800E003 */  jr         $ra
    /* 25A180 0035A100 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 25A184 0035A104 00000000 */  nop
.size func_0035A018, . - func_0035A018
