.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035A818
    /* 25A898 0035A818 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25A89C 0035A81C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25A8A0 0035A820 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25A8A4 0035A824 58900D08 */  j          func_00364160
    /* 25A8A8 0035A828 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25A8AC 0035A82C 00000000 */  nop
.size func_0035A818, . - func_0035A818

glabel func_0035A830
    /* 25A8B0 0035A830 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25A8B4 0035A834 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25A8B8 0035A838 0800BFFF */  sd         $ra, 0x8($sp)
    /* 25A8BC 0035A83C 485B0D0C */  jal        func_00356D20
    /* 25A8C0 0035A840 00000000 */   nop
    /* 25A8C4 0035A844 4300023C */  lui        $v0, %hi(D_42B6A8)
    /* 25A8C8 0035A848 A8B65024 */  addiu      $s0, $v0, %lo(D_42B6A8)
    /* 25A8CC 0035A84C 0000038E */  lw         $v1, 0x0($s0)
    /* 25A8D0 0035A850 05006010 */  beqz       $v1, .L0035A868
    /* 25A8D4 0035A854 0800BFDF */   ld        $ra, 0x8($sp)
    /* 25A8D8 0035A858 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25A8DC 0035A85C 4E5B0D08 */  j          func_00356D38
    /* 25A8E0 0035A860 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25A8E4 0035A864 00000000 */  nop
  .L0035A868:
    /* 25A8E8 0035A868 01000224 */  addiu      $v0, $zero, 0x1
    /* 25A8EC 0035A86C 4E5B0D0C */  jal        func_00356D38
    /* 25A8F0 0035A870 000002AE */   sw        $v0, 0x0($s0)
    /* 25A8F4 0035A874 647B0D0C */  jal        func_0035ED90
    /* 25A8F8 0035A878 00000000 */   nop
    /* 25A8FC 0035A87C 02000224 */  addiu      $v0, $zero, 0x2
    /* 25A900 0035A880 26900D0C */  jal        func_00364098
    /* 25A904 0035A884 000002AE */   sw        $v0, 0x0($s0)
    /* 25A908 0035A888 03000224 */  addiu      $v0, $zero, 0x3
    /* 25A90C 0035A88C CA970D0C */  jal        func_00365F28
    /* 25A910 0035A890 000002AE */   sw        $v0, 0x0($s0)
    /* 25A914 0035A894 04000224 */  addiu      $v0, $zero, 0x4
    /* 25A918 0035A898 26900D0C */  jal        func_00364098
    /* 25A91C 0035A89C 000002AE */   sw        $v0, 0x0($s0)
    /* 25A920 0035A8A0 05000224 */  addiu      $v0, $zero, 0x5
    /* 25A924 0035A8A4 647B0D0C */  jal        func_0035ED90
    /* 25A928 0035A8A8 000002AE */   sw        $v0, 0x0($s0)
    /* 25A92C 0035A8AC 06000224 */  addiu      $v0, $zero, 0x6
    /* 25A930 0035A8B0 A6680D0C */  jal        func_0035A298
    /* 25A934 0035A8B4 000002AE */   sw        $v0, 0x0($s0)
    /* 25A938 0035A8B8 000000AE */  sw         $zero, 0x0($s0)
    /* 25A93C 0035A8BC 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25A940 0035A8C0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25A944 0035A8C4 0800E003 */  jr         $ra
    /* 25A948 0035A8C8 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25A94C 0035A8CC 00000000 */  nop
.size func_0035A830, . - func_0035A830

glabel func_0035A8D0
    /* 25A950 0035A8D0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25A954 0035A8D4 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25A958 0035A8D8 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25A95C 0035A8DC 0C6A0D08 */  j          func_0035A830
    /* 25A960 0035A8E0 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25A964 0035A8E4 00000000 */  nop
.size func_0035A8D0, . - func_0035A8D0
