.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035C408
    /* 25C488 0035C408 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 25C48C 0035C40C 4300023C */  lui        $v0, %hi(D_0042B6DC)
    /* 25C490 0035C410 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25C494 0035C414 2D888000 */  daddu      $s1, $a0, $zero
    /* 25C498 0035C418 1000B2FF */  sd         $s2, 0x10($sp)
    /* 25C49C 0035C41C 4300123C */  lui        $s2, %hi(D_0042C43C)
    /* 25C4A0 0035C420 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25C4A4 0035C424 DCB64224 */  addiu      $v0, $v0, %lo(D_0042B6DC)
    /* 25C4A8 0035C428 1800BFFF */  sd         $ra, 0x18($sp)
    /* 25C4AC 0035C42C 3CC44526 */  addiu      $a1, $s2, %lo(D_0042C43C)
    /* 25C4B0 0035C430 0000438C */  lw         $v1, 0x0($v0)
    /* 25C4B4 0035C434 01006324 */  addiu      $v1, $v1, 0x1
    /* 25C4B8 0035C438 000043AC */  sw         $v1, 0x0($v0)
    /* 25C4BC 0035C43C 0000A48C */  lw         $a0, 0x0($a1)
    /* 25C4C0 0035C440 2D008014 */  bnez       $a0, .L0035C4F8
    /* 25C4C4 0035C444 4300023C */   lui       $v0, %hi(D_0042C440)
    /* 25C4C8 0035C448 4300023C */  lui        $v0, %hi(D_0042C324)
    /* 25C4CC 0035C44C 01001024 */  addiu      $s0, $zero, 0x1
    /* 25C4D0 0035C450 24C3438C */  lw         $v1, %lo(D_0042C324)($v0)
    /* 25C4D4 0035C454 0000B0AC */  sw         $s0, 0x0($a1)
    /* 25C4D8 0035C458 22006018 */  blez       $v1, .L0035C4E4
    /* 25C4DC 0035C45C 4300023C */   lui       $v0, %hi(D_0042C368)
    /* 25C4E0 0035C460 68C34224 */  addiu      $v0, $v0, %lo(D_0042C368)
    /* 25C4E4 0035C464 0000438C */  lw         $v1, 0x0($v0)
    /* 25C4E8 0035C468 04007010 */  beq        $v1, $s0, .L0035C47C
    /* 25C4EC 0035C46C 4300023C */   lui       $v0, %hi(D_0042C3C0)
    /* 25C4F0 0035C470 C0C34224 */  addiu      $v0, $v0, %lo(D_0042C3C0)
    /* 25C4F4 0035C474 926D0D0C */  jal        func_0035B648
    /* 25C4F8 0035C478 0000448C */   lw        $a0, 0x0($v0)
  .L0035C47C:
    /* 25C4FC 0035C47C 4300023C */  lui        $v0, %hi(D_0042C370)
    /* 25C500 0035C480 70C34224 */  addiu      $v0, $v0, %lo(D_0042C370)
    /* 25C504 0035C484 0000438C */  lw         $v1, 0x0($v0)
    /* 25C508 0035C488 04007010 */  beq        $v1, $s0, .L0035C49C
    /* 25C50C 0035C48C 4300023C */   lui       $v0, %hi(D_0042C3C4)
    /* 25C510 0035C490 C4C34224 */  addiu      $v0, $v0, %lo(D_0042C3C4)
    /* 25C514 0035C494 926D0D0C */  jal        func_0035B648
    /* 25C518 0035C498 0000448C */   lw        $a0, 0x0($v0)
  .L0035C49C:
    /* 25C51C 0035C49C E06E0D0C */  jal        func_0035BB80
    /* 25C520 0035C4A0 00000000 */   nop
    /* 25C524 0035C4A4 2D204000 */  daddu      $a0, $v0, $zero
    /* 25C528 0035C4A8 0A009014 */  bne        $a0, $s0, .L0035C4D4
    /* 25C52C 0035C4AC 4300033C */   lui       $v1, %hi(D_0042C3B0)
    /* 25C530 0035C4B0 4300023C */  lui        $v0, %hi(D_0042C36C)
    /* 25C534 0035C4B4 6CC34224 */  addiu      $v0, $v0, %lo(D_0042C36C)
    /* 25C538 0035C4B8 0000438C */  lw         $v1, 0x0($v0)
    /* 25C53C 0035C4BC 04006410 */  beq        $v1, $a0, .L0035C4D0
    /* 25C540 0035C4C0 4300023C */   lui       $v0, %hi(D_0042C3BC)
    /* 25C544 0035C4C4 BCC34224 */  addiu      $v0, $v0, %lo(D_0042C3BC)
    /* 25C548 0035C4C8 926D0D0C */  jal        func_0035B648
    /* 25C54C 0035C4CC 0000448C */   lw        $a0, 0x0($v0)
  .L0035C4D0:
    /* 25C550 0035C4D0 4300033C */  lui        $v1, %hi(D_0042C3B0)
  .L0035C4D4:
    /* 25C554 0035C4D4 B0C36324 */  addiu      $v1, $v1, %lo(D_0042C3B0)
    /* 25C558 0035C4D8 000062DC */  ld         $v0, 0x0($v1)
    /* 25C55C 0035C4DC 01004264 */  daddiu     $v0, $v0, 0x1
    /* 25C560 0035C4E0 000062FC */  sd         $v0, 0x0($v1)
  .L0035C4E4:
    /* 25C564 0035C4E4 90C30D0C */  jal        func_00370E40
    /* 25C568 0035C4E8 00000000 */   nop
    /* 25C56C 0035C4EC 3CC44326 */  addiu      $v1, $s2, %lo(D_0042C43C)
    /* 25C570 0035C4F0 000060AC */  sw         $zero, 0x0($v1)
    /* 25C574 0035C4F4 4300023C */  lui        $v0, %hi(D_0042C440)
  .L0035C4F8:
    /* 25C578 0035C4F8 40C4428C */  lw         $v0, %lo(D_0042C440)($v0)
    /* 25C57C 0035C4FC 06004050 */  beql       $v0, $zero, .L0035C518
    /* 25C580 0035C500 2D100000 */   daddu     $v0, $zero, $zero
    /* 25C584 0035C504 09F84000 */  jalr       $v0
    /* 25C588 0035C508 2D202002 */   daddu     $a0, $s1, $zero
    /* 25C58C 0035C50C 03000010 */  b          .L0035C51C
    /* 25C590 0035C510 0000B0DF */   ld        $s0, 0x0($sp)
    /* 25C594 0035C514 00000000 */  nop
  .L0035C518:
    /* 25C598 0035C518 0000B0DF */  ld         $s0, 0x0($sp)
  .L0035C51C:
    /* 25C59C 0035C51C 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25C5A0 0035C520 1000B2DF */  ld         $s2, 0x10($sp)
    /* 25C5A4 0035C524 1800BFDF */  ld         $ra, 0x18($sp)
    /* 25C5A8 0035C528 0800E003 */  jr         $ra
    /* 25C5AC 0035C52C 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_0035C408, . - func_0035C408

glabel func_0035C530
    /* 25C5B0 0035C530 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25C5B4 0035C534 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25C5B8 0035C538 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25C5BC 0035C53C 02710D08 */  j          func_0035C408
    /* 25C5C0 0035C540 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25C5C4 0035C544 00000000 */  nop
.size func_0035C530, . - func_0035C530
