.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035C3C8
    /* 25C448 0035C3C8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25C44C 0035C3CC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25C450 0035C3D0 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25C454 0035C3D4 60C10D08 */  j          func_00370580
    /* 25C458 0035C3D8 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25C45C 0035C3DC 00000000 */  nop
.size func_0035C3C8, . - func_0035C3C8

glabel func_0035C3E0
    /* 25C460 0035C3E0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25C464 0035C3E4 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25C468 0035C3E8 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25C46C 0035C3EC 66C10D08 */  j          func_00370598
    /* 25C470 0035C3F0 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25C474 0035C3F4 00000000 */  nop
.size func_0035C3E0, . - func_0035C3E0
