.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035CC48
    /* 25CCC8 0035CC48 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25CCCC 0035CC4C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25CCD0 0035CC50 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25CCD4 0035CC54 00B50D08 */  j          func_0036D400
    /* 25CCD8 0035CC58 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25CCDC 0035CC5C 00000000 */  nop
.size func_0035CC48, . - func_0035CC48

glabel func_0035CC60
    /* 25CCE0 0035CC60 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25CCE4 0035CC64 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25CCE8 0035CC68 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25CCEC 0035CC6C 16B50D08 */  j          func_0036D458
    /* 25CCF0 0035CC70 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25CCF4 0035CC74 00000000 */  nop
.size func_0035CC60, . - func_0035CC60
