.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035CD48
    /* 25CDC8 0035CD48 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25CDCC 0035CD4C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25CDD0 0035CD50 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25CDD4 0035CD54 7CB60D08 */  j          func_0036D9F0
    /* 25CDD8 0035CD58 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25CDDC 0035CD5C 00000000 */  nop
.size func_0035CD48, . - func_0035CD48

glabel func_0035CD60
    /* 25CDE0 0035CD60 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25CDE4 0035CD64 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25CDE8 0035CD68 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25CDEC 0035CD6C 9AB60D08 */  j          func_0036DA68
    /* 25CDF0 0035CD70 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25CDF4 0035CD74 00000000 */  nop
.size func_0035CD60, . - func_0035CD60
