.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035CF18
    /* 25CF98 0035CF18 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25CF9C 0035CF1C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25CFA0 0035CF20 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25CFA4 0035CF24 ECB70D08 */  j          func_0036DFB0
    /* 25CFA8 0035CF28 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25CFAC 0035CF2C 00000000 */  nop
.size func_0035CF18, . - func_0035CF18

glabel func_0035CF30
    /* 25CFB0 0035CF30 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25CFB4 0035CF34 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25CFB8 0035CF38 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25CFBC 0035CF3C 02B80D08 */  j          func_0036E008
    /* 25CFC0 0035CF40 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25CFC4 0035CF44 00000000 */  nop
.size func_0035CF30, . - func_0035CF30
