.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035CF48
    /* 25CFC8 0035CF48 0800E003 */  jr         $ra
    /* 25CFCC 0035CF4C 00000000 */   nop
    /* 25CFD0 0035CF50 0800E003 */  jr         $ra
    /* 25CFD4 0035CF54 00000000 */   nop
  glabel func_0035CF58
    /* 25CFD8 0035CF58 0800E003 */  jr         $ra
    /* 25CFDC 0035CF5C 00000000 */   nop
    /* 25CFE0 0035CF60 0800E003 */  jr         $ra
    /* 25CFE4 0035CF64 00000000 */   nop
.size func_0035CF48, . - func_0035CF48

glabel func_0035CF68
    /* 25CFE8 0035CF68 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25CFEC 0035CF6C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25CFF0 0035CF70 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25CFF4 0035CF74 9CB60D08 */  j          func_0036DA70
    /* 25CFF8 0035CF78 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25CFFC 0035CF7C 00000000 */  nop
.size func_0035CF68, . - func_0035CF68

glabel func_0035CF80
    /* 25D000 0035CF80 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25D004 0035CF84 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25D008 0035CF88 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25D00C 0035CF8C A0B60D08 */  j          func_0036DA80
    /* 25D010 0035CF90 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25D014 0035CF94 00000000 */  nop
.size func_0035CF80, . - func_0035CF80
