.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035CE88
    /* 25CF08 0035CE88 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25CF0C 0035CE8C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25CF10 0035CE90 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25CF14 0035CE94 AEB70D08 */  j          func_0036DEB8
    /* 25CF18 0035CE98 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25CF1C 0035CE9C 00000000 */  nop
.size func_0035CE88, . - func_0035CE88

glabel func_0035CEA0
    /* 25CF20 0035CEA0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25CF24 0035CEA4 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25CF28 0035CEA8 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25CF2C 0035CEAC CAB70D08 */  j          func_0036DF28
    /* 25CF30 0035CEB0 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25CF34 0035CEB4 00000000 */  nop
.size func_0035CEA0, . - func_0035CEA0
