.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035D2E8
    /* 25D368 0035D2E8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25D36C 0035D2EC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25D370 0035D2F0 0800BFFF */  sd         $ra, 0x8($sp)
    /* 25D374 0035D2F4 04740D0C */  jal        func_0035D010
    /* 25D378 0035D2F8 2D808000 */   daddu     $s0, $a0, $zero
    /* 25D37C 0035D2FC 01000224 */  addiu      $v0, $zero, 0x1
    /* 25D380 0035D300 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25D384 0035D304 010002A2 */  sb         $v0, 0x1($s0)
    /* 25D388 0035D308 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25D38C 0035D30C 0800E003 */  jr         $ra
    /* 25D390 0035D310 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25D394 0035D314 00000000 */  nop
.size func_0035D2E8, . - func_0035D2E8
