.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035DE68
    /* 25DEE8 0035DE68 0800E003 */  jr         $ra
    /* 25DEEC 0035DE6C 3C0085AC */   sw        $a1, 0x3C($a0)
.size func_0035DE68, . - func_0035DE68

glabel func_0035DE70
    /* 25DEF0 0035DE70 0800E003 */  jr         $ra
    /* 25DEF4 0035DE74 3C00828C */   lw        $v0, 0x3C($a0)
.size func_0035DE70, . - func_0035DE70

glabel func_0035DE78
    /* 25DEF8 0035DE78 0800E003 */  jr         $ra
    /* 25DEFC 0035DE7C 400085AC */   sw        $a1, 0x40($a0)
.size func_0035DE78, . - func_0035DE78

glabel func_0035DE80
    /* 25DF00 0035DE80 0800E003 */  jr         $ra
    /* 25DF04 0035DE84 4000828C */   lw        $v0, 0x40($a0)
.size func_0035DE80, . - func_0035DE80

glabel func_0035DE88
    /* 25DF08 0035DE88 0800E003 */  jr         $ra
    /* 25DF0C 0035DE8C 440085AC */   sw        $a1, 0x44($a0)
.size func_0035DE88, . - func_0035DE88

glabel func_0035DE90
    /* 25DF10 0035DE90 0800E003 */  jr         $ra
    /* 25DF14 0035DE94 4400828C */   lw        $v0, 0x44($a0)
.size func_0035DE90, . - func_0035DE90

glabel func_0035DE98
    /* 25DF18 0035DE98 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25DF1C 0035DE9C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25DF20 0035DEA0 0400848C */  lw         $a0, 0x4($a0)
    /* 25DF24 0035DEA4 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25DF28 0035DEA8 5C550D08 */  j          func_00355570
    /* 25DF2C 0035DEAC 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DE98, . - func_0035DE98

glabel func_0035DEB0
    /* 25DF30 0035DEB0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25DF34 0035DEB4 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25DF38 0035DEB8 0400848C */  lw         $a0, 0x4($a0)
    /* 25DF3C 0035DEBC 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25DF40 0035DEC0 5E550D08 */  j          func_00355578
    /* 25DF44 0035DEC4 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DEB0, . - func_0035DEB0

glabel func_0035DEC8
    /* 25DF48 0035DEC8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25DF4C 0035DECC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25DF50 0035DED0 0400848C */  lw         $a0, 0x4($a0)
    /* 25DF54 0035DED4 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25DF58 0035DED8 60550D08 */  j          func_00355580
    /* 25DF5C 0035DEDC 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DEC8, . - func_0035DEC8

glabel func_0035DEE0
    /* 25DF60 0035DEE0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25DF64 0035DEE4 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25DF68 0035DEE8 0400848C */  lw         $a0, 0x4($a0)
    /* 25DF6C 0035DEEC 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25DF70 0035DEF0 6E550D08 */  j          func_003555B8
    /* 25DF74 0035DEF4 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DEE0, . - func_0035DEE0

glabel func_0035DEF8
    /* 25DF78 0035DEF8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25DF7C 0035DEFC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25DF80 0035DF00 0400848C */  lw         $a0, 0x4($a0)
    /* 25DF84 0035DF04 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25DF88 0035DF08 86550D08 */  j          func_00355618
    /* 25DF8C 0035DF0C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DEF8, . - func_0035DEF8

glabel func_0035DF10
    /* 25DF90 0035DF10 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25DF94 0035DF14 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25DF98 0035DF18 0400848C */  lw         $a0, 0x4($a0)
    /* 25DF9C 0035DF1C 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25DFA0 0035DF20 88550D08 */  j          func_00355620
    /* 25DFA4 0035DF24 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DF10, . - func_0035DF10

glabel func_0035DF28
    /* 25DFA8 0035DF28 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25DFAC 0035DF2C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25DFB0 0035DF30 0400848C */  lw         $a0, 0x4($a0)
    /* 25DFB4 0035DF34 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25DFB8 0035DF38 8A550D08 */  j          func_00355628
    /* 25DFBC 0035DF3C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DF28, . - func_0035DF28

glabel func_0035DF40
    /* 25DFC0 0035DF40 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25DFC4 0035DF44 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25DFC8 0035DF48 0400848C */  lw         $a0, 0x4($a0)
    /* 25DFCC 0035DF4C 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25DFD0 0035DF50 8C550D08 */  j          func_00355630
    /* 25DFD4 0035DF54 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DF40, . - func_0035DF40

glabel func_0035DF58
    /* 25DFD8 0035DF58 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25DFDC 0035DF5C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25DFE0 0035DF60 0400848C */  lw         $a0, 0x4($a0)
    /* 25DFE4 0035DF64 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25DFE8 0035DF68 90550D08 */  j          func_00355640
    /* 25DFEC 0035DF6C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DF58, . - func_0035DF58

glabel func_0035DF70
    /* 25DFF0 0035DF70 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25DFF4 0035DF74 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25DFF8 0035DF78 0400848C */  lw         $a0, 0x4($a0)
    /* 25DFFC 0035DF7C 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E000 0035DF80 8E550D08 */  j          func_00355638
    /* 25E004 0035DF84 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DF70, . - func_0035DF70

glabel func_0035DF88
    /* 25E008 0035DF88 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E00C 0035DF8C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25E010 0035DF90 0400848C */  lw         $a0, 0x4($a0)
    /* 25E014 0035DF94 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E018 0035DF98 92550D08 */  j          func_00355648
    /* 25E01C 0035DF9C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DF88, . - func_0035DF88

glabel func_0035DFA0
    /* 25E020 0035DFA0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E024 0035DFA4 2D100000 */  daddu      $v0, $zero, $zero
    /* 25E028 0035DFA8 05008010 */  beqz       $a0, .L0035DFC0
    /* 25E02C 0035DFAC 0000BFFF */   sd        $ra, 0x0($sp)
    /* 25E030 0035DFB0 0400848C */  lw         $a0, 0x4($a0)
    /* 25E034 0035DFB4 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E038 0035DFB8 94550D08 */  j          func_00355650
    /* 25E03C 0035DFBC 1000BD27 */   addiu     $sp, $sp, 0x10
  .L0035DFC0:
    /* 25E040 0035DFC0 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E044 0035DFC4 0800E003 */  jr         $ra
    /* 25E048 0035DFC8 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25E04C 0035DFCC 00000000 */  nop
.size func_0035DFA0, . - func_0035DFA0

glabel func_0035DFD0
    /* 25E050 0035DFD0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E054 0035DFD4 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25E058 0035DFD8 0400848C */  lw         $a0, 0x4($a0)
    /* 25E05C 0035DFDC 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E060 0035DFE0 9A550D08 */  j          func_00355668
    /* 25E064 0035DFE4 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DFD0, . - func_0035DFD0

glabel func_0035DFE8
    /* 25E068 0035DFE8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E06C 0035DFEC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25E070 0035DFF0 0400848C */  lw         $a0, 0x4($a0)
    /* 25E074 0035DFF4 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E078 0035DFF8 9C550D08 */  j          func_00355670
    /* 25E07C 0035DFFC 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035DFE8, . - func_0035DFE8

glabel func_0035E000
    /* 25E080 0035E000 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E084 0035E004 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25E088 0035E008 0400848C */  lw         $a0, 0x4($a0)
    /* 25E08C 0035E00C 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E090 0035E010 9E550D08 */  j          func_00355678
    /* 25E094 0035E014 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035E000, . - func_0035E000

glabel func_0035E018
    /* 25E098 0035E018 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E09C 0035E01C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25E0A0 0035E020 2D808000 */  daddu      $s0, $a0, $zero
    /* 25E0A4 0035E024 0800BFFF */  sd         $ra, 0x8($sp)
    /* 25E0A8 0035E028 9E550D0C */  jal        func_00355678
    /* 25E0AC 0035E02C 0400048E */   lw        $a0, 0x4($s0)
    /* 25E0B0 0035E030 0B004018 */  blez       $v0, .L0035E060
    /* 25E0B4 0035E034 2D100000 */   daddu     $v0, $zero, $zero
    /* 25E0B8 0035E038 01000292 */  lbu        $v0, 0x1($s0)
    /* 25E0BC 0035E03C FEFF4224 */  addiu      $v0, $v0, -0x2
    /* 25E0C0 0035E040 0200422C */  sltiu      $v0, $v0, 0x2
    /* 25E0C4 0035E044 06004050 */  beql       $v0, $zero, .L0035E060
    /* 25E0C8 0035E048 2D100000 */   daddu     $v0, $zero, $zero
    /* 25E0CC 0035E04C A0550D0C */  jal        func_00355680
    /* 25E0D0 0035E050 0400048E */   lw        $a0, 0x4($s0)
    /* 25E0D4 0035E054 03000010 */  b          .L0035E064
    /* 25E0D8 0035E058 0000B0DF */   ld        $s0, 0x0($sp)
    /* 25E0DC 0035E05C 00000000 */  nop
  .L0035E060:
    /* 25E0E0 0035E060 0000B0DF */  ld         $s0, 0x0($sp)
  .L0035E064:
    /* 25E0E4 0035E064 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25E0E8 0035E068 0800E003 */  jr         $ra
    /* 25E0EC 0035E06C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035E018, . - func_0035E018

glabel func_0035E070
    /* 25E0F0 0035E070 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 25E0F4 0035E074 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25E0F8 0035E078 2D808000 */  daddu      $s0, $a0, $zero
    /* 25E0FC 0035E07C 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25E100 0035E080 2D88A000 */  daddu      $s1, $a1, $zero
    /* 25E104 0035E084 1000BFFF */  sd         $ra, 0x10($sp)
    /* 25E108 0035E088 9E550D0C */  jal        func_00355678
    /* 25E10C 0035E08C 0400048E */   lw        $a0, 0x4($s0)
    /* 25E110 0035E090 0B004018 */  blez       $v0, .L0035E0C0
    /* 25E114 0035E094 80FF0224 */   addiu     $v0, $zero, -0x80
    /* 25E118 0035E098 01000292 */  lbu        $v0, 0x1($s0)
    /* 25E11C 0035E09C FEFF4224 */  addiu      $v0, $v0, -0x2
    /* 25E120 0035E0A0 0200422C */  sltiu      $v0, $v0, 0x2
    /* 25E124 0035E0A4 06004050 */  beql       $v0, $zero, .L0035E0C0
    /* 25E128 0035E0A8 80FF0224 */   addiu     $v0, $zero, -0x80
    /* 25E12C 0035E0AC 0400048E */  lw         $a0, 0x4($s0)
    /* 25E130 0035E0B0 A2550D0C */  jal        func_00355688
    /* 25E134 0035E0B4 2D282002 */   daddu     $a1, $s1, $zero
    /* 25E138 0035E0B8 02000010 */  b          .L0035E0C4
    /* 25E13C 0035E0BC 0000B0DF */   ld        $s0, 0x0($sp)
  .L0035E0C0:
    /* 25E140 0035E0C0 0000B0DF */  ld         $s0, 0x0($sp)
  .L0035E0C4:
    /* 25E144 0035E0C4 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25E148 0035E0C8 1000BFDF */  ld         $ra, 0x10($sp)
    /* 25E14C 0035E0CC 0800E003 */  jr         $ra
    /* 25E150 0035E0D0 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 25E154 0035E0D4 00000000 */  nop
.size func_0035E070, . - func_0035E070
