.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035E0D8
    /* 25E158 0035E0D8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E15C 0035E0DC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25E160 0035E0E0 2D808000 */  daddu      $s0, $a0, $zero
    /* 25E164 0035E0E4 0800BFFF */  sd         $ra, 0x8($sp)
    /* 25E168 0035E0E8 9E550D0C */  jal        func_00355678
    /* 25E16C 0035E0EC 0400048E */   lw        $a0, 0x4($s0)
    /* 25E170 0035E0F0 0B004058 */  blezl      $v0, .L0035E120
    /* 25E174 0035E0F4 0000B0DF */   ld        $s0, 0x0($sp)
    /* 25E178 0035E0F8 01000292 */  lbu        $v0, 0x1($s0)
    /* 25E17C 0035E0FC FEFF4224 */  addiu      $v0, $v0, -0x2
    /* 25E180 0035E100 0200422C */  sltiu      $v0, $v0, 0x2
    /* 25E184 0035E104 06004050 */  beql       $v0, $zero, .L0035E120
    /* 25E188 0035E108 0000B0DF */   ld        $s0, 0x0($sp)
    /* 25E18C 0035E10C 0400048E */  lw         $a0, 0x4($s0)
    /* 25E190 0035E110 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25E194 0035E114 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25E198 0035E118 A6550D08 */  j          func_00355698
    /* 25E19C 0035E11C 1000BD27 */   addiu     $sp, $sp, 0x10
  .L0035E120:
    /* 25E1A0 0035E120 2D100000 */  daddu      $v0, $zero, $zero
    /* 25E1A4 0035E124 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25E1A8 0035E128 0800E003 */  jr         $ra
    /* 25E1AC 0035E12C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035E0D8, . - func_0035E0D8

glabel func_0035E130
    /* 25E1B0 0035E130 0800E003 */  jr         $ra
    /* 25E1B4 0035E134 9800828C */   lw        $v0, 0x98($a0)
.size func_0035E130, . - func_0035E130

glabel func_0035E138
    /* 25E1B8 0035E138 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E1BC 0035E13C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25E1C0 0035E140 0400848C */  lw         $a0, 0x4($a0)
    /* 25E1C4 0035E144 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E1C8 0035E148 6C550D08 */  j          func_003555B0
    /* 25E1CC 0035E14C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035E138, . - func_0035E138

glabel func_0035E150
    /* 25E1D0 0035E150 0800E003 */  jr         $ra
    /* 25E1D4 0035E154 58008224 */   addiu     $v0, $a0, 0x58
.size func_0035E150, . - func_0035E150

glabel func_0035E158
    /* 25E1D8 0035E158 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E1DC 0035E15C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25E1E0 0035E160 0400848C */  lw         $a0, 0x4($a0)
    /* 25E1E4 0035E164 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E1E8 0035E168 A8550D08 */  j          func_003556A0
    /* 25E1EC 0035E16C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035E158, . - func_0035E158

glabel func_0035E170
    /* 25E1F0 0035E170 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E1F4 0035E174 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25E1F8 0035E178 0400848C */  lw         $a0, 0x4($a0)
    /* 25E1FC 0035E17C 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E200 0035E180 B8550D08 */  j          func_003556E0
    /* 25E204 0035E184 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035E170, . - func_0035E170

glabel func_0035E188
    /* 25E208 0035E188 4300023C */  lui        $v0, (0x43466C >> 16)
    /* 25E20C 0035E18C 0800E003 */  jr         $ra
    /* 25E210 0035E190 6C4644AC */   sw        $a0, (0x43466C & 0xFFFF)($v0)
    /* 25E214 0035E194 00000000 */  nop
.size func_0035E188, . - func_0035E188
