.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035E1E8
    /* 25E268 0035E1E8 0800E003 */  jr         $ra
    /* 25E26C 0035E1EC 00000000 */   nop
.size func_0035E1E8, . - func_0035E1E8

glabel func_0035E1F0
    /* 25E270 0035E1F0 0800E003 */  jr         $ra
    /* 25E274 0035E1F4 00000000 */   nop
.size func_0035E1F0, . - func_0035E1F0

glabel func_0035E1F8
    /* 25E278 0035E1F8 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 25E27C 0035E1FC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25E280 0035E200 2D80E000 */  daddu      $s0, $a3, $zero
    /* 25E284 0035E204 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25E288 0035E208 2D88A000 */  daddu      $s1, $a1, $zero
    /* 25E28C 0035E20C 1000B2FF */  sd         $s2, 0x10($sp)
    /* 25E290 0035E210 2D90C000 */  daddu      $s2, $a2, $zero
    /* 25E294 0035E214 1800B3FF */  sd         $s3, 0x18($sp)
    /* 25E298 0035E218 2D988000 */  daddu      $s3, $a0, $zero
    /* 25E29C 0035E21C 2000B4FF */  sd         $s4, 0x20($sp)
    /* 25E2A0 0035E220 2DA00001 */  daddu      $s4, $t0, $zero
    /* 25E2A4 0035E224 2800B5FF */  sd         $s5, 0x28($sp)
    /* 25E2A8 0035E228 3000BFFF */  sd         $ra, 0x30($sp)
    /* 25E2AC 0035E22C 485B0D0C */  jal        func_00356D20
    /* 25E2B0 0035E230 01001524 */   addiu     $s5, $zero, 0x1
    /* 25E2B4 0035E234 FF070726 */  addiu      $a3, $s0, 0x7FF
    /* 25E2B8 0035E238 0000022A */  slti       $v0, $s0, 0x0
    /* 25E2BC 0035E23C 2D180002 */  daddu      $v1, $s0, $zero
    /* 25E2C0 0035E240 0F00063C */  lui        $a2, (0xFFFFF >> 16)
    /* 25E2C4 0035E244 0B18E200 */  movn       $v1, $a3, $v0
    /* 25E2C8 0035E248 00020724 */  addiu      $a3, $zero, 0x200
    /* 25E2CC 0035E24C C31A0300 */  sra        $v1, $v1, 11
    /* 25E2D0 0035E250 FFFFC634 */  ori        $a2, $a2, (0xFFFFF & 0xFFFF)
    /* 25E2D4 0035E254 C0120300 */  sll        $v0, $v1, 11
    /* 25E2D8 0035E258 2D208002 */  daddu      $a0, $s4, $zero
    /* 25E2DC 0035E25C 23100202 */  subu       $v0, $s0, $v0
    /* 25E2E0 0035E260 2D280000 */  daddu      $a1, $zero, $zero
    /* 25E2E4 0035E264 2A100200 */  slt        $v0, $zero, $v0
    /* 25E2E8 0035E268 080071AE */  sw         $s1, 0x8($s3)
    /* 25E2EC 0035E26C 21186200 */  addu       $v1, $v1, $v0
    /* 25E2F0 0035E270 0C0072AE */  sw         $s2, 0xC($s3)
    /* 25E2F4 0035E274 2C0067AE */  sw         $a3, 0x2C($s3)
    /* 25E2F8 0035E278 5C0066AE */  sw         $a2, 0x5C($s3)
    /* 25E2FC 0035E27C 300063AE */  sw         $v1, 0x30($s3)
    /* 25E300 0035E280 010075A2 */  sb         $s5, 0x1($s3)
    /* 25E304 0035E284 020060A2 */  sb         $zero, 0x2($s3)
    /* 25E308 0035E288 040074AE */  sw         $s4, 0x4($s3)
    /* 25E30C 0035E28C 100070AE */  sw         $s0, 0x10($s3)
    /* 25E310 0035E290 140063AE */  sw         $v1, 0x14($s3)
    /* 25E314 0035E294 0F008012 */  beqz       $s4, .L0035E2D4
    /* 25E318 0035E298 580060AE */   sw        $zero, 0x58($s3)
    /* 25E31C 0035E29C 0000838E */  lw         $v1, 0x0($s4)
    /* 25E320 0035E2A0 2400628C */  lw         $v0, 0x24($v1)
    /* 25E324 0035E2A4 09F84000 */  jalr       $v0
    /* 25E328 0035E2A8 00000000 */   nop
    /* 25E32C 0035E2AC 0000838E */  lw         $v1, 0x0($s4)
    /* 25E330 0035E2B0 2D804000 */  daddu      $s0, $v0, $zero
    /* 25E334 0035E2B4 2D208002 */  daddu      $a0, $s4, $zero
    /* 25E338 0035E2B8 2400628C */  lw         $v0, 0x24($v1)
    /* 25E33C 0035E2BC 09F84000 */  jalr       $v0
    /* 25E340 0035E2C0 01000524 */   addiu     $a1, $zero, 0x1
    /* 25E344 0035E2C4 21800202 */  addu       $s0, $s0, $v0
    /* 25E348 0035E2C8 1C0070AE */  sw         $s0, 0x1C($s3)
    /* 25E34C 0035E2CC 400070AE */  sw         $s0, 0x40($s3)
    /* 25E350 0035E2D0 180070AE */  sw         $s0, 0x18($s3)
  .L0035E2D4:
    /* 25E354 0035E2D4 000075A2 */  sb         $s5, 0x0($s3)
    /* 25E358 0035E2D8 440060A2 */  sb         $zero, 0x44($s3)
    /* 25E35C 0035E2DC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25E360 0035E2E0 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25E364 0035E2E4 1000B2DF */  ld         $s2, 0x10($sp)
    /* 25E368 0035E2E8 1800B3DF */  ld         $s3, 0x18($sp)
    /* 25E36C 0035E2EC 2000B4DF */  ld         $s4, 0x20($sp)
    /* 25E370 0035E2F0 2800B5DF */  ld         $s5, 0x28($sp)
    /* 25E374 0035E2F4 3000BFDF */  ld         $ra, 0x30($sp)
    /* 25E378 0035E2F8 4E5B0D08 */  j          func_00356D38
    /* 25E37C 0035E2FC 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_0035E1F8, . - func_0035E1F8

glabel func_0035E300
    /* 25E380 0035E300 43000D3C */  lui        $t5, (0x43466C >> 16)
    /* 25E384 0035E304 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E388 0035E308 6C46A98D */  lw         $t1, (0x43466C & 0xFFFF)($t5)
    /* 25E38C 0035E30C 2D50A000 */  daddu      $t2, $a1, $zero
    /* 25E390 0035E310 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25E394 0035E314 2D800000 */  daddu      $s0, $zero, $zero
    /* 25E398 0035E318 0800BFFF */  sd         $ra, 0x8($sp)
    /* 25E39C 0035E31C 2D608000 */  daddu      $t4, $a0, $zero
    /* 25E3A0 0035E320 2D58C000 */  daddu      $t3, $a2, $zero
    /* 25E3A4 0035E324 2D40E000 */  daddu      $t0, $a3, $zero
    /* 25E3A8 0035E328 1B002019 */  blez       $t1, .L0035E398
    /* 25E3AC 0035E32C 2D280000 */   daddu     $a1, $zero, $zero
    /* 25E3B0 0035E330 4300023C */  lui        $v0, %hi(D_434668)
    /* 25E3B4 0035E334 4300043C */  lui        $a0, %hi(D_434688)
    /* 25E3B8 0035E338 68464724 */  addiu      $a3, $v0, %lo(D_434668)
    /* 25E3BC 0035E33C 88468424 */  addiu      $a0, $a0, %lo(D_434688)
    /* 25E3C0 0035E340 0000E38C */  lw         $v1, 0x0($a3)
    /* 25E3C4 0035E344 40100300 */  sll        $v0, $v1, 1
    /* 25E3C8 0035E348 21104300 */  addu       $v0, $v0, $v1
    /* 25E3CC 0035E34C 40110200 */  sll        $v0, $v0, 5
    /* 25E3D0 0035E350 21804400 */  addu       $s0, $v0, $a0
    /* 25E3D4 0035E354 00000382 */  lb         $v1, 0x0($s0)
    /* 25E3D8 0035E358 10006010 */  beqz       $v1, .L0035E39C
    /* 25E3DC 0035E35C 6C46A38D */   lw        $v1, (0x43466C & 0xFFFF)($t5)
    /* 25E3E0 0035E360 2D302001 */  daddu      $a2, $t1, $zero
    /* 25E3E4 0035E364 0100A524 */  addiu      $a1, $a1, 0x1
  .L0035E368:
    /* 25E3E8 0035E368 2A10A600 */  slt        $v0, $a1, $a2
    /* 25E3EC 0035E36C 0B004010 */  beqz       $v0, .L0035E39C
    /* 25E3F0 0035E370 6C46A38D */   lw        $v1, (0x43466C & 0xFFFF)($t5)
    /* 25E3F4 0035E374 0000E28C */  lw         $v0, 0x0($a3)
    /* 25E3F8 0035E378 21104500 */  addu       $v0, $v0, $a1
    /* 25E3FC 0035E37C 40180200 */  sll        $v1, $v0, 1
    /* 25E400 0035E380 21186200 */  addu       $v1, $v1, $v0
    /* 25E404 0035E384 40190300 */  sll        $v1, $v1, 5
    /* 25E408 0035E388 21806400 */  addu       $s0, $v1, $a0
    /* 25E40C 0035E38C 00000282 */  lb         $v0, 0x0($s0)
    /* 25E410 0035E390 F5FF4054 */  bnel       $v0, $zero, .L0035E368
    /* 25E414 0035E394 0100A524 */   addiu     $a1, $a1, 0x1
  .L0035E398:
    /* 25E418 0035E398 6C46A38D */  lw         $v1, (0x43466C & 0xFFFF)($t5)
  .L0035E39C:
    /* 25E41C 0035E39C 0700A310 */  beq        $a1, $v1, .L0035E3BC
    /* 25E420 0035E3A0 2D100000 */   daddu     $v0, $zero, $zero
    /* 25E424 0035E3A4 2D288001 */  daddu      $a1, $t4, $zero
    /* 25E428 0035E3A8 2D304001 */  daddu      $a2, $t2, $zero
    /* 25E42C 0035E3AC 2D386001 */  daddu      $a3, $t3, $zero
    /* 25E430 0035E3B0 7E780D0C */  jal        func_0035E1F8
    /* 25E434 0035E3B4 2D200002 */   daddu     $a0, $s0, $zero
    /* 25E438 0035E3B8 2D100002 */  daddu      $v0, $s0, $zero
  .L0035E3BC:
    /* 25E43C 0035E3BC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25E440 0035E3C0 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25E444 0035E3C4 0800E003 */  jr         $ra
    /* 25E448 0035E3C8 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25E44C 0035E3CC 00000000 */  nop
.size func_0035E300, . - func_0035E300

glabel func_0035E3D0
    /* 25E450 0035E3D0 43000D3C */  lui        $t5, (0x434674 >> 16)
    /* 25E454 0035E3D4 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E458 0035E3D8 7446A98D */  lw         $t1, (0x434674 & 0xFFFF)($t5)
    /* 25E45C 0035E3DC 2D50A000 */  daddu      $t2, $a1, $zero
    /* 25E460 0035E3E0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25E464 0035E3E4 2D800000 */  daddu      $s0, $zero, $zero
    /* 25E468 0035E3E8 0800BFFF */  sd         $ra, 0x8($sp)
    /* 25E46C 0035E3EC 2D608000 */  daddu      $t4, $a0, $zero
    /* 25E470 0035E3F0 2D58C000 */  daddu      $t3, $a2, $zero
    /* 25E474 0035E3F4 2D40E000 */  daddu      $t0, $a3, $zero
    /* 25E478 0035E3F8 1B002019 */  blez       $t1, .L0035E468
    /* 25E47C 0035E3FC 2D280000 */   daddu     $a1, $zero, $zero
    /* 25E480 0035E400 4300023C */  lui        $v0, %hi(D_434670)
    /* 25E484 0035E404 4300043C */  lui        $a0, %hi(D_434688)
    /* 25E488 0035E408 70464724 */  addiu      $a3, $v0, %lo(D_434670)
    /* 25E48C 0035E40C 88468424 */  addiu      $a0, $a0, %lo(D_434688)
    /* 25E490 0035E410 0000E38C */  lw         $v1, 0x0($a3)
    /* 25E494 0035E414 40100300 */  sll        $v0, $v1, 1
    /* 25E498 0035E418 21104300 */  addu       $v0, $v0, $v1
    /* 25E49C 0035E41C 40110200 */  sll        $v0, $v0, 5
    /* 25E4A0 0035E420 21804400 */  addu       $s0, $v0, $a0
    /* 25E4A4 0035E424 00000382 */  lb         $v1, 0x0($s0)
    /* 25E4A8 0035E428 10006010 */  beqz       $v1, .L0035E46C
    /* 25E4AC 0035E42C 7446A38D */   lw        $v1, (0x434674 & 0xFFFF)($t5)
    /* 25E4B0 0035E430 2D302001 */  daddu      $a2, $t1, $zero
    /* 25E4B4 0035E434 0100A524 */  addiu      $a1, $a1, 0x1
  .L0035E438:
    /* 25E4B8 0035E438 2A10A600 */  slt        $v0, $a1, $a2
    /* 25E4BC 0035E43C 0B004010 */  beqz       $v0, .L0035E46C
    /* 25E4C0 0035E440 7446A38D */   lw        $v1, (0x434674 & 0xFFFF)($t5)
    /* 25E4C4 0035E444 0000E28C */  lw         $v0, 0x0($a3)
    /* 25E4C8 0035E448 21104500 */  addu       $v0, $v0, $a1
    /* 25E4CC 0035E44C 40180200 */  sll        $v1, $v0, 1
    /* 25E4D0 0035E450 21186200 */  addu       $v1, $v1, $v0
    /* 25E4D4 0035E454 40190300 */  sll        $v1, $v1, 5
    /* 25E4D8 0035E458 21806400 */  addu       $s0, $v1, $a0
    /* 25E4DC 0035E45C 00000282 */  lb         $v0, 0x0($s0)
    /* 25E4E0 0035E460 F5FF4054 */  bnel       $v0, $zero, .L0035E438
    /* 25E4E4 0035E464 0100A524 */   addiu     $a1, $a1, 0x1
  .L0035E468:
    /* 25E4E8 0035E468 7446A38D */  lw         $v1, (0x434674 & 0xFFFF)($t5)
  .L0035E46C:
    /* 25E4EC 0035E46C 0700A310 */  beq        $a1, $v1, .L0035E48C
    /* 25E4F0 0035E470 2D100000 */   daddu     $v0, $zero, $zero
    /* 25E4F4 0035E474 2D288001 */  daddu      $a1, $t4, $zero
    /* 25E4F8 0035E478 2D304001 */  daddu      $a2, $t2, $zero
    /* 25E4FC 0035E47C 2D386001 */  daddu      $a3, $t3, $zero
    /* 25E500 0035E480 7E780D0C */  jal        func_0035E1F8
    /* 25E504 0035E484 2D200002 */   daddu     $a0, $s0, $zero
    /* 25E508 0035E488 2D100002 */  daddu      $v0, $s0, $zero
  .L0035E48C:
    /* 25E50C 0035E48C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25E510 0035E490 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25E514 0035E494 0800E003 */  jr         $ra
    /* 25E518 0035E498 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25E51C 0035E49C 00000000 */  nop
.size func_0035E3D0, . - func_0035E3D0

glabel func_0035E4A0
    /* 25E520 0035E4A0 2D188000 */  daddu      $v1, $a0, $zero
    /* 25E524 0035E4A4 2D200000 */  daddu      $a0, $zero, $zero
    /* 25E528 0035E4A8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E52C 0035E4AC 0001A228 */  slti       $v0, $a1, 0x100
    /* 25E530 0035E4B0 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25E534 0035E4B4 2D386000 */  daddu      $a3, $v1, $zero
    /* 25E538 0035E4B8 05004010 */  beqz       $v0, .L0035E4D0
    /* 25E53C 0035E4BC 2D280000 */   daddu     $a1, $zero, $zero
    /* 25E540 0035E4C0 C0780D0C */  jal        func_0035E300
    /* 25E544 0035E4C4 2D300000 */   daddu     $a2, $zero, $zero
    /* 25E548 0035E4C8 04000010 */  b          .L0035E4DC
    /* 25E54C 0035E4CC 0000BFDF */   ld        $ra, 0x0($sp)
  .L0035E4D0:
    /* 25E550 0035E4D0 F4780D0C */  jal        func_0035E3D0
    /* 25E554 0035E4D4 2D300000 */   daddu     $a2, $zero, $zero
    /* 25E558 0035E4D8 0000BFDF */  ld         $ra, 0x0($sp)
  .L0035E4DC:
    /* 25E55C 0035E4DC 0800E003 */  jr         $ra
    /* 25E560 0035E4E0 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25E564 0035E4E4 00000000 */  nop
.size func_0035E4A0, . - func_0035E4A0
