.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035E1B8
    /* 25E238 0035E1B8 4300043C */  lui        $a0, %hi(D_00434688)
    /* 25E23C 0035E1BC F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E240 0035E1C0 2D280000 */  daddu      $a1, $zero, $zero
    /* 25E244 0035E1C4 88468424 */  addiu      $a0, $a0, %lo(D_00434688)
    /* 25E248 0035E1C8 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25E24C 0035E1CC 84D40D0C */  jal        func_00375210
    /* 25E250 0035E1D0 000F0624 */   addiu     $a2, $zero, 0xF00
    /* 25E254 0035E1D4 01000224 */  addiu      $v0, $zero, 0x1
    /* 25E258 0035E1D8 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25E25C 0035E1DC 0800E003 */  jr         $ra
    /* 25E260 0035E1E0 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25E264 0035E1E4 00000000 */  nop
.size func_0035E1B8, . - func_0035E1B8
