.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035E4E8
    /* 25E568 0035E4E8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E56C 0035E4EC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25E570 0035E4F0 2D808000 */  daddu      $s0, $a0, $zero
    /* 25E574 0035E4F4 0E000012 */  beqz       $s0, .L0035E530
    /* 25E578 0035E4F8 0800BFFF */   sd        $ra, 0x8($sp)
    /* 25E57C 0035E4FC FC790D0C */  jal        func_0035E7F0
    /* 25E580 0035E500 00000000 */   nop
    /* 25E584 0035E504 8C790D0C */  jal        func_0035E630
    /* 25E588 0035E508 2D200002 */   daddu     $a0, $s0, $zero
    /* 25E58C 0035E50C 000000A2 */  sb         $zero, 0x0($s0)
    /* 25E590 0035E510 2D200002 */  daddu      $a0, $s0, $zero
    /* 25E594 0035E514 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25E598 0035E518 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25E59C 0035E51C 2D280000 */  daddu      $a1, $zero, $zero
    /* 25E5A0 0035E520 60000624 */  addiu      $a2, $zero, 0x60
    /* 25E5A4 0035E524 84D40D08 */  j          func_00375210
    /* 25E5A8 0035E528 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25E5AC 0035E52C 00000000 */  nop
  .L0035E530:
    /* 25E5B0 0035E530 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25E5B4 0035E534 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25E5B8 0035E538 0800E003 */  jr         $ra
    /* 25E5BC 0035E53C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035E4E8, . - func_0035E4E8

glabel func_0035E540
    /* 25E5C0 0035E540 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 25E5C4 0035E544 1000B2FF */  sd         $s2, 0x10($sp)
    /* 25E5C8 0035E548 2D900001 */  daddu      $s2, $t0, $zero
    /* 25E5CC 0035E54C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25E5D0 0035E550 2D808000 */  daddu      $s0, $a0, $zero
    /* 25E5D4 0035E554 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25E5D8 0035E558 2D88E000 */  daddu      $s1, $a3, $zero
    /* 25E5DC 0035E55C 1800B3FF */  sd         $s3, 0x18($sp)
    /* 25E5E0 0035E560 2D98A000 */  daddu      $s3, $a1, $zero
    /* 25E5E4 0035E564 2000B4FF */  sd         $s4, 0x20($sp)
    /* 25E5E8 0035E568 2800BFFF */  sd         $ra, 0x28($sp)
    /* 25E5EC 0035E56C 60C10D0C */  jal        func_00370580
    /* 25E5F0 0035E570 2DA0C000 */   daddu     $s4, $a2, $zero
    /* 25E5F4 0035E574 C01A1200 */  sll        $v1, $s2, 11
    /* 25E5F8 0035E578 01000224 */  addiu      $v0, $zero, 0x1
    /* 25E5FC 0035E57C 0C0011AE */  sw         $s1, 0xC($s0)
    /* 25E600 0035E580 140012AE */  sw         $s2, 0x14($s0)
    /* 25E604 0035E584 500013AE */  sw         $s3, 0x50($s0)
    /* 25E608 0035E588 540014AE */  sw         $s4, 0x54($s0)
    /* 25E60C 0035E58C 450002A2 */  sb         $v0, 0x45($s0)
    /* 25E610 0035E590 100003AE */  sw         $v1, 0x10($s0)
    /* 25E614 0035E594 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25E618 0035E598 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25E61C 0035E59C 1000B2DF */  ld         $s2, 0x10($sp)
    /* 25E620 0035E5A0 1800B3DF */  ld         $s3, 0x18($sp)
    /* 25E624 0035E5A4 2000B4DF */  ld         $s4, 0x20($sp)
    /* 25E628 0035E5A8 2800BFDF */  ld         $ra, 0x28($sp)
    /* 25E62C 0035E5AC 66C10D08 */  j          func_00370598
    /* 25E630 0035E5B0 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 25E634 0035E5B4 00000000 */  nop
.size func_0035E540, . - func_0035E540
