.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035E788
    /* 25E808 0035E788 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25E80C 0035E78C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25E810 0035E790 0800BFFF */  sd         $ra, 0x8($sp)
    /* 25E814 0035E794 60C10D0C */  jal        func_00370580
    /* 25E818 0035E798 2D808000 */   daddu     $s0, $a0, $zero
    /* 25E81C 0035E79C 0000028E */  lw         $v0, 0x0($s0)
    /* 25E820 0035E7A0 FF00033C */  lui        $v1, (0xFFFF00 >> 16)
    /* 25E824 0035E7A4 00FF6334 */  ori        $v1, $v1, (0xFFFF00 & 0xFFFF)
    /* 25E828 0035E7A8 0100043C */  lui        $a0, (0x10200 >> 16)
    /* 25E82C 0035E7AC 24104300 */  and        $v0, $v0, $v1
    /* 25E830 0035E7B0 00028434 */  ori        $a0, $a0, (0x10200 & 0xFFFF)
    /* 25E834 0035E7B4 08004414 */  bne        $v0, $a0, .L0035E7D8
    /* 25E838 0035E7B8 01000524 */   addiu     $a1, $zero, 0x1
    /* 25E83C 0035E7BC 47000382 */  lb         $v1, 0x47($s0)
    /* 25E840 0035E7C0 01000224 */  addiu      $v0, $zero, 0x1
    /* 25E844 0035E7C4 06006514 */  bne        $v1, $a1, .L0035E7E0
    /* 25E848 0035E7C8 480002A2 */   sb        $v0, 0x48($s0)
    /* 25E84C 0035E7CC 04000010 */  b          .L0035E7E0
    /* 25E850 0035E7D0 470000A2 */   sb        $zero, 0x47($s0)
    /* 25E854 0035E7D4 00000000 */  nop
  .L0035E7D8:
    /* 25E858 0035E7D8 01000224 */  addiu      $v0, $zero, 0x1
    /* 25E85C 0035E7DC 010002A2 */  sb         $v0, 0x1($s0)
  .L0035E7E0:
    /* 25E860 0035E7E0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25E864 0035E7E4 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25E868 0035E7E8 66C10D08 */  j          func_00370598
    /* 25E86C 0035E7EC 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035E788, . - func_0035E788

glabel func_0035E7F0
    /* 25E870 0035E7F0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 25E874 0035E7F4 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25E878 0035E7F8 2D808000 */  daddu      $s0, $a0, $zero
    /* 25E87C 0035E7FC 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25E880 0035E800 1000BFFF */  sd         $ra, 0x10($sp)
    /* 25E884 0035E804 E2790D0C */  jal        func_0035E788
    /* 25E888 0035E808 01001124 */   addiu     $s1, $zero, 0x1
    /* 25E88C 0035E80C 00000000 */  nop
  .L0035E810:
    /* 25E890 0035E810 0C6A0D0C */  jal        func_0035A830
    /* 25E894 0035E814 00000000 */   nop
    /* 25E898 0035E818 01000282 */  lb         $v0, 0x1($s0)
    /* 25E89C 0035E81C FCFF5114 */  bne        $v0, $s1, .L0035E810
    /* 25E8A0 0035E820 00000000 */   nop
    /* 25E8A4 0035E824 2400028E */  lw         $v0, 0x24($s0)
    /* 25E8A8 0035E828 F9FF4014 */  bnez       $v0, .L0035E810
    /* 25E8AC 0035E82C 1000BFDF */   ld        $ra, 0x10($sp)
    /* 25E8B0 0035E830 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25E8B4 0035E834 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25E8B8 0035E838 0800E003 */  jr         $ra
    /* 25E8BC 0035E83C 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_0035E7F0, . - func_0035E7F0

glabel func_0035E840
    /* 25E8C0 0035E840 3C0086AC */  sw         $a2, 0x3C($a0)
    /* 25E8C4 0035E844 0800E003 */  jr         $ra
    /* 25E8C8 0035E848 380085AC */   sw        $a1, 0x38($a0)
    /* 25E8CC 0035E84C 00000000 */  nop
.size func_0035E840, . - func_0035E840

glabel func_0035E850
    /* 25E8D0 0035E850 0300A204 */  bltzl      $a1, .L0035E860
    /* 25E8D4 0035E854 1400828C */   lw        $v0, 0x14($a0)
    /* 25E8D8 0035E858 0800E003 */  jr         $ra
    /* 25E8DC 0035E85C 300085AC */   sw        $a1, 0x30($a0)
  .L0035E860:
    /* 25E8E0 0035E860 0800E003 */  jr         $ra
    /* 25E8E4 0035E864 300082AC */   sw        $v0, 0x30($a0)
.size func_0035E850, . - func_0035E850

glabel func_0035E868
    /* 25E8E8 0035E868 4300033C */  lui        $v1, %hi(D_00434680)
    /* 25E8EC 0035E86C 80466324 */  addiu      $v1, $v1, %lo(D_00434680)
    /* 25E8F0 0035E870 0000628C */  lw         $v0, 0x0($v1)
    /* 25E8F4 0035E874 01004224 */  addiu      $v0, $v0, 0x1
    /* 25E8F8 0035E878 0800E003 */  jr         $ra
    /* 25E8FC 0035E87C 000062AC */   sw        $v0, 0x0($v1)
.size func_0035E868, . - func_0035E868

glabel func_0035E880
    /* 25E900 0035E880 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 25E904 0035E884 2000B0FF */  sd         $s0, 0x20($sp)
    /* 25E908 0035E888 2800B1FF */  sd         $s1, 0x28($sp)
    /* 25E90C 0035E88C 01001124 */  addiu      $s1, $zero, 0x1
    /* 25E910 0035E890 3800B3FF */  sd         $s3, 0x38($sp)
    /* 25E914 0035E894 2D988000 */  daddu      $s3, $a0, $zero
    /* 25E918 0035E898 3000B2FF */  sd         $s2, 0x30($sp)
    /* 25E91C 0035E89C 4000B4FF */  sd         $s4, 0x40($sp)
    /* 25E920 0035E8A0 4800BFFF */  sd         $ra, 0x48($sp)
    /* 25E924 0035E8A4 0800648E */  lw         $a0, 0x8($s3)
    /* 25E928 0035E8A8 3E900D0C */  jal        func_003640F8
    /* 25E92C 0035E8AC 0400748E */   lw        $s4, 0x4($s3)
    /* 25E930 0035E8B0 60C10D0C */  jal        func_00370580
    /* 25E934 0035E8B4 2D804000 */   daddu     $s0, $v0, $zero
    /* 25E938 0035E8B8 02006282 */  lb         $v0, 0x2($s3)
    /* 25E93C 0035E8BC 50005154 */  bnel       $v0, $s1, .L0035EA00
    /* 25E940 0035E8C0 020071A2 */   sb        $s1, 0x2($s3)
    /* 25E944 0035E8C4 3C001156 */  bnel       $s0, $s1, .L0035E9B8
    /* 25E948 0035E8C8 03000224 */   addiu     $v0, $zero, 0x3
    /* 25E94C 0035E8CC 020060A2 */  sb         $zero, 0x2($s3)
    /* 25E950 0035E8D0 66C10D0C */  jal        func_00370598
    /* 25E954 0035E8D4 24007226 */   addiu     $s2, $s3, 0x24
    /* 25E958 0035E8D8 2000708E */  lw         $s0, 0x20($s3)
    /* 25E95C 0035E8DC 1000B127 */  addiu      $s1, $sp, 0x10
    /* 25E960 0035E8E0 2D30A003 */  daddu      $a2, $sp, $zero
    /* 25E964 0035E8E4 C0821000 */  sll        $s0, $s0, 11
    /* 25E968 0035E8E8 2D382002 */  daddu      $a3, $s1, $zero
    /* 25E96C 0035E8EC 2D280002 */  daddu      $a1, $s0, $zero
    /* 25E970 0035E8F0 A4BD0D0C */  jal        func_0036F690
    /* 25E974 0035E8F4 2D204002 */   daddu     $a0, $s2, $zero
    /* 25E978 0035E8F8 0000838E */  lw         $v1, 0x0($s4)
    /* 25E97C 0035E8FC 2D30A003 */  daddu      $a2, $sp, $zero
    /* 25E980 0035E900 2D208002 */  daddu      $a0, $s4, $zero
    /* 25E984 0035E904 2000628C */  lw         $v0, 0x20($v1)
    /* 25E988 0035E908 09F84000 */  jalr       $v0
    /* 25E98C 0035E90C 01000524 */   addiu     $a1, $zero, 0x1
    /* 25E990 0035E910 0000838E */  lw         $v1, 0x0($s4)
    /* 25E994 0035E914 2D208002 */  daddu      $a0, $s4, $zero
    /* 25E998 0035E918 2D280000 */  daddu      $a1, $zero, $zero
    /* 25E99C 0035E91C 1C00628C */  lw         $v0, 0x1C($v1)
    /* 25E9A0 0035E920 09F84000 */  jalr       $v0
    /* 25E9A4 0035E924 2D302002 */   daddu     $a2, $s1, $zero
    /* 25E9A8 0035E928 5800638E */  lw         $v1, 0x58($s3)
    /* 25E9AC 0035E92C 3400628E */  lw         $v0, 0x34($s3)
    /* 25E9B0 0035E930 2000648E */  lw         $a0, 0x20($s3)
    /* 25E9B4 0035E934 3000658E */  lw         $a1, 0x30($s3)
    /* 25E9B8 0035E938 21105000 */  addu       $v0, $v0, $s0
    /* 25E9BC 0035E93C 21186400 */  addu       $v1, $v1, $a0
    /* 25E9C0 0035E940 340062AE */  sw         $v0, 0x34($s3)
    /* 25E9C4 0035E944 000040AE */  sw         $zero, 0x0($s2)
    /* 25E9C8 0035E948 580063AE */  sw         $v1, 0x58($s3)
    /* 25E9CC 0035E94C 280060AE */  sw         $zero, 0x28($s3)
    /* 25E9D0 0035E950 06006514 */  bne        $v1, $a1, .L0035E96C
    /* 25E9D4 0035E954 1400708E */   lw        $s0, 0x14($s3)
    /* 25E9D8 0035E958 3800628E */  lw         $v0, 0x38($s3)
    /* 25E9DC 0035E95C 04004050 */  beql       $v0, $zero, .L0035E970
    /* 25E9E0 0035E960 5800628E */   lw        $v0, 0x58($s3)
    /* 25E9E4 0035E964 09F84000 */  jalr       $v0
    /* 25E9E8 0035E968 3C00648E */   lw        $a0, 0x3C($s3)
  .L0035E96C:
    /* 25E9EC 0035E96C 5800628E */  lw         $v0, 0x58($s3)
  .L0035E970:
    /* 25E9F0 0035E970 2A105000 */  slt        $v0, $v0, $s0
    /* 25E9F4 0035E974 0D004010 */  beqz       $v0, .L0035E9AC
    /* 25E9F8 0035E978 03000224 */   addiu     $v0, $zero, 0x3
    /* 25E9FC 0035E97C 3400628E */  lw         $v0, 0x34($s3)
    /* 25EA00 0035E980 5C00638E */  lw         $v1, 0x5C($s3)
    /* 25EA04 0035E984 C2120200 */  srl        $v0, $v0, 11
    /* 25EA08 0035E988 2B104300 */  sltu       $v0, $v0, $v1
    /* 25EA0C 0035E98C 84004054 */  bnel       $v0, $zero, .L0035EBA0
    /* 25EA10 0035E990 030060A2 */   sb        $zero, 0x3($s3)
    /* 25EA14 0035E994 0F00023C */  lui        $v0, (0xFFFFE >> 16)
    /* 25EA18 0035E998 FEFF4234 */  ori        $v0, $v0, (0xFFFFE & 0xFFFF)
    /* 25EA1C 0035E99C 2B104300 */  sltu       $v0, $v0, $v1
    /* 25EA20 0035E9A0 7F004054 */  bnel       $v0, $zero, .L0035EBA0
    /* 25EA24 0035E9A4 030060A2 */   sb        $zero, 0x3($s3)
    /* 25EA28 0035E9A8 03000224 */  addiu      $v0, $zero, 0x3
  .L0035E9AC:
    /* 25EA2C 0035E9AC 010062A2 */  sb         $v0, 0x1($s3)
    /* 25EA30 0035E9B0 7B000010 */  b          .L0035EBA0
    /* 25EA34 0035E9B4 030060A2 */   sb        $zero, 0x3($s3)
  .L0035E9B8:
    /* 25EA38 0035E9B8 0D000216 */  bne        $s0, $v0, .L0035E9F0
    /* 25EA3C 0035E9BC 00000000 */   nop
    /* 25EA40 0035E9C0 020060A2 */  sb         $zero, 0x2($s3)
    /* 25EA44 0035E9C4 66C10D0C */  jal        func_00370598
    /* 25EA48 0035E9C8 24007026 */   addiu     $s0, $s3, 0x24
    /* 25EA4C 0035E9CC 0000838E */  lw         $v1, 0x0($s4)
    /* 25EA50 0035E9D0 2D208002 */  daddu      $a0, $s4, $zero
    /* 25EA54 0035E9D4 2D280000 */  daddu      $a1, $zero, $zero
    /* 25EA58 0035E9D8 1C00628C */  lw         $v0, 0x1C($v1)
    /* 25EA5C 0035E9DC 09F84000 */  jalr       $v0
    /* 25EA60 0035E9E0 2D300002 */   daddu     $a2, $s0, $zero
    /* 25EA64 0035E9E4 000000AE */  sw         $zero, 0x0($s0)
    /* 25EA68 0035E9E8 60000010 */  b          .L0035EB6C
    /* 25EA6C 0035E9EC 280060AE */   sw        $zero, 0x28($s3)
  .L0035E9F0:
    /* 25EA70 0035E9F0 66C10D0C */  jal        func_00370598
    /* 25EA74 0035E9F4 00000000 */   nop
    /* 25EA78 0035E9F8 6A000010 */  b          .L0035EBA4
    /* 25EA7C 0035E9FC 2000B0DF */   ld        $s0, 0x20($sp)
  .L0035EA00:
    /* 25EA80 0035EA00 240060AE */  sw         $zero, 0x24($s3)
    /* 25EA84 0035EA04 66C10D0C */  jal        func_00370598
    /* 25EA88 0035EA08 280060AE */   sw        $zero, 0x28($s3)
    /* 25EA8C 0035EA0C 44006282 */  lb         $v0, 0x44($s3)
    /* 25EA90 0035EA10 63005150 */  beql       $v0, $s1, .L0035EBA0
    /* 25EA94 0035EA14 020060A2 */   sb        $zero, 0x2($s3)
    /* 25EA98 0035EA18 48006282 */  lb         $v0, 0x48($s3)
    /* 25EA9C 0035EA1C 60005150 */  beql       $v0, $s1, .L0035EBA0
    /* 25EAA0 0035EA20 020060A2 */   sb        $zero, 0x2($s3)
    /* 25EAA4 0035EA24 1400628E */  lw         $v0, 0x14($s3)
    /* 25EAA8 0035EA28 05004014 */  bnez       $v0, .L0035EA40
    /* 25EAAC 0035EA2C 03000224 */   addiu     $v0, $zero, 0x3
    /* 25EAB0 0035EA30 020060A2 */  sb         $zero, 0x2($s3)
    /* 25EAB4 0035EA34 010062A2 */  sb         $v0, 0x1($s3)
    /* 25EAB8 0035EA38 59000010 */  b          .L0035EBA0
    /* 25EABC 0035EA3C 200060AE */   sw        $zero, 0x20($s3)
  .L0035EA40:
    /* 25EAC0 0035EA40 04008012 */  beqz       $s4, .L0035EA54
    /* 25EAC4 0035EA44 00000000 */   nop
    /* 25EAC8 0035EA48 0000828E */  lw         $v0, 0x0($s4)
    /* 25EACC 0035EA4C 06004054 */  bnel       $v0, $zero, .L0035EA68
    /* 25EAD0 0035EA50 2400428C */   lw        $v0, 0x24($v0)
  .L0035EA54:
    /* 25EAD4 0035EA54 1A7A0D0C */  jal        func_0035E868
    /* 25EAD8 0035EA58 020060A2 */   sb        $zero, 0x2($s3)
    /* 25EADC 0035EA5C 51000010 */  b          .L0035EBA4
    /* 25EAE0 0035EA60 2000B0DF */   ld        $s0, 0x20($sp)
    /* 25EAE4 0035EA64 00000000 */  nop
  .L0035EA68:
    /* 25EAE8 0035EA68 2D208002 */  daddu      $a0, $s4, $zero
    /* 25EAEC 0035EA6C 09F84000 */  jalr       $v0
    /* 25EAF0 0035EA70 2D280000 */   daddu     $a1, $zero, $zero
    /* 25EAF4 0035EA74 4000638E */  lw         $v1, 0x40($s3)
    /* 25EAF8 0035EA78 1C00648E */  lw         $a0, 0x1C($s3)
    /* 25EAFC 0035EA7C 23186200 */  subu       $v1, $v1, $v0
    /* 25EB00 0035EA80 2A186400 */  slt        $v1, $v1, $a0
    /* 25EB04 0035EA84 04006054 */  bnel       $v1, $zero, .L0035EA98
    /* 25EB08 0035EA88 0000838E */   lw        $v1, 0x0($s4)
    /* 25EB0C 0035EA8C 44000010 */  b          .L0035EBA0
    /* 25EB10 0035EA90 020060A2 */   sb        $zero, 0x2($s3)
    /* 25EB14 0035EA94 00000000 */  nop
  .L0035EA98:
    /* 25EB18 0035EA98 1000A727 */  addiu      $a3, $sp, 0x10
    /* 25EB1C 0035EA9C 1800668E */  lw         $a2, 0x18($s3)
    /* 25EB20 0035EAA0 2D208002 */  daddu      $a0, $s4, $zero
    /* 25EB24 0035EAA4 1800628C */  lw         $v0, 0x18($v1)
    /* 25EB28 0035EAA8 09F84000 */  jalr       $v0
    /* 25EB2C 0035EAAC 2D280000 */   daddu     $a1, $zero, $zero
    /* 25EB30 0035EAB0 3000648E */  lw         $a0, 0x30($s3)
    /* 25EB34 0035EAB4 1400A28F */  lw         $v0, 0x14($sp)
    /* 25EB38 0035EAB8 2D300000 */  daddu      $a2, $zero, $zero
    /* 25EB3C 0035EABC 5800678E */  lw         $a3, 0x58($s3)
    /* 25EB40 0035EAC0 FF074524 */  addiu      $a1, $v0, 0x7FF
    /* 25EB44 0035EAC4 00004328 */  slti       $v1, $v0, 0x0
    /* 25EB48 0035EAC8 0B10A300 */  movn       $v0, $a1, $v1
    /* 25EB4C 0035EACC 1400638E */  lw         $v1, 0x14($s3)
    /* 25EB50 0035EAD0 23208700 */  subu       $a0, $a0, $a3
    /* 25EB54 0035EAD4 C3120200 */  sra        $v0, $v0, 11
    /* 25EB58 0035EAD8 2A284400 */  slt        $a1, $v0, $a0
    /* 25EB5C 0035EADC 23186700 */  subu       $v1, $v1, $a3
    /* 25EB60 0035EAE0 0B204500 */  movn       $a0, $v0, $a1
    /* 25EB64 0035EAE4 0C00658E */  lw         $a1, 0xC($s3)
    /* 25EB68 0035EAE8 2C00708E */  lw         $s0, 0x2C($s3)
    /* 25EB6C 0035EAEC 2A108300 */  slt        $v0, $a0, $v1
    /* 25EB70 0035EAF0 0B188200 */  movn       $v1, $a0, $v0
    /* 25EB74 0035EAF4 0800648E */  lw         $a0, 0x8($s3)
    /* 25EB78 0035EAF8 2A107000 */  slt        $v0, $v1, $s0
    /* 25EB7C 0035EAFC 2128A700 */  addu       $a1, $a1, $a3
    /* 25EB80 0035EB00 C28F0D0C */  jal        func_00363F08
    /* 25EB84 0035EB04 0B806200 */   movn      $s0, $v1, $v0
    /* 25EB88 0035EB08 1000A68F */  lw         $a2, 0x10($sp)
    /* 25EB8C 0035EB0C 2D280002 */  daddu      $a1, $s0, $zero
    /* 25EB90 0035EB10 DC8F0D0C */  jal        func_00363F70
    /* 25EB94 0035EB14 0800648E */   lw        $a0, 0x8($s3)
    /* 25EB98 0035EB18 1400A48F */  lw         $a0, 0x14($sp)
    /* 25EB9C 0035EB1C 1000A38F */  lw         $v1, 0x10($sp)
    /* 25EBA0 0035EB20 280064AE */  sw         $a0, 0x28($s3)
    /* 25EBA4 0035EB24 240063AE */  sw         $v1, 0x24($s3)
    /* 25EBA8 0035EB28 1D00401C */  bgtz       $v0, .L0035EBA0
    /* 25EBAC 0035EB2C 200062AE */   sw        $v0, 0x20($s3)
    /* 25EBB0 0035EB30 0000838E */  lw         $v1, 0x0($s4)
    /* 25EBB4 0035EB34 24007026 */  addiu      $s0, $s3, 0x24
    /* 25EBB8 0035EB38 2D208002 */  daddu      $a0, $s4, $zero
    /* 25EBBC 0035EB3C 2D280000 */  daddu      $a1, $zero, $zero
    /* 25EBC0 0035EB40 1C00628C */  lw         $v0, 0x1C($v1)
    /* 25EBC4 0035EB44 09F84000 */  jalr       $v0
    /* 25EBC8 0035EB48 2D300002 */   daddu     $a2, $s0, $zero
    /* 25EBCC 0035EB4C 000000AE */  sw         $zero, 0x0($s0)
    /* 25EBD0 0035EB50 280060AE */  sw         $zero, 0x28($s3)
    /* 25EBD4 0035EB54 020060A2 */  sb         $zero, 0x2($s3)
    /* 25EBD8 0035EB58 3E900D0C */  jal        func_003640F8
    /* 25EBDC 0035EB5C 0800648E */   lw        $a0, 0x8($s3)
    /* 25EBE0 0035EB60 03000324 */  addiu      $v1, $zero, 0x3
    /* 25EBE4 0035EB64 0F004314 */  bne        $v0, $v1, .L0035EBA4
    /* 25EBE8 0035EB68 2000B0DF */   ld        $s0, 0x20($sp)
  .L0035EB6C:
    /* 25EBEC 0035EB6C 4300023C */  lui        $v0, %hi(D_0043467C)
    /* 25EBF0 0035EB70 7C46438C */  lw         $v1, %lo(D_0043467C)($v0)
    /* 25EBF4 0035EB74 0B006004 */  bltz       $v1, .L0035EBA4
    /* 25EBF8 0035EB78 2000B0DF */   ld        $s0, 0x20($sp)
    /* 25EBFC 0035EB7C 03006282 */  lb         $v0, 0x3($s3)
    /* 25EC00 0035EB80 2A104300 */  slt        $v0, $v0, $v1
    /* 25EC04 0035EB84 04004014 */  bnez       $v0, .L0035EB98
    /* 25EC08 0035EB88 03006492 */   lbu       $a0, 0x3($s3)
    /* 25EC0C 0035EB8C 04000224 */  addiu      $v0, $zero, 0x4
    /* 25EC10 0035EB90 04000010 */  b          .L0035EBA4
    /* 25EC14 0035EB94 010062A2 */   sb        $v0, 0x1($s3)
  .L0035EB98:
    /* 25EC18 0035EB98 01008224 */  addiu      $v0, $a0, 0x1
    /* 25EC1C 0035EB9C 030062A2 */  sb         $v0, 0x3($s3)
  .L0035EBA0:
    /* 25EC20 0035EBA0 2000B0DF */  ld         $s0, 0x20($sp)
  .L0035EBA4:
    /* 25EC24 0035EBA4 2800B1DF */  ld         $s1, 0x28($sp)
    /* 25EC28 0035EBA8 3000B2DF */  ld         $s2, 0x30($sp)
    /* 25EC2C 0035EBAC 3800B3DF */  ld         $s3, 0x38($sp)
    /* 25EC30 0035EBB0 4000B4DF */  ld         $s4, 0x40($sp)
    /* 25EC34 0035EBB4 4800BFDF */  ld         $ra, 0x48($sp)
    /* 25EC38 0035EBB8 0800E003 */  jr         $ra
    /* 25EC3C 0035EBBC 5000BD27 */   addiu     $sp, $sp, 0x50
.size func_0035E880, . - func_0035E880

glabel func_0035EBC0
    /* 25EC40 0035EBC0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 25EC44 0035EBC4 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25EC48 0035EBC8 2D808000 */  daddu      $s0, $a0, $zero
    /* 25EC4C 0035EBCC 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25EC50 0035EBD0 1000BFFF */  sd         $ra, 0x10($sp)
    /* 25EC54 0035EBD4 02000282 */  lb         $v0, 0x2($s0)
    /* 25EC58 0035EBD8 5E004054 */  bnel       $v0, $zero, .L0035ED54
    /* 25EC5C 0035EBDC 01000382 */   lb        $v1, 0x1($s0)
    /* 25EC60 0035EBE0 48000382 */  lb         $v1, 0x48($s0)
    /* 25EC64 0035EBE4 01000224 */  addiu      $v0, $zero, 0x1
    /* 25EC68 0035EBE8 07006254 */  bnel       $v1, $v0, .L0035EC08
    /* 25EC6C 0035EBEC 46000382 */   lb        $v1, 0x46($s0)
    /* 25EC70 0035EBF0 47000282 */  lb         $v0, 0x47($s0)
    /* 25EC74 0035EBF4 02004014 */  bnez       $v0, .L0035EC00
    /* 25EC78 0035EBF8 480000A2 */   sb        $zero, 0x48($s0)
    /* 25EC7C 0035EBFC 010003A2 */  sb         $v1, 0x1($s0)
  .L0035EC00:
    /* 25EC80 0035EC00 46000382 */  lb         $v1, 0x46($s0)
    /* 25EC84 0035EC04 01000224 */  addiu      $v0, $zero, 0x1
  .L0035EC08:
    /* 25EC88 0035EC08 08006214 */  bne        $v1, $v0, .L0035EC2C
    /* 25EC8C 0035EC0C 00000000 */   nop
    /* 25EC90 0035EC10 0800048E */  lw         $a0, 0x8($s0)
    /* 25EC94 0035EC14 04008050 */  beql       $a0, $zero, .L0035EC28
    /* 25EC98 0035EC18 460000A2 */   sb        $zero, 0x46($s0)
    /* 25EC9C 0035EC1C 8A8F0D0C */  jal        func_00363E28
    /* 25ECA0 0035EC20 080000AE */   sw        $zero, 0x8($s0)
    /* 25ECA4 0035EC24 460000A2 */  sb         $zero, 0x46($s0)
  .L0035EC28:
    /* 25ECA8 0035EC28 490000A2 */  sb         $zero, 0x49($s0)
  .L0035EC2C:
    /* 25ECAC 0035EC2C 60C10D0C */  jal        func_00370580
    /* 25ECB0 0035EC30 00000000 */   nop
    /* 25ECB4 0035EC34 45000382 */  lb         $v1, 0x45($s0)
    /* 25ECB8 0035EC38 01000224 */  addiu      $v0, $zero, 0x1
    /* 25ECBC 0035EC3C 3E006214 */  bne        $v1, $v0, .L0035ED38
    /* 25ECC0 0035EC40 00000000 */   nop
    /* 25ECC4 0035EC44 66C10D0C */  jal        func_00370598
    /* 25ECC8 0035EC48 490003A2 */   sb        $v1, 0x49($s0)
    /* 25ECCC 0035EC4C 0800028E */  lw         $v0, 0x8($s0)
    /* 25ECD0 0035EC50 3C004054 */  bnel       $v0, $zero, .L0035ED44
    /* 25ECD4 0035EC54 47000382 */   lb        $v1, 0x47($s0)
    /* 25ECD8 0035EC58 5000048E */  lw         $a0, 0x50($s0)
    /* 25ECDC 0035EC5C 2D300000 */  daddu      $a2, $zero, $zero
    /* 25ECE0 0035EC60 B68E0D0C */  jal        func_00363AD8
    /* 25ECE4 0035EC64 5400058E */   lw        $a1, 0x54($s0)
    /* 25ECE8 0035EC68 0B004014 */  bnez       $v0, .L0035EC98
    /* 25ECEC 0035EC6C 080002AE */   sw        $v0, 0x8($s0)
    /* 25ECF0 0035EC70 4E00043C */  lui        $a0, %hi(D_004DA838)
    /* 25ECF4 0035EC74 5000058E */  lw         $a1, 0x50($s0)
    /* 25ECF8 0035EC78 5A620D0C */  jal        func_00358968
    /* 25ECFC 0035EC7C 38A88424 */   addiu     $a0, $a0, %lo(D_004DA838)
    /* 25ED00 0035EC80 04000224 */  addiu      $v0, $zero, 0x4
    /* 25ED04 0035EC84 010002A2 */  sb         $v0, 0x1($s0)
    /* 25ED08 0035EC88 450000A2 */  sb         $zero, 0x45($s0)
    /* 25ED0C 0035EC8C 3A000010 */  b          .L0035ED78
    /* 25ED10 0035EC90 490000A2 */   sb        $zero, 0x49($s0)
    /* 25ED14 0035EC94 00000000 */  nop
  .L0035EC98:
    /* 25ED18 0035EC98 2D280000 */  daddu      $a1, $zero, $zero
    /* 25ED1C 0035EC9C 02000624 */  addiu      $a2, $zero, 0x2
    /* 25ED20 0035ECA0 C28F0D0C */  jal        func_00363F08
    /* 25ED24 0035ECA4 2D204000 */   daddu     $a0, $v0, $zero
    /* 25ED28 0035ECA8 A88F0D0C */  jal        func_00363EA0
    /* 25ED2C 0035ECAC 0800048E */   lw        $a0, 0x8($s0)
    /* 25ED30 0035ECB0 0800048E */  lw         $a0, 0x8($s0)
    /* 25ED34 0035ECB4 2D280000 */  daddu      $a1, $zero, $zero
    /* 25ED38 0035ECB8 2D300000 */  daddu      $a2, $zero, $zero
    /* 25ED3C 0035ECBC C28F0D0C */  jal        func_00363F08
    /* 25ED40 0035ECC0 2D884000 */   daddu     $s1, $v0, $zero
    /* 25ED44 0035ECC4 FF7F023C */  lui        $v0, (0x7FFFF800 >> 16)
    /* 25ED48 0035ECC8 1000038E */  lw         $v1, 0x10($s0)
    /* 25ED4C 0035ECCC 00F84234 */  ori        $v0, $v0, (0x7FFFF800 & 0xFFFF)
    /* 25ED50 0035ECD0 05006214 */  bne        $v1, $v0, .L0035ECE8
    /* 25ED54 0035ECD4 C0221100 */   sll       $a0, $s1, 11
    /* 25ED58 0035ECD8 100004AE */  sw         $a0, 0x10($s0)
    /* 25ED5C 0035ECDC 11000010 */  b          .L0035ED24
    /* 25ED60 0035ECE0 140011AE */   sw        $s1, 0x14($s0)
    /* 25ED64 0035ECE4 00000000 */  nop
  .L0035ECE8:
    /* 25ED68 0035ECE8 0C00038E */  lw         $v1, 0xC($s0)
    /* 25ED6C 0035ECEC 2A102302 */  slt        $v0, $s1, $v1
    /* 25ED70 0035ECF0 04004050 */  beql       $v0, $zero, .L0035ED04
    /* 25ED74 0035ECF4 1400028E */   lw        $v0, 0x14($s0)
    /* 25ED78 0035ECF8 0C0011AE */  sw         $s1, 0xC($s0)
    /* 25ED7C 0035ECFC 2D182002 */  daddu      $v1, $s1, $zero
    /* 25ED80 0035ED00 1400028E */  lw         $v0, 0x14($s0)
  .L0035ED04:
    /* 25ED84 0035ED04 21104300 */  addu       $v0, $v0, $v1
    /* 25ED88 0035ED08 2A102202 */  slt        $v0, $s1, $v0
    /* 25ED8C 0035ED0C 06004010 */  beqz       $v0, .L0035ED28
    /* 25ED90 0035ED10 2D200002 */   daddu     $a0, $s0, $zero
    /* 25ED94 0035ED14 23102302 */  subu       $v0, $s1, $v1
    /* 25ED98 0035ED18 C01A0200 */  sll        $v1, $v0, 11
    /* 25ED9C 0035ED1C 140002AE */  sw         $v0, 0x14($s0)
    /* 25EDA0 0035ED20 100003AE */  sw         $v1, 0x10($s0)
  .L0035ED24:
    /* 25EDA4 0035ED24 2D200002 */  daddu      $a0, $s0, $zero
  .L0035ED28:
    /* 25EDA8 0035ED28 A4790D0C */  jal        func_0035E690
    /* 25EDAC 0035ED2C 2D280000 */   daddu     $a1, $zero, $zero
    /* 25EDB0 0035ED30 03000010 */  b          .L0035ED40
    /* 25EDB4 0035ED34 450000A2 */   sb        $zero, 0x45($s0)
  .L0035ED38:
    /* 25EDB8 0035ED38 66C10D0C */  jal        func_00370598
    /* 25EDBC 0035ED3C 00000000 */   nop
  .L0035ED40:
    /* 25EDC0 0035ED40 47000382 */  lb         $v1, 0x47($s0)
  .L0035ED44:
    /* 25EDC4 0035ED44 01000224 */  addiu      $v0, $zero, 0x1
    /* 25EDC8 0035ED48 01006250 */  beql       $v1, $v0, .L0035ED50
    /* 25EDCC 0035ED4C 470000A2 */   sb        $zero, 0x47($s0)
  .L0035ED50:
    /* 25EDD0 0035ED50 01000382 */  lb         $v1, 0x1($s0)
  .L0035ED54:
    /* 25EDD4 0035ED54 02000224 */  addiu      $v0, $zero, 0x2
    /* 25EDD8 0035ED58 08006254 */  bnel       $v1, $v0, .L0035ED7C
    /* 25EDDC 0035ED5C 0000B0DF */   ld        $s0, 0x0($sp)
    /* 25EDE0 0035ED60 49000382 */  lb         $v1, 0x49($s0)
    /* 25EDE4 0035ED64 01000224 */  addiu      $v0, $zero, 0x1
    /* 25EDE8 0035ED68 04006254 */  bnel       $v1, $v0, .L0035ED7C
    /* 25EDEC 0035ED6C 0000B0DF */   ld        $s0, 0x0($sp)
    /* 25EDF0 0035ED70 207A0D0C */  jal        func_0035E880
    /* 25EDF4 0035ED74 2D200002 */   daddu     $a0, $s0, $zero
  .L0035ED78:
    /* 25EDF8 0035ED78 0000B0DF */  ld         $s0, 0x0($sp)
  .L0035ED7C:
    /* 25EDFC 0035ED7C 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25EE00 0035ED80 1000BFDF */  ld         $ra, 0x10($sp)
    /* 25EE04 0035ED84 0800E003 */  jr         $ra
    /* 25EE08 0035ED88 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 25EE0C 0035ED8C 00000000 */  nop
.size func_0035EBC0, . - func_0035EBC0

glabel func_0035ED90
    /* 25EE10 0035ED90 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 25EE14 0035ED94 1800B3FF */  sd         $s3, 0x18($sp)
    /* 25EE18 0035ED98 4300133C */  lui        $s3, %hi(D_00434678)
    /* 25EE1C 0035ED9C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25EE20 0035EDA0 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25EE24 0035EDA4 1000B2FF */  sd         $s2, 0x10($sp)
    /* 25EE28 0035EDA8 2000BFFF */  sd         $ra, 0x20($sp)
    /* 25EE2C 0035EDAC 10C40D0C */  jal        func_00371040
    /* 25EE30 0035EDB0 78466426 */   addiu     $a0, $s3, %lo(D_00434678)
    /* 25EE34 0035EDB4 0E004010 */  beqz       $v0, .L0035EDF0
    /* 25EE38 0035EDB8 4300023C */   lui       $v0, %hi(D_00434688)
    /* 25EE3C 0035EDBC 01001224 */  addiu      $s2, $zero, 0x1
    /* 25EE40 0035EDC0 88465024 */  addiu      $s0, $v0, %lo(D_00434688)
    /* 25EE44 0035EDC4 27001124 */  addiu      $s1, $zero, 0x27
  .L0035EDC8:
    /* 25EE48 0035EDC8 00000282 */  lb         $v0, 0x0($s0)
    /* 25EE4C 0035EDCC 04005254 */  bnel       $v0, $s2, .L0035EDE0
    /* 25EE50 0035EDD0 FFFF3126 */   addiu     $s1, $s1, -0x1
    /* 25EE54 0035EDD4 F07A0D0C */  jal        func_0035EBC0
    /* 25EE58 0035EDD8 2D200002 */   daddu     $a0, $s0, $zero
    /* 25EE5C 0035EDDC FFFF3126 */  addiu      $s1, $s1, -0x1
  .L0035EDE0:
    /* 25EE60 0035EDE0 F9FF2106 */  bgez       $s1, .L0035EDC8
    /* 25EE64 0035EDE4 60001026 */   addiu     $s0, $s0, 0x60
    /* 25EE68 0035EDE8 78466226 */  addiu      $v0, $s3, %lo(D_00434678)
    /* 25EE6C 0035EDEC 000040AC */  sw         $zero, 0x0($v0)
  .L0035EDF0:
    /* 25EE70 0035EDF0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25EE74 0035EDF4 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25EE78 0035EDF8 1000B2DF */  ld         $s2, 0x10($sp)
    /* 25EE7C 0035EDFC 1800B3DF */  ld         $s3, 0x18($sp)
    /* 25EE80 0035EE00 2000BFDF */  ld         $ra, 0x20($sp)
    /* 25EE84 0035EE04 0800E003 */  jr         $ra
    /* 25EE88 0035EE08 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 25EE8C 0035EE0C 00000000 */  nop
.size func_0035ED90, . - func_0035ED90

glabel func_0035EE10
    /* 25EE90 0035EE10 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25EE94 0035EE14 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25EE98 0035EE18 0800BFFF */  sd         $ra, 0x8($sp)
    /* 25EE9C 0035EE1C AC790D0C */  jal        func_0035E6B0
    /* 25EEA0 0035EE20 2D80A000 */   daddu     $s0, $a1, $zero
    /* 25EEA4 0035EE24 000002AE */  sw         $v0, 0x0($s0)
    /* 25EEA8 0035EE28 01000224 */  addiu      $v0, $zero, 0x1
    /* 25EEAC 0035EE2C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25EEB0 0035EE30 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25EEB4 0035EE34 0800E003 */  jr         $ra
    /* 25EEB8 0035EE38 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25EEBC 0035EE3C 00000000 */  nop
.size func_0035EE10, . - func_0035EE10

glabel func_0035EE40
    /* 25EEC0 0035EE40 1C00838C */  lw         $v1, 0x1C($a0)
    /* 25EEC4 0035EE44 01000224 */  addiu      $v0, $zero, 0x1
    /* 25EEC8 0035EE48 0000A3AC */  sw         $v1, 0x0($a1)
    /* 25EECC 0035EE4C 1800858C */  lw         $a1, 0x18($a0)
    /* 25EED0 0035EE50 0800E003 */  jr         $ra
    /* 25EED4 0035EE54 0000C5AC */   sw        $a1, 0x0($a2)
.size func_0035EE40, . - func_0035EE40

glabel func_0035EE58
    /* 25EED8 0035EE58 0800E003 */  jr         $ra
    /* 25EEDC 0035EE5C 0400828C */   lw        $v0, 0x4($a0)
.size func_0035EE58, . - func_0035EE58

glabel func_0035EE60
    /* 25EEE0 0035EE60 01000224 */  addiu      $v0, $zero, 0x1
    /* 25EEE4 0035EE64 180086AC */  sw         $a2, 0x18($a0)
    /* 25EEE8 0035EE68 0800E003 */  jr         $ra
    /* 25EEEC 0035EE6C 1C0085AC */   sw        $a1, 0x1C($a0)
.size func_0035EE60, . - func_0035EE60

glabel func_0035EE70
    /* 25EEF0 0035EE70 2C0085AC */  sw         $a1, 0x2C($a0)
    /* 25EEF4 0035EE74 0800E003 */  jr         $ra
    /* 25EEF8 0035EE78 01000224 */   addiu     $v0, $zero, 0x1
    /* 25EEFC 0035EE7C 00000000 */  nop
.size func_0035EE70, . - func_0035EE70

glabel func_0035EE80
    /* 25EF00 0035EE80 0800E003 */  jr         $ra
    /* 25EF04 0035EE84 00000000 */   nop
.size func_0035EE80, . - func_0035EE80

glabel func_0035EE88
    /* 25EF08 0035EE88 0800E003 */  jr         $ra
    /* 25EF0C 0035EE8C 1000828C */   lw        $v0, 0x10($a0)
.size func_0035EE88, . - func_0035EE88

glabel func_0035EE90
    /* 25EF10 0035EE90 0800E003 */  jr         $ra
    /* 25EF14 0035EE94 1400828C */   lw        $v0, 0x14($a0)
.size func_0035EE90, . - func_0035EE90

glabel func_0035EE98
    /* 25EF18 0035EE98 0800E003 */  jr         $ra
    /* 25EF1C 0035EE9C 440085A0 */   sb        $a1, 0x44($a0)
.size func_0035EE98, . - func_0035EE98

glabel func_0035EEA0
    /* 25EF20 0035EEA0 0800E003 */  jr         $ra
    /* 25EF24 0035EEA4 44008280 */   lb        $v0, 0x44($a0)
.size func_0035EEA0, . - func_0035EEA0

glabel func_0035EEA8
    /* 25EF28 0035EEA8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25EF2C 0035EEAC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25EF30 0035EEB0 2D80A000 */  daddu      $s0, $a1, $zero
    /* 25EF34 0035EEB4 0800BFFF */  sd         $ra, 0x8($sp)
    /* 25EF38 0035EEB8 3E900D0C */  jal        func_003640F8
    /* 25EF3C 0035EEBC 0800848C */   lw        $a0, 0x8($a0)
    /* 25EF40 0035EEC0 000002AE */  sw         $v0, 0x0($s0)
    /* 25EF44 0035EEC4 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25EF48 0035EEC8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25EF4C 0035EECC 0800E003 */  jr         $ra
    /* 25EF50 0035EED0 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25EF54 0035EED4 00000000 */  nop
.size func_0035EEA8, . - func_0035EEA8
