.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035EED8
    /* 25EF58 0035EED8 0000A0AC */  sw         $zero, 0x0($a1)
    /* 25EF5C 0035EEDC 0800E003 */  jr         $ra
    /* 25EF60 0035EEE0 01000224 */   addiu     $v0, $zero, 0x1
    /* 25EF64 0035EEE4 00000000 */  nop
.size func_0035EED8, . - func_0035EED8
