.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035F358
    /* 25F3D8 0035F358 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25F3DC 0035F35C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25F3E0 0035F360 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25F3E4 0035F364 24A40D08 */  j          func_00369090
    /* 25F3E8 0035F368 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25F3EC 0035F36C 00000000 */  nop
.size func_0035F358, . - func_0035F358

glabel func_0035F370
    /* 25F3F0 0035F370 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25F3F4 0035F374 2D20A000 */  daddu      $a0, $a1, $zero
    /* 25F3F8 0035F378 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25F3FC 0035F37C 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25F400 0035F380 44620D08 */  j          func_00358910
    /* 25F404 0035F384 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0035F370, . - func_0035F370

glabel func_0035F388
    /* 25F408 0035F388 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 25F40C 0035F38C 3600023C */  lui        $v0, %hi(func_0035F370)
    /* 25F410 0035F390 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25F414 0035F394 4E00103C */  lui        $s0, %hi(D_004DA870)
    /* 25F418 0035F398 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25F41C 0035F39C 2D888000 */  daddu      $s1, $a0, $zero
    /* 25F420 0035F3A0 2D280000 */  daddu      $a1, $zero, $zero
    /* 25F424 0035F3A4 1000BFFF */  sd         $ra, 0x10($sp)
    /* 25F428 0035F3A8 0A930D0C */  jal        func_00364C28
    /* 25F42C 0035F3AC 70F34424 */   addiu     $a0, $v0, %lo(func_0035F370)
    /* 25F430 0035F3B0 70A81026 */  addiu      $s0, $s0, %lo(D_004DA870)
    /* 25F434 0035F3B4 3700053C */  lui        $a1, %hi(func_00369108)
    /* 25F438 0035F3B8 0891A524 */  addiu      $a1, $a1, %lo(func_00369108)
    /* 25F43C 0035F3BC 2D200002 */  daddu      $a0, $s0, $zero
    /* 25F440 0035F3C0 688D0D0C */  jal        func_003635A0
    /* 25F444 0035F3C4 2D300000 */   daddu     $a2, $zero, $zero
    /* 25F448 0035F3C8 368E0D0C */  jal        func_003638D8
    /* 25F44C 0035F3CC 2D200002 */   daddu     $a0, $s0, $zero
    /* 25F450 0035F3D0 1D002012 */  beqz       $s1, .L0035F448
    /* 25F454 0035F3D4 2D200000 */   daddu     $a0, $zero, $zero
    /* 25F458 0035F3D8 E4AA0D0C */  jal        func_0036AB90
    /* 25F45C 0035F3DC 0400248E */   lw        $a0, 0x4($s1)
    /* 25F460 0035F3E0 F0AA0D0C */  jal        func_0036ABC0
    /* 25F464 0035F3E4 0000248E */   lw        $a0, 0x0($s1)
    /* 25F468 0035F3E8 0800228E */  lw         $v0, 0x8($s1)
    /* 25F46C 0035F3EC 06004014 */  bnez       $v0, .L0035F408
    /* 25F470 0035F3F0 01000424 */   addiu     $a0, $zero, 0x1
    /* 25F474 0035F3F4 2AA40D0C */  jal        func_003690A8
    /* 25F478 0035F3F8 2D200000 */   daddu     $a0, $zero, $zero
    /* 25F47C 0035F3FC 05000010 */  b          .L0035F414
    /* 25F480 0035F400 0C00228E */   lw        $v0, 0xC($s1)
    /* 25F484 0035F404 00000000 */  nop
  .L0035F408:
    /* 25F488 0035F408 2AA40D0C */  jal        func_003690A8
    /* 25F48C 0035F40C 00000000 */   nop
    /* 25F490 0035F410 0C00228E */  lw         $v0, 0xC($s1)
  .L0035F414:
    /* 25F494 0035F414 06004014 */  bnez       $v0, .L0035F430
    /* 25F498 0035F418 0000B0DF */   ld        $s0, 0x0($sp)
    /* 25F49C 0035F41C 2D200000 */  daddu      $a0, $zero, $zero
    /* 25F4A0 0035F420 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25F4A4 0035F424 1000BFDF */  ld         $ra, 0x10($sp)
    /* 25F4A8 0035F428 36A40D08 */  j          func_003690D8
    /* 25F4AC 0035F42C 2000BD27 */   addiu     $sp, $sp, 0x20
  .L0035F430:
    /* 25F4B0 0035F430 01000424 */  addiu      $a0, $zero, 0x1
    /* 25F4B4 0035F434 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25F4B8 0035F438 1000BFDF */  ld         $ra, 0x10($sp)
    /* 25F4BC 0035F43C 36A40D08 */  j          func_003690D8
    /* 25F4C0 0035F440 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 25F4C4 0035F444 00000000 */  nop
  .L0035F448:
    /* 25F4C8 0035F448 E4AA0D0C */  jal        func_0036AB90
    /* 25F4CC 0035F44C 00000000 */   nop
    /* 25F4D0 0035F450 F0AA0D0C */  jal        func_0036ABC0
    /* 25F4D4 0035F454 2D200000 */   daddu     $a0, $zero, $zero
    /* 25F4D8 0035F458 2AA40D0C */  jal        func_003690A8
    /* 25F4DC 0035F45C 2D200000 */   daddu     $a0, $zero, $zero
    /* 25F4E0 0035F460 2D200000 */  daddu      $a0, $zero, $zero
    /* 25F4E4 0035F464 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25F4E8 0035F468 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25F4EC 0035F46C 1000BFDF */  ld         $ra, 0x10($sp)
    /* 25F4F0 0035F470 36A40D08 */  j          func_003690D8
    /* 25F4F4 0035F474 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_0035F388, . - func_0035F388

glabel func_0035F478
    /* 25F4F8 0035F478 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25F4FC 0035F47C 2D108000 */  daddu      $v0, $a0, $zero
    /* 25F500 0035F480 09004010 */  beqz       $v0, .L0035F4A8
    /* 25F504 0035F484 0000BFFF */   sd        $ra, 0x0($sp)
    /* 25F508 0035F488 0400478C */  lw         $a3, 0x4($v0)
    /* 25F50C 0035F48C 0000448C */  lw         $a0, 0x0($v0)
    /* 25F510 0035F490 0800458C */  lw         $a1, 0x8($v0)
    /* 25F514 0035F494 78AA0D0C */  jal        func_0036A9E0
    /* 25F518 0035F498 0C00468C */   lw        $a2, 0xC($v0)
    /* 25F51C 0035F49C 07000010 */  b          .L0035F4BC
    /* 25F520 0035F4A0 0000BFDF */   ld        $ra, 0x0($sp)
    /* 25F524 0035F4A4 00000000 */  nop
  .L0035F4A8:
    /* 25F528 0035F4A8 2D280000 */  daddu      $a1, $zero, $zero
    /* 25F52C 0035F4AC 2D300000 */  daddu      $a2, $zero, $zero
    /* 25F530 0035F4B0 78AA0D0C */  jal        func_0036A9E0
    /* 25F534 0035F4B4 2D380000 */   daddu     $a3, $zero, $zero
    /* 25F538 0035F4B8 0000BFDF */  ld         $ra, 0x0($sp)
  .L0035F4BC:
    /* 25F53C 0035F4BC 0800E003 */  jr         $ra
    /* 25F540 0035F4C0 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25F544 0035F4C4 00000000 */  nop
.size func_0035F478, . - func_0035F478
