.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035F328
    /* 25F3A8 0035F328 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25F3AC 0035F32C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25F3B0 0035F330 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25F3B4 0035F334 80A00D08 */  j          func_00368200
    /* 25F3B8 0035F338 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25F3BC 0035F33C 00000000 */  nop
.size func_0035F328, . - func_0035F328

glabel func_0035F340
    /* 25F3C0 0035F340 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25F3C4 0035F344 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25F3C8 0035F348 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25F3CC 0035F34C 88A00D08 */  j          func_00368220
    /* 25F3D0 0035F350 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25F3D4 0035F354 00000000 */  nop
.size func_0035F340, . - func_0035F340
