.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0035F4C8
    /* 25F548 0035F4C8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25F54C 0035F4CC 0000BFFF */  sd         $ra, 0x0($sp)
    /* 25F550 0035F4D0 0000BFDF */  ld         $ra, 0x0($sp)
    /* 25F554 0035F4D4 DAAA0D08 */  j          func_0036AB68
    /* 25F558 0035F4D8 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25F55C 0035F4DC 00000000 */  nop
.size func_0035F4C8, . - func_0035F4C8

glabel func_0035F4E0
    /* 25F560 0035F4E0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 25F564 0035F4E4 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25F568 0035F4E8 2D808000 */  daddu      $s0, $a0, $zero
    /* 25F56C 0035F4EC 08000012 */  beqz       $s0, .L0035F510
    /* 25F570 0035F4F0 0800BFFF */   sd        $ra, 0x8($sp)
    /* 25F574 0035F4F4 E4AA0D0C */  jal        func_0036AB90
    /* 25F578 0035F4F8 0400048E */   lw        $a0, 0x4($s0)
    /* 25F57C 0035F4FC 0000048E */  lw         $a0, 0x0($s0)
    /* 25F580 0035F500 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25F584 0035F504 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25F588 0035F508 F0AA0D08 */  j          func_0036ABC0
    /* 25F58C 0035F50C 1000BD27 */   addiu     $sp, $sp, 0x10
  .L0035F510:
    /* 25F590 0035F510 E4AA0D0C */  jal        func_0036AB90
    /* 25F594 0035F514 00000000 */   nop
    /* 25F598 0035F518 2D200000 */  daddu      $a0, $zero, $zero
    /* 25F59C 0035F51C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25F5A0 0035F520 0800BFDF */  ld         $ra, 0x8($sp)
    /* 25F5A4 0035F524 F0AA0D08 */  j          func_0036ABC0
    /* 25F5A8 0035F528 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 25F5AC 0035F52C 00000000 */  nop
.size func_0035F4E0, . - func_0035F4E0

glabel func_0035F530
    /* 25F5B0 0035F530 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 25F5B4 0035F534 2D280000 */  daddu      $a1, $zero, $zero
    /* 25F5B8 0035F538 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25F5BC 0035F53C 1000B2FF */  sd         $s2, 0x10($sp)
    /* 25F5C0 0035F540 1800B3FF */  sd         $s3, 0x18($sp)
    /* 25F5C4 0035F544 2000B4FF */  sd         $s4, 0x20($sp)
    /* 25F5C8 0035F548 2DA08000 */  daddu      $s4, $a0, $zero
    /* 25F5CC 0035F54C 2800BFFF */  sd         $ra, 0x28($sp)
    /* 25F5D0 0035F550 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25F5D4 0035F554 0C00908E */  lw         $s0, 0xC($s4)
    /* 25F5D8 0035F558 24B80D0C */  jal        func_0036E090
    /* 25F5DC 0035F55C 2D200002 */   daddu     $a0, $s0, $zero
    /* 25F5E0 0035F560 2D200002 */  daddu      $a0, $s0, $zero
    /* 25F5E4 0035F564 2D280000 */  daddu      $a1, $zero, $zero
    /* 25F5E8 0035F568 1EB80D0C */  jal        func_0036E078
    /* 25F5EC 0035F56C 2D884000 */   daddu     $s1, $v0, $zero
    /* 25F5F0 0035F570 01000524 */  addiu      $a1, $zero, 0x1
    /* 25F5F4 0035F574 2D804000 */  daddu      $s0, $v0, $zero
    /* 25F5F8 0035F578 0000038E */  lw         $v1, 0x0($s0)
    /* 25F5FC 0035F57C 2400628C */  lw         $v0, 0x24($v1)
    /* 25F600 0035F580 09F84000 */  jalr       $v0
    /* 25F604 0035F584 2D200002 */   daddu     $a0, $s0, $zero
    /* 25F608 0035F588 0000038E */  lw         $v1, 0x0($s0)
    /* 25F60C 0035F58C 2D904000 */  daddu      $s2, $v0, $zero
    /* 25F610 0035F590 2D200002 */  daddu      $a0, $s0, $zero
    /* 25F614 0035F594 2400628C */  lw         $v0, 0x24($v1)
    /* 25F618 0035F598 09F84000 */  jalr       $v0
    /* 25F61C 0035F59C 2D280000 */   daddu     $a1, $zero, $zero
    /* 25F620 0035F5A0 2D202002 */  daddu      $a0, $s1, $zero
    /* 25F624 0035F5A4 01000524 */  addiu      $a1, $zero, 0x1
    /* 25F628 0035F5A8 20BF0D0C */  jal        func_0036FC80
    /* 25F62C 0035F5AC 2D984000 */   daddu     $s3, $v0, $zero
    /* 25F630 0035F5B0 2D202002 */  daddu      $a0, $s1, $zero
    /* 25F634 0035F5B4 2D280000 */  daddu      $a1, $zero, $zero
    /* 25F638 0035F5B8 20BF0D0C */  jal        func_0036FC80
    /* 25F63C 0035F5BC 2D804000 */   daddu     $s0, $v0, $zero
    /* 25F640 0035F5C0 4E00043C */  lui        $a0, %hi(D_4DA878)
    /* 25F644 0035F5C4 21385302 */  addu       $a3, $s2, $s3
    /* 25F648 0035F5C8 2D284002 */  daddu      $a1, $s2, $zero
    /* 25F64C 0035F5CC 2D306002 */  daddu      $a2, $s3, $zero
    /* 25F650 0035F5D0 78A88424 */  addiu      $a0, $a0, %lo(D_4DA878)
    /* 25F654 0035F5D4 7214040C */  jal        func_001051C8
    /* 25F658 0035F5D8 2D884000 */   daddu     $s1, $v0, $zero
    /* 25F65C 0035F5DC 4E00043C */  lui        $a0, %hi(D_4DA898)
    /* 25F660 0035F5E0 21381102 */  addu       $a3, $s0, $s1
    /* 25F664 0035F5E4 2D280002 */  daddu      $a1, $s0, $zero
    /* 25F668 0035F5E8 21801302 */  addu       $s0, $s0, $s3
    /* 25F66C 0035F5EC 2D302002 */  daddu      $a2, $s1, $zero
    /* 25F670 0035F5F0 7214040C */  jal        func_001051C8
    /* 25F674 0035F5F4 98A88424 */   addiu     $a0, $a0, %lo(D_4DA898)
    /* 25F678 0035F5F8 4E00043C */  lui        $a0, %hi(D_4DA8B8)
    /* 25F67C 0035F5FC 21905102 */  addu       $s2, $s2, $s1
    /* 25F680 0035F600 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25F684 0035F604 21305002 */  addu       $a2, $s2, $s0
    /* 25F688 0035F608 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25F68C 0035F60C 01008582 */  lb         $a1, 0x1($s4)
    /* 25F690 0035F610 B8A88424 */  addiu      $a0, $a0, %lo(D_4DA8B8)
    /* 25F694 0035F614 1000B2DF */  ld         $s2, 0x10($sp)
    /* 25F698 0035F618 1800B3DF */  ld         $s3, 0x18($sp)
    /* 25F69C 0035F61C 2000B4DF */  ld         $s4, 0x20($sp)
    /* 25F6A0 0035F620 2800BFDF */  ld         $ra, 0x28($sp)
    /* 25F6A4 0035F624 72140408 */  j          func_001051C8
    /* 25F6A8 0035F628 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 25F6AC 0035F62C 00000000 */  nop
.size func_0035F530, . - func_0035F530

glabel func_0035F630
    /* 25F6B0 0035F630 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 25F6B4 0035F634 3F00A224 */  addiu      $v0, $a1, 0x3F
    /* 25F6B8 0035F638 C0FF0324 */  addiu      $v1, $zero, -0x40
    /* 25F6BC 0035F63C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 25F6C0 0035F640 24804300 */  and        $s0, $v0, $v1
    /* 25F6C4 0035F644 1000B2FF */  sd         $s2, 0x10($sp)
    /* 25F6C8 0035F648 23100502 */  subu       $v0, $s0, $a1
    /* 25F6CC 0035F64C 0800B1FF */  sd         $s1, 0x8($sp)
    /* 25F6D0 0035F650 1800B3FF */  sd         $s3, 0x18($sp)
    /* 25F6D4 0035F654 2390C200 */  subu       $s2, $a2, $v0
    /* 25F6D8 0035F658 05008004 */  bltz       $a0, .L0035F670
    /* 25F6DC 0035F65C 2000BFFF */   sd        $ra, 0x20($sp)
    /* 25F6E0 0035F660 0400A050 */  beql       $a1, $zero, .L0035F674
    /* 25F6E4 0035F664 4E00043C */   lui       $a0, %hi(D_4DA8D0)
    /* 25F6E8 0035F668 0700C104 */  bgez       $a2, .L0035F688
    /* 25F6EC 0035F66C 4300063C */   lui       $a2, %hi(D_42B6E0)
  .L0035F670:
    /* 25F6F0 0035F670 4E00043C */  lui        $a0, %hi(D_4DA8D0)
  .L0035F674:
    /* 25F6F4 0035F674 44620D0C */  jal        func_00358910
    /* 25F6F8 0035F678 D0A88424 */   addiu     $a0, $a0, %lo(D_4DA8D0)
    /* 25F6FC 0035F67C AA000010 */  b          .L0035F928
    /* 25F700 0035F680 2D100000 */   daddu     $v0, $zero, $zero
    /* 25F704 0035F684 00000000 */  nop
  .L0035F688:
    /* 25F708 0035F688 01001324 */  addiu      $s3, $zero, 0x1
    /* 25F70C 0035F68C E0B6C524 */  addiu      $a1, $a2, %lo(D_42B6E0)
    /* 25F710 0035F690 04008238 */  xori       $v0, $a0, 0x4
    /* 25F714 0035F694 0000A380 */  lb         $v1, 0x0($a1)
    /* 25F718 0035F698 0B988200 */  movn       $s3, $a0, $v0
    /* 25F71C 0035F69C 0D006010 */  beqz       $v1, .L0035F6D4
    /* 25F720 0035F6A0 2D380000 */   daddu     $a3, $zero, $zero
    /* 25F724 0035F6A4 2D18A000 */  daddu      $v1, $a1, $zero
    /* 25F728 0035F6A8 0100E724 */  addiu      $a3, $a3, 0x1
    /* 25F72C 0035F6AC 00000000 */  nop
  .L0035F6B0:
    /* 25F730 0035F6B0 1000E228 */  slti       $v0, $a3, 0x10
    /* 25F734 0035F6B4 07004010 */  beqz       $v0, .L0035F6D4
    /* 25F738 0035F6B8 C4006324 */   addiu     $v1, $v1, 0xC4
    /* 25F73C 0035F6BC 00006280 */  lb         $v0, 0x0($v1)
    /* 25F740 0035F6C0 00000000 */  nop
    /* 25F744 0035F6C4 00000000 */  nop
    /* 25F748 0035F6C8 00000000 */  nop
    /* 25F74C 0035F6CC F8FF4054 */  bnel       $v0, $zero, .L0035F6B0
    /* 25F750 0035F6D0 0100E724 */   addiu     $a3, $a3, 0x1
  .L0035F6D4:
    /* 25F754 0035F6D4 10000324 */  addiu      $v1, $zero, 0x10
    /* 25F758 0035F6D8 9300E310 */  beq        $a3, $v1, .L0035F928
    /* 25F75C 0035F6DC 2D100000 */   daddu     $v0, $zero, $zero
    /* 25F760 0035F6E0 40100700 */  sll        $v0, $a3, 1
    /* 25F764 0035F6E4 E0B6C324 */  addiu      $v1, $a2, %lo(D_42B6E0)
    /* 25F768 0035F6E8 21104700 */  addu       $v0, $v0, $a3
    /* 25F76C 0035F6EC 2D280000 */  daddu      $a1, $zero, $zero
    /* 25F770 0035F6F0 00110200 */  sll        $v0, $v0, 4
    /* 25F774 0035F6F4 C4000624 */  addiu      $a2, $zero, 0xC4
    /* 25F778 0035F6F8 21104700 */  addu       $v0, $v0, $a3
    /* 25F77C 0035F6FC 80100200 */  sll        $v0, $v0, 2
    /* 25F780 0035F700 21884300 */  addu       $s1, $v0, $v1
    /* 25F784 0035F704 84D40D0C */  jal        func_00375210
    /* 25F788 0035F708 2D202002 */   daddu     $a0, $s1, $zero
    /* 25F78C 0035F70C 030033A2 */  sb         $s3, 0x3($s1)
    /* 25F790 0035F710 80111300 */  sll        $v0, $s3, 6
    /* 25F794 0035F714 24000A24 */  addiu      $t2, $zero, 0x24
    /* 25F798 0035F718 21105300 */  addu       $v0, $v0, $s3
    /* 25F79C 0035F71C 00200824 */  addiu      $t0, $zero, 0x2000
    /* 25F7A0 0035F720 80100200 */  sll        $v0, $v0, 2
    /* 25F7A4 0035F724 60200924 */  addiu      $t1, $zero, 0x2060
    /* 25F7A8 0035F728 23105300 */  subu       $v0, $v0, $s3
    /* 25F7AC 0035F72C 2C0030AE */  sw         $s0, 0x2C($s1)
    /* 25F7B0 0035F730 80110200 */  sll        $v0, $v0, 6
    /* 25F7B4 0035F734 300028AE */  sw         $t0, 0x30($s1)
    /* 25F7B8 0035F738 23284202 */  subu       $a1, $s2, $v0
    /* 25F7BC 0035F73C 21100202 */  addu       $v0, $s0, $v0
    /* 25F7C0 0035F740 DCFEA324 */  addiu      $v1, $a1, -0x124
    /* 25F7C4 0035F744 DB06A524 */  addiu      $a1, $a1, 0x6DB
    /* 25F7C8 0035F748 00006728 */  slti       $a3, $v1, 0x0
    /* 25F7CC 0035F74C 2D204000 */  daddu      $a0, $v0, $zero
    /* 25F7D0 0035F750 0B18A700 */  movn       $v1, $a1, $a3
    /* 25F7D4 0035F754 200022AE */  sw         $v0, 0x20($s1)
    /* 25F7D8 0035F758 C31A0300 */  sra        $v1, $v1, 11
    /* 25F7DC 0035F75C 340029AE */  sw         $t1, 0x34($s1)
    /* 25F7E0 0035F760 C01A0300 */  sll        $v1, $v1, 11
    /* 25F7E4 0035F764 28002AAE */  sw         $t2, 0x28($s1)
    /* 25F7E8 0035F768 21386A00 */  addu       $a3, $v1, $t2
    /* 25F7EC 0035F76C 240023AE */  sw         $v1, 0x24($s1)
    /* 25F7F0 0035F770 21104700 */  addu       $v0, $v0, $a3
    /* 25F7F4 0035F774 140020AE */  sw         $zero, 0x14($s1)
    /* 25F7F8 0035F778 B00022AE */  sw         $v0, 0xB0($s1)
    /* 25F7FC 0035F77C 24000624 */  addiu      $a2, $zero, 0x24
    /* 25F800 0035F780 D6B90D0C */  jal        func_0036E758
    /* 25F804 0035F784 2D286000 */   daddu     $a1, $v1, $zero
    /* 25F808 0035F788 2B004010 */  beqz       $v0, .L0035F838
    /* 25F80C 0035F78C 100022AE */   sw        $v0, 0x10($s1)
    /* 25F810 0035F790 2D204000 */  daddu      $a0, $v0, $zero
    /* 25F814 0035F794 28790D0C */  jal        func_0035E4A0
    /* 25F818 0035F798 2D280000 */   daddu     $a1, $zero, $zero
    /* 25F81C 0035F79C 26004010 */  beqz       $v0, .L0035F838
    /* 25F820 0035F7A0 080022AE */   sw        $v0, 0x8($s1)
    /* 25F824 0035F7A4 1400601A */  blez       $s3, .L0035F7F8
    /* 25F828 0035F7A8 2D800000 */   daddu     $s0, $zero, $zero
    /* 25F82C 0035F7AC 18003226 */  addiu      $s2, $s1, 0x18
    /* 25F830 0035F7B0 3400268E */  lw         $a2, 0x34($s1)
    /* 25F834 0035F7B4 00000000 */  nop
  .L0035F7B8:
    /* 25F838 0035F7B8 3000258E */  lw         $a1, 0x30($s1)
    /* 25F83C 0035F7BC 1820D000 */  mult       $a0, $a2, $s0
    /* 25F840 0035F7C0 01001026 */  addiu      $s0, $s0, 0x1
    /* 25F844 0035F7C4 2C00228E */  lw         $v0, 0x2C($s1)
    /* 25F848 0035F7C8 2330C500 */  subu       $a2, $a2, $a1
    /* 25F84C 0035F7CC 40300600 */  sll        $a2, $a2, 1
    /* 25F850 0035F7D0 40280500 */  sll        $a1, $a1, 1
    /* 25F854 0035F7D4 40200400 */  sll        $a0, $a0, 1
    /* 25F858 0035F7D8 D6B90D0C */  jal        func_0036E758
    /* 25F85C 0035F7DC 21204400 */   addu      $a0, $v0, $a0
    /* 25F860 0035F7E0 2A181302 */  slt        $v1, $s0, $s3
    /* 25F864 0035F7E4 000042AE */  sw         $v0, 0x0($s2)
    /* 25F868 0035F7E8 13004010 */  beqz       $v0, .L0035F838
    /* 25F86C 0035F7EC 04005226 */   addiu     $s2, $s2, 0x4
    /* 25F870 0035F7F0 F1FF6054 */  bnel       $v1, $zero, .L0035F7B8
    /* 25F874 0035F7F4 3400268E */   lw        $a2, 0x34($s1)
  .L0035F7F8:
    /* 25F878 0035F7F8 18003026 */  addiu      $s0, $s1, 0x18
    /* 25F87C 0035F7FC 1000248E */  lw         $a0, 0x10($s1)
    /* 25F880 0035F800 2D286002 */  daddu      $a1, $s3, $zero
    /* 25F884 0035F804 12740D0C */  jal        func_0035D048
    /* 25F888 0035F808 2D300002 */   daddu     $a2, $s0, $zero
    /* 25F88C 0035F80C 0A004010 */  beqz       $v0, .L0035F838
    /* 25F890 0035F810 040022AE */   sw        $v0, 0x4($s1)
    /* 25F894 0035F814 2D200002 */  daddu      $a0, $s0, $zero
    /* 25F898 0035F818 32730D0C */  jal        func_0035CCC8
    /* 25F89C 0035F81C 2D286002 */   daddu     $a1, $s3, $zero
    /* 25F8A0 0035F820 05004010 */  beqz       $v0, .L0035F838
    /* 25F8A4 0035F824 0C0022AE */   sw        $v0, 0xC($s1)
    /* 25F8A8 0035F828 56AB0D0C */  jal        func_0036AD58
    /* 25F8AC 0035F82C 1000248E */   lw        $a0, 0x10($s1)
    /* 25F8B0 0035F830 05004014 */  bnez       $v0, .L0035F848
    /* 25F8B4 0035F834 940022AE */   sw        $v0, 0x94($s1)
  .L0035F838:
    /* 25F8B8 0035F838 867E0D0C */  jal        func_0035FA18
    /* 25F8BC 0035F83C 2D202002 */   daddu     $a0, $s1, $zero
    /* 25F8C0 0035F840 39000010 */  b          .L0035F928
    /* 25F8C4 0035F844 2D100000 */   daddu     $v0, $zero, $zero
  .L0035F848:
    /* 25F8C8 0035F848 0800258E */  lw         $a1, 0x8($s1)
    /* 25F8CC 0035F84C ACAB0D0C */  jal        func_0036AEB0
    /* 25F8D0 0035F850 2D204000 */   daddu     $a0, $v0, $zero
    /* 25F8D4 0035F854 485B0D0C */  jal        func_00356D20
    /* 25F8D8 0035F858 00000000 */   nop
    /* 25F8DC 0035F85C 2400228E */  lw         $v0, 0x24($s1)
    /* 25F8E0 0035F860 4300063C */  lui        $a2, (0x4355C0 >> 16)
    /* 25F8E4 0035F864 593F013C */  lui        $at, (0x3F599999 >> 16)
    /* 25F8E8 0035F868 99992134 */  ori        $at, $at, (0x3F599999 & 0xFFFF)
    /* 25F8EC 0035F86C 00088144 */  mtc1       $at, $f1
    /* 25F8F0 0035F870 00004328 */  slti       $v1, $v0, 0x0
    /* 25F8F4 0035F874 FF074424 */  addiu      $a0, $v0, 0x7FF
    /* 25F8F8 0035F878 0B108300 */  movn       $v0, $a0, $v1
    /* 25F8FC 0035F87C C055C58C */  lw         $a1, (0x4355C0 & 0xFFFF)($a2)
    /* 25F900 0035F880 C3120200 */  sra        $v0, $v0, 11
    /* 25F904 0035F884 400020A6 */  sh         $zero, 0x40($s1)
    /* 25F908 0035F888 001C0200 */  sll        $v1, $v0, 16
    /* 25F90C 0035F88C 3C0022A6 */  sh         $v0, 0x3C($s1)
    /* 25F910 0035F890 031C0300 */  sra        $v1, $v1, 16
    /* 25F914 0035F894 380025AE */  sw         $a1, 0x38($s1)
    /* 25F918 0035F898 00008344 */  mtc1       $v1, $f0
    /* 25F91C 0035F89C 20008046 */  cvt.s.w    $f0, $f0
    /* 25F920 0035F8A0 02000146 */  mul.s      $f0, $f0, $f1
    /* 25F924 0035F8A4 64000046 */  .word      0x46000064                    # cvt.w.s    $f1, $f0 # 00000000 <InstrIdType: CPU_COP1_FPUS>
    /* 25F928 0035F8A8 00080244 */  mfc1       $v0, $f1
    /* 25F92C 0035F8AC 0B00601A */  blez       $s3, .L0035F8DC
    /* 25F930 0035F8B0 3E0022A6 */   sh        $v0, 0x3E($s1)
    /* 25F934 0035F8B4 2D806002 */  daddu      $s0, $s3, $zero
    /* 25F938 0035F8B8 80FF0324 */  addiu      $v1, $zero, -0x80
    /* 25F93C 0035F8BC 42002226 */  addiu      $v0, $s1, 0x42
  .L0035F8C0:
    /* 25F940 0035F8C0 FFFF1026 */  addiu      $s0, $s0, -0x1
    /* 25F944 0035F8C4 000043A4 */  sh         $v1, 0x0($v0)
    /* 25F948 0035F8C8 00000000 */  nop
    /* 25F94C 0035F8CC 00000000 */  nop
    /* 25F950 0035F8D0 00000000 */  nop
    /* 25F954 0035F8D4 FAFF0016 */  bnez       $s0, .L0035F8C0
    /* 25F958 0035F8D8 02004224 */   addiu     $v0, $v0, 0x2
  .L0035F8DC:
    /* 25F95C 0035F8DC 01001024 */  addiu      $s0, $zero, 0x1
    /* 25F960 0035F8E0 460020A6 */  sh         $zero, 0x46($s1)
    /* 25F964 0035F8E4 6C0030A2 */  sb         $s0, 0x6C($s1)
    /* 25F968 0035F8E8 2D202002 */  daddu      $a0, $s1, $zero
    /* 25F96C 0035F8EC 540020AE */  sw         $zero, 0x54($s1)
    /* 25F970 0035F8F0 2D280000 */  daddu      $a1, $zero, $zero
    /* 25F974 0035F8F4 580020AE */  sw         $zero, 0x58($s1)
    /* 25F978 0035F8F8 5C0020AE */  sw         $zero, 0x5C($s1)
    /* 25F97C 0035F8FC 600020A6 */  sh         $zero, 0x60($s1)
    /* 25F980 0035F900 640020AE */  sw         $zero, 0x64($s1)
    /* 25F984 0035F904 680020A6 */  sh         $zero, 0x68($s1)
    /* 25F988 0035F908 6A0020A6 */  sh         $zero, 0x6A($s1)
    /* 25F98C 0035F90C 6D0030A2 */  sb         $s0, 0x6D($s1)
    /* 25F990 0035F910 720020A2 */  sb         $zero, 0x72($s1)
    /* 25F994 0035F914 96840D0C */  jal        func_00361258
    /* 25F998 0035F918 880020AE */   sw        $zero, 0x88($s1)
    /* 25F99C 0035F91C 4E5B0D0C */  jal        func_00356D38
    /* 25F9A0 0035F920 000030A2 */   sb        $s0, 0x0($s1)
    /* 25F9A4 0035F924 2D102002 */  daddu      $v0, $s1, $zero
  .L0035F928:
    /* 25F9A8 0035F928 0000B0DF */  ld         $s0, 0x0($sp)
    /* 25F9AC 0035F92C 0800B1DF */  ld         $s1, 0x8($sp)
    /* 25F9B0 0035F930 1000B2DF */  ld         $s2, 0x10($sp)
    /* 25F9B4 0035F934 1800B3DF */  ld         $s3, 0x18($sp)
    /* 25F9B8 0035F938 2000BFDF */  ld         $ra, 0x20($sp)
    /* 25F9BC 0035F93C 0800E003 */  jr         $ra
    /* 25F9C0 0035F940 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 25F9C4 0035F944 00000000 */  nop
.size func_0035F630, . - func_0035F630
