.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_003609C8
    /* 260A48 003609C8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 260A4C 003609CC 06008014 */  bnez       $a0, .L003609E8
    /* 260A50 003609D0 0000BFFF */   sd        $ra, 0x0($sp)
    /* 260A54 003609D4 4E00043C */  lui        $a0, %hi(D_004DAC00)
    /* 260A58 003609D8 0000BFDF */  ld         $ra, 0x0($sp)
    /* 260A5C 003609DC 00AC8424 */  addiu      $a0, $a0, %lo(D_004DAC00)
    /* 260A60 003609E0 44620D08 */  j          func_00358910
    /* 260A64 003609E4 1000BD27 */   addiu     $sp, $sp, 0x10
  .L003609E8:
    /* 260A68 003609E8 0000BFDF */  ld         $ra, 0x0($sp)
    /* 260A6C 003609EC 380085AC */  sw         $a1, 0x38($a0)
    /* 260A70 003609F0 0800E003 */  jr         $ra
    /* 260A74 003609F4 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_003609C8, . - func_003609C8

glabel func_003609F8
    /* 260A78 003609F8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 260A7C 003609FC 2D388000 */  daddu      $a3, $a0, $zero
    /* 260A80 00360A00 0000BFFF */  sd         $ra, 0x0($sp)
    /* 260A84 00360A04 0600E014 */  bnez       $a3, .L00360A20
    /* 260A88 00360A08 2D40A000 */   daddu     $t0, $a1, $zero
    /* 260A8C 00360A0C 4E00043C */  lui        $a0, %hi(D_004DAC30)
    /* 260A90 00360A10 0000BFDF */  ld         $ra, 0x0($sp)
    /* 260A94 00360A14 30AC8424 */  addiu      $a0, $a0, %lo(D_004DAC30)
    /* 260A98 00360A18 44620D08 */  j          func_00358910
    /* 260A9C 00360A1C 1000BD27 */   addiu     $sp, $sp, 0x10
  .L00360A20:
    /* 260AA0 00360A20 00008644 */  mtc1       $a2, $f0
    /* 260AA4 00360A24 20008046 */  cvt.s.w    $f0, $f0
    /* 260AA8 00360A28 3C00E584 */  lh         $a1, 0x3C($a3)
    /* 260AAC 00360A2C 0000BFDF */  ld         $ra, 0x0($sp)
    /* 260AB0 00360A30 02600046 */  mul.s      $f0, $f12, $f0
    /* 260AB4 00360A34 64000046 */  .word      0x46000064                    # cvt.w.s    $f1, $f0 # 00000000 <InstrIdType: CPU_COP1_FPUS>
    /* 260AB8 00360A38 00080344 */  mfc1       $v1, $f1
    /* 260ABC 00360A3C 1F006424 */  addiu      $a0, $v1, 0x1F
    /* 260AC0 00360A40 00006228 */  slti       $v0, $v1, 0x0
    /* 260AC4 00360A44 0B188200 */  movn       $v1, $a0, $v0
    /* 260AC8 00360A48 43190300 */  sra        $v1, $v1, 5
    /* 260ACC 00360A4C 18186800 */  mult       $v1, $v1, $t0
    /* 260AD0 00360A50 C0100300 */  sll        $v0, $v1, 3
    /* 260AD4 00360A54 21104300 */  addu       $v0, $v0, $v1
    /* 260AD8 00360A58 40100200 */  sll        $v0, $v0, 1
    /* 260ADC 00360A5C FF074424 */  addiu      $a0, $v0, 0x7FF
    /* 260AE0 00360A60 2D184000 */  daddu      $v1, $v0, $zero
    /* 260AE4 00360A64 00004228 */  slti       $v0, $v0, 0x0
    /* 260AE8 00360A68 0B188200 */  movn       $v1, $a0, $v0
    /* 260AEC 00360A6C C31A0300 */  sra        $v1, $v1, 11
    /* 260AF0 00360A70 2A106500 */  slt        $v0, $v1, $a1
    /* 260AF4 00360A74 0B286200 */  movn       $a1, $v1, $v0
    /* 260AF8 00360A78 3E00E5A4 */  sh         $a1, 0x3E($a3)
    /* 260AFC 00360A7C 0800E003 */  jr         $ra
    /* 260B00 00360A80 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 260B04 00360A84 00000000 */  nop
.size func_003609F8, . - func_003609F8
