.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00360C68
    /* 260CE8 00360C68 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 260CEC 00360C6C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 260CF0 00360C70 2D808000 */  daddu      $s0, $a0, $zero
    /* 260CF4 00360C74 06000016 */  bnez       $s0, .L00360C90
    /* 260CF8 00360C78 0800BFFF */   sd        $ra, 0x8($sp)
    /* 260CFC 00360C7C 4E00043C */  lui        $a0, %hi(D_004DAD28)
    /* 260D00 00360C80 44620D0C */  jal        func_00358910
    /* 260D04 00360C84 28AD8424 */   addiu     $a0, $a0, %lo(D_004DAD28)
    /* 260D08 00360C88 0E000010 */  b          .L00360CC4
    /* 260D0C 00360C8C FFFF0224 */   addiu     $v0, $zero, -0x1
  .L00360C90:
    /* 260D10 00360C90 1400038E */  lw         $v1, 0x14($s0)
    /* 260D14 00360C94 0A006010 */  beqz       $v1, .L00360CC0
    /* 260D18 00360C98 2D206000 */   daddu     $a0, $v1, $zero
    /* 260D1C 00360C9C 0000638C */  lw         $v1, 0x0($v1)
    /* 260D20 00360CA0 2400628C */  lw         $v0, 0x24($v1)
    /* 260D24 00360CA4 09F84000 */  jalr       $v0
    /* 260D28 00360CA8 01000524 */   addiu     $a1, $zero, 0x1
    /* 260D2C 00360CAC 3E000386 */  lh         $v1, 0x3E($s0)
    /* 260D30 00360CB0 C01A0300 */  sll        $v1, $v1, 11
    /* 260D34 00360CB4 2A104300 */  slt        $v0, $v0, $v1
    /* 260D38 00360CB8 02000010 */  b          .L00360CC4
    /* 260D3C 00360CBC 0100422C */   sltiu     $v0, $v0, 0x1
  .L00360CC0:
    /* 260D40 00360CC0 2D100000 */  daddu      $v0, $zero, $zero
  .L00360CC4:
    /* 260D44 00360CC4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 260D48 00360CC8 0800BFDF */  ld         $ra, 0x8($sp)
    /* 260D4C 00360CCC 0800E003 */  jr         $ra
    /* 260D50 00360CD0 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 260D54 00360CD4 00000000 */  nop
.size func_00360C68, . - func_00360C68
