.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_003638D8
    /* 263958 003638D8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 26395C 003638DC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 263960 003638E0 2D808000 */  daddu      $s0, $a0, $zero
    /* 263964 003638E4 0800B1FF */  sd         $s1, 0x8($sp)
    /* 263968 003638E8 09000016 */  bnez       $s0, .L00363910
    /* 26396C 003638EC 1000BFFF */   sd        $ra, 0x10($sp)
    /* 263970 003638F0 4E00043C */  lui        $a0, %hi(D_4DB280)
    /* 263974 003638F4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 263978 003638F8 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26397C 003638FC 80B28424 */  addiu      $a0, $a0, %lo(D_4DB280)
    /* 263980 00363900 1000BFDF */  ld         $ra, 0x10($sp)
    /* 263984 00363904 EA8C0D08 */  j          func_003633A8
    /* 263988 00363908 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 26398C 0036390C 00000000 */  nop
  .L00363910:
    /* 263990 00363910 70DB0D0C */  jal        func_00376DC0
    /* 263994 00363914 00000000 */   nop
    /* 263998 00363918 2D884000 */  daddu      $s1, $v0, $zero
    /* 26399C 0036391C 08002016 */  bnez       $s1, .L00363940
    /* 2639A0 00363920 2D200002 */   daddu     $a0, $s0, $zero
    /* 2639A4 00363924 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2639A8 00363928 6400023C */  lui        $v0, (0x640000 >> 16)
    /* 2639AC 0036392C 0800B1DF */  ld         $s1, 0x8($sp)
    /* 2639B0 00363930 1000BFDF */  ld         $ra, 0x10($sp)
    /* 2639B4 00363934 A8CB40A0 */  sb         $zero, -0x3458($v0)
    /* 2639B8 00363938 0800E003 */  jr         $ra
    /* 2639BC 0036393C 2000BD27 */   addiu     $sp, $sp, 0x20
  .L00363940:
    /* 2639C0 00363940 E88D0D0C */  jal        func_003637A0
    /* 2639C4 00363944 00000000 */   nop
    /* 2639C8 00363948 2D200002 */  daddu      $a0, $s0, $zero
    /* 2639CC 0036394C 688E0D0C */  jal        func_003639A0
    /* 2639D0 00363950 2D282002 */   daddu     $a1, $s1, $zero
    /* 2639D4 00363954 6400043C */  lui        $a0, %hi(D_63CBA8)
    /* 2639D8 00363958 01000324 */  addiu      $v1, $zero, 0x1
    /* 2639DC 0036395C A8CB8424 */  addiu      $a0, $a0, %lo(D_63CBA8)
    /* 2639E0 00363960 2D280002 */  daddu      $a1, $s0, $zero
    /* 2639E4 00363964 06004314 */  bne        $v0, $v1, .L00363980
    /* 2639E8 00363968 01002626 */   addiu     $a2, $s1, 0x1
    /* 2639EC 0036396C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 2639F0 00363970 0800B1DF */  ld         $s1, 0x8($sp)
    /* 2639F4 00363974 1000BFDF */  ld         $ra, 0x10($sp)
    /* 2639F8 00363978 16D40D08 */  j          func_00375058
    /* 2639FC 0036397C 2000BD27 */   addiu     $sp, $sp, 0x20
  .L00363980:
    /* 263A00 00363980 4E00043C */  lui        $a0, %hi(D_4DB2A8)
    /* 263A04 00363984 0000B0DF */  ld         $s0, 0x0($sp)
    /* 263A08 00363988 0800B1DF */  ld         $s1, 0x8($sp)
    /* 263A0C 0036398C A8B28424 */  addiu      $a0, $a0, %lo(D_4DB2A8)
    /* 263A10 00363990 1000BFDF */  ld         $ra, 0x10($sp)
    /* 263A14 00363994 EA8C0D08 */  j          func_003633A8
    /* 263A18 00363998 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 263A1C 0036399C 00000000 */  nop
.size func_003638D8, . - func_003638D8

glabel func_003639A0
    /* 263A20 003639A0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 263A24 003639A4 6400023C */  lui        $v0, %hi(D_63C9AC)
    /* 263A28 003639A8 2000BFFF */  sd         $ra, 0x20($sp)
    /* 263A2C 003639AC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 263A30 003639B0 2D800000 */  daddu      $s0, $zero, $zero
    /* 263A34 003639B4 0800B1FF */  sd         $s1, 0x8($sp)
    /* 263A38 003639B8 ACC95124 */  addiu      $s1, $v0, %lo(D_63C9AC)
    /* 263A3C 003639BC 1000B2FF */  sd         $s2, 0x10($sp)
    /* 263A40 003639C0 2D90A000 */  daddu      $s2, $a1, $zero
    /* 263A44 003639C4 1800B3FF */  sd         $s3, 0x18($sp)
    /* 263A48 003639C8 2D988000 */  daddu      $s3, $a0, $zero
    /* 263A4C 003639CC 2D282002 */  daddu      $a1, $s1, $zero
  .L003639D0:
    /* 263A50 003639D0 10003126 */  addiu      $s1, $s1, 0x10
    /* 263A54 003639D4 2D206002 */  daddu      $a0, $s3, $zero
    /* 263A58 003639D8 2ADC0D0C */  jal        func_003770A8
    /* 263A5C 003639DC 2D304002 */   daddu     $a2, $s2, $zero
    /* 263A60 003639E0 03004014 */  bnez       $v0, .L003639F0
    /* 263A64 003639E4 01001026 */   addiu     $s0, $s0, 0x1
    /* 263A68 003639E8 05000010 */  b          .L00363A00
    /* 263A6C 003639EC 01000224 */   addiu     $v0, $zero, 0x1
  .L003639F0:
    /* 263A70 003639F0 2000022A */  slti       $v0, $s0, 0x20
    /* 263A74 003639F4 F6FF4014 */  bnez       $v0, .L003639D0
    /* 263A78 003639F8 2D282002 */   daddu     $a1, $s1, $zero
    /* 263A7C 003639FC 2D100000 */  daddu      $v0, $zero, $zero
  .L00363A00:
    /* 263A80 00363A00 0000B0DF */  ld         $s0, 0x0($sp)
    /* 263A84 00363A04 0800B1DF */  ld         $s1, 0x8($sp)
    /* 263A88 00363A08 1000B2DF */  ld         $s2, 0x10($sp)
    /* 263A8C 00363A0C 1800B3DF */  ld         $s3, 0x18($sp)
    /* 263A90 00363A10 2000BFDF */  ld         $ra, 0x20($sp)
    /* 263A94 00363A14 0800E003 */  jr         $ra
    /* 263A98 00363A18 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 263A9C 00363A1C 00000000 */  nop
.size func_003639A0, . - func_003639A0

glabel func_00363A20
    /* 263AA0 00363A20 6400023C */  lui        $v0, %hi(D_63CBA8)
    /* 263AA4 00363A24 0800E003 */  jr         $ra
    /* 263AA8 00363A28 A8CB4224 */   addiu     $v0, $v0, %lo(D_63CBA8)
    /* 263AAC 00363A2C 00000000 */  nop
.size func_00363A20, . - func_00363A20

glabel func_00363A30
    /* 263AB0 00363A30 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 263AB4 00363A34 0800B1FF */  sd         $s1, 0x8($sp)
    /* 263AB8 00363A38 2D888000 */  daddu      $s1, $a0, $zero
    /* 263ABC 00363A3C 1000B2FF */  sd         $s2, 0x10($sp)
    /* 263AC0 00363A40 2D90A000 */  daddu      $s2, $a1, $zero
    /* 263AC4 00363A44 1800B3FF */  sd         $s3, 0x18($sp)
    /* 263AC8 00363A48 0000B0FF */  sd         $s0, 0x0($sp)
    /* 263ACC 00363A4C 2000BFFF */  sd         $ra, 0x20($sp)
    /* 263AD0 00363A50 00002282 */  lb         $v0, 0x0($s1)
    /* 263AD4 00363A54 06004014 */  bnez       $v0, .L00363A70
    /* 263AD8 00363A58 2D98C000 */   daddu     $s3, $a2, $zero
    /* 263ADC 00363A5C 708F0D0C */  jal        func_00363DC0
    /* 263AE0 00363A60 00000000 */   nop
    /* 263AE4 00363A64 00002382 */  lb         $v1, 0x0($s1)
    /* 263AE8 00363A68 14006010 */  beqz       $v1, .L00363ABC
    /* 263AEC 00363A6C 2D100000 */   daddu     $v0, $zero, $zero
  .L00363A70:
    /* 263AF0 00363A70 2D284002 */  daddu      $a1, $s2, $zero
    /* 263AF4 00363A74 64940D0C */  jal        func_00365190
    /* 263AF8 00363A78 2D202002 */   daddu     $a0, $s1, $zero
    /* 263AFC 00363A7C C28D0D0C */  jal        func_00363708
    /* 263B00 00363A80 2D202002 */   daddu     $a0, $s1, $zero
    /* 263B04 00363A84 2D804000 */  daddu      $s0, $v0, $zero
    /* 263B08 00363A88 0B000016 */  bnez       $s0, .L00363AB8
    /* 263B0C 00363A8C 2D202002 */   daddu     $a0, $s1, $zero
    /* 263B10 00363A90 708F0D0C */  jal        func_00363DC0
    /* 263B14 00363A94 00000000 */   nop
    /* 263B18 00363A98 C28D0D0C */  jal        func_00363708
    /* 263B1C 00363A9C 2D202002 */   daddu     $a0, $s1, $zero
    /* 263B20 00363AA0 2D204002 */  daddu      $a0, $s2, $zero
    /* 263B24 00363AA4 2D804000 */  daddu      $s0, $v0, $zero
    /* 263B28 00363AA8 04000012 */  beqz       $s0, .L00363ABC
    /* 263B2C 00363AAC 2D286002 */   daddu     $a1, $s3, $zero
    /* 263B30 00363AB0 2ADB0D0C */  jal        func_00376CA8
    /* 263B34 00363AB4 00000000 */   nop
  .L00363AB8:
    /* 263B38 00363AB8 2D100002 */  daddu      $v0, $s0, $zero
  .L00363ABC:
    /* 263B3C 00363ABC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 263B40 00363AC0 0800B1DF */  ld         $s1, 0x8($sp)
    /* 263B44 00363AC4 1000B2DF */  ld         $s2, 0x10($sp)
    /* 263B48 00363AC8 1800B3DF */  ld         $s3, 0x18($sp)
    /* 263B4C 00363ACC 2000BFDF */  ld         $ra, 0x20($sp)
    /* 263B50 00363AD0 0800E003 */  jr         $ra
    /* 263B54 00363AD4 3000BD27 */   addiu     $sp, $sp, 0x30
.size func_00363A30, . - func_00363A30

glabel func_00363AD8
    /* 263B58 00363AD8 70FDBD27 */  addiu      $sp, $sp, -0x290
    /* 263B5C 00363ADC 6802B1FF */  sd         $s1, 0x268($sp)
    /* 263B60 00363AE0 2D888000 */  daddu      $s1, $a0, $zero
    /* 263B64 00363AE4 7802B3FF */  sd         $s3, 0x278($sp)
    /* 263B68 00363AE8 2D98A000 */  daddu      $s3, $a1, $zero
    /* 263B6C 00363AEC 8002B4FF */  sd         $s4, 0x280($sp)
    /* 263B70 00363AF0 2DA0C000 */  daddu      $s4, $a2, $zero
    /* 263B74 00363AF4 6002B0FF */  sd         $s0, 0x260($sp)
    /* 263B78 00363AF8 7002B2FF */  sd         $s2, 0x270($sp)
    /* 263B7C 00363AFC 04002016 */  bnez       $s1, .L00363B10
    /* 263B80 00363B00 8802BFFF */   sd        $ra, 0x288($sp)
    /* 263B84 00363B04 4E00043C */  lui        $a0, %hi(D_4DB2D0)
    /* 263B88 00363B08 32000010 */  b          .L00363BD4
    /* 263B8C 00363B0C D0B28424 */   addiu     $a0, $a0, %lo(D_4DB2D0)
  .L00363B10:
    /* 263B90 00363B10 3001B227 */  addiu      $s2, $sp, 0x130
    /* 263B94 00363B14 2D20A003 */  daddu      $a0, $sp, $zero
    /* 263B98 00363B18 2D284002 */  daddu      $a1, $s2, $zero
    /* 263B9C 00363B1C 1E8F0D0C */  jal        func_00363C78
    /* 263BA0 00363B20 2D302002 */   daddu     $a2, $s1, $zero
    /* 263BA4 00363B24 3001A283 */  lb         $v0, 0x130($sp)
    /* 263BA8 00363B28 03004014 */  bnez       $v0, .L00363B38
    /* 263BAC 00363B2C 4E00043C */   lui       $a0, %hi(D_4DB2D0)
    /* 263BB0 00363B30 28000010 */  b          .L00363BD4
    /* 263BB4 00363B34 D0B28424 */   addiu     $a0, $a0, %lo(D_4DB2D0)
  .L00363B38:
    /* 263BB8 00363B38 008F0D0C */  jal        func_00363C00
    /* 263BBC 00363B3C 00000000 */   nop
    /* 263BC0 00363B40 2D804000 */  daddu      $s0, $v0, $zero
    /* 263BC4 00363B44 04000016 */  bnez       $s0, .L00363B58
    /* 263BC8 00363B48 2D302002 */   daddu     $a2, $s1, $zero
    /* 263BCC 00363B4C 4E00043C */  lui        $a0, %hi(D_4DB2F0)
    /* 263BD0 00363B50 20000010 */  b          .L00363BD4
    /* 263BD4 00363B54 F0B28424 */   addiu     $a0, $a0, %lo(D_4DB2F0)
  .L00363B58:
    /* 263BD8 00363B58 2D20A003 */  daddu      $a0, $sp, $zero
    /* 263BDC 00363B5C 8C8E0D0C */  jal        func_00363A30
    /* 263BE0 00363B60 2D284002 */   daddu     $a1, $s2, $zero
    /* 263BE4 00363B64 06004014 */  bnez       $v0, .L00363B80
    /* 263BE8 00363B68 000002AE */   sw        $v0, 0x0($s0)
    /* 263BEC 00363B6C 1A8F0D0C */  jal        func_00363C68
    /* 263BF0 00363B70 2D200002 */   daddu     $a0, $s0, $zero
    /* 263BF4 00363B74 4E00043C */  lui        $a0, %hi(D_4DB338)
    /* 263BF8 00363B78 16000010 */  b          .L00363BD4
    /* 263BFC 00363B7C 38B38424 */   addiu     $a0, $a0, %lo(D_4DB338)
  .L00363B80:
    /* 263C00 00363B80 1000428C */  lw         $v0, 0x10($v0)
    /* 263C04 00363B84 06004010 */  beqz       $v0, .L00363BA0
    /* 263C08 00363B88 2D286002 */   daddu     $a1, $s3, $zero
    /* 263C0C 00363B8C 2D204002 */  daddu      $a0, $s2, $zero
    /* 263C10 00363B90 09F84000 */  jalr       $v0
    /* 263C14 00363B94 2D308002 */   daddu     $a2, $s4, $zero
    /* 263C18 00363B98 07000010 */  b          .L00363BB8
    /* 263C1C 00363B9C 040002AE */   sw        $v0, 0x4($s0)
  .L00363BA0:
    /* 263C20 00363BA0 1A8F0D0C */  jal        func_00363C68
    /* 263C24 00363BA4 2D200002 */   daddu     $a0, $s0, $zero
    /* 263C28 00363BA8 4E00043C */  lui        $a0, %hi(D_4DB358)
    /* 263C2C 00363BAC 09000010 */  b          .L00363BD4
    /* 263C30 00363BB0 58B38424 */   addiu     $a0, $a0, %lo(D_4DB358)
    /* 263C34 00363BB4 00000000 */  nop
  .L00363BB8:
    /* 263C38 00363BB8 0400028E */  lw         $v0, 0x4($s0)
    /* 263C3C 00363BBC 08004054 */  bnel       $v0, $zero, .L00363BE0
    /* 263C40 00363BC0 2D100002 */   daddu     $v0, $s0, $zero
    /* 263C44 00363BC4 1A8F0D0C */  jal        func_00363C68
    /* 263C48 00363BC8 2D200002 */   daddu     $a0, $s0, $zero
    /* 263C4C 00363BCC 4E00043C */  lui        $a0, %hi(D_4DB370)
    /* 263C50 00363BD0 70B38424 */  addiu      $a0, $a0, %lo(D_4DB370)
  .L00363BD4:
    /* 263C54 00363BD4 EA8C0D0C */  jal        func_003633A8
    /* 263C58 00363BD8 00000000 */   nop
    /* 263C5C 00363BDC 2D100000 */  daddu      $v0, $zero, $zero
  .L00363BE0:
    /* 263C60 00363BE0 6002B0DF */  ld         $s0, 0x260($sp)
    /* 263C64 00363BE4 6802B1DF */  ld         $s1, 0x268($sp)
    /* 263C68 00363BE8 7002B2DF */  ld         $s2, 0x270($sp)
    /* 263C6C 00363BEC 7802B3DF */  ld         $s3, 0x278($sp)
    /* 263C70 00363BF0 8002B4DF */  ld         $s4, 0x280($sp)
    /* 263C74 00363BF4 8802BFDF */  ld         $ra, 0x288($sp)
    /* 263C78 00363BF8 0800E003 */  jr         $ra
    /* 263C7C 00363BFC 9002BD27 */   addiu     $sp, $sp, 0x290
.size func_00363AD8, . - func_00363AD8

glabel func_00363C00
    /* 263C80 00363C00 6400053C */  lui        $a1, %hi(D_63C868)
    /* 263C84 00363C04 68C8A224 */  addiu      $v0, $a1, %lo(D_63C868)
    /* 263C88 00363C08 04004224 */  addiu      $v0, $v0, 0x4
    /* 263C8C 00363C0C 0000438C */  lw         $v1, 0x0($v0)
    /* 263C90 00363C10 0C006010 */  beqz       $v1, .L00363C44
    /* 263C94 00363C14 2D200000 */   daddu     $a0, $zero, $zero
    /* 263C98 00363C18 2D184000 */  daddu      $v1, $v0, $zero
    /* 263C9C 00363C1C 01008424 */  addiu      $a0, $a0, 0x1
  .L00363C20:
    /* 263CA0 00363C20 28008228 */  slti       $v0, $a0, 0x28
    /* 263CA4 00363C24 07004010 */  beqz       $v0, .L00363C44
    /* 263CA8 00363C28 08006324 */   addiu     $v1, $v1, 0x8
    /* 263CAC 00363C2C 0000628C */  lw         $v0, 0x0($v1)
    /* 263CB0 00363C30 00000000 */  nop
    /* 263CB4 00363C34 00000000 */  nop
    /* 263CB8 00363C38 00000000 */  nop
    /* 263CBC 00363C3C F8FF4054 */  bnel       $v0, $zero, .L00363C20
    /* 263CC0 00363C40 01008424 */   addiu     $a0, $a0, 0x1
  .L00363C44:
    /* 263CC4 00363C44 28000324 */  addiu      $v1, $zero, 0x28
    /* 263CC8 00363C48 04008310 */  beq        $a0, $v1, .L00363C5C
    /* 263CCC 00363C4C 2D100000 */   daddu     $v0, $zero, $zero
    /* 263CD0 00363C50 C0180400 */  sll        $v1, $a0, 3
    /* 263CD4 00363C54 68C8A224 */  addiu      $v0, $a1, %lo(D_63C868)
    /* 263CD8 00363C58 21106200 */  addu       $v0, $v1, $v0
  .L00363C5C:
    /* 263CDC 00363C5C 0800E003 */  jr         $ra
    /* 263CE0 00363C60 00000000 */   nop
    /* 263CE4 00363C64 00000000 */  nop
.size func_00363C00, . - func_00363C00
