.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00363C68
    /* 263CE8 00363C68 000080AC */  sw         $zero, 0x0($a0)
    /* 263CEC 00363C6C 0800E003 */  jr         $ra
    /* 263CF0 00363C70 040080AC */   sw        $zero, 0x4($a0)
    /* 263CF4 00363C74 00000000 */  nop
.size func_00363C68, . - func_00363C68
