.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00368C58
    /* 268CD8 00368C58 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 268CDC 00368C5C 2000B4FF */  sd         $s4, 0x20($sp)
    /* 268CE0 00368C60 6400143C */  lui        $s4, %hi(D_63CF00)
    /* 268CE4 00368C64 0000B0FF */  sd         $s0, 0x0($sp)
    /* 268CE8 00368C68 2D808000 */  daddu      $s0, $a0, $zero
    /* 268CEC 00368C6C 0800B1FF */  sd         $s1, 0x8($sp)
    /* 268CF0 00368C70 2D88C000 */  daddu      $s1, $a2, $zero
    /* 268CF4 00368C74 1000B2FF */  sd         $s2, 0x10($sp)
    /* 268CF8 00368C78 2D90A000 */  daddu      $s2, $a1, $zero
    /* 268CFC 00368C7C 00100624 */  addiu      $a2, $zero, 0x1000
    /* 268D00 00368C80 00CF8426 */  addiu      $a0, $s4, %lo(D_63CF00)
    /* 268D04 00368C84 2D280000 */  daddu      $a1, $zero, $zero
    /* 268D08 00368C88 1800B3FF */  sd         $s3, 0x18($sp)
    /* 268D0C 00368C8C 2800BFFF */  sd         $ra, 0x28($sp)
    /* 268D10 00368C90 84D40D0C */  jal        func_00375210
    /* 268D14 00368C94 2D98E000 */   daddu     $s3, $a3, $zero
    /* 268D18 00368C98 4300033C */  lui        $v1, (0x437730 >> 16)
    /* 268D1C 00368C9C 3077628C */  lw         $v0, (0x437730 & 0xFFFF)($v1)
    /* 268D20 00368CA0 03004010 */  beqz       $v0, .L00368CB0
    /* 268D24 00368CA4 00000000 */   nop
    /* 268D28 00368CA8 E0A20D0C */  jal        func_00368B80
    /* 268D2C 00368CAC 00000000 */   nop
  .L00368CB0:
    /* 268D30 00368CB0 05000012 */  beqz       $s0, .L00368CC8
    /* 268D34 00368CB4 00000000 */   nop
    /* 268D38 00368CB8 03004012 */  beqz       $s2, .L00368CC8
    /* 268D3C 00368CBC 00000000 */   nop
    /* 268D40 00368CC0 03002016 */  bnez       $s1, .L00368CD0
    /* 268D44 00368CC4 00000000 */   nop
  .L00368CC8:
    /* 268D48 00368CC8 E0A20D0C */  jal        func_00368B80
    /* 268D4C 00368CCC 00000000 */   nop
  .L00368CD0:
    /* 268D50 00368CD0 44000012 */  beqz       $s0, .L00368DE4
    /* 268D54 00368CD4 2D100000 */   daddu     $v0, $zero, $zero
    /* 268D58 00368CD8 0B004016 */  bnez       $s2, .L00368D08
    /* 268D5C 00368CDC 4300023C */   lui       $v0, (0x437748 >> 16)
    /* 268D60 00368CE0 4877438C */  lw         $v1, (0x437748 & 0xFFFF)($v0)
    /* 268D64 00368CE4 3F006054 */  bnel       $v1, $zero, .L00368DE4
    /* 268D68 00368CE8 2D100000 */   daddu     $v0, $zero, $zero
    /* 268D6C 00368CEC 4E00043C */  lui        $a0, %hi(D_4DC760)
    /* 268D70 00368CF0 2D280000 */  daddu      $a1, $zero, $zero
    /* 268D74 00368CF4 7214040C */  jal        func_001051C8
    /* 268D78 00368CF8 60C78424 */   addiu     $a0, $a0, %lo(D_4DC760)
    /* 268D7C 00368CFC 39000010 */  b          .L00368DE4
    /* 268D80 00368D00 2D100000 */   daddu     $v0, $zero, $zero
    /* 268D84 00368D04 00000000 */  nop
  .L00368D08:
    /* 268D88 00368D08 0B002016 */  bnez       $s1, .L00368D38
    /* 268D8C 00368D0C 2D204002 */   daddu     $a0, $s2, $zero
    /* 268D90 00368D10 4300023C */  lui        $v0, (0x437748 >> 16)
    /* 268D94 00368D14 4877438C */  lw         $v1, (0x437748 & 0xFFFF)($v0)
    /* 268D98 00368D18 32006054 */  bnel       $v1, $zero, .L00368DE4
    /* 268D9C 00368D1C 2D100000 */   daddu     $v0, $zero, $zero
    /* 268DA0 00368D20 4E00043C */  lui        $a0, %hi(D_4DC790)
    /* 268DA4 00368D24 2D280000 */  daddu      $a1, $zero, $zero
    /* 268DA8 00368D28 7214040C */  jal        func_001051C8
    /* 268DAC 00368D2C 90C78424 */   addiu     $a0, $a0, %lo(D_4DC790)
    /* 268DB0 00368D30 2C000010 */  b          .L00368DE4
    /* 268DB4 00368D34 2D100000 */   daddu     $v0, $zero, $zero
  .L00368D38:
    /* 268DB8 00368D38 2D280000 */  daddu      $a1, $zero, $zero
    /* 268DBC 00368D3C 00CF9426 */  addiu      $s4, $s4, %lo(D_63CF00)
    /* 268DC0 00368D40 84D40D0C */  jal        func_00375210
    /* 268DC4 00368D44 2D302002 */   daddu     $a2, $s1, $zero
    /* 268DC8 00368D48 2D200002 */  daddu      $a0, $s0, $zero
    /* 268DCC 00368D4C D6A10D0C */  jal        func_00368758
    /* 268DD0 00368D50 2D288002 */   daddu     $a1, $s4, $zero
    /* 268DD4 00368D54 10004054 */  bnel       $v0, $zero, .L00368D98
    /* 268DD8 00368D58 09007026 */   addiu     $s0, $s3, 0x9
    /* 268DDC 00368D5C 4300023C */  lui        $v0, (0x437748 >> 16)
    /* 268DE0 00368D60 4877438C */  lw         $v1, (0x437748 & 0xFFFF)($v0)
    /* 268DE4 00368D64 06006014 */  bnez       $v1, .L00368D80
    /* 268DE8 00368D68 4E00053C */   lui       $a1, %hi(D_4DC7E8)
    /* 268DEC 00368D6C 4E00043C */  lui        $a0, %hi(D_4DC7C0)
    /* 268DF0 00368D70 2D280002 */  daddu      $a1, $s0, $zero
    /* 268DF4 00368D74 7214040C */  jal        func_001051C8
    /* 268DF8 00368D78 C0C78424 */   addiu     $a0, $a0, %lo(D_4DC7C0)
    /* 268DFC 00368D7C 4E00053C */  lui        $a1, %hi(D_4DC7E8)
  .L00368D80:
    /* 268E00 00368D80 2D200000 */  daddu      $a0, $zero, $zero
    /* 268E04 00368D84 E89D0D0C */  jal        func_003677A0
    /* 268E08 00368D88 E8C7A524 */   addiu     $a1, $a1, %lo(D_4DC7E8)
    /* 268E0C 00368D8C 15000010 */  b          .L00368DE4
    /* 268E10 00368D90 2D100000 */   daddu     $v0, $zero, $zero
    /* 268E14 00368D94 00000000 */  nop
  .L00368D98:
    /* 268E18 00368D98 2D288002 */  daddu      $a1, $s4, $zero
    /* 268E1C 00368D9C 1B003002 */  divu       $zero, $s1, $s0
    /* 268E20 00368DA0 00100624 */  addiu      $a2, $zero, 0x1000
    /* 268E24 00368DA4 2D406002 */  daddu      $t0, $s3, $zero
    /* 268E28 00368DA8 2D204002 */  daddu      $a0, $s2, $zero
    /* 268E2C 00368DAC 01000052 */  beql       $s0, $zero, .L00368DB4
    /* 268E30 00368DB0 CD010000 */   break     0, 7
  .L00368DB4:
    /* 268E34 00368DB4 12880000 */  mflo       $s1
    /* 268E38 00368DB8 2D382002 */  daddu      $a3, $s1, $zero
    /* 268E3C 00368DBC 70A10D0C */  jal        func_003685C0
    /* 268E40 00368DC0 C0881100 */   sll       $s1, $s1, 3
    /* 268E44 00368DC4 2D204002 */  daddu      $a0, $s2, $zero
    /* 268E48 00368DC8 38A20D0C */  jal        func_003688E0
    /* 268E4C 00368DCC 2D284000 */   daddu     $a1, $v0, $zero
    /* 268E50 00368DD0 01000052 */  beql       $s0, $zero, .L00368DD8
    /* 268E54 00368DD4 CD010000 */   break     0, 7
  .L00368DD8:
    /* 268E58 00368DD8 01006326 */  addiu      $v1, $s3, 0x1
    /* 268E5C 00368DDC 18104300 */  mult       $v0, $v0, $v1
    /* 268E60 00368DE0 21102202 */  addu       $v0, $s1, $v0
  .L00368DE4:
    /* 268E64 00368DE4 0000B0DF */  ld         $s0, 0x0($sp)
    /* 268E68 00368DE8 0800B1DF */  ld         $s1, 0x8($sp)
    /* 268E6C 00368DEC 1000B2DF */  ld         $s2, 0x10($sp)
    /* 268E70 00368DF0 1800B3DF */  ld         $s3, 0x18($sp)
    /* 268E74 00368DF4 2000B4DF */  ld         $s4, 0x20($sp)
    /* 268E78 00368DF8 2800BFDF */  ld         $ra, 0x28($sp)
    /* 268E7C 00368DFC 0800E003 */  jr         $ra
    /* 268E80 00368E00 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 268E84 00368E04 00000000 */  nop
.size func_00368C58, . - func_00368C58
