.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00369E48
    /* 269EC8 00369E48 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 269ECC 00369E4C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 269ED0 00369E50 78A70D0C */  jal        func_00369DE0
    /* 269ED4 00369E54 00000000 */   nop
    /* 269ED8 00369E58 0000BFDF */  ld         $ra, 0x0($sp)
    /* 269EDC 00369E5C 3F100200 */  dsra32     $v0, $v0, 0
    /* 269EE0 00369E60 0800E003 */  jr         $ra
    /* 269EE4 00369E64 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00369E48, . - func_00369E48

glabel func_00369E68
    /* 269EE8 00369E68 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 269EEC 00369E6C 0000BFFF */  sd         $ra, 0x0($sp)
    /* 269EF0 00369E70 78A70D0C */  jal        func_00369DE0
    /* 269EF4 00369E74 00000000 */   nop
    /* 269EF8 00369E78 FFFF033C */  lui        $v1, (0xFFFF0000 >> 16)
    /* 269EFC 00369E7C 3E180300 */  dsrl32     $v1, $v1, 0
    /* 269F00 00369E80 0000BFDF */  ld         $ra, 0x0($sp)
    /* 269F04 00369E84 24104300 */  and        $v0, $v0, $v1
    /* 269F08 00369E88 3C100200 */  dsll32     $v0, $v0, 0
    /* 269F0C 00369E8C 3F100200 */  dsra32     $v0, $v0, 0
    /* 269F10 00369E90 0800E003 */  jr         $ra
    /* 269F14 00369E94 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00369E68, . - func_00369E68

glabel func_00369E98
    /* 269F18 00369E98 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 269F1C 00369E9C 2D180000 */  daddu      $v1, $zero, $zero
    /* 269F20 00369EA0 0000BFFF */  sd         $ra, 0x0($sp)
    /* 269F24 00369EA4 2A008010 */  beqz       $a0, .L00369F50
    /* 269F28 00369EA8 2D100000 */   daddu     $v0, $zero, $zero
    /* 269F2C 00369EAC CB000224 */  addiu      $v0, $zero, 0xCB
    /* 269F30 00369EB0 2100A210 */  beq        $a1, $v0, .L00369F38
    /* 269F34 00369EB4 CC00A228 */   slti      $v0, $a1, 0xCC
    /* 269F38 00369EB8 0B004010 */  beqz       $v0, .L00369EE8
    /* 269F3C 00369EBC CD000224 */   addiu     $v0, $zero, 0xCD
    /* 269F40 00369EC0 C9000224 */  addiu      $v0, $zero, 0xC9
    /* 269F44 00369EC4 1400A210 */  beq        $a1, $v0, .L00369F18
    /* 269F48 00369EC8 CA00A228 */   slti      $v0, $a1, 0xCA
    /* 269F4C 00369ECC 16004010 */  beqz       $v0, .L00369F28
    /* 269F50 00369ED0 C8000224 */   addiu     $v0, $zero, 0xC8
    /* 269F54 00369ED4 0C00A210 */  beq        $a1, $v0, .L00369F08
    /* 269F58 00369ED8 2D106000 */   daddu     $v0, $v1, $zero
    /* 269F5C 00369EDC 1D000010 */  b          .L00369F54
    /* 269F60 00369EE0 0000BFDF */   ld        $ra, 0x0($sp)
    /* 269F64 00369EE4 00000000 */  nop
  .L00369EE8:
    /* 269F68 00369EE8 1300A210 */  beq        $a1, $v0, .L00369F38
    /* 269F6C 00369EEC CD00A228 */   slti      $v0, $a1, 0xCD
    /* 269F70 00369EF0 0D004014 */  bnez       $v0, .L00369F28
    /* 269F74 00369EF4 2B010224 */   addiu     $v0, $zero, 0x12B
    /* 269F78 00369EF8 1300A210 */  beq        $a1, $v0, .L00369F48
    /* 269F7C 00369EFC 2D106000 */   daddu     $v0, $v1, $zero
    /* 269F80 00369F00 14000010 */  b          .L00369F54
    /* 269F84 00369F04 0000BFDF */   ld        $ra, 0x0($sp)
  .L00369F08:
    /* 269F88 00369F08 7EA70D0C */  jal        func_00369DF8
    /* 269F8C 00369F0C 00000000 */   nop
    /* 269F90 00369F10 0E000010 */  b          .L00369F4C
    /* 269F94 00369F14 2D184000 */   daddu     $v1, $v0, $zero
  .L00369F18:
    /* 269F98 00369F18 86A70D0C */  jal        func_00369E18
    /* 269F9C 00369F1C 00000000 */   nop
    /* 269FA0 00369F20 0A000010 */  b          .L00369F4C
    /* 269FA4 00369F24 2D184000 */   daddu     $v1, $v0, $zero
  .L00369F28:
    /* 269FA8 00369F28 92A70D0C */  jal        func_00369E48
    /* 269FAC 00369F2C 00000000 */   nop
    /* 269FB0 00369F30 06000010 */  b          .L00369F4C
    /* 269FB4 00369F34 2D184000 */   daddu     $v1, $v0, $zero
  .L00369F38:
    /* 269FB8 00369F38 9AA70D0C */  jal        func_00369E68
    /* 269FBC 00369F3C 00000000 */   nop
    /* 269FC0 00369F40 02000010 */  b          .L00369F4C
    /* 269FC4 00369F44 2D184000 */   daddu     $v1, $v0, $zero
  .L00369F48:
    /* 269FC8 00369F48 01000324 */  addiu      $v1, $zero, 0x1
  .L00369F4C:
    /* 269FCC 00369F4C 2D106000 */  daddu      $v0, $v1, $zero
  .L00369F50:
    /* 269FD0 00369F50 0000BFDF */  ld         $ra, 0x0($sp)
  .L00369F54:
    /* 269FD4 00369F54 0800E003 */  jr         $ra
    /* 269FD8 00369F58 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 269FDC 00369F5C 00000000 */  nop
.size func_00369E98, . - func_00369E98

glabel func_00369F60
    /* 269FE0 00369F60 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 269FE4 00369F64 0000B0FF */  sd         $s0, 0x0($sp)
    /* 269FE8 00369F68 0800BFFF */  sd         $ra, 0x8($sp)
    /* 269FEC 00369F6C 70DB0D0C */  jal        func_00376DC0
    /* 269FF0 00369F70 2D808000 */   daddu     $s0, $a0, $zero
    /* 269FF4 00369F74 2D304000 */  daddu      $a2, $v0, $zero
    /* 269FF8 00369F78 10000224 */  addiu      $v0, $zero, 0x10
    /* 269FFC 00369F7C 1100C32C */  sltiu      $v1, $a2, 0x11
    /* 26A000 00369F80 0A304300 */  movz       $a2, $v0, $v1
    /* 26A004 00369F84 0D00C010 */  beqz       $a2, .L00369FBC
    /* 26A008 00369F88 2D280000 */   daddu     $a1, $zero, $zero
    /* 26A00C 00369F8C 3A000724 */  addiu      $a3, $zero, 0x3A
    /* 26A010 00369F90 21100502 */  addu       $v0, $s0, $a1
    /* 26A014 00369F94 00000000 */  nop
  .L00369F98:
    /* 26A018 00369F98 0100A524 */  addiu      $a1, $a1, 0x1
    /* 26A01C 00369F9C 00004380 */  lb         $v1, 0x0($v0)
    /* 26A020 00369FA0 01000224 */  addiu      $v0, $zero, 0x1
    /* 26A024 00369FA4 06006710 */  beq        $v1, $a3, .L00369FC0
    /* 26A028 00369FA8 2B20A600 */   sltu      $a0, $a1, $a2
    /* 26A02C 00369FAC 00000000 */  nop
    /* 26A030 00369FB0 00000000 */  nop
    /* 26A034 00369FB4 F8FF8014 */  bnez       $a0, .L00369F98
    /* 26A038 00369FB8 21100502 */   addu      $v0, $s0, $a1
  .L00369FBC:
    /* 26A03C 00369FBC 2D100000 */  daddu      $v0, $zero, $zero
  .L00369FC0:
    /* 26A040 00369FC0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26A044 00369FC4 0800BFDF */  ld         $ra, 0x8($sp)
    /* 26A048 00369FC8 0800E003 */  jr         $ra
    /* 26A04C 00369FCC 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_00369F60, . - func_00369F60

glabel func_00369FD0
    /* 26A050 00369FD0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 26A054 00369FD4 06000624 */  addiu      $a2, $zero, 0x6
    /* 26A058 00369FD8 1000B0FF */  sd         $s0, 0x10($sp)
    /* 26A05C 00369FDC 2D808000 */  daddu      $s0, $a0, $zero
    /* 26A060 00369FE0 2D280000 */  daddu      $a1, $zero, $zero
    /* 26A064 00369FE4 1800BFFF */  sd         $ra, 0x18($sp)
    /* 26A068 00369FE8 84D40D0C */  jal        func_00375210
    /* 26A06C 00369FEC 2D20A003 */   daddu     $a0, $sp, $zero
    /* 26A070 00369FF0 0300028A */  lwl        $v0, 0x3($s0)
    /* 26A074 00369FF4 0000029A */  lwr        $v0, 0x0($s0)
    /* 26A078 00369FF8 0300A2AB */  swl        $v0, 0x3($sp)
    /* 26A07C 00369FFC 4E00053C */  lui        $a1, %hi(D_4DCB78)
    /* 26A080 0036A000 78CBA524 */  addiu      $a1, $a1, %lo(D_4DCB78)
    /* 26A084 0036A004 2D20A003 */  daddu      $a0, $sp, $zero
    /* 26A088 0036A008 0000A2BB */  swr        $v0, 0x0($sp)
    /* 26A08C 0036A00C D8DA0D0C */  jal        func_00376B60
    /* 26A090 0036A010 0500A0A3 */   sb        $zero, 0x5($sp)
    /* 26A094 0036A014 1000B0DF */  ld         $s0, 0x10($sp)
    /* 26A098 0036A018 0100422C */  sltiu      $v0, $v0, 0x1
    /* 26A09C 0036A01C 1800BFDF */  ld         $ra, 0x18($sp)
    /* 26A0A0 0036A020 0800E003 */  jr         $ra
    /* 26A0A4 0036A024 2000BD27 */   addiu     $sp, $sp, 0x20
.size func_00369FD0, . - func_00369FD0

glabel func_0036A028
    /* 26A0A8 0036A028 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 26A0AC 0036A02C 0800B1FF */  sd         $s1, 0x8($sp)
    /* 26A0B0 0036A030 2D88A000 */  daddu      $s1, $a1, $zero
    /* 26A0B4 0036A034 1000B2FF */  sd         $s2, 0x10($sp)
    /* 26A0B8 0036A038 2D908000 */  daddu      $s2, $a0, $zero
    /* 26A0BC 0036A03C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26A0C0 0036A040 1800BFFF */  sd         $ra, 0x18($sp)
    /* 26A0C4 0036A044 D8A70D0C */  jal        func_00369F60
    /* 26A0C8 0036A048 000020A2 */   sb        $zero, 0x0($s1)
    /* 26A0CC 0036A04C 04004014 */  bnez       $v0, .L0036A060
    /* 26A0D0 0036A050 4300053C */   lui       $a1, %hi(D_437E10)
    /* 26A0D4 0036A054 2D202002 */  daddu      $a0, $s1, $zero
    /* 26A0D8 0036A058 2ADB0D0C */  jal        func_00376CA8
    /* 26A0DC 0036A05C 107EA524 */   addiu     $a1, $a1, %lo(D_437E10)
  .L0036A060:
    /* 26A0E0 0036A060 F4A70D0C */  jal        func_00369FD0
    /* 26A0E4 0036A064 2D202002 */   daddu     $a0, $s1, $zero
    /* 26A0E8 0036A068 01000324 */  addiu      $v1, $zero, 0x1
    /* 26A0EC 0036A06C 1A004354 */  bnel       $v0, $v1, .L0036A0D8
    /* 26A0F0 0036A070 2D284002 */   daddu     $a1, $s2, $zero
    /* 26A0F4 0036A074 4300103C */  lui        $s0, %hi(D_437D08)
    /* 26A0F8 0036A078 2D202002 */  daddu      $a0, $s1, $zero
    /* 26A0FC 0036A07C 087D1026 */  addiu      $s0, $s0, %lo(D_437D08)
    /* 26A100 0036A080 28DA0D0C */  jal        func_003768A0
    /* 26A104 0036A084 2D280002 */   daddu     $a1, $s0, $zero
    /* 26A108 0036A088 70DB0D0C */  jal        func_00376DC0
    /* 26A10C 0036A08C 2D200002 */   daddu     $a0, $s0, $zero
    /* 26A110 0036A090 5C000424 */  addiu      $a0, $zero, 0x5C
    /* 26A114 0036A094 21105000 */  addu       $v0, $v0, $s0
    /* 26A118 0036A098 FFFF4280 */  lb         $v0, -0x1($v0)
    /* 26A11C 0036A09C 0D004410 */  beq        $v0, $a0, .L0036A0D4
    /* 26A120 0036A0A0 2F000324 */   addiu     $v1, $zero, 0x2F
    /* 26A124 0036A0A4 0C004310 */  beq        $v0, $v1, .L0036A0D8
    /* 26A128 0036A0A8 2D284002 */   daddu     $a1, $s2, $zero
    /* 26A12C 0036A0AC 0A004010 */  beqz       $v0, .L0036A0D8
    /* 26A130 0036A0B0 00000000 */   nop
    /* 26A134 0036A0B4 00004282 */  lb         $v0, 0x0($s2)
    /* 26A138 0036A0B8 07004410 */  beq        $v0, $a0, .L0036A0D8
    /* 26A13C 0036A0BC 00000000 */   nop
    /* 26A140 0036A0C0 04004310 */  beq        $v0, $v1, .L0036A0D4
    /* 26A144 0036A0C4 4E00053C */   lui       $a1, %hi(D_4DCB80)
    /* 26A148 0036A0C8 2D202002 */  daddu      $a0, $s1, $zero
    /* 26A14C 0036A0CC 28DA0D0C */  jal        func_003768A0
    /* 26A150 0036A0D0 80CBA524 */   addiu     $a1, $a1, %lo(D_4DCB80)
  .L0036A0D4:
    /* 26A154 0036A0D4 2D284002 */  daddu      $a1, $s2, $zero
  .L0036A0D8:
    /* 26A158 0036A0D8 28DA0D0C */  jal        func_003768A0
    /* 26A15C 0036A0DC 2D202002 */   daddu     $a0, $s1, $zero
    /* 26A160 0036A0E0 70DB0D0C */  jal        func_00376DC0
    /* 26A164 0036A0E4 2D202002 */   daddu     $a0, $s1, $zero
    /* 26A168 0036A0E8 2D304000 */  daddu      $a2, $v0, $zero
    /* 26A16C 0036A0EC 0D00C018 */  blez       $a2, .L0036A124
    /* 26A170 0036A0F0 2D280000 */   daddu     $a1, $zero, $zero
    /* 26A174 0036A0F4 5C000824 */  addiu      $t0, $zero, 0x5C
    /* 26A178 0036A0F8 2F000724 */  addiu      $a3, $zero, 0x2F
    /* 26A17C 0036A0FC 21202502 */  addu       $a0, $s1, $a1
  .L0036A100:
    /* 26A180 0036A100 0100A524 */  addiu      $a1, $a1, 0x1
    /* 26A184 0036A104 00008280 */  lb         $v0, 0x0($a0)
    /* 26A188 0036A108 02004814 */  bne        $v0, $t0, .L0036A114
    /* 26A18C 0036A10C 2A18A600 */   slt       $v1, $a1, $a2
    /* 26A190 0036A110 000087A0 */  sb         $a3, 0x0($a0)
  .L0036A114:
    /* 26A194 0036A114 00000000 */  nop
    /* 26A198 0036A118 00000000 */  nop
    /* 26A19C 0036A11C F8FF6014 */  bnez       $v1, .L0036A100
    /* 26A1A0 0036A120 21202502 */   addu      $a0, $s1, $a1
  .L0036A124:
    /* 26A1A4 0036A124 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26A1A8 0036A128 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26A1AC 0036A12C 1000B2DF */  ld         $s2, 0x10($sp)
    /* 26A1B0 0036A130 1800BFDF */  ld         $ra, 0x18($sp)
    /* 26A1B4 0036A134 0800E003 */  jr         $ra
    /* 26A1B8 0036A138 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 26A1BC 0036A13C 00000000 */  nop
.size func_0036A028, . - func_0036A028

glabel func_0036A140
    /* 26A1C0 0036A140 00260400 */  sll        $a0, $a0, 24
    /* 26A1C4 0036A144 2F000224 */  addiu      $v0, $zero, 0x2F
    /* 26A1C8 0036A148 03260400 */  sra        $a0, $a0, 24
    /* 26A1CC 0036A14C 5C008338 */  xori       $v1, $a0, 0x5C
    /* 26A1D0 0036A150 0800E003 */  jr         $ra
    /* 26A1D4 0036A154 0B108300 */   movn      $v0, $a0, $v1
.size func_0036A140, . - func_0036A140

glabel func_0036A158
    /* 26A1D8 0036A158 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 26A1DC 0036A15C 00260400 */  sll        $a0, $a0, 24
    /* 26A1E0 0036A160 0800B1FF */  sd         $s1, 0x8($sp)
    /* 26A1E4 0036A164 008E0500 */  sll        $s1, $a1, 24
    /* 26A1E8 0036A168 038E1100 */  sra        $s1, $s1, 24
    /* 26A1EC 0036A16C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26A1F0 0036A170 1000BFFF */  sd         $ra, 0x10($sp)
    /* 26A1F4 0036A174 50A80D0C */  jal        func_0036A140
    /* 26A1F8 0036A178 03260400 */   sra       $a0, $a0, 24
    /* 26A1FC 0036A17C 2D202002 */  daddu      $a0, $s1, $zero
    /* 26A200 0036A180 50A80D0C */  jal        func_0036A140
    /* 26A204 0036A184 2D804000 */   daddu     $s0, $v0, $zero
    /* 26A208 0036A188 FFFF0324 */  addiu      $v1, $zero, -0x1
    /* 26A20C 0036A18C 26800202 */  xor        $s0, $s0, $v0
    /* 26A210 0036A190 2D100000 */  daddu      $v0, $zero, $zero
    /* 26A214 0036A194 0B107000 */  movn       $v0, $v1, $s0
    /* 26A218 0036A198 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26A21C 0036A19C 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26A220 0036A1A0 1000BFDF */  ld         $ra, 0x10($sp)
    /* 26A224 0036A1A4 0800E003 */  jr         $ra
    /* 26A228 0036A1A8 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 26A22C 0036A1AC 00000000 */  nop
.size func_0036A158, . - func_0036A158

glabel func_0036A1B0
    /* 26A230 0036A1B0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 26A234 0036A1B4 1000B2FF */  sd         $s2, 0x10($sp)
    /* 26A238 0036A1B8 2D90A000 */  daddu      $s2, $a1, $zero
    /* 26A23C 0036A1BC 0800B1FF */  sd         $s1, 0x8($sp)
    /* 26A240 0036A1C0 1800B3FF */  sd         $s3, 0x18($sp)
    /* 26A244 0036A1C4 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26A248 0036A1C8 2000BFFF */  sd         $ra, 0x20($sp)
    /* 26A24C 0036A1CC 70DB0D0C */  jal        func_00376DC0
    /* 26A250 0036A1D0 2D988000 */   daddu     $s3, $a0, $zero
    /* 26A254 0036A1D4 2D204002 */  daddu      $a0, $s2, $zero
    /* 26A258 0036A1D8 70DB0D0C */  jal        func_00376DC0
    /* 26A25C 0036A1DC 2D884000 */   daddu     $s1, $v0, $zero
    /* 26A260 0036A1E0 03002212 */  beq        $s1, $v0, .L0036A1F0
    /* 26A264 0036A1E4 00000000 */   nop
  .L0036A1E8:
    /* 26A268 0036A1E8 0F000010 */  b          .L0036A228
    /* 26A26C 0036A1EC FFFF0224 */   addiu     $v0, $zero, -0x1
  .L0036A1F0:
    /* 26A270 0036A1F0 0C00201A */  blez       $s1, .L0036A224
    /* 26A274 0036A1F4 2D800000 */   daddu     $s0, $zero, $zero
    /* 26A278 0036A1F8 21185002 */  addu       $v1, $s2, $s0
    /* 26A27C 0036A1FC 00000000 */  nop
  .L0036A200:
    /* 26A280 0036A200 21107002 */  addu       $v0, $s3, $s0
    /* 26A284 0036A204 00006580 */  lb         $a1, 0x0($v1)
    /* 26A288 0036A208 01001026 */  addiu      $s0, $s0, 0x1
    /* 26A28C 0036A20C 56A80D0C */  jal        func_0036A158
    /* 26A290 0036A210 00004480 */   lb        $a0, 0x0($v0)
    /* 26A294 0036A214 F4FF4014 */  bnez       $v0, .L0036A1E8
    /* 26A298 0036A218 2A181102 */   slt       $v1, $s0, $s1
    /* 26A29C 0036A21C F8FF6014 */  bnez       $v1, .L0036A200
    /* 26A2A0 0036A220 21185002 */   addu      $v1, $s2, $s0
  .L0036A224:
    /* 26A2A4 0036A224 2D100000 */  daddu      $v0, $zero, $zero
  .L0036A228:
    /* 26A2A8 0036A228 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26A2AC 0036A22C 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26A2B0 0036A230 1000B2DF */  ld         $s2, 0x10($sp)
    /* 26A2B4 0036A234 1800B3DF */  ld         $s3, 0x18($sp)
    /* 26A2B8 0036A238 2000BFDF */  ld         $ra, 0x20($sp)
    /* 26A2BC 0036A23C 0800E003 */  jr         $ra
    /* 26A2C0 0036A240 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 26A2C4 0036A244 00000000 */  nop
.size func_0036A1B0, . - func_0036A1B0
