.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036A248
    /* 26A2C8 0036A248 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 26A2CC 0036A24C 2000B2FF */  sd         $s2, 0x20($sp)
    /* 26A2D0 0036A250 2D900000 */  daddu      $s2, $zero, $zero
    /* 26A2D4 0036A254 2800B3FF */  sd         $s3, 0x28($sp)
    /* 26A2D8 0036A258 2D98A000 */  daddu      $s3, $a1, $zero
    /* 26A2DC 0036A25C 3000B4FF */  sd         $s4, 0x30($sp)
    /* 26A2E0 0036A260 2DA00000 */  daddu      $s4, $zero, $zero
    /* 26A2E4 0036A264 3800B5FF */  sd         $s5, 0x38($sp)
    /* 26A2E8 0036A268 2DA8C000 */  daddu      $s5, $a2, $zero
    /* 26A2EC 0036A26C 5000BEFF */  sd         $fp, 0x50($sp)
    /* 26A2F0 0036A270 2DF0E000 */  daddu      $fp, $a3, $zero
    /* 26A2F4 0036A274 1000B0FF */  sd         $s0, 0x10($sp)
    /* 26A2F8 0036A278 1800B1FF */  sd         $s1, 0x18($sp)
    /* 26A2FC 0036A27C 4000B6FF */  sd         $s6, 0x40($sp)
    /* 26A300 0036A280 4800B7FF */  sd         $s7, 0x48($sp)
    /* 26A304 0036A284 5800BFFF */  sd         $ra, 0x58($sp)
    /* 26A308 0036A288 0000A4AF */  sw         $a0, 0x0($sp)
    /* 26A30C 0036A28C 00006282 */  lb         $v0, 0x0($s3)
    /* 26A310 0036A290 3D004010 */  beqz       $v0, .L0036A388
    /* 26A314 0036A294 2D280000 */   daddu     $a1, $zero, $zero
    /* 26A318 0036A298 C0101500 */  sll        $v0, $s5, 3
    /* 26A31C 0036A29C 2D206002 */  daddu      $a0, $s3, $zero
    /* 26A320 0036A2A0 0400A2AF */  sw         $v0, 0x4($sp)
    /* 26A324 0036A2A4 0A001724 */  addiu      $s7, $zero, 0xA
    /* 26A328 0036A2A8 0D001624 */  addiu      $s6, $zero, 0xD
    /* 26A32C 0036A2AC 00008280 */  lb         $v0, 0x0($a0)
  .L0036A2B0:
    /* 26A330 0036A2B0 5C000624 */  addiu      $a2, $zero, 0x5C
    /* 26A334 0036A2B4 04004614 */  bne        $v0, $a2, .L0036A2C8
    /* 26A338 0036A2B8 00008390 */   lbu       $v1, 0x0($a0)
    /* 26A33C 0036A2BC 2F000224 */  addiu      $v0, $zero, 0x2F
    /* 26A340 0036A2C0 2F000324 */  addiu      $v1, $zero, 0x2F
    /* 26A344 0036A2C4 000082A0 */  sb         $v0, 0x0($a0)
  .L0036A2C8:
    /* 26A348 0036A2C8 00160300 */  sll        $v0, $v1, 24
    /* 26A34C 0036A2CC 03160200 */  sra        $v0, $v0, 24
    /* 26A350 0036A2D0 06005750 */  beql       $v0, $s7, .L0036A2EC
    /* 26A354 0036A2D4 01008280 */   lb        $v0, 0x1($a0)
    /* 26A358 0036A2D8 04005650 */  beql       $v0, $s6, .L0036A2EC
    /* 26A35C 0036A2DC 01008280 */   lb        $v0, 0x1($a0)
    /* 26A360 0036A2E0 23004014 */  bnez       $v0, .L0036A370
    /* 26A364 0036A2E4 01004326 */   addiu     $v1, $s2, 0x1
    /* 26A368 0036A2E8 01008280 */  lb         $v0, 0x1($a0)
  .L0036A2EC:
    /* 26A36C 0036A2EC 06005750 */  beql       $v0, $s7, .L0036A308
    /* 26A370 0036A2F0 01005226 */   addiu     $s2, $s2, 0x1
    /* 26A374 0036A2F4 04005650 */  beql       $v0, $s6, .L0036A308
    /* 26A378 0036A2F8 01005226 */   addiu     $s2, $s2, 0x1
    /* 26A37C 0036A2FC 04004014 */  bnez       $v0, .L0036A310
    /* 26A380 0036A300 FFFF8224 */   addiu     $v0, $a0, -0x1
    /* 26A384 0036A304 01005226 */  addiu      $s2, $s2, 0x1
  .L0036A308:
    /* 26A388 0036A308 21207202 */  addu       $a0, $s3, $s2
    /* 26A38C 0036A30C FFFF8224 */  addiu      $v0, $a0, -0x1
  .L0036A310:
    /* 26A390 0036A310 00004380 */  lb         $v1, 0x0($v0)
    /* 26A394 0036A314 03007710 */  beq        $v1, $s7, .L0036A324
    /* 26A398 0036A318 23884502 */   subu      $s1, $s2, $a1
    /* 26A39C 0036A31C 03007654 */  bnel       $v1, $s6, .L0036A32C
    /* 26A3A0 0036A320 1810D403 */   mult      $v0, $fp, $s4
  .L0036A324:
    /* 26A3A4 0036A324 000040A0 */  sb         $zero, 0x0($v0)
    /* 26A3A8 0036A328 1810D403 */  mult       $v0, $fp, $s4
  .L0036A32C:
    /* 26A3AC 0036A32C 0400A38F */  lw         $v1, 0x4($sp)
    /* 26A3B0 0036A330 2D302002 */  daddu      $a2, $s1, $zero
    /* 26A3B4 0036A334 21286502 */  addu       $a1, $s3, $a1
    /* 26A3B8 0036A338 21805400 */  addu       $s0, $v0, $s4
    /* 26A3BC 0036A33C 0000A28F */  lw         $v0, 0x0($sp)
    /* 26A3C0 0036A340 21807000 */  addu       $s0, $v1, $s0
    /* 26A3C4 0036A344 21805000 */  addu       $s0, $v0, $s0
    /* 26A3C8 0036A348 16D40D0C */  jal        func_00375058
    /* 26A3CC 0036A34C 2D200002 */   daddu     $a0, $s0, $zero
    /* 26A3D0 0036A350 21301102 */  addu       $a2, $s0, $s1
    /* 26A3D4 0036A354 FFFFC280 */  lb         $v0, -0x1($a2)
    /* 26A3D8 0036A358 01004054 */  bnel       $v0, $zero, .L0036A360
    /* 26A3DC 0036A35C 0000C0A0 */   sb        $zero, 0x0($a2)
  .L0036A360:
    /* 26A3E0 0036A360 01004326 */  addiu      $v1, $s2, 0x1
    /* 26A3E4 0036A364 01009426 */  addiu      $s4, $s4, 0x1
    /* 26A3E8 0036A368 07009512 */  beq        $s4, $s5, .L0036A388
    /* 26A3EC 0036A36C 2D286000 */   daddu     $a1, $v1, $zero
  .L0036A370:
    /* 26A3F0 0036A370 2D906000 */  daddu      $s2, $v1, $zero
    /* 26A3F4 0036A374 21107202 */  addu       $v0, $s3, $s2
    /* 26A3F8 0036A378 2D204000 */  daddu      $a0, $v0, $zero
    /* 26A3FC 0036A37C 00008380 */  lb         $v1, 0x0($a0)
    /* 26A400 0036A380 CBFF6054 */  bnel       $v1, $zero, .L0036A2B0
    /* 26A404 0036A384 00008280 */   lb        $v0, 0x0($a0)
  .L0036A388:
    /* 26A408 0036A388 4300023C */  lui        $v0, %hi(D_00437CF0)
    /* 26A40C 0036A38C F07C4224 */  addiu      $v0, $v0, %lo(D_00437CF0)
    /* 26A410 0036A390 0000438C */  lw         $v1, 0x0($v0)
    /* 26A414 0036A394 07006054 */  bnel       $v1, $zero, .L0036A3B4
    /* 26A418 0036A398 2D108002 */   daddu     $v0, $s4, $zero
    /* 26A41C 0036A39C 0C005EAC */  sw         $fp, 0xC($v0)
    /* 26A420 0036A3A0 0000A38F */  lw         $v1, 0x0($sp)
    /* 26A424 0036A3A4 080055AC */  sw         $s5, 0x8($v0)
    /* 26A428 0036A3A8 000043AC */  sw         $v1, 0x0($v0)
    /* 26A42C 0036A3AC 040054AC */  sw         $s4, 0x4($v0)
    /* 26A430 0036A3B0 2D108002 */  daddu      $v0, $s4, $zero
  .L0036A3B4:
    /* 26A434 0036A3B4 1000B0DF */  ld         $s0, 0x10($sp)
    /* 26A438 0036A3B8 1800B1DF */  ld         $s1, 0x18($sp)
    /* 26A43C 0036A3BC 2000B2DF */  ld         $s2, 0x20($sp)
    /* 26A440 0036A3C0 2800B3DF */  ld         $s3, 0x28($sp)
    /* 26A444 0036A3C4 3000B4DF */  ld         $s4, 0x30($sp)
    /* 26A448 0036A3C8 3800B5DF */  ld         $s5, 0x38($sp)
    /* 26A44C 0036A3CC 4000B6DF */  ld         $s6, 0x40($sp)
    /* 26A450 0036A3D0 4800B7DF */  ld         $s7, 0x48($sp)
    /* 26A454 0036A3D4 5000BEDF */  ld         $fp, 0x50($sp)
    /* 26A458 0036A3D8 5800BFDF */  ld         $ra, 0x58($sp)
    /* 26A45C 0036A3DC 0800E003 */  jr         $ra
    /* 26A460 0036A3E0 6000BD27 */   addiu     $sp, $sp, 0x60
    /* 26A464 0036A3E4 00000000 */  nop
.size func_0036A248, . - func_0036A248
