.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036ACC8
    /* 26AD48 0036ACC8 4300033C */  lui        $v1, %hi(D_00437D00)
    /* 26AD4C 0036ACCC 0800E003 */  jr         $ra
    /* 26AD50 0036ACD0 007D628C */   lw        $v0, %lo(D_00437D00)($v1)
    /* 26AD54 0036ACD4 00000000 */  nop
.size func_0036ACC8, . - func_0036ACC8
