.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036BF68
    /* 26BFE8 0036BF68 2D308000 */  daddu      $a2, $a0, $zero
    /* 26BFEC 0036BF6C 2D280000 */  daddu      $a1, $zero, $zero
    /* 26BFF0 0036BF70 0800C88C */  lw         $t0, 0x8($a2)
    /* 26BFF4 0036BF74 0C00C78C */  lw         $a3, 0xC($a2)
  .L0036BF78:
    /* 26BFF8 0036BF78 80100500 */  sll        $v0, $a1, 2
    /* 26BFFC 0036BF7C 0100A524 */  addiu      $a1, $a1, 0x1
    /* 26C000 0036BF80 21204700 */  addu       $a0, $v0, $a3
    /* 26C004 0036BF84 21104800 */  addu       $v0, $v0, $t0
    /* 26C008 0036BF88 6000A328 */  slti       $v1, $a1, 0x60
    /* 26C00C 0036BF8C 000040AC */  sw         $zero, 0x0($v0)
    /* 26C010 0036BF90 F9FF6014 */  bnez       $v1, .L0036BF78
    /* 26C014 0036BF94 000080AC */   sw        $zero, 0x0($a0)
    /* 26C018 0036BF98 40000224 */  addiu      $v0, $zero, 0x40
    /* 26C01C 0036BF9C 1400C0AC */  sw         $zero, 0x14($a2)
    /* 26C020 0036BFA0 0800E003 */  jr         $ra
    /* 26C024 0036BFA4 1800C2AC */   sw        $v0, 0x18($a2)
.size func_0036BF68, . - func_0036BF68

glabel func_0036BFA8
    /* 26C028 0036BFA8 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 26C02C 0036BFAC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26C030 0036BFB0 00840500 */  sll        $s0, $a1, 16
    /* 26C034 0036BFB4 0800B1FF */  sd         $s1, 0x8($sp)
    /* 26C038 0036BFB8 2D888000 */  daddu      $s1, $a0, $zero
    /* 26C03C 0036BFBC 1000B2FF */  sd         $s2, 0x10($sp)
    /* 26C040 0036BFC0 2D90C000 */  daddu      $s2, $a2, $zero
    /* 26C044 0036BFC4 1800B3FF */  sd         $s3, 0x18($sp)
    /* 26C048 0036BFC8 2D98E000 */  daddu      $s3, $a3, $zero
    /* 26C04C 0036BFCC 2000BFFF */  sd         $ra, 0x20($sp)
    /* 26C050 0036BFD0 0CAF0D0C */  jal        func_0036BC30
    /* 26C054 0036BFD4 03841000 */   sra       $s0, $s0, 16
    /* 26C058 0036BFD8 2D202002 */  daddu      $a0, $s1, $zero
    /* 26C05C 0036BFDC 2D280002 */  daddu      $a1, $s0, $zero
    /* 26C060 0036BFE0 2D304002 */  daddu      $a2, $s2, $zero
    /* 26C064 0036BFE4 02B00D0C */  jal        func_0036C008
    /* 26C068 0036BFE8 2D386002 */   daddu     $a3, $s3, $zero
    /* 26C06C 0036BFEC 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26C070 0036BFF0 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26C074 0036BFF4 1000B2DF */  ld         $s2, 0x10($sp)
    /* 26C078 0036BFF8 1800B3DF */  ld         $s3, 0x18($sp)
    /* 26C07C 0036BFFC 2000BFDF */  ld         $ra, 0x20($sp)
    /* 26C080 0036C000 12AF0D08 */  j          func_0036BC48
    /* 26C084 0036C004 3000BD27 */   addiu     $sp, $sp, 0x30
.size func_0036BFA8, . - func_0036BFA8

glabel func_0036C008
    /* 26C088 0036C008 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 26C08C 0036C00C 2DC08000 */  daddu      $t8, $a0, $zero
    /* 26C090 0036C010 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26C094 0036C014 4E000D3C */  lui        $t5, %hi(D_4DCEE0)
    /* 26C098 0036C018 E0CEAD25 */  addiu      $t5, $t5, %lo(D_4DCEE0)
    /* 26C09C 0036C01C 002C0500 */  sll        $a1, $a1, 16
    /* 26C0A0 0036C020 1C00038F */  lw         $v1, 0x1C($t8)
    /* 26C0A4 0036C024 032C0500 */  sra        $a1, $a1, 16
    /* 26C0A8 0036C028 2000028F */  lw         $v0, 0x20($t8)
    /* 26C0AC 0036C02C 11F20B24 */  addiu      $t3, $zero, -0xDEF
    /* 26C0B0 0036C030 80180300 */  sll        $v1, $v1, 2
    /* 26C0B4 0036C034 2AF80F24 */  addiu      $t7, $zero, -0x7D6
    /* 26C0B8 0036C038 80100200 */  sll        $v0, $v0, 2
    /* 26C0BC 0036C03C 21186D00 */  addu       $v1, $v1, $t5
    /* 26C0C0 0036C040 21104D00 */  addu       $v0, $v0, $t5
    /* 26C0C4 0036C044 0000648C */  lw         $a0, 0x0($v1)
    /* 26C0C8 0036C048 0000488C */  lw         $t0, 0x0($v0)
    /* 26C0CC 0036C04C 2800028F */  lw         $v0, 0x28($t8)
    /* 26C0D0 0036C050 1820A400 */  mult       $a0, $a1, $a0
    /* 26C0D4 0036C054 1828A870 */  mult1      $a1, $a1, $t0
    /* 26C0D8 0036C058 0800088F */  lw         $t0, 0x8($t8)
    /* 26C0DC 0036C05C 80100200 */  sll        $v0, $v0, 2
    /* 26C0E0 0036C060 14000A8F */  lw         $t2, 0x14($t8)
    /* 26C0E4 0036C064 21104D00 */  addu       $v0, $v0, $t5
    /* 26C0E8 0036C068 24000C8F */  lw         $t4, 0x24($t8)
    /* 26C0EC 0036C06C 0000438C */  lw         $v1, 0x0($v0)
    /* 26C0F0 0036C070 EF0D0224 */  addiu      $v0, $zero, 0xDEF
    /* 26C0F4 0036C074 03230400 */  sra        $a0, $a0, 12
    /* 26C0F8 0036C078 032B0500 */  sra        $a1, $a1, 12
    /* 26C0FC 0036C07C 1848A300 */  mult       $t1, $a1, $v1
    /* 26C100 0036C080 18188370 */  mult1      $v1, $a0, $v1
    /* 26C104 0036C084 0C00108F */  lw         $s0, 0xC($t8)
    /* 26C108 0036C088 80700A00 */  sll        $t6, $t2, 2
    /* 26C10C 0036C08C 2D50C001 */  daddu      $t2, $t6, $zero
    /* 26C110 0036C090 2170C801 */  addu       $t6, $t6, $t0
    /* 26C114 0036C094 80600C00 */  sll        $t4, $t4, 2
    /* 26C118 0036C098 D6070824 */  addiu      $t0, $zero, 0x7D6
    /* 26C11C 0036C09C 031B0300 */  sra        $v1, $v1, 12
    /* 26C120 0036C0A0 034B0900 */  sra        $t1, $t1, 12
    /* 26C124 0036C0A4 18586B00 */  mult       $t3, $v1, $t3
    /* 26C128 0036C0A8 18186870 */  mult1      $v1, $v1, $t0
    /* 26C12C 0036C0AC 18782F71 */  mult1      $t7, $t1, $t7
    /* 26C130 0036C0B0 18482201 */  mult       $t1, $t1, $v0
    /* 26C134 0036C0B4 21608D01 */  addu       $t4, $t4, $t5
    /* 26C138 0036C0B8 21685001 */  addu       $t5, $t2, $s0
    /* 26C13C 0036C0BC 2D50C001 */  daddu      $t2, $t6, $zero
    /* 26C140 0036C0C0 0000828D */  lw         $v0, 0x0($t4)
    /* 26C144 0036C0C4 0000A88D */  lw         $t0, 0x0($t5)
    /* 26C148 0036C0C8 21586F01 */  addu       $t3, $t3, $t7
    /* 26C14C 0036C0CC 00004C8D */  lw         $t4, 0x0($t2)
    /* 26C150 0036C0D0 035B0B00 */  sra        $t3, $t3, 12
    /* 26C154 0036C0D4 1828A200 */  mult       $a1, $a1, $v0
    /* 26C158 0036C0D8 0000CBAD */  sw         $t3, 0x0($t6)
    /* 26C15C 0036C0DC FF7F0B24 */  addiu      $t3, $zero, 0x7FFF
    /* 26C160 0036C0E0 18208270 */  mult1      $a0, $a0, $v0
    /* 26C164 0036C0E4 21482301 */  addu       $t1, $t1, $v1
    /* 26C168 0036C0E8 1400028F */  lw         $v0, 0x14($t8)
    /* 26C16C 0036C0EC 034B0900 */  sra        $t1, $t1, 12
    /* 26C170 0036C0F0 032B0500 */  sra        $a1, $a1, 12
    /* 26C174 0036C0F4 FF7F0A24 */  addiu      $t2, $zero, 0x7FFF
    /* 26C178 0036C0F8 80100200 */  sll        $v0, $v0, 2
    /* 26C17C 0036C0FC 2128A800 */  addu       $a1, $a1, $t0
    /* 26C180 0036C100 21105000 */  addu       $v0, $v0, $s0
    /* 26C184 0036C104 03230400 */  sra        $a0, $a0, 12
    /* 26C188 0036C108 000049AC */  sw         $t1, 0x0($v0)
    /* 26C18C 0036C10C 00800224 */  addiu      $v0, $zero, -0x8000
    /* 26C190 0036C110 21208C00 */  addu       $a0, $a0, $t4
    /* 26C194 0036C114 00800C24 */  addiu      $t4, $zero, -0x8000
    /* 26C198 0036C118 1400088F */  lw         $t0, 0x14($t8)
    /* 26C19C 0036C11C 2A504401 */  slt        $t2, $t2, $a0
    /* 26C1A0 0036C120 2A586501 */  slt        $t3, $t3, $a1
    /* 26C1A4 0036C124 0080A328 */  slti       $v1, $a1, -0x8000
    /* 26C1A8 0036C128 00808D28 */  slti       $t5, $a0, -0x8000
    /* 26C1AC 0036C12C 1800098F */  lw         $t1, 0x18($t8)
    /* 26C1B0 0036C130 0B284300 */  movn       $a1, $v0, $v1
    /* 26C1B4 0036C134 FF7F0224 */  addiu      $v0, $zero, 0x7FFF
    /* 26C1B8 0036C138 01000825 */  addiu      $t0, $t0, 0x1
    /* 26C1BC 0036C13C 0B208D01 */  movn       $a0, $t4, $t5
    /* 26C1C0 0036C140 00004A39 */  xori       $t2, $t2, 0x0
    /* 26C1C4 0036C144 00006B39 */  xori       $t3, $t3, 0x0
    /* 26C1C8 0036C148 FF7F0324 */  addiu      $v1, $zero, 0x7FFF
    /* 26C1CC 0036C14C 0B204A00 */  movn       $a0, $v0, $t2
    /* 26C1D0 0036C150 0B286B00 */  movn       $a1, $v1, $t3
    /* 26C1D4 0036C154 2A480901 */  slt        $t1, $t0, $t1
    /* 26C1D8 0036C158 0000C4A4 */  sh         $a0, 0x0($a2)
    /* 26C1DC 0036C15C 140008AF */  sw         $t0, 0x14($t8)
    /* 26C1E0 0036C160 02002015 */  bnez       $t1, .L0036C16C
    /* 26C1E4 0036C164 0000E5A4 */   sh        $a1, 0x0($a3)
    /* 26C1E8 0036C168 140000AF */  sw         $zero, 0x14($t8)
  .L0036C16C:
    /* 26C1EC 0036C16C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26C1F0 0036C170 0800E003 */  jr         $ra
    /* 26C1F4 0036C174 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0036C008, . - func_0036C008

glabel func_0036C178
    /* 26C1F8 0036C178 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 26C1FC 0036C17C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26C200 0036C180 2D808000 */  daddu      $s0, $a0, $zero
    /* 26C204 0036C184 0800B1FF */  sd         $s1, 0x8($sp)
    /* 26C208 0036C188 2D88A000 */  daddu      $s1, $a1, $zero
    /* 26C20C 0036C18C 1000B2FF */  sd         $s2, 0x10($sp)
    /* 26C210 0036C190 2D90C000 */  daddu      $s2, $a2, $zero
    /* 26C214 0036C194 1800B3FF */  sd         $s3, 0x18($sp)
    /* 26C218 0036C198 2000BFFF */  sd         $ra, 0x20($sp)
    /* 26C21C 0036C19C 0CAF0D0C */  jal        func_0036BC30
    /* 26C220 0036C1A0 2D98E000 */   daddu     $s3, $a3, $zero
    /* 26C224 0036C1A4 2D200002 */  daddu      $a0, $s0, $zero
    /* 26C228 0036C1A8 2D282002 */  daddu      $a1, $s1, $zero
    /* 26C22C 0036C1AC 2D304002 */  daddu      $a2, $s2, $zero
    /* 26C230 0036C1B0 76B00D0C */  jal        func_0036C1D8
    /* 26C234 0036C1B4 2D386002 */   daddu     $a3, $s3, $zero
    /* 26C238 0036C1B8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26C23C 0036C1BC 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26C240 0036C1C0 1000B2DF */  ld         $s2, 0x10($sp)
    /* 26C244 0036C1C4 1800B3DF */  ld         $s3, 0x18($sp)
    /* 26C248 0036C1C8 2000BFDF */  ld         $ra, 0x20($sp)
    /* 26C24C 0036C1CC 12AF0D08 */  j          func_0036BC48
    /* 26C250 0036C1D0 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 26C254 0036C1D4 00000000 */  nop
.size func_0036C178, . - func_0036C178
