.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036C3C8
    /* 26C448 0036C3C8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 26C44C 0036C3CC 06008014 */  bnez       $a0, .L0036C3E8
    /* 26C450 0036C3D0 0000BFFF */   sd        $ra, 0x0($sp)
    /* 26C454 0036C3D4 4E00043C */  lui        $a0, %hi(D_004DD358)
    /* 26C458 0036C3D8 0000BFDF */  ld         $ra, 0x0($sp)
    /* 26C45C 0036C3DC 58D38424 */  addiu      $a0, $a0, %lo(D_004DD358)
    /* 26C460 0036C3E0 2EAF0D08 */  j          func_0036BCB8
    /* 26C464 0036C3E4 1000BD27 */   addiu     $sp, $sp, 0x10
  .L0036C3E8:
    /* 26C468 0036C3E8 7F00A324 */  addiu      $v1, $a1, 0x7F
    /* 26C46C 0036C3EC FF00622C */  sltiu      $v0, $v1, 0xFF
    /* 26C470 0036C3F0 08004050 */  beql       $v0, $zero, .L0036C414
    /* 26C474 0036C3F4 4E00043C */   lui       $a0, %hi(D_004DD380)
    /* 26C478 0036C3F8 81FFC228 */  slti       $v0, $a2, -0x7F
    /* 26C47C 0036C3FC 05004054 */  bnel       $v0, $zero, .L0036C414
    /* 26C480 0036C400 4E00043C */   lui       $a0, %hi(D_004DD380)
    /* 26C484 0036C404 8000C228 */  slti       $v0, $a2, 0x80
    /* 26C488 0036C408 07004014 */  bnez       $v0, .L0036C428
    /* 26C48C 0036C40C 81FFA724 */   addiu     $a3, $a1, -0x7F
    /* 26C490 0036C410 4E00043C */  lui        $a0, %hi(D_004DD380)
  .L0036C414:
    /* 26C494 0036C414 0000BFDF */  ld         $ra, 0x0($sp)
    /* 26C498 0036C418 80D38424 */  addiu      $a0, $a0, %lo(D_004DD380)
    /* 26C49C 0036C41C 2EAF0D08 */  j          func_0036BCB8
    /* 26C4A0 0036C420 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 26C4A4 0036C424 00000000 */  nop
  .L0036C428:
    /* 26C4A8 0036C428 02006104 */  bgez       $v1, .L0036C434
    /* 26C4AC 0036C42C 2D106000 */   daddu     $v0, $v1, $zero
    /* 26C4B0 0036C430 23100200 */  negu       $v0, $v0
  .L0036C434:
    /* 26C4B4 0036C434 0300E104 */  bgez       $a3, .L0036C444
    /* 26C4B8 0036C438 1C0082AC */   sw        $v0, 0x1C($a0)
    /* 26C4BC 0036C43C 7F000224 */  addiu      $v0, $zero, 0x7F
    /* 26C4C0 0036C440 23384500 */  subu       $a3, $v0, $a1
  .L0036C444:
    /* 26C4C4 0036C444 7F00C224 */  addiu      $v0, $a2, 0x7F
    /* 26C4C8 0036C448 81FFC324 */  addiu      $v1, $a2, -0x7F
    /* 26C4CC 0036C44C 01004204 */  bltzl      $v0, .L0036C454
    /* 26C4D0 0036C450 23100200 */   negu      $v0, $v0
  .L0036C454:
    /* 26C4D4 0036C454 200087AC */  sw         $a3, 0x20($a0)
    /* 26C4D8 0036C458 03006104 */  bgez       $v1, .L0036C468
    /* 26C4DC 0036C45C 240082AC */   sw        $v0, 0x24($a0)
    /* 26C4E0 0036C460 7F000224 */  addiu      $v0, $zero, 0x7F
    /* 26C4E4 0036C464 23184600 */  subu       $v1, $v0, $a2
  .L0036C468:
    /* 26C4E8 0036C468 0000BFDF */  ld         $ra, 0x0($sp)
    /* 26C4EC 0036C46C 280083AC */  sw         $v1, 0x28($a0)
    /* 26C4F0 0036C470 0800E003 */  jr         $ra
    /* 26C4F4 0036C474 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0036C3C8, . - func_0036C3C8

glabel func_0036C478
    /* 26C4F8 0036C478 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 26C4FC 0036C47C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26C500 0036C480 2D808000 */  daddu      $s0, $a0, $zero
    /* 26C504 0036C484 0800B1FF */  sd         $s1, 0x8($sp)
    /* 26C508 0036C488 1000BFFF */  sd         $ra, 0x10($sp)
    /* 26C50C 0036C48C 0CAF0D0C */  jal        func_0036BC30
    /* 26C510 0036C490 2D88A000 */   daddu     $s1, $a1, $zero
    /* 26C514 0036C494 2D200002 */  daddu      $a0, $s0, $zero
    /* 26C518 0036C498 2EB10D0C */  jal        func_0036C4B8
    /* 26C51C 0036C49C 2D282002 */   daddu     $a1, $s1, $zero
    /* 26C520 0036C4A0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26C524 0036C4A4 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26C528 0036C4A8 1000BFDF */  ld         $ra, 0x10($sp)
    /* 26C52C 0036C4AC 12AF0D08 */  j          func_0036BC48
    /* 26C530 0036C4B0 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 26C534 0036C4B4 00000000 */  nop
.size func_0036C478, . - func_0036C478
