.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036C4B8
    /* 26C538 0036C4B8 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 26C53C 0036C4BC 2D388000 */  daddu      $a3, $a0, $zero
    /* 26C540 0036C4C0 0000BFFF */  sd         $ra, 0x0($sp)
    /* 26C544 0036C4C4 0600E014 */  bnez       $a3, .L0036C4E0
    /* 26C548 0036C4C8 2D20A000 */   daddu     $a0, $a1, $zero
    /* 26C54C 0036C4CC 4E00043C */  lui        $a0, %hi(D_004DD3B0)
    /* 26C550 0036C4D0 0000BFDF */  ld         $ra, 0x0($sp)
    /* 26C554 0036C4D4 B0D38424 */  addiu      $a0, $a0, %lo(D_004DD3B0)
    /* 26C558 0036C4D8 2EAF0D08 */  j          func_0036BCB8
    /* 26C55C 0036C4DC 1000BD27 */   addiu     $sp, $sp, 0x10
  .L0036C4E0:
    /* 26C560 0036C4E0 0700801C */  bgtz       $a0, .L0036C500
    /* 26C564 0036C4E4 EE020324 */   addiu     $v1, $zero, 0x2EE
    /* 26C568 0036C4E8 4E00043C */  lui        $a0, %hi(D_004DD3D8)
    /* 26C56C 0036C4EC 0000BFDF */  ld         $ra, 0x0($sp)
    /* 26C570 0036C4F0 D8D38424 */  addiu      $a0, $a0, %lo(D_004DD3D8)
    /* 26C574 0036C4F4 2EAF0D08 */  j          func_0036BCB8
    /* 26C578 0036C4F8 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 26C57C 0036C4FC 00000000 */  nop
  .L0036C500:
    /* 26C580 0036C500 01000524 */  addiu      $a1, $zero, 0x1
    /* 26C584 0036C504 1A008300 */  div        $zero, $a0, $v1
    /* 26C588 0036C508 01006050 */  beql       $v1, $zero, .L0036C510
    /* 26C58C 0036C50C CD010000 */   break     0, 7
  .L0036C510:
    /* 26C590 0036C510 1000E4AC */  sw         $a0, 0x10($a3)
    /* 26C594 0036C514 60000624 */  addiu      $a2, $zero, 0x60
    /* 26C598 0036C518 0000BFDF */  ld         $ra, 0x0($sp)
    /* 26C59C 0036C51C 12100000 */  mflo       $v0
    /* 26C5A0 0036C520 61004328 */  slti       $v1, $v0, 0x61
    /* 26C5A4 0036C524 2A200200 */  slt        $a0, $zero, $v0
    /* 26C5A8 0036C528 0A10A400 */  movz       $v0, $a1, $a0
    /* 26C5AC 0036C52C 00006338 */  xori       $v1, $v1, 0x0
    /* 26C5B0 0036C530 0A10C300 */  movz       $v0, $a2, $v1
    /* 26C5B4 0036C534 1800E2AC */  sw         $v0, 0x18($a3)
    /* 26C5B8 0036C538 0800E003 */  jr         $ra
    /* 26C5BC 0036C53C 1000BD27 */   addiu     $sp, $sp, 0x10
.size func_0036C4B8, . - func_0036C4B8

glabel func_0036C540
    /* 26C5C0 0036C540 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 26C5C4 0036C544 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26C5C8 0036C548 2D808000 */  daddu      $s0, $a0, $zero
    /* 26C5CC 0036C54C 1000B2FF */  sd         $s2, 0x10($sp)
    /* 26C5D0 0036C550 2D90C000 */  daddu      $s2, $a2, $zero
    /* 26C5D4 0036C554 1800B3FF */  sd         $s3, 0x18($sp)
    /* 26C5D8 0036C558 0800B1FF */  sd         $s1, 0x8($sp)
    /* 26C5DC 0036C55C 2000BFFF */  sd         $ra, 0x20($sp)
    /* 26C5E0 0036C560 03000282 */  lb         $v0, 0x3($s0)
    /* 26C5E4 0036C564 02004228 */  slti       $v0, $v0, 0x2
    /* 26C5E8 0036C568 0B004010 */  beqz       $v0, .L0036C598
    /* 26C5EC 0036C56C 2D98A000 */   daddu     $s3, $a1, $zero
    /* 26C5F0 0036C570 4E00043C */  lui        $a0, %hi(D_004DD408)
    /* 26C5F4 0036C574 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26C5F8 0036C578 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26C5FC 0036C57C 08D48424 */  addiu      $a0, $a0, %lo(D_004DD408)
    /* 26C600 0036C580 1000B2DF */  ld         $s2, 0x10($sp)
    /* 26C604 0036C584 1800B3DF */  ld         $s3, 0x18($sp)
    /* 26C608 0036C588 2000BFDF */  ld         $ra, 0x20($sp)
    /* 26C60C 0036C58C 44620D08 */  j          func_00358910
    /* 26C610 0036C590 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 26C614 0036C594 00000000 */  nop
  .L0036C598:
    /* 26C618 0036C598 D27F0D0C */  jal        func_0035FF48
    /* 26C61C 0036C59C 00000000 */   nop
    /* 26C620 0036C5A0 9EB10D0C */  jal        func_0036C678
    /* 26C624 0036C5A4 2D200002 */   daddu     $a0, $s0, $zero
    /* 26C628 0036C5A8 3700043C */  lui        $a0, %hi(func_0036C820)
    /* 26C62C 0036C5AC 2D280000 */  daddu      $a1, $zero, $zero
    /* 26C630 0036C5B0 18AF0D0C */  jal        func_0036BC60
    /* 26C634 0036C5B4 20C88424 */   addiu     $a0, $a0, %lo(func_0036C820)
    /* 26C638 0036C5B8 3AAF0D0C */  jal        func_0036BCE8
    /* 26C63C 0036C5BC 2D200000 */   daddu     $a0, $zero, $zero
    /* 26C640 0036C5C0 0400028E */  lw         $v0, 0x4($s0)
    /* 26C644 0036C5C4 F2700D0C */  jal        func_0035C3C8
    /* 26C648 0036C5C8 0400518C */   lw        $s1, 0x4($v0)
    /* 26C64C 0036C5CC 2D206002 */  daddu      $a0, $s3, $zero
    /* 26C650 0036C5D0 68AF0D0C */  jal        func_0036BDA0
    /* 26C654 0036C5D4 2D284002 */   daddu     $a1, $s2, $zero
    /* 26C658 0036C5D8 2D804000 */  daddu      $s0, $v0, $zero
    /* 26C65C 0036C5DC 0A000016 */  bnez       $s0, .L0036C608
    /* 26C660 0036C5E0 2D200002 */   daddu     $a0, $s0, $zero
    /* 26C664 0036C5E4 4E00043C */  lui        $a0, %hi(D_004DD448)
    /* 26C668 0036C5E8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26C66C 0036C5EC 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26C670 0036C5F0 48D48424 */  addiu      $a0, $a0, %lo(D_004DD448)
    /* 26C674 0036C5F4 1000B2DF */  ld         $s2, 0x10($sp)
    /* 26C678 0036C5F8 1800B3DF */  ld         $s3, 0x18($sp)
    /* 26C67C 0036C5FC 2000BFDF */  ld         $ra, 0x20($sp)
    /* 26C680 0036C600 44620D08 */  j          func_00358910
    /* 26C684 0036C604 3000BD27 */   addiu     $sp, $sp, 0x30
  .L0036C608:
    /* 26C688 0036C608 E800258E */  lw         $a1, 0xE8($s1)
    /* 26C68C 0036C60C DEB00D0C */  jal        func_0036C378
    /* 26C690 0036C610 EC00268E */   lw        $a2, 0xEC($s1)
    /* 26C694 0036C614 E40030AE */  sw         $s0, 0xE4($s1)
    /* 26C698 0036C618 3700023C */  lui        $v0, %hi(func_0036C748)
    /* 26C69C 0036C61C 3700033C */  lui        $v1, %hi(func_0036C7D0)
    /* 26C6A0 0036C620 3700043C */  lui        $a0, %hi(func_0036C7B8)
    /* 26C6A4 0036C624 3700053C */  lui        $a1, %hi(func_0036C808)
    /* 26C6A8 0036C628 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26C6AC 0036C62C 48C74224 */  addiu      $v0, $v0, %lo(func_0036C748)
    /* 26C6B0 0036C630 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26C6B4 0036C634 D0C76324 */  addiu      $v1, $v1, %lo(func_0036C7D0)
    /* 26C6B8 0036C638 1000B2DF */  ld         $s2, 0x10($sp)
    /* 26C6BC 0036C63C B8C78424 */  addiu      $a0, $a0, %lo(func_0036C7B8)
    /* 26C6C0 0036C640 1800B3DF */  ld         $s3, 0x18($sp)
    /* 26C6C4 0036C644 08C8A524 */  addiu      $a1, $a1, %lo(func_0036C808)
    /* 26C6C8 0036C648 2000BFDF */  ld         $ra, 0x20($sp)
    /* 26C6CC 0036C64C 4300063C */  lui        $a2, %hi(D_004355D0)
    /* 26C6D0 0036C650 4200073C */  lui        $a3, %hi(D_00427B9C)
    /* 26C6D4 0036C654 4200083C */  lui        $t0, %hi(D_00427BA0)
    /* 26C6D8 0036C658 4300093C */  lui        $t1, %hi(D_00433C60)
    /* 26C6DC 0036C65C D055C2AC */  sw         $v0, %lo(D_004355D0)($a2)
    /* 26C6E0 0036C660 9C7BE3AC */  sw         $v1, %lo(D_00427B9C)($a3)
    /* 26C6E4 0036C664 A07B04AD */  sw         $a0, %lo(D_00427BA0)($t0)
    /* 26C6E8 0036C668 603C25AD */  sw         $a1, %lo(D_00433C60)($t1)
    /* 26C6EC 0036C66C F8700D08 */  j          func_0035C3E0
    /* 26C6F0 0036C670 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 26C6F4 0036C674 00000000 */  nop
.size func_0036C540, . - func_0036C540
