.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036E0B8
    /* 26E138 0036E0B8 4400023C */  lui        $v0, (0x440000 >> 16)
    /* 26E13C 0036E0BC 0800E003 */  jr         $ra
    /* 26E140 0036E0C0 40E640AC */   sw        $zero, -0x19C0($v0)
    /* 26E144 0036E0C4 00000000 */  nop
.size func_0036E0B8, . - func_0036E0B8
