.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036E0A8
    /* 26E128 0036E0A8 4400023C */  lui        $v0, (0x440000 >> 16)
    /* 26E12C 0036E0AC 0800E003 */  jr         $ra
    /* 26E130 0036E0B0 40E640AC */   sw        $zero, -0x19C0($v0)
    /* 26E134 0036E0B4 00000000 */  nop
.size func_0036E0A8, . - func_0036E0A8
