.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036E938
    /* 26E9B8 0036E938 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 26E9BC 0036E93C 1000B2FF */  sd         $s2, 0x10($sp)
    /* 26E9C0 0036E940 2D90A000 */  daddu      $s2, $a1, $zero
    /* 26E9C4 0036E944 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26E9C8 0036E948 2D808000 */  daddu      $s0, $a0, $zero
    /* 26E9CC 0036E94C 0800B1FF */  sd         $s1, 0x8($sp)
    /* 26E9D0 0036E950 2D88E000 */  daddu      $s1, $a3, $zero
    /* 26E9D4 0036E954 1800B3FF */  sd         $s3, 0x18($sp)
    /* 26E9D8 0036E958 2000BFFF */  sd         $ra, 0x20($sp)
    /* 26E9DC 0036E95C 42B80D0C */  jal        func_0036E108
    /* 26E9E0 0036E960 2D98C000 */   daddu     $s3, $a2, $zero
    /* 26E9E4 0036E964 20004016 */  bnez       $s2, .L0036E9E8
    /* 26E9E8 0036E968 01000224 */   addiu     $v0, $zero, 0x1
    /* 26E9EC 0036E96C 1400038E */  lw         $v1, 0x14($s0)
    /* 26E9F0 0036E970 2000028E */  lw         $v0, 0x20($s0)
    /* 26E9F4 0036E974 2400048E */  lw         $a0, 0x24($s0)
    /* 26E9F8 0036E978 1000058E */  lw         $a1, 0x10($s0)
    /* 26E9FC 0036E97C 23104300 */  subu       $v0, $v0, $v1
    /* 26EA00 0036E980 21104400 */  addu       $v0, $v0, $a0
    /* 26EA04 0036E984 1C00068E */  lw         $a2, 0x1C($s0)
    /* 26EA08 0036E988 2A18A200 */  slt        $v1, $a1, $v0
    /* 26EA0C 0036E98C 0B10A300 */  movn       $v0, $a1, $v1
    /* 26EA10 0036E990 2A205300 */  slt        $a0, $v0, $s3
    /* 26EA14 0036E994 0A106402 */  movz       $v0, $s3, $a0
    /* 26EA18 0036E998 040022AE */  sw         $v0, 0x4($s1)
    /* 26EA1C 0036E99C 1400048E */  lw         $a0, 0x14($s0)
    /* 26EA20 0036E9A0 2000038E */  lw         $v1, 0x20($s0)
    /* 26EA24 0036E9A4 21108200 */  addu       $v0, $a0, $v0
    /* 26EA28 0036E9A8 2130C400 */  addu       $a2, $a2, $a0
    /* 26EA2C 0036E9AC 1A004300 */  div        $zero, $v0, $v1
    /* 26EA30 0036E9B0 000026AE */  sw         $a2, 0x0($s1)
    /* 26EA34 0036E9B4 01006050 */  beql       $v1, $zero, .L0036E9BC
    /* 26EA38 0036E9B8 CD010000 */   break     0, 7
  .L0036E9BC:
    /* 26EA3C 0036E9BC 1000048E */  lw         $a0, 0x10($s0)
    /* 26EA40 0036E9C0 2800038E */  lw         $v1, 0x28($s0)
    /* 26EA44 0036E9C4 10280000 */  mfhi       $a1
    /* 26EA48 0036E9C8 140005AE */  sw         $a1, 0x14($s0)
    /* 26EA4C 0036E9CC 0400228E */  lw         $v0, 0x4($s1)
    /* 26EA50 0036E9D0 23208200 */  subu       $a0, $a0, $v0
    /* 26EA54 0036E9D4 100004AE */  sw         $a0, 0x10($s0)
    /* 26EA58 0036E9D8 0400228E */  lw         $v0, 0x4($s1)
    /* 26EA5C 0036E9DC 21186200 */  addu       $v1, $v1, $v0
    /* 26EA60 0036E9E0 29000010 */  b          .L0036EA88
    /* 26EA64 0036E9E4 280003AE */   sw        $v1, 0x28($s0)
  .L0036E9E8:
    /* 26EA68 0036E9E8 21004256 */  bnel       $s2, $v0, .L0036EA70
    /* 26EA6C 0036E9EC 3800028E */   lw        $v0, 0x38($s0)
    /* 26EA70 0036E9F0 1800038E */  lw         $v1, 0x18($s0)
    /* 26EA74 0036E9F4 2000028E */  lw         $v0, 0x20($s0)
    /* 26EA78 0036E9F8 2400048E */  lw         $a0, 0x24($s0)
    /* 26EA7C 0036E9FC 0C00058E */  lw         $a1, 0xC($s0)
    /* 26EA80 0036EA00 23104300 */  subu       $v0, $v0, $v1
    /* 26EA84 0036EA04 21104400 */  addu       $v0, $v0, $a0
    /* 26EA88 0036EA08 1C00068E */  lw         $a2, 0x1C($s0)
    /* 26EA8C 0036EA0C 2A18A200 */  slt        $v1, $a1, $v0
    /* 26EA90 0036EA10 0B10A300 */  movn       $v0, $a1, $v1
    /* 26EA94 0036EA14 2A205300 */  slt        $a0, $v0, $s3
    /* 26EA98 0036EA18 0A106402 */  movz       $v0, $s3, $a0
    /* 26EA9C 0036EA1C 040022AE */  sw         $v0, 0x4($s1)
    /* 26EAA0 0036EA20 1800048E */  lw         $a0, 0x18($s0)
    /* 26EAA4 0036EA24 2000038E */  lw         $v1, 0x20($s0)
    /* 26EAA8 0036EA28 21108200 */  addu       $v0, $a0, $v0
    /* 26EAAC 0036EA2C 2130C400 */  addu       $a2, $a2, $a0
    /* 26EAB0 0036EA30 1A004300 */  div        $zero, $v0, $v1
    /* 26EAB4 0036EA34 000026AE */  sw         $a2, 0x0($s1)
    /* 26EAB8 0036EA38 01006050 */  beql       $v1, $zero, .L0036EA40
    /* 26EABC 0036EA3C CD010000 */   break     0, 7
  .L0036EA40:
    /* 26EAC0 0036EA40 0C00048E */  lw         $a0, 0xC($s0)
    /* 26EAC4 0036EA44 3000038E */  lw         $v1, 0x30($s0)
    /* 26EAC8 0036EA48 10280000 */  mfhi       $a1
    /* 26EACC 0036EA4C 180005AE */  sw         $a1, 0x18($s0)
    /* 26EAD0 0036EA50 0400228E */  lw         $v0, 0x4($s1)
    /* 26EAD4 0036EA54 23208200 */  subu       $a0, $a0, $v0
    /* 26EAD8 0036EA58 0C0004AE */  sw         $a0, 0xC($s0)
    /* 26EADC 0036EA5C 0400228E */  lw         $v0, 0x4($s1)
    /* 26EAE0 0036EA60 21186200 */  addu       $v1, $v1, $v0
    /* 26EAE4 0036EA64 08000010 */  b          .L0036EA88
    /* 26EAE8 0036EA68 300003AE */   sw        $v1, 0x30($s0)
    /* 26EAEC 0036EA6C 00000000 */  nop
  .L0036EA70:
    /* 26EAF0 0036EA70 000020AE */  sw         $zero, 0x0($s1)
    /* 26EAF4 0036EA74 04004010 */  beqz       $v0, .L0036EA88
    /* 26EAF8 0036EA78 040020AE */   sw        $zero, 0x4($s1)
    /* 26EAFC 0036EA7C 3C00048E */  lw         $a0, 0x3C($s0)
    /* 26EB00 0036EA80 09F84000 */  jalr       $v0
    /* 26EB04 0036EA84 FDFF0524 */   addiu     $a1, $zero, -0x3
  .L0036EA88:
    /* 26EB08 0036EA88 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26EB0C 0036EA8C 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26EB10 0036EA90 1000B2DF */  ld         $s2, 0x10($sp)
    /* 26EB14 0036EA94 1800B3DF */  ld         $s3, 0x18($sp)
    /* 26EB18 0036EA98 2000BFDF */  ld         $ra, 0x20($sp)
    /* 26EB1C 0036EA9C 48B80D08 */  j          func_0036E120
    /* 26EB20 0036EAA0 3000BD27 */   addiu     $sp, $sp, 0x30
    /* 26EB24 0036EAA4 00000000 */  nop
.size func_0036E938, . - func_0036E938
