.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036F058
    /* 26F0D8 0036F058 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 26F0DC 0036F05C 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26F0E0 0036F060 2D808000 */  daddu      $s0, $a0, $zero
    /* 26F0E4 0036F064 05000012 */  beqz       $s0, .L0036F07C
    /* 26F0E8 0036F068 0800BFFF */   sd        $ra, 0x8($sp)
    /* 26F0EC 0036F06C 2D280000 */  daddu      $a1, $zero, $zero
    /* 26F0F0 0036F070 84D40D0C */  jal        func_00375210
    /* 26F0F4 0036F074 30000624 */   addiu     $a2, $zero, 0x30
    /* 26F0F8 0036F078 040000A2 */  sb         $zero, 0x4($s0)
  .L0036F07C:
    /* 26F0FC 0036F07C 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26F100 0036F080 0800BFDF */  ld         $ra, 0x8($sp)
    /* 26F104 0036F084 0800E003 */  jr         $ra
    /* 26F108 0036F088 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 26F10C 0036F08C 00000000 */  nop
.size func_0036F058, . - func_0036F058

glabel func_0036F090
    /* 26F110 0036F090 0800E003 */  jr         $ra
    /* 26F114 0036F094 0800828C */   lw        $v0, 0x8($a0)
.size func_0036F090, . - func_0036F090

glabel func_0036F098
    /* 26F118 0036F098 2C0086AC */  sw         $a2, 0x2C($a0)
    /* 26F11C 0036F09C 0800E003 */  jr         $ra
    /* 26F120 0036F0A0 280085AC */   sw        $a1, 0x28($a0)
    /* 26F124 0036F0A4 00000000 */  nop
.size func_0036F098, . - func_0036F098
