.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036F588
    /* 26F608 0036F588 80100500 */  sll        $v0, $a1, 2
    /* 26F60C 0036F58C 0400A52C */  sltiu      $a1, $a1, 0x4
    /* 26F610 0036F590 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 26F614 0036F594 2D408000 */  daddu      $t0, $a0, $zero
    /* 26F618 0036F598 1000BFFF */  sd         $ra, 0x10($sp)
    /* 26F61C 0036F59C 21104800 */  addu       $v0, $v0, $t0
    /* 26F620 0036F5A0 0900A014 */  bnez       $a1, .L0036F5C8
    /* 26F624 0036F5A4 0000E0AC */   sw        $zero, 0x0($a3)
    /* 26F628 0036F5A8 2800028D */  lw         $v0, 0x28($t0)
    /* 26F62C 0036F5AC 16004050 */  beql       $v0, $zero, .L0036F608
    /* 26F630 0036F5B0 2D100000 */   daddu     $v0, $zero, $zero
    /* 26F634 0036F5B4 2C00048D */  lw         $a0, 0x2C($t0)
    /* 26F638 0036F5B8 09F84000 */  jalr       $v0
    /* 26F63C 0036F5BC FDFF0524 */   addiu     $a1, $zero, -0x3
    /* 26F640 0036F5C0 11000010 */  b          .L0036F608
    /* 26F644 0036F5C4 2D100000 */   daddu     $v0, $zero, $zero
  .L0036F5C8:
    /* 26F648 0036F5C8 1800438C */  lw         $v1, 0x18($v0)
    /* 26F64C 0036F5CC 0E006010 */  beqz       $v1, .L0036F608
    /* 26F650 0036F5D0 2D100000 */   daddu     $v0, $zero, $zero
    /* 26F654 0036F5D4 0F006268 */  ldl        $v0, 0xF($v1)
    /* 26F658 0036F5D8 0800626C */  ldr        $v0, 0x8($v1)
    /* 26F65C 0036F5DC 0700A2B3 */  sdl        $v0, 0x7($sp)
    /* 26F660 0036F5E0 0000A2B7 */  sdr        $v0, 0x0($sp)
    /* 26F664 0036F5E4 01000424 */  addiu      $a0, $zero, 0x1
    /* 26F668 0036F5E8 0400A38F */  lw         $v1, 0x4($sp)
    /* 26F66C 0036F5EC 0000E3AC */  sw         $v1, 0x0($a3)
    /* 26F670 0036F5F0 2A106600 */  slt        $v0, $v1, $a2
    /* 26F674 0036F5F4 26306600 */  xor        $a2, $v1, $a2
    /* 26F678 0036F5F8 05000381 */  lb         $v1, 0x5($t0)
    /* 26F67C 0036F5FC 02006410 */  beq        $v1, $a0, .L0036F608
    /* 26F680 0036F600 0100422C */   sltiu     $v0, $v0, 0x1
    /* 26F684 0036F604 0100C22C */  sltiu      $v0, $a2, 0x1
  .L0036F608:
    /* 26F688 0036F608 1000BFDF */  ld         $ra, 0x10($sp)
    /* 26F68C 0036F60C 0800E003 */  jr         $ra
    /* 26F690 0036F610 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 26F694 0036F614 00000000 */  nop
.size func_0036F588, . - func_0036F588
