.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_0036F898
    /* 26F918 0036F898 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 26F91C 0036F89C 10008224 */  addiu      $v0, $a0, 0x10
    /* 26F920 0036F8A0 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26F924 0036F8A4 2D80A000 */  daddu      $s0, $a1, $zero
    /* 26F928 0036F8A8 000002AE */  sw         $v0, 0x0($s0)
    /* 26F92C 0036F8AC 0800BFFF */  sd         $ra, 0x8($sp)
    /* 26F930 0036F8B0 E2BD0D0C */  jal        func_0036F788
    /* 26F934 0036F8B4 08008424 */   addiu     $a0, $a0, 0x8
    /* 26F938 0036F8B8 040002AE */  sw         $v0, 0x4($s0)
    /* 26F93C 0036F8BC 0800BFDF */  ld         $ra, 0x8($sp)
    /* 26F940 0036F8C0 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26F944 0036F8C4 0800E003 */  jr         $ra
    /* 26F948 0036F8C8 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 26F94C 0036F8CC 00000000 */  nop
.size func_0036F898, . - func_0036F898

glabel func_0036F8D0
    /* 26F950 0036F8D0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 26F954 0036F8D4 1800B3FF */  sd         $s3, 0x18($sp)
    /* 26F958 0036F8D8 2D98E000 */  daddu      $s3, $a3, $zero
    /* 26F95C 0036F8DC 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26F960 0036F8E0 1000B2FF */  sd         $s2, 0x10($sp)
    /* 26F964 0036F8E4 2D90C000 */  daddu      $s2, $a2, $zero
    /* 26F968 0036F8E8 2000B4FF */  sd         $s4, 0x20($sp)
    /* 26F96C 0036F8EC 2800B5FF */  sd         $s5, 0x28($sp)
    /* 26F970 0036F8F0 2DA8A000 */  daddu      $s5, $a1, $zero
    /* 26F974 0036F8F4 0800B1FF */  sd         $s1, 0x8($sp)
    /* 26F978 0036F8F8 3000BFFF */  sd         $ra, 0x30($sp)
    /* 26F97C 0036F8FC 000060AE */  sw         $zero, 0x0($s3)
    /* 26F980 0036F900 040060AE */  sw         $zero, 0x4($s3)
    /* 26F984 0036F904 0000828C */  lw         $v0, 0x0($a0)
    /* 26F988 0036F908 0400838C */  lw         $v1, 0x4($a0)
    /* 26F98C 0036F90C 2D804000 */  daddu      $s0, $v0, $zero
    /* 26F990 0036F910 0B000010 */  b          .L0036F940
    /* 26F994 0036F914 21A04300 */   addu      $s4, $v0, $v1
  .L0036F918:
    /* 26F998 0036F918 05004012 */  beqz       $s2, .L0036F930
    /* 26F99C 0036F91C 00000000 */   nop
    /* 26F9A0 0036F920 2ADC0D0C */  jal        func_003770A8
    /* 26F9A4 0036F924 00000000 */   nop
    /* 26F9A8 0036F928 15004050 */  beql       $v0, $zero, .L0036F980
    /* 26F9AC 0036F92C 0000B0DF */   ld        $s0, 0x0($sp)
  .L0036F930:
    /* 26F9B0 0036F930 E2BD0D0C */  jal        func_0036F788
    /* 26F9B4 0036F934 08000426 */   addiu     $a0, $s0, 0x8
    /* 26F9B8 0036F938 21100202 */  addu       $v0, $s0, $v0
    /* 26F9BC 0036F93C 10005024 */  addiu      $s0, $v0, 0x10
  .L0036F940:
    /* 26F9C0 0036F940 2B881402 */  sltu       $s1, $s0, $s4
    /* 26F9C4 0036F944 0C002012 */  beqz       $s1, .L0036F978
    /* 26F9C8 0036F948 2D100000 */   daddu     $v0, $zero, $zero
    /* 26F9CC 0036F94C 2D200002 */  daddu      $a0, $s0, $zero
    /* 26F9D0 0036F950 2D28A002 */  daddu      $a1, $s5, $zero
    /* 26F9D4 0036F954 2ADC0D0C */  jal        func_003770A8
    /* 26F9D8 0036F958 07000624 */   addiu     $a2, $zero, 0x7
    /* 26F9DC 0036F95C 2D200002 */  daddu      $a0, $s0, $zero
    /* 26F9E0 0036F960 2D284002 */  daddu      $a1, $s2, $zero
    /* 26F9E4 0036F964 ECFF4014 */  bnez       $v0, .L0036F918
    /* 26F9E8 0036F968 07000624 */   addiu     $a2, $zero, 0x7
    /* 26F9EC 0036F96C 26BE0D0C */  jal        func_0036F898
    /* 26F9F0 0036F970 2D286002 */   daddu     $a1, $s3, $zero
    /* 26F9F4 0036F974 2D100000 */  daddu      $v0, $zero, $zero
  .L0036F978:
    /* 26F9F8 0036F978 0B101102 */  movn       $v0, $s0, $s1
    /* 26F9FC 0036F97C 0000B0DF */  ld         $s0, 0x0($sp)
  .L0036F980:
    /* 26FA00 0036F980 0800B1DF */  ld         $s1, 0x8($sp)
    /* 26FA04 0036F984 1000B2DF */  ld         $s2, 0x10($sp)
    /* 26FA08 0036F988 1800B3DF */  ld         $s3, 0x18($sp)
    /* 26FA0C 0036F98C 2000B4DF */  ld         $s4, 0x20($sp)
    /* 26FA10 0036F990 2800B5DF */  ld         $s5, 0x28($sp)
    /* 26FA14 0036F994 3000BFDF */  ld         $ra, 0x30($sp)
    /* 26FA18 0036F998 0800E003 */  jr         $ra
    /* 26FA1C 0036F99C 4000BD27 */   addiu     $sp, $sp, 0x40
.size func_0036F8D0, . - func_0036F8D0

glabel func_0036F9A0
    /* 26FA20 0036F9A0 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 26FA24 0036F9A4 6400023C */  lui        $v0, %hi(D_63EF40)
    /* 26FA28 0036F9A8 0000B0FF */  sd         $s0, 0x0($sp)
    /* 26FA2C 0036F9AC 6400103C */  lui        $s0, %hi(D_63F040)
    /* 26FA30 0036F9B0 40EF4224 */  addiu      $v0, $v0, %lo(D_63EF40)
    /* 26FA34 0036F9B4 0800BFFF */  sd         $ra, 0x8($sp)
    /* 26FA38 0036F9B8 40F01026 */  addiu      $s0, $s0, %lo(D_63F040)
    /* 26FA3C 0036F9BC 000044AC */  sw         $a0, 0x0($v0)
    /* 26FA40 0036F9C0 040045AC */  sw         $a1, 0x4($v0)
    /* 26FA44 0036F9C4 2D284000 */  daddu      $a1, $v0, $zero
    /* 26FA48 0036F9C8 080046AC */  sw         $a2, 0x8($v0)
    /* 26FA4C 0036F9CC 03000624 */  addiu      $a2, $zero, 0x3
    /* 26FA50 0036F9D0 2D380002 */  daddu      $a3, $s0, $zero
    /* 26FA54 0036F9D4 20000424 */  addiu      $a0, $zero, 0x20
    /* 26FA58 0036F9D8 829D0D0C */  jal        func_00367608
    /* 26FA5C 0036F9DC 01000824 */   addiu     $t0, $zero, 0x1
    /* 26FA60 0036F9E0 0000028E */  lw         $v0, 0x0($s0)
    /* 26FA64 0036F9E4 0800BFDF */  ld         $ra, 0x8($sp)
    /* 26FA68 0036F9E8 0000B0DF */  ld         $s0, 0x0($sp)
    /* 26FA6C 0036F9EC 0800E003 */  jr         $ra
    /* 26FA70 0036F9F0 1000BD27 */   addiu     $sp, $sp, 0x10
    /* 26FA74 0036F9F4 00000000 */  nop
.size func_0036F9A0, . - func_0036F9A0
