.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.30.2 */

glabel func_00373818
    /* 273898 00373818 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 27389C 0037381C 3700023C */  lui        $v0, %hi(func_003737D8)
    /* 2738A0 00373820 0000B0FF */  sd         $s0, 0x0($sp)
    /* 2738A4 00373824 2D808000 */  daddu      $s0, $a0, $zero
    /* 2738A8 00373828 D8374224 */  addiu      $v0, $v0, %lo(func_003737D8)
    /* 2738AC 0037382C 01000324 */  addiu      $v1, $zero, 0x1
    /* 2738B0 00373830 0800B1FF */  sd         $s1, 0x8($sp)
    /* 2738B4 00373834 E4011126 */  addiu      $s1, $s0, 0x1E4
    /* 2738B8 00373838 1000BFFF */  sd         $ra, 0x10($sp)
    /* 2738BC 0037383C 2D202002 */  daddu      $a0, $s1, $zero
    /* 2738C0 00373840 3C0002AE */  sw         $v0, 0x3C($s0)
    /* 2738C4 00373844 2D380002 */  daddu      $a3, $s0, $zero
    /* 2738C8 00373848 380003AE */  sw         $v1, 0x38($s0)
    /* 2738CC 0037384C 04000524 */  addiu      $a1, $zero, 0x4
    /* 2738D0 00373850 82CD0D0C */  jal        func_00373608
    /* 2738D4 00373854 2D300000 */   daddu     $a2, $zero, $zero
    /* 2738D8 00373858 3C020426 */  addiu      $a0, $s0, 0x23C
    /* 2738DC 0037385C 2D380002 */  daddu      $a3, $s0, $zero
    /* 2738E0 00373860 09000524 */  addiu      $a1, $zero, 0x9
    /* 2738E4 00373864 82CD0D0C */  jal        func_00373608
    /* 2738E8 00373868 01000624 */   addiu     $a2, $zero, 0x1
    /* 2738EC 0037386C 94020426 */  addiu      $a0, $s0, 0x294
    /* 2738F0 00373870 2D380002 */  daddu      $a3, $s0, $zero
    /* 2738F4 00373874 0A000524 */  addiu      $a1, $zero, 0xA
    /* 2738F8 00373878 82CD0D0C */  jal        func_00373608
    /* 2738FC 0037387C 02000624 */   addiu     $a2, $zero, 0x2
    /* 273900 00373880 D80100AE */  sw         $zero, 0x1D8($s0)
    /* 273904 00373884 03000224 */  addiu      $v0, $zero, 0x3
    /* 273908 00373888 E00111AE */  sw         $s1, 0x1E0($s0)
    /* 27390C 0037388C DC0102AE */  sw         $v0, 0x1DC($s0)
    /* 273910 00373890 0800B1DF */  ld         $s1, 0x8($sp)
    /* 273914 00373894 0000B0DF */  ld         $s0, 0x0($sp)
    /* 273918 00373898 1000BFDF */  ld         $ra, 0x10($sp)
    /* 27391C 0037389C 0800E003 */  jr         $ra
    /* 273920 003738A0 2000BD27 */   addiu     $sp, $sp, 0x20
    /* 273924 003738A4 00000000 */  nop
.size func_00373818, . - func_00373818
