/**
 * @file dir_data.c
 * System Direction (Dipswitch) Menu Data
 */

#include "common.h"
#include "structs.h"

const u8 Dir_Menu_Max_Data[10][7] = { { 1, 1, 1, 3, 1, 3, 2 }, { 1, 1, 3, 1, 1, 2, 0 }, { 1, 1, 1, 1, 1, 1, 2 },
                                      { 1, 1, 1, 2, 0, 0, 0 }, { 1, 1, 1, 1, 2, 0, 0 }, { 1, 1, 1, 3, 2, 0, 0 },
                                      { 1, 1, 1, 1, 1, 2, 0 }, { 1, 1, 1, 1, 1, 1, 2 }, { 1, 1, 1, 1, 1, 1, 2 },
                                      { 1, 1, 3, 1, 2, 0, 0 } };

const DirData Dir_Default_Data = { .contents = { { 1, 1, 1, 1, 1, 1, 1 },
                                                 { 1, 0, 1, 1, 1, 1, 1 },
                                                 { 1, 1, 1, 1, 1, 1, 1 },
                                                 { 1, 1, 0, 0, 1, 1, 1 },
                                                 { 1, 0, 1, 1, 1, 1, 1 },
                                                 { 1, 1, 1, 2, 0, 0, 1 },
                                                 { 1, 1, 1, 1, 0, 1, 1 },
                                                 { 0, 0, 0, 0, 0, 0, 0 },
                                                 { 0, 0, 0, 0, 0, 0, 0 },
                                                 { 0, 0, 1, 1, 0, 0, 0 } },
                                   .sum = 0 };

const u8 Page_Data[10] = { 6, 5, 5, 3, 4, 4, 5, 6, 6, 4 };

s8* Letter_Data_51[10][6][4] = { { { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "S/#;;;/L", "S/##;;/L", "S/###;/L", "S/####/L" },
                                   { "OFF", "ON", NULL, NULL },
                                   { "S/#;;;/L", "S/##;;/L", "S/###;/L", "S/####/L" } },
                                 { { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "S/#;;;/L", "S/##;;/L", "S/###;/L", "S/####/L" },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL } },
                                 { { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL } },
                                 { { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "3rd", "2nd", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL } },
                                 { { "OFF", "ON", NULL, NULL },
                                   { "3rd", "2nd", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL } },
                                 { { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "S/#;;;/L", "S/##;;/L", "S/###;/L", "S/####/L" },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL } },
                                 { { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "3rd", "2nd", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL } },
                                 { { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL } },
                                 { { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL } },
                                 { { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "S/#;;;/L", "S/##;;/L", "S/###;/L", "S/####/L" },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL },
                                   { "OFF", "ON", NULL, NULL } } };
